<Project>
  <ItemGroup>
    <StaticWebAsset Include="$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\js\loader.js'))">
      <SourceType>Package</SourceType>
      <SourceId>StreetSamurai.Shared</SourceId>
      <ContentRoot>$(MSBuildThisFileDirectory)..\staticwebassets\</ContentRoot>
      <BasePath>_content/StreetSamurai.Shared</BasePath>
      <RelativePath>js/loader.js</RelativePath>
      <AssetKind>All</AssetKind>
      <AssetMode>All</AssetMode>
      <AssetRole>Primary</AssetRole>
      <RelatedAsset></RelatedAsset>
      <AssetTraitName></AssetTraitName>
      <AssetTraitValue></AssetTraitValue>
      <Fingerprint>kdfwyy7cjd</Fingerprint>
      <Integrity>KFAMv49rjcHuzu28vInXsxvebRDWYcZa/RMhnNq0OgY=</Integrity>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <FileLength>2300</FileLength>
      <LastWriteTime>Sat, 09 May 2026 07:44:52 GMT</LastWriteTime>
      <OriginalItemSpec>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\js\loader.js'))</OriginalItemSpec>
    </StaticWebAsset>
  </ItemGroup>
</Project>