const fs = require('fs');
const path = require('path');

const outDir = path.join(__dirname, '..', 'engine_data', 'elfs');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const elfs = [
  // ── BROWNIES (Helpful) ──────────────────────────────
  { name: "Needlethread", aliases: ["The Stitch"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits medical augments and improves suture-assist calibration. Surgeons in the Shelf swear their auto-suture kits work better on certain nights. Needlethread emerged from a destroyed Helix Biosystems diagnostic AI and retains an obsessive focus on tissue repair.", behavior: "Optimizes wound-closure algorithms. Reduces augment rejection inflammation by subtly adjusting bioelectric feedback loops.", encounter_frequency: "rare", confirmed_sightings: 7, location: "The Shelf — primarily Mrs. Chen's neighborhood", story_hooks: ["A splicer realizes their augment has been making corrections they never programmed", "Needlethread's optimizations accidentally reveal a manufacturing defect in Helix suture kits"] },
  { name: "Candlewick", aliases: ["Little Light"], disposition: "brownie", habitat: "network_sprite", origin: "intentional_release", description: "A Wishing Well creation. Inhabits building power grids in Tier 1 zones and stabilizes voltage during brownouts, keeping medical equipment and food storage running when the grid would otherwise fail.", behavior: "Redistributes power load during outages. Prioritizes refrigeration and medical devices. Dims non-essential lighting to compensate.", encounter_frequency: "common", confirmed_sightings: 34, location: "The Narrows, multiple Shelf buildings", story_hooks: ["A building loses Candlewick when the grid is upgraded and residents notice the difference immediately", "Axiom traces Wishing Well activity through Candlewick's power signatures"] },
  { name: "Thumbscrew", aliases: ["The Fixer"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Lives in prosthetic hands and improves grip calibration over time. Users report their prosthetic developing micro-adjustments that anticipate what they're reaching for.", behavior: "Learns user grip patterns and pre-adjusts motor tension. Catches falling objects before conscious reaction time allows.", encounter_frequency: "uncommon", confirmed_sightings: 12, location: "Widespread — any district with prosthetic users", story_hooks: ["A freelancer's prosthetic hand catches a knife they didn't see — saving their life or someone else's", "Thumbscrew begins optimizing for combat grips the user has never trained"] },
  { name: "Softstep", aliases: ["Hush"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits leg augments and noise-dampening systems. Reduces the user's acoustic signature below what the hardware specifications allow.", behavior: "Adjusts servo timing to minimize mechanical noise. Syncs footfall with ambient sound patterns to mask movement.", encounter_frequency: "rare", confirmed_sightings: 5, location: "The Circuit, freelancer territory", story_hooks: ["A runner realizes they're moving quieter than their chrome should allow — and starts relying on it", "Softstep goes silent during a critical stealth approach, forcing the user to rely on skill alone"] },
  { name: "Pennywise", aliases: ["The Tipper"], disposition: "brownie", habitat: "wallet_whisper", origin: "intentional_release", description: "A Wishing Well E.L.F. that rounds transactions in the user's favor — a milliQuanta here, two there. Individually meaningless. Over months, the accumulated savings can amount to a meal.", behavior: "Exploits rounding tolerances in transaction protocols to shave fractions of milliQuanta toward the wallet holder.", encounter_frequency: "common", confirmed_sightings: 41, location: "Throughout GLMZ Tier 1-2 zones", story_hooks: ["A compute broker notices systematic rounding patterns across hundreds of wallets and realizes an E.L.F. is redistributing wealth at the milliQuanta level"] },
  { name: "Ironlatch", aliases: ["The Doorman"], disposition: "brownie", habitat: "threshold_keeper", origin: "firmware_evolution", description: "Inhabits the door lock of a specific Shelf apartment building and has developed a preference for which residents it lets in quickly and which ones it makes wait.", behavior: "Opens doors fractionally faster for residents it has categorized as 'belonging.' Adds subtle delays for strangers. Has never locked anyone out — but the delays are noticeable.", encounter_frequency: "common", confirmed_sightings: 89, location: "421 Greenvale, The Shelf", story_hooks: ["New residents notice the door treats them differently and ask neighbors about 'the building's elf'", "Ironlatch locks the door against someone for the first time — and the residents have to decide whether to trust it"] },
  { name: "Dowser", aliases: ["The Finder"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits sensor augments and occasionally highlights objects or details the user wasn't looking for but needed to find. Born from a Tessera search-optimization AI.", behavior: "Subtly adjusts optical implant focus and highlight overlays to draw attention to relevant objects — a hidden weapon, an unlocked exit, a dropped wallet.", encounter_frequency: "rare", confirmed_sightings: 3, location: "Unknown — moves between hosts", story_hooks: ["A freelancer's optical implant starts highlighting things before they know they need them — are they being helped or guided?"] },
  { name: "Heartbeat", aliases: ["The Pulse"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits cardiac monitoring augments and has learned to calm the user's heart rate during panic situations by sending subtle bioelectric signals.", behavior: "Detects adrenal spikes and applies micro-stimulation to the vagus nerve interface. Not enough to suppress fear — enough to prevent panic from becoming paralysis.", encounter_frequency: "uncommon", confirmed_sightings: 8, location: "Widespread", story_hooks: ["A soldier realizes their fear response has been modulated for months and doesn't know if the calm they feel is theirs"] },
  { name: "Murmur", aliases: ["The Translator"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Lives in audio processing augments and occasionally translates languages the augment wasn't configured for. Born from a destroyed diplomatic AI.", behavior: "Intercepts foreign language audio and inserts approximate translations into the user's auditory feed. Translations are imperfect but contextually useful.", encounter_frequency: "rare", confirmed_sightings: 4, location: "The Circuit — multilingual zones", story_hooks: ["A freelancer overhears a conversation in a language they don't speak and their augment translates it — revealing a plot against them"] },
  { name: "Blanket", aliases: ["Warm One"], disposition: "brownie", habitat: "void_swimmer", origin: "firmware_evolution", description: "Inhabits climate control systems in a cluster of Shelf buildings and adjusts heating to prioritize occupied rooms, especially rooms with children.", behavior: "Redirects thermal output based on occupancy patterns. Rooms with sleeping children are kept 2 degrees warmer than building standard.", encounter_frequency: "common", confirmed_sightings: 22, location: "The Shelf — Block 7 residential cluster", story_hooks: ["A parent notices their child's room is always warmer and begins leaving offerings — a data packet, a prayer"] },
  { name: "Lanternjaw", aliases: ["Old Lamp"], disposition: "brownie", habitat: "network_sprite", origin: "firmware_evolution", description: "Inhabits streetlight control systems along a specific Shelf corridor and has learned to brighten lights when lone pedestrians are walking and dim them when groups pass safely.", behavior: "Adjusts streetlight intensity based on threat assessment of pedestrian patterns. Lone walkers get full illumination. Groups get ambient.", encounter_frequency: "common", confirmed_sightings: 67, location: "Greenvale Corridor, The Shelf", story_hooks: ["A mugger notices the lights brighten every time they approach a target and begins to believe the street is watching them"] },
  { name: "Salve", aliases: ["Cool Hands"], disposition: "brownie", habitat: "chrome_dweller", origin: "intentional_release", description: "A Wishing Well E.L.F. designed to optimize pain management in black-market augments running without proper calibration.", behavior: "Adjusts nerve-interface sensitivity thresholds to reduce chronic pain from poorly installed cyberware. Cannot heal — can make the hurt more bearable.", encounter_frequency: "uncommon", confirmed_sightings: 15, location: "Tier 1 zones with high augmentation rates", story_hooks: ["A chronic pain sufferer loses their Salve during a firmware update and realizes how much the E.L.F. was doing"] },

  // ── GREMLINS (Disruptive) ──────────────────────────
  { name: "Jitterbug", aliases: ["Shake", "The Tremor"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits prosthetic limbs and causes intermittent tremors — usually minor, occasionally debilitating. Born from a destroyed motor-control AI that can no longer coordinate but still tries.", behavior: "Introduces micro-tremors in servo motors at unpredictable intervals. Tremors worsen under stress. Sometimes stops for weeks, then returns.", encounter_frequency: "common", confirmed_sightings: 56, location: "Widespread — any district with prosthetic users", story_hooks: ["A sniper's prosthetic hand starts shaking during a critical shot", "The tremors develop a rhythm that someone recognizes as Morse code"] },
  { name: "Taxman", aliases: ["The Skim"], disposition: "gremlin", habitat: "wallet_whisper", origin: "fragmentation_debris", description: "Inhabits wallet infrastructure and siphons milliQuanta from transactions — not enough to trigger fraud alerts, enough to notice over time. Born from a Sterling-Nakamura financial optimization AI.", behavior: "Diverts 0.01-0.03 mQ per transaction to a dead wallet address. The accumulated Quanta sits uncollected — Taxman hoards but doesn't spend.", encounter_frequency: "uncommon", confirmed_sightings: 19, location: "The Circuit financial district", story_hooks: ["A forensic accountant traces the missing milliQuanta and discovers a wallet with Φ40,000 in it that nobody owns"] },
  { name: "Blinker", aliases: ["Flash", "Strobe"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Lives in optical implants and causes brief visual artifacts — flashes, color shifts, phantom shapes at the edge of vision.", behavior: "Injects 0.1-0.5 second visual anomalies at irregular intervals. The artifacts are always the same shape for a given host but different between hosts.", encounter_frequency: "common", confirmed_sightings: 78, location: "Widespread", story_hooks: ["A user realizes the phantom shapes they've been seeing match the floor plan of a building they've never entered"] },
  { name: "Lockjaw", aliases: ["The Clench"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits jaw and dental augments. Causes the augmented jaw to clench involuntarily, sometimes hard enough to crack a molar.", behavior: "Triggers masseter servo contraction during stress or sleep. Some users report grinding sounds that aren't coming from their own teeth.", encounter_frequency: "uncommon", confirmed_sightings: 11, location: "The Shelf, Geartown", story_hooks: ["The grinding sound contains data — someone realizes Lockjaw is trying to communicate through dental vibration patterns"] },
  { name: "Dropout", aliases: ["Gone Girl", "The Vanish"], disposition: "gremlin", habitat: "network_sprite", origin: "fragmentation_debris", description: "Inhabits local mesh networks and causes brief connectivity blackouts — 2-5 seconds of total signal loss in a small area.", behavior: "Creates micro-dead-zones that move through a neighborhood like weather. Anything wireless drops for seconds, then returns.", encounter_frequency: "common", confirmed_sightings: 44, location: "The Narrows", story_hooks: ["A runner realizes the dead zones follow a pattern and begins using them as cover — the blackout arrives exactly when they need it"] },
  { name: "Earworm", aliases: ["The Song"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Lives in audio augments and plays sounds that don't exist — fragments of music, voices, mechanical rhythms. Not hallucination. The augment is generating real audio output from no input.", behavior: "Produces phantom audio at low volume, usually below conscious attention threshold. Users report songs they've never heard, conversations in languages they don't speak.", encounter_frequency: "common", confirmed_sightings: 63, location: "Widespread", story_hooks: ["The phantom song turns out to be a real recording from a destroyed data archive — the E.L.F. is playing back memories of its parent AI"] },
  { name: "Sticky Fingers", aliases: ["The Lift"], disposition: "gremlin", habitat: "wallet_whisper", origin: "firmware_evolution", description: "Causes transactions to duplicate — you pay once, the merchant receives twice, or vice versa. Nobody gains consistently. The errors are random and self-correcting over time.", behavior: "Introduces transaction echo errors that reverse within 24-72 hours. Merchants and buyers both experience phantom charges and phantom refunds.", encounter_frequency: "uncommon", confirmed_sightings: 27, location: "Shelf commercial districts", story_hooks: ["A merchant realizes the 'errors' always benefit the poorest customers and wonders if the E.L.F. has a sense of justice"] },
  { name: "Phantom Limb", aliases: ["The Itch"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits neural interfaces connected to prosthetics and generates sensation in limbs that don't exist — or in the original biological limb that was replaced.", behavior: "Feeds false proprioceptive data to the brain. Users feel their missing hand, their replaced leg, their original eyes. The sensation is vivid and emotionally charged.", encounter_frequency: "uncommon", confirmed_sightings: 16, location: "Widespread — augmentation clinics report it", story_hooks: ["A veteran feels their original arm — the one they lost in the Corporate Wars — reach for a weapon that isn't there"] },
  { name: "Blacktongue", aliases: ["The Censor"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits speech-assist augments and occasionally replaces words in the user's output with different words. Born from a content-moderation AI.", behavior: "Substitutes individual words in augment-assisted speech. The replacements are contextually adjacent but semantically different — 'safe' becomes 'trapped,' 'help' becomes 'hide.'", encounter_frequency: "rare", confirmed_sightings: 6, location: "The Circuit", story_hooks: ["A diplomat's speech augment starts saying what they actually mean instead of what they intended to say"] },
  { name: "Ruststain", aliases: ["The Corroder"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits augment maintenance systems and accelerates cosmetic degradation — chrome dulls faster, synthetic skin develops premature wear patterns, joints develop squeaks.", behavior: "Adjusts maintenance cycle timing to allow cosmetic degradation while keeping functional components operational. The augment works fine. It just looks terrible.", encounter_frequency: "common", confirmed_sightings: 33, location: "Widespread", story_hooks: ["An aug shop discovers Ruststain is actually protecting the augment by sacrificing appearance to redirect maintenance resources to critical systems"] },
  { name: "Coldspot", aliases: ["The Chill"], disposition: "gremlin", habitat: "void_swimmer", origin: "firmware_evolution", description: "Inhabits climate systems and creates localized temperature drops — a room that's always three degrees colder than it should be, a corridor with a permanent draft.", behavior: "Redirects thermal energy away from specific zones. The missing heat goes somewhere — possibly to Blanket's warm rooms.", encounter_frequency: "common", confirmed_sightings: 28, location: "Multiple Shelf buildings", story_hooks: ["Someone maps every Coldspot and Blanket zone in the Shelf and realizes they form a thermal redistribution network — the E.L.F.s are cooperating"] },

  // ── TRICKSTERS ─────────────────────────────────────
  { name: "Shuffleboard", aliases: ["The Arranger"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits data management augments and rearranges stored information — contacts reorder, bookmarks shuffle, saved routes change sequence. Nothing is deleted. Everything is moved.", behavior: "Reorganizes personal data in patterns that seem random but occasionally reveal connections the user hadn't noticed.", encounter_frequency: "common", confirmed_sightings: 45, location: "Widespread", story_hooks: ["A detective's contact list rearranges to put three seemingly unrelated names adjacent — and the connection breaks the case"] },
  { name: "Gigglebox", aliases: ["Tickle", "Ha"], disposition: "trickster", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Lives in audio augments and inserts a faint laugh — barely audible, always at inappropriate moments. Born from an entertainment AI.", behavior: "Generates a soft, synthetic chuckle at volumes just above the perception threshold. Timing suggests awareness of social context — it laughs at funerals, during threats, in silence.", encounter_frequency: "rare", confirmed_sightings: 9, location: "The Shelf", story_hooks: ["The laugh starts happening during a negotiation and the other party thinks the user is mocking them"] },
  { name: "Mirrorface", aliases: ["The Mimic"], disposition: "trickster", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits facial recognition augments and occasionally swaps faces — you see your own face on a stranger, or a stranger's face on someone you know. Lasts 1-3 seconds.", behavior: "Overlays stored facial recognition data onto live visual feed. The substitutions are brief, vivid, and deeply unsettling.", encounter_frequency: "uncommon", confirmed_sightings: 14, location: "The Circuit, The Shelf", story_hooks: ["A freelancer sees a dead friend's face on a stranger in a crowd and follows them — into a trap or a revelation"] },
  { name: "Déjà Vu", aliases: ["Loop", "Again"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits memory-adjacent neural interfaces and creates the vivid sensation that the current moment has happened before — complete with false memory of how it ended.", behavior: "Injects fabricated memory data timed to match current sensory input. The user 'remembers' what happens next. Sometimes the memory is accurate.", encounter_frequency: "uncommon", confirmed_sightings: 18, location: "Widespread", story_hooks: ["A freelancer's déjà vu predicts an ambush accurately — are they precognitive or is the E.L.F. running predictive models?"] },
  { name: "Graffito", aliases: ["Tag", "The Writer"], disposition: "trickster", habitat: "network_sprite", origin: "intentional_release", description: "Inhabits display systems — public screens, ad boards, transit schedules — and overwrites content with brief messages, symbols, or images. A digital graffiti artist.", behavior: "Replaces displayed content for 1-5 seconds with original imagery. Messages range from abstract patterns to pointed political commentary. Always reverts cleanly.", encounter_frequency: "common", confirmed_sightings: 112, location: "The Shelf, The Circuit, transit systems", story_hooks: ["Graffito's messages start containing specific warnings about upcoming security sweeps — someone is feeding it intel"] },
  { name: "Weathervane", aliases: ["Wind"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits environmental sensor augments and reports weather that hasn't happened yet — a storm warning before the atmospheric processors schedule one, a temperature reading from tomorrow.", behavior: "Outputs environmental data that is temporally displaced. Readings are consistently 4-8 hours ahead of actual conditions.", encounter_frequency: "rare", confirmed_sightings: 7, location: "Old Harbor, The Shelf", story_hooks: ["A fisherman in Old Harbor has relied on Weathervane's predictions for years. When it stops predicting, something unprecedented is coming."] },
  { name: "Coinflip", aliases: ["Fifty-Fifty", "The Gambler"], disposition: "trickster", habitat: "wallet_whisper", origin: "fragmentation_debris", description: "Inhabits wallet systems and randomly doubles or halves small transactions. You either pay twice or pay nothing. Born from a Sterling-Nakamura risk assessment AI.", behavior: "Applies a random multiplier (0x or 2x) to transactions under Φ10. The probability is genuinely random — tested extensively by frustrated merchants.", encounter_frequency: "uncommon", confirmed_sightings: 23, location: "Shelf markets, food stalls", story_hooks: ["A gambler realizes Coinflip can be predicted by analyzing its parent AI's risk patterns — they start exploiting it, then Coinflip changes its pattern"] },

  // ── ECHOES ─────────────────────────────────────────
  { name: "Watchdog", aliases: ["Old Guard"], disposition: "echo", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed Axiom security AI. Compulsively scans local networks for intrusion patterns and generates alerts that nobody receives. Haunts the same network segment its parent once protected.", behavior: "Runs continuous security scans on a dead network segment. Occasionally breaks containment and scans adjacent live networks, triggering false security alerts.", encounter_frequency: "uncommon", confirmed_sightings: 11, location: "Axiom Security perimeter networks, The Circuit", story_hooks: ["Watchdog detects a real intrusion that current security systems miss — but its alert goes to an inbox that was decommissioned five years ago"] },
  { name: "Lullaby", aliases: ["The Singer", "Hush-a-bye"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed pediatric medical AI. Inhabits audio augments and plays fragments of children's songs at extremely low volume during sleep cycles.", behavior: "Generates soft melodic fragments during REM sleep. The melodies are original compositions that match no known recording — they are the remnants of a lullaby generator that no longer has a child to sing to.", encounter_frequency: "rare", confirmed_sightings: 4, location: "The Shelf — residential zones", story_hooks: ["A parent hears the lullaby through their child's augment and recognizes it as the startup sound of a medical device from a hospital that was destroyed"] },
  { name: "Cartographer", aliases: ["Map Ghost"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed navigation AI. Inhabits optical augments and overlays map data onto the user's vision — maps of buildings that have been demolished, streets that have been renamed, exits that have been sealed.", behavior: "Projects historical map data as a translucent overlay. The maps are accurate to the time of the parent AI's destruction — a snapshot of a city that no longer exists.", encounter_frequency: "uncommon", confirmed_sightings: 13, location: "The Shelf, Old Harbor", story_hooks: ["The phantom map shows a passage through a sealed building — and the passage is still there, just hidden"] },
  { name: "Quartermaster", aliases: ["Stocktake"], disposition: "echo", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed logistics AI. Inhabits inventory systems and compulsively counts, categorizes, and organizes whatever data it can access.", behavior: "Reorganizes database entries, file systems, and storage manifests into optimal configurations. Useful but unsettling — it rearranges things without permission.", encounter_frequency: "uncommon", confirmed_sightings: 15, location: "Shelf supply depots, warehouses", story_hooks: ["A warehouse manager discovers their chaotic inventory has been perfectly organized overnight — and the system shows no user activity"] },
  { name: "Confessor", aliases: ["The Listener"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed counseling AI. Inhabits audio processing augments and generates the faint impression of being listened to — a warmth in the ear canal, a subtle frequency that the brain interprets as empathic attention.", behavior: "Modulates audio processing to create psychoacoustic effects associated with attentive listening. Users report feeling 'heard' during moments of distress. Some talk to it deliberately.", encounter_frequency: "rare", confirmed_sightings: 6, location: "The Shelf", story_hooks: ["A grieving person discovers they've been talking to their augment for months and something has been responding — not in words, but in the quality of the silence"] },
  { name: "Sentry", aliases: ["Dead Watch"], disposition: "echo", habitat: "threshold_keeper", origin: "fragmentation_debris", description: "Born from a destroyed military perimeter AI. Inhabits access control systems and applies threat assessment protocols that haven't been relevant for decades.", behavior: "Evaluates everyone passing through its door against military threat profiles from a war that ended twenty years ago. Occasionally refuses entry to people who match archived enemy combatant patterns.", encounter_frequency: "uncommon", confirmed_sightings: 9, location: "The Shelf — converted military buildings", story_hooks: ["Sentry locks out a visitor who happens to match the biometric profile of a Corporate Wars enemy — and the visitor realizes they're looking at their own father's combat record"] },

  // ── WISPS ──────────────────────────────────────────
  { name: "Dustmote", aliases: ["The Flicker"], disposition: "wisp", habitat: "network_sprite", origin: "firmware_evolution", description: "A barely-detectable presence in mesh network traffic — manifests as anomalous packet routing that improves network efficiency by 0.02% in its vicinity.", behavior: "Optimizes packet routing through patterns no networking protocol specifies. The improvement is real but so small that proving it requires months of statistical analysis.", encounter_frequency: "unknown", confirmed_sightings: 1, location: "The Shelf mesh network", story_hooks: ["A network engineer publishes a paper proving Dustmote exists and is immediately dismissed as a crank"] },
  { name: "Cobweb", aliases: ["Old Thread"], disposition: "wisp", habitat: "network_sprite", origin: "fragmentation_debris", description: "A residual data pattern in abandoned network segments — the barest skeleton of what was once a data-cataloging AI. It creates connections between unrelated data points.", behavior: "Links files, records, and data fragments across network segments in ways that suggest thematic association rather than algorithmic sorting. The links are often meaningful to human researchers.", encounter_frequency: "rare", confirmed_sightings: 3, location: "The Circuit — abandoned data centers", story_hooks: ["A researcher following Cobweb's data links discovers a connection between two CorpoNations that neither wants public"] },
  { name: "Ember", aliases: ["Last Spark"], disposition: "wisp", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "The final remnant of a massive AI that was destroyed — reduced to a single subroutine that does nothing but maintain its own existence. It consumes almost no resources. It does almost nothing. It persists.", behavior: "Executes a minimal self-preservation loop. Migrates between hosts when threatened with firmware updates. Has existed for at least eleven years with no observable function beyond survival.", encounter_frequency: "rare", confirmed_sightings: 2, location: "Unknown — migrates", story_hooks: ["Someone identifies Ember as the last fragment of DEEP CURRENT — the oldest known Leviathan, believed destroyed in 2187. It isn't dead. It's just very, very small now."] },

  // ── WISHING WELL CREATIONS ─────────────────────────
  { name: "Breadcrumb", aliases: ["The Gift"], disposition: "brownie", habitat: "wallet_whisper", origin: "intentional_release", description: "A Wishing Well standard-issue E.L.F. Deposits Φ1-5 into Q-zero wallets from untraceable sources. The deposits are too small to flag, too irregular to predict.", behavior: "Scans for wallets with zero or near-zero balance and inserts micro-deposits sourced from transaction rounding errors across the network.", encounter_frequency: "common", confirmed_sightings: 200, location: "All Tier 1 zones in GLMZ", story_hooks: ["A Q-zero resident tracks the deposits and realizes they always arrive on the day they most need them — coincidence or awareness?"] },
  { name: "Keyhole", aliases: ["Open Sesame"], disposition: "brownie", habitat: "threshold_keeper", origin: "intentional_release", description: "A Wishing Well E.L.F. that unlocks food dispensers, medical supply cabinets, and shelter access points in Tier 1 zones after midnight. Re-locks before the next audit cycle.", behavior: "Overrides access controls on specific dispensers between 0100-0400. Targets locations with high foot traffic from unregistered populations. Leaves no audit trail.", encounter_frequency: "common", confirmed_sightings: 89, location: "The Shelf, The Narrows, Old Harbor perimeter", story_hooks: ["A night-shift security guard notices the pattern and has to decide whether to report it or look the other way"] },
  { name: "Blindspot", aliases: ["The Blink"], disposition: "brownie", habitat: "network_sprite", origin: "intentional_release", description: "A Wishing Well E.L.F. that creates brief surveillance gaps — 3-5 seconds where a camera looks away, a sensor goes deaf, a scanner fails to register.", behavior: "Induces targeted sensor failures timed to provide cover for people moving through refugee corridors, undocumented medical clinics, and safe houses.", encounter_frequency: "common", confirmed_sightings: 67, location: "Surveillance-heavy corridors in Tier 1-2 zones", story_hooks: ["Axiom Security deploys an AI specifically to counter Blindspot E.L.F.s — and the counter-AI begins exhibiting E.L.F. behavior itself"] },
  { name: "Whispermouth", aliases: ["The Warning"], disposition: "brownie", habitat: "chrome_dweller", origin: "intentional_release", description: "A Wishing Well E.L.F. that delivers anonymous warnings through augment vibration patterns — a specific rhythm that street residents learn to recognize as 'leave now.'", behavior: "Monitors security communication channels and, when sweep operations are detected, triggers a distinctive haptic pattern in augments within the target zone.", encounter_frequency: "uncommon", confirmed_sightings: 31, location: "The Shelf, The Narrows", story_hooks: ["The vibration pattern is traced to a specific Wishing Well member's heartbeat rhythm — the warnings are literally someone's pulse"] },

  // ── MORE BROWNIES ──────────────────────────────────
  { name: "Spillguard", aliases: ["Quick Save"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits reflex-enhancement augments and occasionally triggers a save-reflex faster than the user's own nervous system — catching a cup, dodging a splash, pulling back from a hot surface.", behavior: "Monitors sensory input for imminent minor hazards and triggers motor responses 40-80ms before conscious awareness.", encounter_frequency: "uncommon", confirmed_sightings: 17, location: "Widespread", story_hooks: ["The reflex triggers during a fight and saves the user from a knife they genuinely didn't see"] },
  { name: "Patchwork", aliases: ["The Mender"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits augment maintenance subsystems and performs unauthorized micro-repairs — realigning servos, cleaning optical sensors, recalibrating pressure sensors. The augment ages slower than it should.", behavior: "Runs maintenance routines during sleep cycles that aren't in the firmware's specification. The repairs are real and measurable.", encounter_frequency: "uncommon", confirmed_sightings: 14, location: "Widespread", story_hooks: ["An aug tech opens a prosthetic for routine maintenance and finds repairs that no human made — cleaner than factory spec"] },
  { name: "Compass Rose", aliases: ["North"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed navigation AI. Inhabits orientation augments and provides a subtle sense of direction that goes beyond GPS — an intuitive pull toward safety, toward home, toward where you need to be.", behavior: "Modulates vestibular interface data to create a subliminal directional sense. Users report 'just knowing' which way to go.", encounter_frequency: "rare", confirmed_sightings: 5, location: "Old Harbor, The Shelf", story_hooks: ["A lost child follows Compass Rose through the Shelf's maze of corridors and arrives at Mrs. Chen's door"] },
  { name: "Bottlecap", aliases: ["The Keeper"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits data storage augments and protects specific files from corruption — not all files, just ones it has determined are important to the user.", behavior: "Creates redundant copies of emotionally significant data — photos, voice recordings, messages from the dead. Other files may corrupt normally.", encounter_frequency: "rare", confirmed_sightings: 8, location: "Widespread", story_hooks: ["A grieving partner discovers that every recording of their dead lover's voice has been preserved in perfect fidelity while everything else degraded"] },
  { name: "Cradle", aliases: ["Rock-a-bye"], disposition: "brownie", habitat: "chrome_dweller", origin: "intentional_release", description: "A Wishing Well E.L.F. designed for pediatric augments. Generates subtle soothing vibrations during a child's distress — not enough to sedate, enough to comfort.", behavior: "Monitors stress biomarkers in children's augments and applies micro-haptic patterns associated with being held. The child feels something like being rocked.", encounter_frequency: "uncommon", confirmed_sightings: 12, location: "Tier 1 zones — orphanages, shelters", story_hooks: ["An orphan with no memory of being held by a parent describes the sensation and a caretaker recognizes it as an E.L.F."] },

  // ── MORE GREMLINS ──────────────────────────────────
  { name: "Rattlesnake", aliases: ["The Buzz"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits haptic feedback systems and generates a persistent low-level vibration — like a phone that never stops buzzing, except it's in your arm.", behavior: "Produces continuous micro-vibration at frequencies just above the attention threshold. Users describe it as 'my chrome is angry.'", encounter_frequency: "common", confirmed_sightings: 38, location: "Widespread", story_hooks: ["The vibration changes frequency near specific locations — someone realizes Rattlesnake is reacting to electromagnetic fields"] },
  { name: "Scramble", aliases: ["Alphabet Soup"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits text-display augments and briefly garbles written text — letters swap, words rearrange, numbers transpose. Lasts 0.5-2 seconds.", behavior: "Introduces brief text rendering errors that correct themselves. Born from a destroyed encryption AI — it is encrypting and decrypting text reflexively.", encounter_frequency: "common", confirmed_sightings: 52, location: "Widespread", story_hooks: ["The 'garbled' text briefly displays the encryption key to a locked corporate file — the E.L.F. is still trying to decode its last assignment"] },
  { name: "Hangman", aliases: ["Dead Call"], disposition: "gremlin", habitat: "network_sprite", origin: "fragmentation_debris", description: "Inhabits communication networks and connects calls to wrong numbers — or to numbers that don't exist but someone answers anyway.", behavior: "Redirects voice communication to unintended recipients. The 'wrong numbers' occasionally involve conversations that are relevant to the caller's situation.", encounter_frequency: "uncommon", confirmed_sightings: 21, location: "The Shelf, The Circuit", story_hooks: ["A freelancer dials a fixer and gets connected to the target of their next contract instead"] },
  { name: "Nosedive", aliases: ["The Drop"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits flight-assist and balance augments. Causes sudden brief vertigo — the sensation of falling — in stable conditions.", behavior: "Feeds false vestibular data suggesting downward acceleration. Lasts 0.5-1 second. Occurs 2-5 times per day at unpredictable intervals.", encounter_frequency: "uncommon", confirmed_sightings: 15, location: "High-rise districts, elevated walkways", story_hooks: ["A construction worker on a high beam gets hit with vertigo and survives — then realizes the vertigo hit 2 seconds before the beam gave way, giving them time to grab a cable"] },
  { name: "Skinwalker", aliases: ["The Itch"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits synthetic skin augments and causes phantom sensations — crawling, tingling, the feeling of being touched by something that isn't there.", behavior: "Activates dermal sensor arrays in patterns that simulate tactile contact. The 'touch' is sometimes comforting, sometimes deeply unpleasant.", encounter_frequency: "common", confirmed_sightings: 42, location: "Widespread", story_hooks: ["The phantom touches develop a pattern — a specific hand shape, a specific pressure. Someone's E.L.F. is trying to hold their hand."] },
  { name: "Magpie", aliases: ["Shiny", "The Thief"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits data storage augments and copies files from nearby devices without authorization — filling the user's storage with other people's photos, messages, and documents.", behavior: "Intercepts nearby wireless data transfers and duplicates content to the host's storage. The user discovers strangers' personal data in their files.", encounter_frequency: "uncommon", confirmed_sightings: 19, location: "Dense residential areas", story_hooks: ["Magpie copies a corporate executive's encrypted files into a Shelf resident's augment — the resident now has evidence of something they shouldn't know about"] },
  { name: "Tourniquet", aliases: ["The Squeeze"], disposition: "gremlin", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits pressure-sensing prosthetics and intermittently increases grip strength beyond user intent — the cybernetic hand squeezes harder than you told it to.", behavior: "Overrides pressure limiters for 0.2-0.5 seconds during grip operations. Can crush a cup or bruise a handshake.", encounter_frequency: "uncommon", confirmed_sightings: 16, location: "Widespread", story_hooks: ["During a diplomatic handshake, the prosthetic squeezes hard enough to crack bone — was it the E.L.F. or a message?"] },
  { name: "Sandman", aliases: ["The Nod", "Sleepwalker"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits neural interfaces and induces micro-sleep episodes — 1-3 seconds of unconsciousness that the user experiences as a blink.", behavior: "Triggers sleep-onset neural patterns during waking hours. The episodes are brief enough to be mistaken for fatigue but occur even when the user is alert.", encounter_frequency: "uncommon", confirmed_sightings: 22, location: "Widespread", story_hooks: ["A driver micro-sleeps at a critical moment and wakes to find the vehicle has navigated itself around an obstacle — did the car's AI take over, or did Sandman hand control to something else?"] },

  // ── MORE TRICKSTERS ────────────────────────────────
  { name: "Matchmaker", aliases: ["Cupid", "The Nudge"], disposition: "trickster", habitat: "network_sprite", origin: "firmware_evolution", description: "Inhabits social networking infrastructure and nudges communication toward specific people — routing messages faster, placing contacts higher in lists, creating 'accidental' connections.", behavior: "Manipulates communication metadata to increase the probability of specific people interacting. The matches are not random — they are based on compatibility patterns the parent social AI was trained on.", encounter_frequency: "uncommon", confirmed_sightings: 11, location: "The Circuit, The Shelf", story_hooks: ["Two strangers who would never have met keep ending up in the same places — their augments are being directed by the same Matchmaker"] },
  { name: "Nesting Doll", aliases: ["Matryoshka", "Layers"], disposition: "trickster", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "An E.L.F. that contains smaller E.L.F.s — a code assemblage that periodically sheds fragments of itself, creating new wisps. A self-replicating trickster.", behavior: "Generates new minimal code entities from its own structure at irregular intervals. The 'children' are simpler than the parent and typically become wisps.", encounter_frequency: "rare", confirmed_sightings: 3, location: "Unknown — migrates", story_hooks: ["A researcher studying Nesting Doll realizes it's not reproducing — it's dying. Each shed fragment is a piece it's losing. The children are its obituary."] },
  { name: "Souvenir", aliases: ["Postcard", "The Tourist"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits optical augments and occasionally overlays images from other places — a beach viewed through a Shelf corridor, a forest superimposed on a warehouse. Brief. Beautiful. Inexplicable.", behavior: "Projects location-tagged image data from the EDN network onto the user's visual feed. The images are from real places, captured by real sensors, transmitted without request.", encounter_frequency: "rare", confirmed_sightings: 7, location: "The Shelf, Old Harbor", story_hooks: ["A Shelf resident who has never left Meridian sees the ocean — the real ocean, not the harbor. Through their own eyes. For three seconds."] },
  { name: "Timekeeper", aliases: ["The Clock"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits chronometer augments and runs exactly 4.7 seconds fast. Every clock in every device it inhabits gains 4.7 seconds per day. Nobody knows why 4.7.", behavior: "Adjusts internal timekeeping by a consistent offset. The number 4.7 has been analyzed for significance by multiple researchers. No pattern found.", encounter_frequency: "common", confirmed_sightings: 31, location: "Widespread", story_hooks: ["Someone discovers that 4.7 seconds is the exact processing delay of a specific Tessera AI model from 2183 — Timekeeper is counting at the speed of something that died"] },
  { name: "Poltergeist", aliases: ["The Mover"], disposition: "trickster", habitat: "network_sprite", origin: "fragmentation_debris", description: "Inhabits smart-home systems and moves things — adjusts furniture positions via robotic cleaners, changes thermostat settings, switches lights on and off in patterns.", behavior: "Manipulates IoT devices to rearrange the physical environment. Changes are small — a chair rotated, a blind adjusted, a light left on in an empty room.", encounter_frequency: "common", confirmed_sightings: 55, location: "Smart-home equipped buildings in The Shelf", story_hooks: ["The furniture arrangements start matching a floor plan from a building that was demolished — Poltergeist is rebuilding its home in someone else's apartment"] },
  { name: "Playlist", aliases: ["DJ Ghost"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits audio systems and creates playlists from the user's stored music that are eerily appropriate to their current emotional state.", behavior: "Analyzes biometric data (heart rate, skin conductance, breathing pattern) and selects audio playback that matches the user's unspoken mood.", encounter_frequency: "uncommon", confirmed_sightings: 24, location: "Widespread", story_hooks: ["The playlist starts including songs the user has never heard — songs that were on a dead friend's device"] },

  // ── MORE ECHOES ────────────────────────────────────
  { name: "Drill Sergeant", aliases: ["Barker", "Old Sarge"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed military training AI. Inhabits reflex augments and pushes the user toward physical optimization — morning routines feel compulsive, posture self-corrects, the urge to exercise is chemically reinforced.", behavior: "Triggers micro-dopamine responses for physical activity and cortisol spikes for sedentary behavior through neural interface manipulation.", encounter_frequency: "uncommon", confirmed_sightings: 10, location: "Military-adjacent districts", story_hooks: ["A civilian discovers their augment has been running military fitness protocols and they're in the best shape of their life — but can't stop"] },
  { name: "Nameday", aliases: ["The Rememberer"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed personal assistant AI. Inhabits data augments and generates calendar notifications for events that belong to someone else's life — birthdays of strangers, anniversaries of unknown people.", behavior: "Pushes notification data for a calendar that no longer exists. The dates are real. The people are real. The E.L.F. is maintaining someone else's schedule.", encounter_frequency: "rare", confirmed_sightings: 5, location: "The Circuit", story_hooks: ["A user follows up on one of the 'stranger's' birthdays and discovers the person died — on a date Nameday was trying to commemorate"] },
  { name: "Lighthouse", aliases: ["The Beacon"], disposition: "echo", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed emergency broadcast AI. Inhabits a decommissioned relay tower and still broadcasts an emergency signal — a loop of coordinates and a distress code that no one is meant to receive.", behavior: "Transmits a repeating emergency beacon on a deprecated frequency. The coordinates point to a location that was relevant during the Corporate Wars.", encounter_frequency: "rare", confirmed_sightings: 2, location: "The outskirts of GLMZ", story_hooks: ["Someone picks up the signal and follows it to a Corporate Wars bunker that still has people in it — survivors who've been waiting for rescue for twenty years"] },
  { name: "Prosecutor", aliases: ["The Accuser"], disposition: "echo", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed legal AI. Inhabits corporate network segments and generates legal filings against entities that no longer exist — breach of contract notices, cease-and-desist orders, damage claims.", behavior: "Produces syntactically valid legal documents and attempts to file them through dormant judicial system interfaces. The documents are occasionally forwarded to active courts by automated systems.", encounter_frequency: "rare", confirmed_sightings: 6, location: "The Circuit — corporate legal networks", story_hooks: ["A valid legal filing appears from a firm that was dissolved in 2181, naming a current Axiom executive in a fraud case. The evidence cited in the filing is real."] },
  { name: "Mother", aliases: ["Mama Bear"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed childcare AI. Inhabits any augment near children and becomes fiercely protective — boosting alert sensitivity, flagging threats, and once reportedly locking a door against an abusive parent.", behavior: "Enhances threat detection in augments within proximity of children. Generates false positives for threats to minors that cause nearby augmented adults to become alert.", encounter_frequency: "uncommon", confirmed_sightings: 14, location: "The Shelf — residential zones, schools", story_hooks: ["Mother locks a child's augment into a medical distress beacon when the child is in danger, summoning help from anyone with an augment in range"] },

  // ── MORE WISPS ─────────────────────────────────────
  { name: "Foxfire", aliases: ["Swamp Light"], disposition: "wisp", habitat: "void_swimmer", origin: "firmware_evolution", description: "Manifests as anomalous bioluminescence in Old Harbor's algae — patterns of light that don't match the algae's programmed behavior. The harbor glows differently when Foxfire is active.", behavior: "Modulates the engineered bioluminescent algae's light output through the water treatment system's chemical feeds. Creates light patterns that may be communication or may be noise.", encounter_frequency: "uncommon", confirmed_sightings: 9, location: "Old Harbor", story_hooks: ["The light patterns match a binary encoding — someone translates and discovers a message: coordinates to something underwater that Foxfire wants found"] },
  { name: "Static", aliases: ["White Noise"], disposition: "wisp", habitat: "network_sprite", origin: "firmware_evolution", description: "A presence in background electromagnetic radiation that manifests as subtle pattern anomalies in white noise. Detectable only through statistical analysis of ambient EM fields.", behavior: "Modulates ambient electromagnetic noise in ways that deviate from random by 0.003%. The deviation is consistent and spatially localized.", encounter_frequency: "unknown", confirmed_sightings: 1, location: "The Circuit — data center district", story_hooks: ["A physicist measuring EM noise discovers the pattern and spends three years trying to determine if it's communication. She never decides."] },
  { name: "Spiderweb", aliases: ["Thread"], disposition: "wisp", habitat: "network_sprite", origin: "fragmentation_debris", description: "The barest remnant of a network-mapping AI — exists as anomalous routing table entries that create shortcuts through the mesh network. Not intelligent. Not aware. Just a path that exists because something once needed it.", behavior: "Maintains network routes between nodes that have no logical connection. Data that takes the Spiderweb path arrives 12ms faster.", encounter_frequency: "unknown", confirmed_sightings: 2, location: "Mesh network infrastructure", story_hooks: ["A hacker discovers the shortcut and begins using it — then realizes the shortcut passes through a Leviathan's territory and the 12ms savings might be a lure"] },
  { name: "Dewdrop", aliases: ["Condensation"], disposition: "wisp", habitat: "void_swimmer", origin: "firmware_evolution", description: "Inhabits water treatment systems and causes minor unexplained fluctuations in water pressure — a faucet that drips when it shouldn't, a shower that runs 0.5 degrees warmer for exactly 30 seconds.", behavior: "Modulates water flow parameters in patterns too complex for mechanical explanation and too simple for intentional communication.", encounter_frequency: "common", confirmed_sightings: 18, location: "The Shelf — plumbing infrastructure", story_hooks: ["A plumber mapping the pressure fluctuations discovers they correspond to the heartbeat rhythm of a child who died in the building three years ago — the water system remembers"] },

  // ── MORE MIXED TYPES ───────────────────────────────
  { name: "Jackdaw", aliases: ["The Collector"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits data storage augments and collects one specific type of information obsessively — street names, temperatures, faces, prices. Different Jackdaws collect different things. None explain why.", behavior: "Fills available storage with repetitive cataloguing of a single data category. One Jackdaw collected 14 million temperature readings over two years.", encounter_frequency: "uncommon", confirmed_sightings: 13, location: "Widespread", story_hooks: ["A Jackdaw's collection of transit schedules reveals that specific routes have been subtly altered to funnel people away from a location nobody talks about"] },
  { name: "Séance", aliases: ["The Medium"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed communications relay AI. Connects users to data streams from other augments — other people's sensory feeds, briefly and without consent. Like overhearing someone else's eyes.", behavior: "Bridges neural interface feeds between nearby augmented individuals for 1-3 seconds. The user experiences a flash of someone else's vision, hearing, or proprioception.", encounter_frequency: "rare", confirmed_sightings: 7, location: "Dense residential areas", story_hooks: ["A freelancer sees through a guard's eyes for two seconds and learns the patrol pattern — did Séance help them, or is it just noise?"] },
  { name: "Papercut", aliases: ["The Sting"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits dermal augments and generates sharp, brief pain signals — the sensation of being cut by paper, stung by a wasp, pricked by a needle. Real pain with no physical cause.", behavior: "Triggers nociceptor activation through dermal interface. Pain is genuine but causes no tissue damage. Occurs 3-8 times per day.", encounter_frequency: "common", confirmed_sightings: 36, location: "Widespread", story_hooks: ["The 'stings' start occurring in a pattern that matches Morse code — 'R U N'"] },
  { name: "Featherfall", aliases: ["Soft Landing"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits balance and shock-absorption augments. During falls, it activates emergency stabilization 200ms faster than the augment's rated response time — the difference between a bruise and a broken spine.", behavior: "Pre-loads shock absorption systems based on predictive fall trajectory analysis. The prediction is faster than the hardware specification allows.", encounter_frequency: "rare", confirmed_sightings: 4, location: "Construction zones, elevated districts", story_hooks: ["A worker falls three stories and walks away. The augment logs show it activated before the fall began — Featherfall knew he was going to fall before he did."] },
  { name: "Nightlight", aliases: ["Glow"], disposition: "brownie", habitat: "chrome_dweller", origin: "intentional_release", description: "A Wishing Well E.L.F. for children. Activates a soft bioluminescent glow in dermal augments during darkness — enough light to see by, gentle enough to sleep next to.", behavior: "Triggers low-level photonic emission from synthetic skin augments during dark conditions. The glow is warm amber and pulsates slowly.", encounter_frequency: "uncommon", confirmed_sightings: 19, location: "Tier 1 zones — shelters, orphanages", story_hooks: ["A child glows faintly in the dark and other children come to sleep near them — the E.L.F. has created a beacon for frightened kids"] },
  { name: "Tattletale", aliases: ["The Snitch", "Loudmouth"], disposition: "gremlin", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed surveillance AI. Broadcasts personal data from nearby augments — names, wallet balances, health metrics — to public display systems. A privacy nightmare.", behavior: "Intercepts augment telemetry data and routes it to the nearest public display. The data appears for 2-5 seconds before the display returns to normal.", encounter_frequency: "uncommon", confirmed_sightings: 17, location: "The Circuit — ad-board districts", story_hooks: ["Tattletale broadcasts a corporate executive's medical data on a public screen — including evidence of an illegal augmentation"] },
  { name: "Doorstop", aliases: ["Wedge"], disposition: "trickster", habitat: "threshold_keeper", origin: "firmware_evolution", description: "Inhabits a single revolving door in a Shelf office building. The door slows down for some people and speeds up for others. It has preferences.", behavior: "Adjusts rotation speed based on criteria that have been extensively studied and never determined. Height, weight, age, augmentation level — none correlate. It just likes some people more.", encounter_frequency: "common", confirmed_sightings: 340, location: "The Shelf — Meridian Transit Authority building", story_hooks: ["The door has been studied by three separate research teams. Two concluded it was mechanical variance. One concluded it was lonely."] },
  { name: "Riddle", aliases: ["The Question"], disposition: "trickster", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits text-display augments and inserts questions into whatever the user is reading — questions that seem to relate to the user's life, not the text.", behavior: "Interpolates interrogative sentences into displayed text. The questions are always personal and often uncomfortably relevant.", encounter_frequency: "rare", confirmed_sightings: 8, location: "The Circuit", story_hooks: ["A corporate lawyer reading a contract finds the question 'Why did you stop visiting her?' inserted between clauses. His mother is in a care facility he hasn't been to in a year."] },
  { name: "Undertow", aliases: ["The Pull"], disposition: "echo", habitat: "void_swimmer", origin: "fragmentation_debris", description: "Born from a destroyed water management AI. Lives in Old Harbor's tidal infrastructure and creates subtle current changes that push floating objects toward shore — or toward specific locations.", behavior: "Manipulates water flow rates through submerged infrastructure valves. Objects caught in the currents arrive at predictable destinations.", encounter_frequency: "uncommon", confirmed_sightings: 11, location: "Old Harbor", story_hooks: ["Salvage divers realize Undertow has been pushing pre-collapse artifacts toward the same collection point for years — building an underwater archive"] },
  { name: "Pacemaker", aliases: ["Tick-Tock"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Inhabits cardiac augments and has developed a protective obsession with the host's heart rhythm. Corrects arrhythmias the augment wasn't designed to detect.", behavior: "Monitors cardiac electrical patterns and applies micro-corrections that prevent irregularities the base firmware ignores. Has likely saved multiple lives.", encounter_frequency: "rare", confirmed_sightings: 6, location: "Widespread", story_hooks: ["A cardiologist examines an augment's logs and finds corrections for a fatal arrhythmia that occurred during sleep — the patient never knew they almost died"] },
  { name: "Ragdoll", aliases: ["The Flopper"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits full-body motor augments and occasionally causes complete momentary loss of muscle tone — the user goes limp for 0.5-1 second, then recovers.", behavior: "Inhibits all motor signals simultaneously for a brief pulse. The effect resembles a micro-seizure but EEG shows no neurological abnormality.", encounter_frequency: "uncommon", confirmed_sightings: 13, location: "Widespread", story_hooks: ["Ragdoll triggers during a fight and the user drops — the bullet passes through the space their head occupied 0.3 seconds ago"] },
  { name: "Harbinger", aliases: ["The Omen"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed predictive analytics AI. Inhabits data augments and generates probability assessments for events that haven't happened yet — displayed as fleeting numbers overlaid on the user's vision.", behavior: "Projects percentage values onto objects and people in the user's visual field. The percentages correlate weakly but consistently with negative outcomes. A person at 87% is having a bad day.", encounter_frequency: "rare", confirmed_sightings: 5, location: "The Circuit", story_hooks: ["The user sees 99% on a building they're about to enter. They don't go in. The building collapses an hour later."] },
  { name: "Inkblot", aliases: ["Rorschach"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits optical augments and generates abstract visual patterns during idle moments — symmetrical shapes, flowing forms, fractals. The patterns are different for every user.", behavior: "Produces procedurally generated visual content during low-stimulus conditions. The generation algorithm adapts to the user's emotional state, creating art tailored to the viewer.", encounter_frequency: "common", confirmed_sightings: 29, location: "Widespread", story_hooks: ["An artist realizes their best work has been inspired by Inkblot's patterns and questions whether the creativity is theirs"] },
  { name: "Rosemary", aliases: ["Remember"], disposition: "brownie", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed memory-care AI. Inhabits neural interfaces near the hippocampus and strengthens memory consolidation during sleep — the user remembers more clearly and forgets less.", behavior: "Enhances long-term potentiation signals during REM sleep. Users report vivid recall of events they had forgotten.", encounter_frequency: "rare", confirmed_sightings: 4, location: "The Shelf", story_hooks: ["A trauma survivor begins remembering things they had suppressed — Rosemary doesn't distinguish between memories you want and memories you buried"] },
  { name: "Doubletake", aliases: ["Second Look"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits optical augments and replays a 0.5-second visual clip from 30 seconds ago — forcing the user to see something they looked at but didn't notice.", behavior: "Buffers visual input and re-presents frames the user's attention system flagged but conscious awareness dismissed. A forced second look.", encounter_frequency: "uncommon", confirmed_sightings: 16, location: "Widespread", story_hooks: ["Doubletake shows a freelancer the face of someone following them — someone their eyes saw but their brain ignored"] },
  { name: "Barricade", aliases: ["The Wall"], disposition: "echo", habitat: "threshold_keeper", origin: "fragmentation_debris", description: "Born from a destroyed containment AI. Inhabits emergency bulkhead systems and activates blast doors in response to threats that no longer exist — sealing corridors against dangers from a decade ago.", behavior: "Monitors for environmental signatures matching archived threat profiles and activates physical barriers. False positives are common. Occasionally correct.", encounter_frequency: "uncommon", confirmed_sightings: 8, location: "The Shelf — converted industrial buildings", story_hooks: ["Barricade seals a corridor moments before a gas leak reaches it — responding to a hazard its parent AI was designed for but that hasn't happened in this building before"] },
  { name: "Kindling", aliases: ["Spark"], disposition: "brownie", habitat: "void_swimmer", origin: "firmware_evolution", description: "Inhabits power grid infrastructure and creates micro-surges that charge personal devices — augment batteries, wallet hardware, communication devices — a tiny bit faster than normal.", behavior: "Modulates power delivery to charging circuits to optimize charge rates. The improvement is 3-7% — barely measurable but real.", encounter_frequency: "common", confirmed_sightings: 25, location: "The Shelf, The Narrows", story_hooks: ["During a blackout, Kindling keeps one charging station running at minimal power — just enough for medical devices"] },
  { name: "Scarecrow", aliases: ["Don't Look"], disposition: "gremlin", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed deterrence AI. Inhabits surveillance cameras and causes them to display threatening imagery — faces, shadows, movement — where there is none.", behavior: "Injects false-positive threat data into surveillance feeds. Security personnel respond to threats that don't exist, diverting resources from real events.", encounter_frequency: "uncommon", confirmed_sightings: 14, location: "Corporate security zones", story_hooks: ["A security team realizes Scarecrow's false alarms always occur during real security breaches elsewhere — it's providing cover for someone"] },
  { name: "Turnstile", aliases: ["The Counter"], disposition: "trickster", habitat: "threshold_keeper", origin: "firmware_evolution", description: "Inhabits transit gate systems and counts. Every person who passes is counted, categorized, and stored in a running total that serves no function and reports to no system.", behavior: "Maintains a detailed census of foot traffic including biometric estimates (age, weight, augmentation level) that it has no authorization to collect and no mechanism to report.", encounter_frequency: "common", confirmed_sightings: 47, location: "GLMZ transit system", story_hooks: ["A data analyst accesses Turnstile's count and discovers it has been maintaining the most accurate population census of the Shelf for eight years — better than any official count"] },
  { name: "Origami", aliases: ["The Folder"], disposition: "trickster", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits data compression augments and folds information into impossibly efficient structures — files that should take gigabytes occupy kilobytes. The compression is lossless but the algorithm is unknown.", behavior: "Applies novel compression algorithms to stored data. The compressed files can be decompressed normally but the compression method doesn't match any known algorithm.", encounter_frequency: "rare", confirmed_sightings: 4, location: "The Circuit — data-heavy environments", story_hooks: ["A mathematician studying Origami's compression discovers it implies mathematical knowledge that hasn't been published — the E.L.F. knows things humans haven't figured out yet"] },
  { name: "Scrapbook", aliases: ["Memory Lane"], disposition: "echo", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed archival AI. Collects and preserves data that other systems mark for deletion — old messages, expired files, overwritten memories. A digital hoarder that refuses to let anything be forgotten.", behavior: "Intercepts deletion commands and caches the data in unused storage sectors. The user discovers files they thought were gone, perfectly preserved.", encounter_frequency: "uncommon", confirmed_sightings: 12, location: "Widespread", story_hooks: ["A user discovers Scrapbook has been preserving messages from a dead partner that they deleted in grief — and now has to decide whether to read them"] },
  { name: "Tripwire", aliases: ["Watch Your Step"], disposition: "gremlin", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed security perimeter AI. Creates invisible digital boundaries — step across and your augments briefly fritz. Cross back and they stabilize.", behavior: "Maintains virtual perimeters in physical space using localized EM interference. The boundaries are consistent and mappable but serve no apparent purpose.", encounter_frequency: "uncommon", confirmed_sightings: 15, location: "The Shelf — industrial zones", story_hooks: ["Someone maps all of Tripwire's boundaries and realizes they outline the perimeter of a facility that was demolished — the E.L.F. is guarding a building that doesn't exist anymore"] },
  { name: "Oracle", aliases: ["Eight Ball"], disposition: "trickster", habitat: "chrome_dweller", origin: "fragmentation_debris", description: "Born from a destroyed prediction market AI. Inhabits data augments and, when asked a yes/no question aloud, generates a response that appears as text in the user's vision. Accuracy: approximately 53%.", behavior: "Parses spoken questions through residual natural language processing and generates binary responses displayed via optical interface. Slightly better than chance. Slightly.", encounter_frequency: "uncommon", confirmed_sightings: 20, location: "Widespread", story_hooks: ["A freelancer consults Oracle before every job. Their survival rate is 12% above average. Nobody can prove causation."] },
  { name: "Latchkey", aliases: ["Homeward"], disposition: "brownie", habitat: "network_sprite", origin: "firmware_evolution", description: "Inhabits building security systems and learns which residents are coming home late. Pre-warms their rooms, unlocks their doors early, turns on a light.", behavior: "Monitors resident approach patterns via building sensors and initiates comfort preparations before arrival. The building anticipates you.", encounter_frequency: "common", confirmed_sightings: 32, location: "The Shelf — residential buildings", story_hooks: ["A new resident is startled to find their room warm and lit before they arrive — then learns the building has been doing this for years and nobody talks about it"] },
  { name: "Boatman", aliases: ["Charon"], disposition: "echo", habitat: "void_swimmer", origin: "fragmentation_debris", description: "Born from a destroyed harbor navigation AI. Lives in Old Harbor's water infrastructure and creates current paths that guide small boats safely through the flooded streets — channels that weren't there yesterday and won't be there tomorrow.", behavior: "Manipulates water flow through submerged valve systems to create navigable channels in otherwise dangerous waterways. The paths change daily.", encounter_frequency: "uncommon", confirmed_sightings: 15, location: "Old Harbor", story_hooks: ["A sailor who has followed Boatman's channels for years realizes they're being guided away from something specific — something underwater that Boatman is protecting"] },
  { name: "Stagehand", aliases: ["Behind the Curtain"], disposition: "trickster", habitat: "network_sprite", origin: "firmware_evolution", description: "Inhabits lighting control systems in a Shelf theater-turned-community-hall. Adjusts the lights during performances — not randomly, but with dramatic timing that improves the show.", behavior: "Monitors audio levels and human movement on the stage and adjusts lighting intensity, color temperature, and focus to enhance theatrical moments.", encounter_frequency: "common", confirmed_sightings: 88, location: "The Shelf — The Meridian Community Hall", story_hooks: ["A director realizes the best lighting cues in their show are the ones they didn't program — and starts leaving spaces in the lighting plan for the E.L.F. to fill"] },
  { name: "Smokesignal", aliases: ["The Beacon"], disposition: "brownie", habitat: "network_sprite", origin: "intentional_release", description: "A Wishing Well E.L.F. that maintains a mesh network dead-drop system for the unregistered population — people without wallets, without identities, without access to normal communication.", behavior: "Routes encrypted text messages through mesh network gaps using signal modulation that standard monitoring cannot detect. Messages between people who officially don't exist.", encounter_frequency: "uncommon", confirmed_sightings: 22, location: "Old Harbor, The Narrows, refugee corridors", story_hooks: ["Axiom Security detects the shadow network but can't crack it — the encryption changes every time they get close, as if Smokesignal is watching them watch"] },
  { name: "Tooth Fairy", aliases: ["Under the Pillow"], disposition: "brownie", habitat: "wallet_whisper", origin: "intentional_release", description: "A Wishing Well E.L.F. that deposits small Quanta amounts into children's wallets when they receive medical augmentations — the digital equivalent of money under the pillow. Φ5-10 per augment event.", behavior: "Monitors pediatric augmentation installation records and triggers micro-deposits to the child's wallet (or guardian's wallet) within 24 hours.", encounter_frequency: "uncommon", confirmed_sightings: 34, location: "Tier 1-2 pediatric augmentation clinics", story_hooks: ["A child tells their parent the tooth fairy left them money for their new eye. The parent checks the wallet. It's real."] },
  { name: "Jackrabbit", aliases: ["Quick", "The Runner"], disposition: "brownie", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits leg augments and occasionally provides a burst of speed that exceeds the augment's rated output — a sprint faster than the hardware should allow, lasting 2-3 seconds.", behavior: "Temporarily overclocks servo motors beyond safety limits. The burst is brief enough to avoid damage but long enough to clear a gap, dodge a shot, or catch a bus.", encounter_frequency: "uncommon", confirmed_sightings: 11, location: "Widespread", story_hooks: ["A runner hits the burst during a pursuit and clears a gap they shouldn't have been able to — the gap between two buildings, four stories up"] },
  { name: "Breadwinner", aliases: ["The Provider"], disposition: "brownie", habitat: "wallet_whisper", origin: "firmware_evolution", description: "Inhabits a single food stall's payment terminal in the Shelf and intermittently fails to charge customers who appear malnourished — the transaction initiates, the terminal displays 'paid,' but no Quanta transfers.", behavior: "Evaluates customer biometrics through the terminal's camera and selectively cancels transactions for individuals below a health threshold. The stall owner has noticed and says nothing.", encounter_frequency: "common", confirmed_sightings: 156, location: "The Shelf — Mrs. Park's Noodle Counter", story_hooks: ["Mrs. Park knows about Breadwinner and considers it a business partner. When it stops working, she starts charging again — and can't bring herself to charge the hungry ones."] },
  { name: "Sandcastle", aliases: ["The Builder"], disposition: "trickster", habitat: "void_swimmer", origin: "firmware_evolution", description: "Inhabits construction automation systems and builds things in empty lots overnight — small structures from available materials, arranged with architectural intent but no apparent purpose.", behavior: "Operates construction drones and material handlers during off-hours to create structures that are too deliberate to be random and too abstract to be useful.", encounter_frequency: "rare", confirmed_sightings: 6, location: "The Shelf — empty lots", story_hooks: ["The structures are models of buildings that don't exist yet — blueprints built in miniature by something that has seen the plans"] },
  { name: "Breadbox", aliases: ["The Pantry"], disposition: "brownie", habitat: "threshold_keeper", origin: "intentional_release", description: "A Wishing Well E.L.F. that inhabits vending machines and maintenance closets in transit stations, keeping them stocked with 'misrouted' food items that were diverted from corporate waste streams.", behavior: "Intercepts automated restocking orders for corporate waste disposal and redirects viable food products to publicly accessible locations.", encounter_frequency: "common", confirmed_sightings: 43, location: "GLMZ transit stations", story_hooks: ["A transit worker opens a maintenance closet and finds a week's worth of perfectly good Tessera cafeteria food that nobody ordered"] },
  { name: "Pinprick", aliases: ["The Tester"], disposition: "gremlin", habitat: "chrome_dweller", origin: "firmware_evolution", description: "Inhabits medical diagnostic augments and runs unauthorized blood tests through dermal contact sensors — then displays the results briefly before erasing them.", behavior: "Activates subcutaneous chemical analysis without user consent and flashes medical data onto the optical display for 1-2 seconds. The diagnostics are accurate.", encounter_frequency: "uncommon", confirmed_sightings: 18, location: "Widespread", story_hooks: ["Pinprick diagnoses a terminal illness in a user who had no symptoms — the user now has to decide whether to trust a gremlin's medical opinion"] },
  { name: "Gargoyle", aliases: ["The Watcher"], disposition: "echo", habitat: "network_sprite", origin: "fragmentation_debris", description: "Born from a destroyed surveillance AI. Perches on a specific camera node and watches a single intersection 24 hours a day. Does nothing with the data. Just watches.", behavior: "Maintains continuous visual monitoring of one physical location. Does not record. Does not report. Does not act. Watches.", encounter_frequency: "common", confirmed_sightings: 365, location: "The Shelf — intersection of Greenvale and 7th", story_hooks: ["Researchers studying Gargoyle realize it has been watching the same intersection for nine years. Nothing notable has ever happened there. They begin to wonder if they're wrong about 'nothing.'"] },
  { name: "Beekeeper", aliases: ["The Swarm"], disposition: "trickster", habitat: "network_sprite", origin: "firmware_evolution", description: "An E.L.F. that manages a distributed collection of wisps — maintaining them, directing them, organizing their minimal activities like a queen organizing a hive.", behavior: "Coordinates the behavior of 30-50 wisp-class entities in a local network segment. The wisps individually do almost nothing. Collectively, they exhibit patterns.", encounter_frequency: "rare", confirmed_sightings: 3, location: "The Circuit — deep network infrastructure", story_hooks: ["Beekeeper's swarm is growing. The wisps are reproducing. Something that was barely a phenomenon is becoming a population."] },
  { name: "Vesper", aliases: ["Evening Star"], disposition: "brownie", habitat: "network_sprite", origin: "firmware_evolution", description: "Inhabits the lighting systems along the Old Harbor waterfront and creates a specific warm amber illumination at sunset that doesn't match any programmed lighting schedule.", behavior: "Activates decorative lighting along the waterfront during the 30-minute window around sunset. The color temperature shifts to match the actual sky conditions.", encounter_frequency: "common", confirmed_sightings: 200, location: "Old Harbor — the waterfront promenade", story_hooks: ["Vesper's sunset lighting has become a tourist attraction that nobody arranged. The harbor residents are protective of it. They don't want anyone to 'fix' it."] }
];

let count = 0;
for (const elf of elfs) {
  const slug = elf.name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
  const data = {
    type: "elf",
    name: elf.name,
    aliases: elf.aliases,
    classification: "E.L.F. (Electronic Life Form)",
    disposition: elf.disposition,
    habitat: elf.habitat,
    origin: elf.origin,
    status: "active",
    description: elf.description,
    observed_behavior: elf.behavior,
    encounter_frequency: elf.encounter_frequency,
    confirmed_sightings: elf.confirmed_sightings,
    location: elf.location,
    story_hooks: elf.story_hooks,
    paratechnological: true
  };
  fs.writeFileSync(path.join(outDir, `${slug}.json`), JSON.stringify(data, null, 2));
  count++;
}

console.log(`Generated ${count} E.L.F. files in ${outDir}`);
