SET QUOTED_IDENTIFIER ON;
UPDATE Beats SET [Text]=N'Teo ran Dagny''s household first thing, before the driver readings, before anything else the morning owed her, because she''d promised herself the night before that she would and because putting it off a second time would have made the promise itself into a kind of dishonesty.

The number came back the way she''d expected it to and still managed to make her sit back from the desk a moment when it landed. Forty years of accumulated mass — furniture, books, four decades of photographs, the ordinary accretion of a life lived in one set of rooms longer than most people in Candelaria had been alive at all — ran to Φ4,800 on the jettison formula, the same formula that had set Priya''s Φ2,100 and Wen''s exempted zero, the largest single household figure Teo had entered into the ledger since she''d taken the job. Not close to the next-largest. Not by half.

She checked it twice, the way she checked every figure that surprised her, tracing the mass estimate back through the load survey she''d run in Household 12 herself, months ago, before any of this had a vote attached to it. The number held. It wasn''t a mistake, and it wasn''t a guess dressed up as precision. It was simply what forty years looked like, converted into the only unit Teo''s ledger had a column for.

She finished the DESCEND figure with that number sitting in it, ran the proportional split one more time across all forty-one households the way she''d run it a dozen times with the same eight hundred forty-seven thousand and eleven fewer completed rows, and watched Priya''s structural share move, for the first time since she''d opened this file, past the flat line she''d been treating as a ceiling instead of an average. Added to Priya''s existing Φ2,100 — hers regardless of any vote, guaranteed by the jettison program already running — the completed column put her total past eight thousand four hundred. Not by a distance that made the number feel inevitable. Past it, plainly, the way a level finally reads true after the last shim goes under a table leg nobody thought needed one.

She didn''t write an explanation into the posting. She''d learned, doing this every Monday for a year, that the postings that held up best were the ones that resisted the temptation to argue for themselves. She wrote the figures the way she always wrote them — forty-one lines, one per household, no names attached beyond the household number, Dagny''s line sitting where it belonged in the list instead of set apart or underlined, exactly as anonymous and exactly as legible as every other line above and below it — and pinned the full sheet beside the altitude number on the commons wall before the morning traffic through the passenger deck had properly started.

She stayed nearby for a while, not to watch the reaction, she told herself, though she knew that was only half true. A machinist from the third floor stopped, read the sheet top to bottom, and moved on without comment. The widow in 8-D stood longer, found her own household''s line, nodded once at whatever she found there, and left. Priya came by an hour later, alone, and Teo watched her find Household 12''s figure the way a person finds a number they''ve been braced for without knowing exactly what shape it would take, and watched her do, standing right there at the wall, the same subtraction Teo had already done twice at her own desk — Dagny''s allocation against the total, the total against the average, the average against Φ8,400 — and watched her arrive, silently, at the same answer.

Priya didn''t say anything to Teo. She didn''t need to. Her hand came up, briefly, to press flat against her sternum, the gesture Teo had learned to read months ago as someone holding a weight in place rather than gesturing, and then she turned and walked back toward the lift without a word, and Teo let her go without following, because there wasn''t anything left to add to a sheet that had already said, plainly and without her help, everything it had to say.

Wen read the same sheet an hour after that, on his way to the shop, and stood at Dagny''s line the way he''d stood at his own jigs the week before — not arguing with it, just looking at the weight of it, the way a man looks at a load he recognizes even when it isn''t his. He didn''t say anything either. Teo had stopped expecting anyone to. The sheet wasn''t built to be argued with. It was built to be true, and for one morning, hanging on the wall beside a number that read three hundred sixty-four meters, it was the truest thing in Candelaria, and it belonged, the way it always had, to no one in particular and to all forty-one households equally, whether they liked what it told them or not.

Teo was careful, standing there, not to let anyone read more into the sheet than it actually said. It wasn''t a promise. Dagny hadn''t voted yet, hadn''t said a word about the offer since the message she''d sent to the second meeting, and the figure on the wall was only what the formula returned if the vote passed and every household''s true mass entered the split the way the ledger assumed it would — a projection built honestly out of real numbers, not a guarantee that any of it would land the way the arithmetic wanted it to. She''d learned, over a year of Monday postings, that the difference between those two things mattered more than almost anything else she put on that wall, and she said so, quietly, to the one resident who asked her directly whether the sheet meant Priya''s shortfall was as good as closed. It wasn''t as good as closed. It was as good as possible, which was a smaller and more honest thing to promise, and she wasn''t going to let a wall of true figures pretend to be more certain than the vote that hadn''t happened yet.' WHERE Id='019F3AC8-397D-7DBA-AC48-4CDB516FBE3B';