SET QUOTED_IDENTIFIER ON;
UPDATE Beats SET [Text]=N'The common space had never held all forty-one households at once before tonight, not for any of the five meetings that had come before it, because a vote asked something none of the meetings had — that everyone show up, not just the ones with something to say.

Chairs had been brought in from three decks'' worth of storage, and even then people stood along both walls the way Teo always stood, though tonight she''d given up her usual stretch of wall to someone''s grandmother and found a spot instead near the vote table itself, where Wen''s jigs had sat three weeks ago and where, tonight, a plain wooden box sat in their place, slotted at the top, empty.

Sigrun didn''t open with a speech. She''d said everything there was to say three nights ago, word for word, and she said so now, briefly, before she said anything else. "I''m not going to read the offer again," she said. "You''ve all heard it as many times as I can read it. Tonight there''s one piece of business, and it isn''t discussion." She held up a single ballot card, blank, the same card every household had already been given that afternoon, one per household, numbered on the back where the co-op''s own record already logged which number belonged to which door. "Mark it yes or no. Fold it once. Household number stays on the back, same as it''s always been on every document this bloc''s ever filed — nothing about tonight is anonymous, and nothing about tonight needs to be. Bring it to the box yourselves. I''ll count them here, in front of you, with Teo, so nobody has to take either of our word for the total."

Nobody asked a question. There wasn''t one left to ask.

Teo watched them come forward, household by household, in no particular order, the way a room moves when nobody''s told it to line up — the machinist from the third floor, the widow from 8-D, a man Teo mostly knew by his door number who folded his card and held it a beat longer than most before letting it drop. She watched Priya come forward early, alone, her card already folded before she reached the box. She watched Wen come forward near the middle of the line, unhurried, the same economy of motion he brought to everything, and drop his card without looking at anyone. She watched Sigrun herself step up last of all, mark nothing on the card she''d been holding since the start of the meeting except her own household number and a line through both boxes at once, deliberate, unhidden, and set it into the box in full view of the room, because an abstention that happened in secret wasn''t the vote she''d told Teo she owed the process.

She did not watch for Dagny''s card specifically. She told herself that, and it was mostly true. Dagny came forward somewhere in the second half of the line, unremarkable among forty other households doing the same thing, folded her card the way everyone folded theirs, and returned to her seat without a word to anyone on either side of her.

When the box was full, Sigrun carried it to the small table at the front and opened it there, in front of the room, and she and Teo sorted the cards into three piles the way they''d agreed beforehand they would — not reading names aloud, not narrating who''d cast what, only building three stacks and counting each one twice before either of them trusted the total enough to say it out loud. It took longer than anyone in the room seemed to want it to take. Nobody spoke while it happened. The only sound Teo registered, standing that close to the box, was the room''s collective breathing and, faint under everything, the frame''s own Hush, steady, unbothered by anything happening at the table in front of it.

Sigrun straightened at last, held the three stacks where the room could see their relative sizes even before she said the numbers, and read them the way she read everything now — flat, unhurried, no weight added anywhere the count itself hadn''t already put there.

"Twenty-three yes," she said. "Seventeen no. One abstention." She set the stacks down. "The offer is accepted."

Nobody cheered. Nobody argued it. The room absorbed the number the way it had absorbed every hard number these last months, the particular stillness of forty-one households hearing the last figure in a sequence they''d been living inside for weeks, and Teo understood, watching it land, that whatever came next — the packing, the strip crews, the thirty-day window Ashgrave had promised — none of it was going to feel like victory to twenty-three households or defeat to seventeen. It was going to feel like what it was: a number, real, counted twice, belonging now to all forty-one of them whether they''d wanted it to or not.

Sigrun didn''t say anything further. She folded the empty box shut, and the room began, slowly, to come apart the way rooms did after a decision instead of a discussion, and Teo stayed at the table a moment longer than she needed to, looking at the three stacks of cards still sitting where the count had left them, thinking that somewhere in the seventeen was Wen''s, and somewhere in the twenty-three was Priya''s, and somewhere in one of those two piles — she didn''t yet know which — was the single card that mattered most to the arithmetic she still had left to finish tonight.' WHERE Id='019F3AC8-397D-793D-B34D-8F9C4C20143D';