SET QUOTED_IDENTIFIER ON;
UPDATE Beats SET [Text]=N'Teo went out to the outer ring before her shift properly started, before the driver readings and the morning traffic through the passenger deck, because she''d found over the past year that dawn was the only hour Candelaria let her look at itself without anyone needing anything from her while she did it.

The ring ran the bloc''s full circumference, one level below the commons, a walkway wide enough for two people, railed on the outboard side, glass from waist height to ceiling so the city could get in without the cold getting in with it. She''d walked it a hundred times. She still stopped at the same window she always stopped at, the one on the ring''s eastern arc where the light came up first.

The lake was down there the way it was always down there, a smear of grey-silver going pale at its edges as the sun found it, too far below to show her anything but its shape. Beyond it, the Gray Zone''s low sprawl, patient and undramatic in the dawn light the way it never looked in trideo footage. Further still, the Spires, catching the sun a full twenty minutes before it would reach the bloc, altitude buying light the same way it bought everything else in this city.

Candelaria was still up here. Still airborne, still holding its own weight the way it had held it for sixty years, the Hush sitting under everything the way it should on a morning like this — no strain in it that she could hear, nothing new since her last reading, the frame doing exactly what an aging frame does at three hundred fifty-nine meters and not one thing more.

She didn''t run any numbers standing at that window. That was the part of the morning she''d learned to protect, deliberately, the way she protected almost nothing else in her life — twenty minutes where the ledger stayed shut and the wrist display stayed dark and she let herself just look at what she was going to spend the rest of the day calculating the cost of. She''d tried, the first few months on this job, to use the time productively, running projections against the view the way she ran them against everything else. She''d stopped. Not because the projections were wrong. Because she''d noticed that doing arithmetic at this particular window, at this particular hour, made the view into one more column instead of the one part of her day that wasn''t.

In five weeks now, not six — the number Ruslan had named at the gantry had been ticking down the whole time she''d let herself think of it as fixed — the bloc that held this window would not be holding it from three hundred fifty-nine meters anymore, vote or no vote. That part had never been in question, not since the day she''d read the coherence curve and understood what it was actually telling her. The vote tonight wouldn''t change the curve. It would only change what happened on the far side of it — an orderly descent with a payout attached, or an unscheduled one without.

She thought, standing at the glass with the lake going from grey to pale gold below her, that she had spent a year believing her job was to slow something down, and that she had been wrong about that from close to the beginning, in a way she''d only recently let herself say plainly, even to herself. She couldn''t slow the frame. Nobody could; that had never been on the table, not for her, not for Ashgrave, not for forty-one households who''d spent five meetings arguing about a choice that was never actually about whether Candelaria came down. It was always going to come down. The frame''s curve had settled that the day it was drawn, years before any of them had a vote to schedule.

What she could do — the actual shape of her job, once she stopped mistaking it for the other one — was calculate what reached the ground, and in what condition, and belonging to whom. Priya''s shortfall. Wen''s thirty years. Dagny''s four decades of rooms. Her own fifty-one kilos, sitting in a room upstairs, weighing exactly what they''d weighed the day she''d moved in and not an ounce more since. None of it was hers to save. All of it was hers to weigh, correctly, honestly, in time for whatever came next to be met with real numbers instead of hope dressed up as arithmetic.

The light had fully found the Spires now, and was working its way down toward the Gray Zone, and would reach the lake last of all, the way it always did, altitude asserting itself even in something as unbought as sunrise. Teo watched it a while longer, past the point where watching it served any purpose she could have named to Sigrun or Ruslan or anyone else who might have asked her what she was doing out here instead of at her desk.

Then she turned from the window, because the driver readings weren''t going to run themselves, and because tonight was the vote, and because whatever the room decided in a few hours, someone in this bloc needed to already be standing ready with an honest ledger when it did.' WHERE Id='019F3AC8-397D-75DC-9826-31380555311F';