<Project>
  <ItemGroup>
    <StaticWebAssetEndpoint Include="_content/StreetSamurai.Shared/js/loader.js">
      <AssetFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\js\loader.js'))</AssetFile>
      <Selectors><![CDATA[[]]]></Selectors>
      <EndpointProperties><![CDATA[[{"Name":"integrity","Value":"sha256-KFAMv49rjcHuzu28vInXsxvebRDWYcZa/RMhnNq0OgY="}]]]></EndpointProperties>
      <ResponseHeaders><![CDATA[[{"Name":"Cache-Control","Value":"no-cache"},{"Name":"Content-Length","Value":"2300"},{"Name":"Content-Type","Value":"text/javascript"},{"Name":"ETag","Value":"\u0022KFAMv49rjcHuzu28vInXsxvebRDWYcZa/RMhnNq0OgY=\u0022"},{"Name":"Last-Modified","Value":"Sat, 09 May 2026 07:44:52 GMT"},{"Name":"Vary","Value":"Accept-Encoding"}]]]></ResponseHeaders>
    </StaticWebAssetEndpoint>
    <StaticWebAssetEndpoint Include="_content/StreetSamurai.Shared/js/loader.kdfwyy7cjd.js">
      <AssetFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\js\loader.js'))</AssetFile>
      <Selectors><![CDATA[[]]]></Selectors>
      <EndpointProperties><![CDATA[[{"Name":"fingerprint","Value":"kdfwyy7cjd"},{"Name":"integrity","Value":"sha256-KFAMv49rjcHuzu28vInXsxvebRDWYcZa/RMhnNq0OgY="},{"Name":"label","Value":"_content/StreetSamurai.Shared/js/loader.js"}]]]></EndpointProperties>
      <ResponseHeaders><![CDATA[[{"Name":"Cache-Control","Value":"max-age=31536000, immutable"},{"Name":"Content-Length","Value":"2300"},{"Name":"Content-Type","Value":"text/javascript"},{"Name":"ETag","Value":"\u0022KFAMv49rjcHuzu28vInXsxvebRDWYcZa/RMhnNq0OgY=\u0022"},{"Name":"Last-Modified","Value":"Sat, 09 May 2026 07:44:52 GMT"},{"Name":"Vary","Value":"Accept-Encoding"}]]]></ResponseHeaders>
    </StaticWebAssetEndpoint>
  </ItemGroup>
</Project>