using System.Text;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Prose.Core.Data;

namespace Prose.Core.Services;

/// <summary>
/// Reverses double-encoded UTF-8 corruption ("mojibake") in every NVARCHAR
/// column across the canon tables. The source JSON files were generated by an
/// earlier pipeline that read UTF-8 bytes as Windows-1252 and re-encoded as
/// UTF-8 — so <c>ó</c> ended up stored as <c>Ã³</c>, <c>—</c> as <c>â€"</c>,
/// <c>'</c> as <c>â€™</c>, and so on. This pass reverses the encoding error
/// in pure C# and updates the row.
///
/// Algorithm: for each string with any high-bit char, take its char codes as
/// cp1252 bytes (with the well-known 0x80–0x9F mapping), decode as strict
/// UTF-8. If the decoder accepts the bytes AND the result genuinely differs,
/// keep it. Otherwise leave the row untouched — better to skip than scramble
/// well-formed text.
///
/// Idempotent: re-running on already-clean rows is a no-op (cleaned strings
/// can't be re-decoded as valid UTF-8 since they no longer contain the
/// telltale Ã/â/etc. lead byte sequences).
/// </summary>
public class MojibakeRepairService
{
    private readonly IDbContextFactory<ProseDbContext> dbFactory;
    private readonly ILogger<MojibakeRepairService> log;

    private static readonly Encoding Utf8 = new UTF8Encoding(false, throwOnInvalidBytes: true);

    public MojibakeRepairService(
        IDbContextFactory<ProseDbContext> dbFactory,
        ILogger<MojibakeRepairService> log)
    {
        this.dbFactory = dbFactory;
        this.log       = log;
    }

    public sealed class RepairResult
    {
        public int TablesScanned     { get; set; }
        public int ColumnsScanned    { get; set; }
        public int RowsScanned       { get; set; }
        public int CellsRepaired     { get; set; }
        public int CellsLeftAlone    { get; set; }
        public List<string> Errors   { get; } = new();
        public Dictionary<string, int> PerTable { get; } = new();
    }

    /// <summary>
    /// Walk every NVARCHAR(MAX|N) column on every base table, repairing
    /// double-encoded text in place. Skips system tables and history shadows.
    /// </summary>
    public async Task<RepairResult> RepairAllAsync(IProgress<string>? progress = null, CancellationToken ct = default)
    {
        var result = new RepairResult();

        await using var db = await dbFactory.CreateDbContextAsync(ct);
        var connStr = db.Database.GetConnectionString()
            ?? throw new InvalidOperationException("No connection string configured.");

        // Open a fresh connection with MARS so we can issue UPDATEs while a
        // SELECT reader is still open. EF's pooled connection won't have MARS
        // unless the factory's connection string had it, so we open our own.
        var builder = new SqlConnectionStringBuilder(connStr) { MultipleActiveResultSets = true };
        await using var conn = new SqlConnection(builder.ToString());
        await conn.OpenAsync(ct);

        var tables = await LoadTextColumnsAsync(conn, ct);
        result.TablesScanned = tables.Count;

        foreach (var t in tables)
        {
            if (ct.IsCancellationRequested) break;
            result.ColumnsScanned += t.TextCols.Count;
            try
            {
                var fixedRows = await RepairTableAsync(conn, t, result, ct);
                if (fixedRows > 0)
                {
                    result.PerTable[t.Name] = fixedRows;
                    progress?.Report($"  {t.Name,-32} repaired {fixedRows,5} cell(s)");
                }
            }
            catch (Exception ex)
            {
                log.LogWarning(ex, "Mojibake repair failed on table {Table}", t.Name);
                result.Errors.Add($"{t.Name}: {ex.Message}");
            }
        }

        return result;
    }

    // ── per-table repair ───────────────────────────────────────────────────────

    private record TextTable(string Name, List<string> PkCols, List<string> TextCols);

    private async Task<List<TextTable>> LoadTextColumnsAsync(SqlConnection conn, CancellationToken ct)
    {
        var grouped = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        await using (var cmd = new SqlCommand("""
            SELECT t.name AS table_name, c.name AS col_name
            FROM sys.columns c
            JOIN sys.tables  t ON t.object_id = c.object_id
            WHERE t.is_ms_shipped = 0
              AND t.temporal_type <> 1
              AND t.name <> 'sysdiagrams'
              AND c.is_computed = 0
              AND c.generated_always_type = 0
              AND TYPE_NAME(c.system_type_id) IN ('nvarchar','nchar')
            ORDER BY t.name, c.column_id;
            """, conn))
        await using (var rdr = await cmd.ExecuteReaderAsync(ct))
            while (await rdr.ReadAsync(ct))
            {
                var t = rdr.GetString(0);
                var c = rdr.GetString(1);
                if (!grouped.TryGetValue(t, out var list)) grouped[t] = list = new();
                list.Add(c);
            }

        var tables = new List<TextTable>();
        foreach (var (tableName, cols) in grouped)
        {
            var pks = await LoadPkColumnsAsync(conn, tableName, ct);
            if (pks.Count == 0) continue;
            tables.Add(new TextTable(tableName, pks, cols));
        }
        return tables;
    }

    private static async Task<List<string>> LoadPkColumnsAsync(SqlConnection conn, string table, CancellationToken ct)
    {
        await using var cmd = new SqlCommand("""
            SELECT c.name
            FROM sys.indexes i
            JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id
            JOIN sys.columns c        ON c.object_id  = ic.object_id AND c.column_id = ic.column_id
            WHERE i.object_id = OBJECT_ID(@t) AND i.is_primary_key = 1
            ORDER BY ic.key_ordinal;
            """, conn);
        cmd.Parameters.AddWithValue("@t", $"dbo.{table}");
        var list = new List<string>();
        await using var rdr = await cmd.ExecuteReaderAsync(ct);
        while (await rdr.ReadAsync(ct)) list.Add(rdr.GetString(0));
        return list;
    }

    private async Task<int> RepairTableAsync(SqlConnection conn, TextTable t, RepairResult result, CancellationToken ct)
    {
        var pkList   = string.Join(", ", t.PkCols.Select(c => $"[{c}]"));
        var colList  = string.Join(", ", t.TextCols.Select(c => $"[{c}]"));
        var selectSql = $"SELECT {pkList}, {colList} FROM [dbo].[{t.Name}]";

        // Buffer rows that need an update, then apply outside the read loop so
        // we don't depend on MARS-only multi-statement semantics.
        var pending = new List<(object[] pk, List<(string col, string newValue)> dirty)>();

        await using (var cmd = new SqlCommand(selectSql, conn) { CommandTimeout = 0 })
        await using (var rdr = await cmd.ExecuteReaderAsync(ct))
        {
            var pkCount = t.PkCols.Count;
            while (await rdr.ReadAsync(ct))
            {
                result.RowsScanned++;
                var dirtyCols = new List<(string col, string newValue)>();
                for (int i = 0; i < t.TextCols.Count; i++)
                {
                    if (rdr.IsDBNull(pkCount + i)) continue;
                    var current = rdr.GetString(pkCount + i);
                    var repaired = TryReverseMojibake(current) ?? RepairMixed(current);
                    if (repaired != null && repaired != current)
                        dirtyCols.Add((t.TextCols[i], repaired));
                    else
                        result.CellsLeftAlone++;
                }
                if (dirtyCols.Count > 0)
                {
                    var pkValues = new object[pkCount];
                    for (int i = 0; i < pkCount; i++) pkValues[i] = rdr.GetValue(i);
                    pending.Add((pkValues, dirtyCols));
                }
            }
        }

        var fixedCells = 0;
        foreach (var (pk, dirty) in pending)
        {
            await UpdateRowAsync(conn, t, pk, dirty, ct);
            fixedCells += dirty.Count;
            result.CellsRepaired += dirty.Count;
        }
        return fixedCells;
    }

    private static async Task UpdateRowAsync(SqlConnection conn, TextTable t,
        object[] pkValues, List<(string col, string newValue)> dirty, CancellationToken ct)
    {
        var setExprs   = string.Join(", ", dirty.Select((d, i) => $"[{d.col}] = @v{i}"));
        var whereExprs = string.Join(" AND ", t.PkCols.Select((c, i) => $"[{c}] = @k{i}"));
        var sql = $"UPDATE [dbo].[{t.Name}] SET {setExprs} WHERE {whereExprs}";
        await using var cmd = new SqlCommand(sql, conn) { CommandTimeout = 0 };
        for (int i = 0; i < dirty.Count; i++) cmd.Parameters.AddWithValue($"@v{i}", dirty[i].newValue);
        for (int i = 0; i < t.PkCols.Count; i++) cmd.Parameters.AddWithValue($"@k{i}", pkValues[i]);
        await cmd.ExecuteNonQueryAsync(ct);
    }

    // ── detection ─────────────────────────────────────────────────────────────

    public sealed class DetectResult
    {
        public int BeatsAffected { get; set; }
        public List<DetectHit> Hits { get; } = new();
    }

    public sealed record DetectHit(Guid BeatId, string NodeTitle, string Excerpt);

    /// <summary>
    /// Scan beats belonging to <paramref name="nodeId"/> (or all beats when
    /// <c>null</c>) and report any that contain mojibake without modifying them.
    /// </summary>
    public async Task<DetectResult> DetectNodeAsync(Guid? nodeId = null, CancellationToken ct = default)
    {
        await using var db = await dbFactory.CreateDbContextAsync(ct);
        var result = new DetectResult();

        IEnumerable<Prose.Core.Data.Entities.Beat> beats;
        if (nodeId.HasValue)
        {
            // SS-A43: beats live on chapter children for book-mode stories.
            // Recurses past any nested Collection (2026-08-09 fix).
            var searchIds = await NodeWorkbenchService.GetLeafDescendantIdsAsync(db, nodeId.Value, ct);

            var beatIds = await db.BeatNodes
                .Where(sb => searchIds.Contains(sb.NodeId) && sb.IsEnabled)
                .Select(sb => sb.BeatId)
                .ToListAsync(ct);
            beats = await db.Beats.AsNoTracking().Where(b => beatIds.Contains(b.Id)).ToListAsync(ct);
        }
        else
        {
            beats = await db.Beats.AsNoTracking().ToListAsync(ct);
        }

        string nodeTitle = nodeId.HasValue
            ? (await db.Nodes.AsNoTracking()
                .Where(s => s.Id == nodeId.Value)
                .Select(s => s.Title)
                .FirstOrDefaultAsync(ct) ?? nodeId.Value.ToString())
            : "(all nodes)";

        foreach (var beat in beats)
        {
            bool textDirty  = !string.IsNullOrEmpty(beat.Text)      && ContainsMojibake(beat.Text!);
            bool titleDirty = !string.IsNullOrEmpty(beat.Title)  && ContainsMojibake(beat.Title!);
            if (!textDirty && !titleDirty) continue;

            result.BeatsAffected++;
            var sample = (beat.Text ?? beat.Title ?? "").Length > 120
                ? (beat.Text ?? beat.Title ?? "")[..120] + "…"
                : (beat.Text ?? beat.Title ?? "");
            result.Hits.Add(new DetectHit(beat.Id, nodeTitle, sample));
        }

        return result;
    }

    /// <summary>
    /// Open a .docx file and count mojibake occurrences in its body XML.
    /// Returns 0 if the file cannot be opened (locked / missing).
    /// </summary>
    public static int CountDocxMojibake(string docxPath)
    {
        try
        {
            using var zip = System.IO.Compression.ZipFile.OpenRead(docxPath);
            var entry = zip.GetEntry("word/document.xml");
            if (entry is null) return 0;
            using var reader = new System.IO.StreamReader(entry.Open(), Encoding.UTF8);
            var xml = reader.ReadToEnd();
            int count = 0;
            for (int i = 0; i < xml.Length - 1; i++)
                if (xml[i] == 'â' && xml[i + 1] == '€') count++;
            return count;
        }
        catch { return 0; }
    }

    /// <summary>Fast check: returns true if the string contains the â€ mojibake prefix.</summary>
    public static bool ContainsMojibake(string s)
    {
        for (int i = 0; i < s.Length - 1; i++)
            if (s[i] == 'â' && s[i + 1] == '€') return true;
        return false;
    }

    // ── core mojibake reversal ─────────────────────────────────────────────────

    /// <summary>
    /// Targeted repair for mixed-content strings: scans for consecutive runs of
    /// CP1252-encodable characters and tries UTF-8 decoding on each run. Works where
    /// <see cref="TryReverseMojibake"/> fails — strings that contain legitimate
    /// Unicode code points above U+00FF that are not in the CP1252 0x80–0x9F
    /// special block (e.g. an already-correct U+2014 or U+00E9 interspersed with
    /// mojibake). Tries <see cref="TryReverseMojibake"/> first; falls through to the
    /// run-scan only when that fails.
    /// </summary>
    public static string? RepairMixed(string s)
    {
        if (!ContainsMojibake(s)) return null;

        // Fast path: pure-mojibake strings decode cleanly in one pass.
        var fast = TryReverseMojibake(s);
        if (fast != null) return fast;

        var sb = new StringBuilder(s.Length);
        bool changed = false;
        int i = 0;

        while (i < s.Length)
        {
            byte? b0 = ToCp1252Byte(s[i]);
            if (b0 == null || b0.Value < 0x80)
            {
                sb.Append(s[i++]);
                continue;
            }

            // Collect a run of consecutive CP1252-encodable high characters.
            int runStart = i;
            var run = new List<byte>();
            while (i < s.Length)
            {
                byte? rb = ToCp1252Byte(s[i]);
                if (rb == null) break;
                run.Add(rb.Value);
                i++;
            }

            // Try to decode the run as strict UTF-8.
            string? decoded = null;
            try { decoded = Utf8.GetString(run.ToArray()); }
            catch { /* not valid UTF-8 — leave run as-is */ }

            var original = s.Substring(runStart, i - runStart);
            if (decoded != null && decoded != original)
            {
                sb.Append(decoded);
                changed = true;
            }
            else
            {
                sb.Append(original);
            }
        }

        return changed ? sb.ToString() : null;
    }

    /// <summary>Returns the CP1252 byte for <paramref name="ch"/>, or <c>null</c> if the
    /// character cannot be represented in CP1252 (i.e. > U+00FF and not in the
    /// 0x80–0x9F special block).</summary>
    private static byte? ToCp1252Byte(char ch)
    {
        if (ch <= '') return (byte)ch;
        if (ch <= 'ÿ') return (byte)ch;
        return ch switch
        {
            '€' => 0x80, '‚' => 0x82, 'ƒ' => 0x83, '„' => 0x84, '…' => 0x85,
            '†' => 0x86, '‡' => 0x87, 'ˆ' => 0x88, '‰' => 0x89, 'Š' => 0x8A,
            '‹' => 0x8B, 'Œ' => 0x8C, 'Ž' => 0x8E,
            '‘' => 0x91, '’' => 0x92, '“' => 0x93, '”' => 0x94, '•' => 0x95,
            '–' => 0x96, '—' => 0x97, '˜' => 0x98, '™' => 0x99, 'š' => 0x9A,
            '›' => 0x9B, 'œ' => 0x9C, 'ž' => 0x9E, 'Ÿ' => 0x9F,
            _ => null,
        };
    }

    /// <summary>
    /// Returns the corrected string, or <c>null</c> if no repair applies.
    /// Strategy: every char's lower 8 bits are taken as cp1252 bytes (with the
    /// 0x80–0x9F printable range mapped from their Unicode equivalents), then
    /// decoded as strict UTF-8. If the decoder throws, the input wasn't
    /// double-encoded — leave it alone. If the result equals the input,
    /// also leave alone (idempotent).
    /// </summary>
    public static string? TryReverseMojibake(string s)
    {
        if (string.IsNullOrEmpty(s)) return null;
        // Cheap pre-filter: ASCII-only strings can't be mojibake.
        bool anyHighBit = false;
        for (int i = 0; i < s.Length; i++) if (s[i] > 0x7F) { anyHighBit = true; break; }
        if (!anyHighBit) return null;

        try
        {
            var bytes = new byte[s.Length];
            for (int i = 0; i < s.Length; i++)
            {
                var ch = s[i];
                bytes[i] = ch switch
                {
                    '€' => 0x80, '‚' => 0x82, 'ƒ' => 0x83, '„' => 0x84, '…' => 0x85,
                    '†' => 0x86, '‡' => 0x87, 'ˆ' => 0x88, '‰' => 0x89, 'Š' => 0x8A,
                    '‹' => 0x8B, 'Œ' => 0x8C, 'Ž' => 0x8E,
                    '‘' => 0x91, '’' => 0x92, '“' => 0x93, '”' => 0x94, '•' => 0x95,
                    '–' => 0x96, '—' => 0x97, '˜' => 0x98, '™' => 0x99, 'š' => 0x9A,
                    '›' => 0x9B, 'œ' => 0x9C, 'ž' => 0x9E, 'Ÿ' => 0x9F,
                    _   => ch <= 0x00FF ? (byte)ch : (byte)0,
                };
                // Char outside both cp1252 windows means we can't reverse it
                // (it's already a clean Unicode code point). Bail.
                if (bytes[i] == 0 && ch != '\0') return null;
            }
            var decoded = Utf8.GetString(bytes);
            return decoded == s ? null : decoded;
        }
        catch
        {
            return null; // not valid UTF-8 → leave alone
        }
    }
}
