// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prose.Core.Kdp;

#nullable disable

namespace Prose.Core.Kdp.Migrations
{
    [DbContext(typeof(KdpDbContext))]
    [Migration("20260923150437_InitialKdpStore")]
    partial class InitialKdpStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Prose.Core.Kdp.KdpBook", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishingDetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LastPublish", "Prose.Core.Kdp.KdpBook.LastPublish#KdpPublishSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Asin")
                                .HasColumnType("TEXT");

                            b1.Property<string>("File")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("PublishedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Version")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SignOff", "Prose.Core.Kdp.KdpBook.SignOff#KdpSignOff", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("ChangedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ChangedBy")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Ready")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Code");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpCategoryTree", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("StartPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Crawl", "Prose.Core.Kdp.KdpCategoryTree.Crawl#KdpCrawlInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("CrawledAt")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("MaxDepth")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Via")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Slug");

                    b.ToTable("CategoryTrees");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Counts", "Prose.Core.Kdp.KdpImport.Counts#KdpTransferCounts", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Books")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CategoryTrees")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PublishRecords")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RunLines")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Runs")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Titles")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpPublishRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Publish", "Prose.Core.Kdp.KdpPublishRecord.Publish#KdpPublishSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Asin")
                                .HasColumnType("TEXT");

                            b1.Property<string>("File")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("PublishedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Version")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code", "RecordedAt");

                    b.ToTable("PublishRecords");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Codes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogFileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogFileName")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpRunLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Id");

                    b.ToTable("RunLines");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpTitle", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.HasIndex("TitleId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpTitleNote", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("TitleNotes");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpPublishRecord", b =>
                {
                    b.HasOne("Prose.Core.Kdp.KdpBook", null)
                        .WithMany("History")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpRunLine", b =>
                {
                    b.HasOne("Prose.Core.Kdp.KdpRun", null)
                        .WithMany("Lines")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpBook", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Prose.Core.Kdp.KdpRun", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
