using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Server;
using Prose.Core.Services;

namespace Prose.Mcp;

// ── Survey tools ───────────────────────────────────────────────────────────
// create_survey              — create a new survey with typed questions
// get_survey                 — retrieve a survey with questions + answers
// list_surveys               — list surveys by status
// answer_survey_question     — record a user's answer for one question
// mark_survey_question_applied — log that a question's fix has been applied
// complete_survey            — mark a survey as completed
// get_survey_html            — generate artifact HTML ready to publish

/// <summary>
/// Survey management: create, answer, apply, and complete canon-sync or
/// contradiction-resolution surveys. Surveys are persisted in the DB so the
/// full decision trail is available across sessions. HTML for the interactive
/// artifact is generated by <c>get_survey_html</c>.
/// </summary>
[McpServerToolType]
public class SurveyTools(SurveyService surveyService)
{
    static readonly JsonSerializerOptions JsonOpts = new() { WriteIndented = false };

    /// <summary>Create a new survey with typed questions.</summary>
    [McpServerTool, Description(
        "Create a new canon-sync or contradiction-resolution survey. " +
        "questions is a JSON array of {questionKey, title, context?, questionType?, options} where " +
        "options is an array of {key, label, description?}. " +
        "questionType values: PlaceDescription, TechnologyDescription, WeaponRename, " +
        "FactionDescription, CharacterDescription, BeatText, DocUpdate, " +
        "ContradictionResolve, Custom. " +
        "Returns the survey id and slug. Call get_survey_html to generate the artifact HTML.")]
    public async Task<string> CreateSurvey(
        [Description("URL-safe slug, e.g. 'canon-sync-2026-07-05'.")] string slug,
        [Description("Human-readable title.")] string title,
        [Description("JSON array of question objects. Each: {questionKey, title, context?, questionType?, options:[{key,label,description?}]}")] string questionsJson,
        [Description("Optional purpose / scope description.")] string? purpose = null,
        [Description("Universe slug ('glmz' or 'fantasy'). Omit for universe-neutral.")] string? universeSlug = null)
    {
        List<SurveyQuestionInput> questions;
        try
        {
            var raw = JsonSerializer.Deserialize<List<SurveyQuestionInputRaw>>(
                questionsJson,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                ?? [];
            questions = raw.Select(r => new SurveyQuestionInput(
                r.QuestionKey ?? "",
                r.Title ?? "",
                (r.Options ?? []).Select(o => new SurveyOptionDto(
                    o.Key ?? "", o.Label ?? "", o.Description)).ToList(),
                r.Context,
                r.QuestionType ?? "Custom")).ToList();
        }
        catch (Exception ex)
        {
            return JsonSerializer.Serialize(new { ok = false, error = $"Invalid questionsJson: {ex.Message}" }, JsonOpts);
        }

        try
        {
            var survey = await surveyService.CreateSurveyAsync(slug, title, purpose, questions);
            return JsonSerializer.Serialize(new
            {
                ok        = true,
                surveyId  = survey.Id,
                slug      = survey.Slug,
                title     = survey.Title,
                questions = survey.Questions.Count,
            }, JsonOpts);
        }
        catch (InvalidOperationException ex)
        {
            return JsonSerializer.Serialize(new { ok = false, error = ex.Message }, JsonOpts);
        }
    }

    /// <summary>Retrieve a survey with all questions and answers.</summary>
    [McpServerTool, Description(
        "Retrieve a survey with all questions and their current answer state. " +
        "Returns the survey metadata, each question's key/title/type/options/selectedOption/applyStatus.")]
    public async Task<string> GetSurvey(
        [Description("Survey slug.")] string slug)
    {
        var survey = await surveyService.GetSurveyAsync(slug);
        if (survey is null)
            return JsonSerializer.Serialize(new { ok = false, error = $"Survey '{slug}' not found." }, JsonOpts);

        return JsonSerializer.Serialize(new
        {
            ok     = true,
            id     = survey.Id,
            slug   = survey.Slug,
            title  = survey.Title,
            status = survey.Status,
            questions = survey.Questions.OrderBy(q => q.SortOrder).Select(q => new
            {
                id             = q.Id,
                key            = q.QuestionKey,
                type           = q.QuestionType,
                title          = q.Title,
                selectedOption = q.SelectedOption,
                answeredAt     = q.AnsweredAt,
                applyStatus    = q.ApplyStatus,
                applyNotes     = q.ApplyNotes,
            }),
        }, JsonOpts);
    }

    /// <summary>List surveys, optionally filtered by status.</summary>
    [McpServerTool, Description(
        "List surveys. Filter by status ('Open' or 'Completed') or omit for all.")]
    public async Task<string> ListSurveys(
        [Description("'Open' or 'Completed'. Omit for all.")] string? status = null)
    {
        var surveys = await surveyService.ListSurveysAsync(status);
        return JsonSerializer.Serialize(new
        {
            ok      = true,
            count   = surveys.Count,
            surveys = surveys.Select(s => new
            {
                slug      = s.Slug,
                title     = s.Title,
                status    = s.Status,
                questions = s.Questions.Count,
                answered  = s.Questions.Count(q => q.SelectedOption != null),
                applied   = s.Questions.Count(q => q.ApplyStatus == "Applied"),
                createdAt = s.CreatedAt,
            }),
        }, JsonOpts);
    }

    /// <summary>Record a user's answer for one question.</summary>
    [McpServerTool, Description(
        "Record the user's answer for one survey question. " +
        "selectedOption is the letter key ('a', 'b', 'c', or 'd'). " +
        "Call this once per question after the user exports their answers from the artifact.")]
    public async Task<string> AnswerSurveyQuestion(
        [Description("Survey slug.")] string surveySlug,
        [Description("Question key, e.g. 'Q-001'.")] string questionKey,
        [Description("Selected option letter: 'a', 'b', 'c', or 'd'.")] string selectedOption)
    {
        var ok = await surveyService.RecordAnswerAsync(surveySlug, questionKey, selectedOption);
        if (!ok)
            return JsonSerializer.Serialize(new { ok = false, error = $"Question '{questionKey}' not found in survey '{surveySlug}'." }, JsonOpts);
        return JsonSerializer.Serialize(new { ok = true, surveySlug, questionKey, selectedOption }, JsonOpts);
    }

    /// <summary>Log that a question's fix has been applied to the DB / docs.</summary>
    [McpServerTool, Description(
        "Mark a survey question as applied (or skipped) after the fix has been made. " +
        "applyStatus: 'Applied' (default) or 'Skipped'. " +
        "applyNotes should describe what was changed (SQL table/column, MCP tool used, etc.).")]
    public async Task<string> MarkSurveyQuestionApplied(
        [Description("Survey slug.")] string surveySlug,
        [Description("Question key, e.g. 'Q-001'.")] string questionKey,
        [Description("Description of what was changed.")] string applyNotes,
        [Description("'Applied' or 'Skipped'. Defaults to 'Applied'.")] string applyStatus = "Applied")
    {
        var ok = await surveyService.MarkQuestionAppliedAsync(surveySlug, questionKey, applyNotes, applyStatus);
        if (!ok)
            return JsonSerializer.Serialize(new { ok = false, error = $"Question '{questionKey}' not found in survey '{surveySlug}'." }, JsonOpts);
        return JsonSerializer.Serialize(new { ok = true, surveySlug, questionKey, applyStatus }, JsonOpts);
    }

    /// <summary>Mark a survey as completed.</summary>
    [McpServerTool, Description(
        "Mark a survey as Completed. All questions should be Applied or Skipped before calling this.")]
    public async Task<string> CompleteSurvey(
        [Description("Survey slug.")] string slug)
    {
        var ok = await surveyService.CompleteSurveyAsync(slug);
        if (!ok)
            return JsonSerializer.Serialize(new { ok = false, error = $"Survey '{slug}' not found." }, JsonOpts);
        return JsonSerializer.Serialize(new { ok = true, slug, status = "Completed" }, JsonOpts);
    }

    /// <summary>Generate the interactive artifact HTML for a survey.</summary>
    [McpServerTool, Description(
        "Generate the interactive artifact HTML for a survey. " +
        "Returns the full HTML string ready to be published as an artifact. " +
        "After calling this, publish it via the Artifact tool with the survey slug as the filename.")]
    public async Task<string> GetSurveyHtml(
        [Description("Survey slug.")] string slug)
    {
        try
        {
            var html = await surveyService.GenerateHtmlAsync(slug);
            return JsonSerializer.Serialize(new { ok = true, slug, html }, JsonOpts);
        }
        catch (InvalidOperationException ex)
        {
            return JsonSerializer.Serialize(new { ok = false, error = ex.Message }, JsonOpts);
        }
    }

    // Raw deserialization helpers (anonymous-like shape from questionsJson)
    private sealed class SurveyQuestionInputRaw
    {
        public string? QuestionKey  { get; set; }
        public string? QuestionType { get; set; }
        public string? Title        { get; set; }
        public string? Context      { get; set; }
        public List<SurveyOptionRaw>? Options { get; set; }
    }

    private sealed class SurveyOptionRaw
    {
        public string? Key         { get; set; }
        public string? Label       { get; set; }
        public string? Description { get; set; }
    }
}
