using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Prose.Core.Data;
using Prose.Core.Services;

namespace Prose.Cli;

/// <summary>
/// prose --audit-book --slug &lt;book-or-chapter-slug&gt; [--deep] [--full] [--model &lt;id&gt;] [--out &lt;path&gt;]
///
/// The "Player Piano" — one repeatable command that runs the full QA battery against a
/// node and emits a single consolidated scorecard: the Structural Integrity Index (SII), a
/// deterministic rollup over Findings (never an LLM opinion vote — see BookHealthService).
///
/// Tiers (cumulative — each includes the one before):
///   FREE  (always)  — deterministic + near-zero-cost checks: census, coverage, plant-audit,
///                     prose-check, noun-consistency, timeline-check, beat-verification,
///                     outline-coordination.
///   DEEP  (--deep)  — one LLM call per check per node: examine-emotion, book-audit,
///                     diagnose-node, check-fidelity, logic-sweep, craft-checklist,
///                     check-canon, altitude-audit, reader-qa comprehension.
///   FULL  (--full, implies --deep) — heaviest multi-call audits, cost scales with book
///                     length: storyscope-audit, swain-audit, chekhov-audit.
///
/// This is a thin formatter over Prose.Core.Services.BookHealthService — the battery and
/// the SII arithmetic both live there so the MCP book_health tool can share the exact same
/// logic without going through this CLI layer.
/// </summary>
public static class AuditNodeCli
{
    public static async Task<int> RunAsync(IServiceProvider sp, string[] args)
    {
        var slug    = GetArg(args, "--slug");
        var full    = args.Contains("--full");
        var deep    = args.Contains("--deep") || full;
        var model   = GetArg(args, "--model");
        var outPath = GetArg(args, "--out");
        var json    = args.Contains("--json");
        if (slug == null) { Console.Error.WriteLine("Usage: prose --audit-book --slug <slug> [--deep] [--full] [--model <id>] [--out <path>] [--json]"); return 2; }

        var dbFactory = sp.GetRequiredService<IDbContextFactory<ProseDbContext>>();
        var monitor   = sp.GetRequiredService<WorkflowMonitorService>();
        var bookHealth = sp.GetRequiredService<BookHealthService>();
        var granularity = sp.GetRequiredService<BeatGranularityService>();
        var proseMetrics = sp.GetRequiredService<BeatProseMetricsService>();

        await using var db = await dbFactory.CreateDbContextAsync();
        var root = await db.Nodes.AsNoTracking()
            .Where(s => s.Slug == slug || s.NodeCode == slug)
            .Select(s => new { s.Id, s.Title, s.Slug })
            .FirstOrDefaultAsync();
        if (root == null) { Console.Error.WriteLine($"Node not found: {slug}"); return 2; }

        var children = await db.Nodes.AsNoTracking()
            .Where(s => s.ParentNodeId == root.Id)
            .OrderBy(s => s.SortKey)
            .Select(s => new ChapterRef(s.Id, s.Title, s.Slug))
            .ToListAsync();
        var chapters = children.Count > 0 ? children : [new ChapterRef(root.Id, root.Title, root.Slug)];

        var sb = new StringBuilder();
        void W(string s = "") => sb.AppendLine(s);

        var tier = full ? BookHealthTier.Full : deep ? BookHealthTier.Deep : BookHealthTier.Free;

        W($"# Node Audit — {root.Title} ({root.Slug})");
        W($"_Generated by `prose --audit-book`, {tier.ToString().ToUpperInvariant()} tier{(model != null ? $", model={model}" : "")}._");
        W();

        // ── SECTION 1: CENSUS ────────────────────────────────────────────────────
        W("## 1. Population / tagging / scoring census");
        W();
        W("| Ch | Beats | Text | Desc | Struct | Tone | Score | EQ | Mentions |");
        W("|----|-------|------|-----|--------|------|-------|----|----------|");

        var gaps = new List<string>();
        int totBeats = 0, totText = 0, totSyn = 0, totStruct = 0, totTone = 0, totScore = 0, totEq = 0, totMentionBeats = 0;

        foreach (var ch in chapters)
        {
            var stats = await CensusChapterAsync(db, ch.Id);
            totBeats += stats.Beats; totText += stats.Text; totSyn += stats.Syn; totStruct += stats.Struct;
            totTone += stats.Tone; totScore += stats.Scored; totEq += stats.Eq; totMentionBeats += stats.MentionBeats;
            W($"| {Trunc(ch.Title, 22)} | {stats.Beats} | {stats.Text} | {stats.Syn} | {stats.Struct} | {stats.Tone} | {stats.Scored} | {stats.Eq} | {stats.MentionBeats} |");
        }
        W($"| **TOTAL** | {totBeats} | {totText} | {totSyn} | {totStruct} | {totTone} | {totScore} | {totEq} | {totMentionBeats} |");
        W();

        if (totText < totBeats)  gaps.Add($"{totBeats - totText} beat(s) have no prose text.");
        if (totSyn < totBeats)   gaps.Add($"{totBeats - totSyn} beat(s) missing Description (degrades mode detection + pacing — backfill or generate).");
        if (totStruct < totBeats) gaps.Add($"{totBeats - totStruct} beat(s) missing StructureRole (derivable from position — deterministic backfill).");
        if (totMentionBeats < totBeats) gaps.Add($"{totBeats - totMentionBeats} beat(s) not entity-scanned (run prose --scan-entity-mentions).");

        // ── SECTION 2: COVERAGE ──────────────────────────────────────────────────
        W("## 2. Prose-engine service coverage");
        W();
        var coverage = await monitor.GetNodeCoverageAsync(root.Id);
        W($"Coverage — {coverage.TotalBeatsLogged} beats logged");
        foreach (var s in coverage.ServiceStats)
            W($"- {s.Service}: {(s.ApplicableCalls > 0 ? $"{s.ActivationRate:P0}" : "n/a")} ({s.ActiveCalls}/{s.ApplicableCalls})");
        if (coverage.Gaps.Count > 0) foreach (var g in coverage.Gaps) gaps.Add($"Coverage: {g}");
        W();

        // ── SECTION 3: BATTERY ───────────────────────────────────────────────────
        W("## 3. Battery results");
        W();
        SettingsService? settings = null;
        string? savedModel = null;
        if (model != null)
        {
            settings = sp.GetRequiredService<SettingsService>();
            savedModel = settings.Model;
            settings.Model = model;
        }

        BookHealthReport report;
        try
        {
            report = await bookHealth.RunAsync(root.Id, tier);
        }
        finally
        {
            if (settings != null && savedModel != null) settings.Model = savedModel;
        }

        foreach (var c in report.Checks)
            W($"- {(c.Success ? "✅" : "❌")} {c.Name}{(c.Success ? "" : $" — {Trunc(c.Note, 100)}")}");
        W();

        // ── SECTION 4: DIAGNOSTICS (informational — do not affect SII) ──────────
        W("## 4. Diagnostics (informational — do not affect SII)");
        W();
        try
        {
            var gran = await granularity.AnalyzeAsync(root.Slug!);
            if (gran != null)
                W($"- Beat granularity: {gran.OkCount} ok, {gran.SplitCount} flagged SPLIT, {gran.MergeCount} flagged MERGE (avg {gran.AvgChars:N0} chars/beat).");
        }
        catch (Exception ex) { W($"- Beat granularity: unavailable ({ex.Message})"); }
        try
        {
            var metrics = await proseMetrics.ComputeNodeAsync(root.Id);
            W($"- Prose metrics: mean TTR {metrics.MeanTtr:F2}, mean Flesch reading-ease {metrics.MeanFleschReadingEase:F1}, {metrics.Outliers.Count} outlier beat(s).");
        }
        catch (Exception ex) { W($"- Prose metrics: unavailable ({ex.Message})"); }
        W();

        // ── SECTION 5: SCORECARD — Structural Integrity Index ────────────────────
        W("## 5. Scorecard — Structural Integrity Index");
        W();
        W($"**SII: {report.Sii} / 100 — Grade {report.Grade}**");
        W();
        W($"_Computed {report.GeneratedAt:yyyy-MM-dd HH:mm} UTC from open Findings + {report.RateAdjustments.Count} rate metric(s)._ ");
        W("_Not a vote — a fixed, reproducible formula. Re-running with no underlying changes reproduces the same number._");
        W();

        var totalFindingsDeduction = report.FindingsDeduction.Sum(d => d.CappedPoints);
        W($"### Findings deduction (−{totalFindingsDeduction})");
        W();
        if (report.FindingsDeduction.Count == 0)
            W("_No open findings in scope — clean._");
        else
        {
            W("| Category | High | Medium | Low | Capped |");
            W("|---|--:|--:|--:|--:|");
            foreach (var d in report.FindingsDeduction)
                W($"| {d.Category} | {d.High} | {d.Medium} | {d.Low} | −{d.CappedPoints} |");
        }
        W();

        var totalRateAdjustment = report.RateAdjustments.Sum(r => r.Adjustment);
        W($"### Rate adjustments ({(totalRateAdjustment <= 0 ? totalRateAdjustment.ToString() : $"+{totalRateAdjustment}")})");
        W();
        if (report.RateAdjustments.Count == 0)
            W("_None computed this run (requires --full for Swain/StoryScope, --deep for CraftChecklist)._");
        else
        {
            W("| Metric | Value | Adjustment |");
            W("|---|---|--:|");
            foreach (var r in report.RateAdjustments)
                W($"| {r.Metric} | {r.Value} | {r.Adjustment} |");
        }
        foreach (var e in report.ExcludedFromScore)
            W($"_{e}_");
        W();
        W($"### Why this number");
        W($"100 − {totalFindingsDeduction} (open findings, capped per category) {(totalRateAdjustment <= 0 ? "−" : "+")} {Math.Abs(totalRateAdjustment)} (rate metrics) = **{report.Sii}**.");
        W();

        // ── SECTION 6: GAPS ───────────────────────────────────────────────────────
        W("## 6. Gaps & recommended actions");
        W();
        if (gaps.Count == 0) W("_No structural gaps detected._");
        else foreach (var g in gaps) W($"- {g}");
        W();

        var reportText = sb.ToString();
        if (json)
            Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(report,
                new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));
        else
            Console.WriteLine(reportText);

        if (outPath != null)
        {
            await File.WriteAllTextAsync(outPath, reportText);
            Console.WriteLine($"\nReport written to {outPath}");
        }

        var blocking = report.FindingsDeduction.Sum(d => d.High);
        return report.Sii < 60 ? 2 : blocking > 0 ? 1 : 0;
    }

    private record ChapterRef(Guid Id, string Title, string? Slug);
    private record Census(int Beats, int Text, int Syn, int Struct, int Tone, int Scored, int Eq, int MentionBeats);

    private static async Task<Census> CensusChapterAsync(ProseDbContext db, Guid chapterId)
    {
        var beats = await (from sb in db.BeatNodes.AsNoTracking()
                           join b in db.Beats.AsNoTracking() on sb.BeatId equals b.Id
                           where sb.NodeId == chapterId && sb.IsEnabled
                           select new { b.Id, b.Text, b.Description, b.StructureRole, b.EmotionalTone, b.Score, b.EmotionalScore }).ToListAsync();
        var ids = beats.Select(b => b.Id).ToList();
        var mentionBeats = await db.BeatEntityMentions.AsNoTracking()
            .Where(m => ids.Contains(m.BeatId)).Select(m => m.BeatId).Distinct().CountAsync();
        return new Census(
            Beats:        beats.Count,
            Text:         beats.Count(b => !string.IsNullOrEmpty(b.Text)),
            Syn:          beats.Count(b => !string.IsNullOrEmpty(b.Description)),
            Struct:       beats.Count(b => b.StructureRole != null),
            Tone:         beats.Count(b => b.EmotionalTone != null),
            Scored:       beats.Count(b => b.Score != null),
            Eq:           beats.Count(b => b.EmotionalScore != null),
            MentionBeats: mentionBeats);
    }

    private static string Trunc(string s, int max) => s.Length <= max ? s : s[..(max - 1)] + "…";

    private static string? GetArg(string[] args, string flag)
    {
        var i = Array.IndexOf(args, flag);
        return i >= 0 && i + 1 < args.Length ? args[i + 1] : null;
    }
}
