SET QUOTED_IDENTIFIER ON;
UPDATE Beats SET [Text]=N'The core hummed, and Teo Mamani did not like the sound of that.

A healthy frame ran silent. That was the whole of what the Hush meant: sixty years of Coherence Drivers holding Aerobloc Candelaria''s mass in a state that declined most of its own weight, and doing it so cleanly that nobody standing in a kitchen four decks up ever thought about physics at all. When the frame strained, it hummed, low and rising, like a held breath let out too slow. Teo had spent eleven years learning to hear the difference between a Hum that meant nothing and a Hum that meant the schedule needed updating. This one meant the schedule needed updating.

She stood on the core''s lower gantry with her wrist display open to the stress distribution, and she read it the way she read everything: as load, as list, as an argument between weight and the frame''s diminishing patience for weight. The bloc was down at the nose by a hair, a quarter-degree list to the east quadrant, nothing a resident would ever feel underfoot. Teo felt it the way another person might feel a held note going flat. Three months ago the readout would have been clean. Now it carried a tremor along the primary field, a stutter in the coherence lattice that no recalibration schedule she could propose to the co-op would actually pay for.

Almagre worked beside her, or above her, or through her — she had stopped assigning the automaton a location years ago. Its presence was procedural: readouts adjusting, trim limits enforcing themselves a half-second before she would have called for them. It did not speak unless asked, and this morning it hadn''t been asked. She liked that about it. It made no case for itself. It simply held the ceiling she gave it.

"Projected coherence decay," she said, not quite to Almagre and not quite to herself, and the wrist display answered with a curve she already knew by heart. Aerobloc Candelaria: built 2166, sixty years old this spring, forty-one households, a cylinder of home stacked twelve decks around a core that was failing in the ordinary way old things fail — not with a bang, with an argument that math always won. Current altitude, three hundred eighty-three meters. Losing close to a meter a day, and the rate climbing, not falling.

Three hundred twenty meters was the number that mattered more than the rest. Below it: The Low. No governance line, no Air Tax bracket that made sense anymore, no insurer willing to write a policy on a home that had crossed out of the city''s counted air. Above it, Candelaria was a residence. Below it, Candelaria was salvage waiting for a claimant. Forty-two days, by Teo''s own schedule, before the bloc had lost enough lift that jettison stopped being optional and became the only lever left to pull.

She had built that schedule herself, week by week, number by number, and she did not soften it for anyone, including herself. It was the one document in the co-op that never negotiated. Every other conversation in Candelaria ran on hope, or fear, or the particular arithmetic of what a person could stand to lose. The schedule only subtracted.

She scrolled to the mass ledger next, the long column of everything not bolted into a household''s fixture rights: the cistern tank on deck nine that served six units and could serve four if she moved the piping; the storage floor on deck three, half-empty since the Alvarenga family relocated to a ground-tier block two years back; forty crates of maintenance stock nobody had inventoried since the last chair''s term. None of it was anyone''s grandmother''s chair. None of it would cost a person their kitchen or their floor. It was simply mass, sitting where mass had always sat, waiting for someone with her job to notice it could sit somewhere lighter, or not at all.

She marked the storage floor first. Not because it was the heaviest item — the cistern beat it by a wide margin — but because it was the easiest to move without anyone downstairs feeling their home tilt under them, literally or otherwise. Trim work was never about the biggest number. It was about the number you could take without anyone noticing you''d taken it.

"First candidate," she told Almagre, and watched the automaton log it without comment, the way it logged everything: no opinion offered, none invited. "Log it provisional. I want two more weeks of readings before it moves."

Two more weeks she might not have, if the Hum kept climbing the way this morning''s readout suggested it would.

She closed the display and stood a moment longer on the gantry, listening. The Hush had a texture, when you''d spent long enough with it — a kind of held quiet that felt, underfoot, like a floor that trusted you. She could still hear that trust this morning, mostly. Under it, thin as a wire pulled tight, the Hum, telling her what forty-two days actually meant.

Below her, twelve decks up through the core shaft, forty-one households were making breakfast, sending children off on the transit lift, painting over yesterday''s number on the commons wall with today''s, not yet knowing that a man named Ruslan Adeyinka had already drafted the letter that would arrive in all of their wrist displays within the week. Teo didn''t know it yet either. She only knew the number on her own display, and the number on the wall, and the widening gap between what the bloc weighed and what it could still afford to weigh.

She logged her shift start, gathered her tools, and went up to walk the spine, because a schedule was only as honest as the last time you''d checked it against the thing itself.' WHERE Id='019F3AC8-394D-7849-A057-5B6AF36D44CD';
UPDATE Beats SET [Text]=N'The commons wall was the first thing anyone saw coming off the transit lift, and this morning someone had already been up a ladder with a brush. Yesterday''s number was gone under a coat of pale grey. In its place, in numerals a hand-span tall: 382. Below it, smaller, the line that had been there since before Teo took the job: ALTITUDE, METERS, POSTED WEEKLY. Someone had added, years ago in a different hand, a line under that too: WE ARE STILL HERE. Nobody had ever painted over it.

Teo stood in front of the wall long enough to be sure the number matched her own readout, the way she did most mornings, and then she started her walk.

Aerobloc Candelaria ran twelve decks around a central core, a cylinder that had never been built to look like anything but what it was: cheap lift, honest structure, forty-one households packed into a shape that made the trim math simple and the hallways narrow. Sixty years old this spring. Teo had read the original commissioning plates once, down on deck one where nobody went anymore, and the date stamped into the metal — 2166 — had startled her the way old dates always did, a reminder that the bloc had been rising and falling and rising again since before her mother was born on a tether platform two hundred kilometers east of here.

She walked deck by deck, the way she walked most days when the numbers asked for verification instead of just belief. Deck three: the storage floor, half the crates gone to dust under a skin of undisturbed condensation, the other half stacked by people who''d stopped believing anyone would ever come sort them. Deck five: the handholds outside 5-C, worn pale and smooth along one particular curve where a woman nobody remembered the name of had steadied herself for thirty years before she died in her own bed, and where everyone since had put their hand in exactly the same place out of habit more than need. Deck seven: an Air Tax bracket notice, three weeks old, taped beside a door, the numbers on it slightly higher than the notice before it, because a bloc at 382 meters paid a different bracket than a bloc at 400.

She knew which households sat over which structural members the way another person might know which relatives sat where at a funeral. It wasn''t sentiment. It was the job. If a quadrant needed to come down in mass — if she needed six units on the water main instead of nine, if a corridor needed to close because the frame under it had gone soft in the readings — she needed to know, before she ever proposed it to Sigrun, exactly whose morning that decision would rearrange. Deck nine held the widow in 8-D, who had outlived a husband and, this year, the extra income his shop shift used to bring in. Deck eleven held a family of four stacked into space meant for two, waiting on a transfer list that hadn''t moved in three years. None of them were mass to her. They were loads, and loads had lives, and she had never once let herself forget that a lever arm was also somebody''s kitchen table.

At deck four she passed a door with a hand-lettered sign she''d seen a hundred times without really reading it: CASTELLANOS — MACHINE SHOP, ESTABLISHED 2186. Forty years, near enough. She''d been inside twice, both times for readings on the deck''s load rating, and both times the man inside had watched her instruments the way some people watched weather.

Near the core access on deck two, a boy she didn''t know ran past her toward the transit lift, late for school transit, and an old man leaning against the rail — not one of the eight names she carried in her head as decision-makers, just a machinist off the third floor, retired, out for his morning air — nodded to her the way people nodded to the person who painted the number on the wall. Not warmly. Not unkindly. The way you nod to weather.

She stopped at the outer skin window on deck six, where the city dropped away below in its long grey haze, the lake a smear of light far down, the Gray Zone beyond it, the Spires further still, catching sun that hadn''t reached the bloc yet. From here Candelaria looked like what it was: a home built for people who couldn''t afford to live any higher, holding its lift the way a tired arm holds a weight it has held too long.

Freeboard was the word she used for this feeling, though nobody but another trim engineer would have understood why. It meant the margin between the water and the rail on an old surface hull, back when hulls floated on water instead of holding themselves up against nothing. Candelaria''s freeboard was altitude now, sixty-two meters of it between where the bloc sat and where the law stopped caring what happened to it. Sixty-two meters was not a small number. It was also not, at a meter a day and climbing, a number that behaved like it would last.

Three hundred eighty-two meters. Thirty-eight days until jettison stopped being a word on her schedule and became a fact in someone''s hallway.

She turned back toward the core, already composing the week''s posting in her head — not the wording, the wording never changed, just the number — and did not yet know that in three days a letter from a man she had never met would arrive in forty-one wrist displays at once, offering to buy the whole weight of the problem out from under her.

She only knew, walking the spine the way she walked it most mornings, which walls held which lives, and which lives, if it ever came to redistributing quadrants instead of crates, could bear to be moved without the bloc losing anything but square footage. It was a short list. It got shorter every week the Hum climbed.' WHERE Id='019F3AC8-397C-7E21-8B58-9E4B5317227C';
UPDATE Beats SET [Text]=N'The letter arrived on a Wednesday, the way most things that changed a household''s math arrived: quietly, through neuretics, sitting in forty-one wrist displays at the same hour of the same morning, so that nobody in Candelaria could claim they''d heard it first.

Teo read it standing at the core gantry rail, three days into the week''s readings, because Sigrun had forwarded it to her before it went out wide — a courtesy, or a warning, Teo hadn''t decided which. The sender line read AshgraveMaterials Reclamation Division, and under that, a name: Ruslan Adeyinka, Senior Broker. She didn''t know the name. She knew the company the way anyone who worked mass and structure in this city knew it — a CorpoNation that bought failing lift assets before the law could seize them for nothing, stripped what could be stripped, and sold the rest as certified salvage. AshgraveMaterials didn''t demolish blocs. It priced them, and then it owned whatever it had priced.

The letter itself was short, which surprised her more than its contents did.

AshgraveMaterials Reclamation Division is prepared to purchase the structural mass of Aerobloc Candelaria in full, effective upon co-op ratification. Total offer: Φ847,000. Distributed evenly across forty-one registered households, this represents approximately Φ20,650 per household. AshgraveMaterials will additionally fund relocation to ground-tier residential blocks for all current residents, coordinated through the co-op chair. This offer does not expire on a rolling basis; it will remain open for the co-op''s full deliberation period. A structural assessment accompanies this offer as an appendix and is available to any resident on request.

She read the number twice, the way she read any number that arrived without her having calculated it first. Φ847,000 was not an arbitrary figure. Somebody at AshgraveMaterials had run the frame''s remaining recoverable mass against current salvage rates and landed on something specific, something that hadn''t been rounded to look generous. It read like her own ledger. That was what unsettled her about it — not the amount, but the fact that whoever built it thought in the same units she did.

She opened the appendix out of the habit of checking anyone''s structural math against her own, and found, to her private annoyance, that it was clean. Coherence decay curve, current altitude, projected time to the 320-meter line — the numbers matched her schedule within a rounding error. Whoever had written this had either gotten hold of her weekly postings, which were public, or had run an independent assessment good enough to land in the same place. Either way, it meant Ruslan Adeyinka wasn''t guessing. He''d read the bloc the way she''d read it herself, from the outside, and reached the conclusion she reached every morning and told no one but her ledger: that the frame was old, and old frames did not recover, they only bought time against a curve that always won in the end.

What the letter didn''t say, because it had no column for it, was what Φ20,650 meant differently in each of the forty-one households it would land in. Teo already knew, from three years of running the mass ledger, that it wouldn''t mean the same thing twice. Some households would read it as a rescue. Some would read it as an insult. She thought, briefly and without wanting to, of Priya Guðmundsen''s kitchen, the wrist display balance Teo had glimpsed once by accident, the shortfall that number would very nearly answer. She thought, just as briefly, of the machine shop on deck four, forty years of calibration bolted into a floor that Φ20,650 could never buy back.

Already, faint through the shared channel every household kept half-open for co-op business, she could feel the bloc''s attention shift. Nothing on that channel was private — it never was, in Candelaria; the co-op''s whole culture ran on things said in the open, postings on a wall, offers read aloud — but she could still register the change in its texture the way she registered a change in the Hum: not words yet, just weight moving, forty-one households feeling the same number land in forty-one different places at once.

Almagre logged the letter''s arrival without being asked, filing it under Co-Op Correspondence — Pending Ratification, and Teo let it, because that was accurate, and because the automaton''s filing never carried an opinion she''d have to argue with.

She forwarded no response. It wasn''t hers to answer. Her job started after a decision existed, not before — she turned mass into numbers, she didn''t turn people into decisions. But she stayed at the rail longer than the reading required, watching the letter sit open on her display beside the week''s coherence curve, two documents that agreed with each other completely and would, she suspected, agree with nothing else in the bloc for a long time to come.

Below, on the commons wall, the number still read 380, freshly repainted that morning to match the day''s drop. Above it, someone would need to decide, soon, whether that number was a countdown to a landing or a countdown to a sale. Teo closed the display, logged her hours, and went to find Sigrun, because whatever this letter turned into, the chair would need the schedule laid next to it before she called anyone into a room to talk about either one.

Behind her, the frame hummed on, the same low strain it had carried all week, indifferent to offers, patient the way only physics could afford to be patient, waiting on nobody''s vote to keep doing exactly what it had been doing for sixty years: getting slowly, honestly, measurably tired.

She thought about the appendix again on her way to find Sigrun, the way its curve sat so evenly against her own. Two people, working from opposite ends of the same bloc, had looked at the same tired frame and arrived at the same honest number. It was, she thought, the one part of this she didn''t yet know how to feel about — not the offer, not the money, just the fact that somebody outside Candelaria had done her arithmetic and gotten the same answer she had, without ever once needing to know a single name that lived inside it.' WHERE Id='019F3AC8-397D-765D-B322-1A94325715BC';
UPDATE Beats SET [Text]=N'Sigrun called the meeting for the second evening after the letter, which Teo understood as its own kind of decision: not so soon that people would say she''d rushed them, not so late that anyone could say she''d sat on it. The common space on deck one filled the way it always filled for something that mattered — fast at first, then slow, then all at once in the last five minutes, until every bench was taken and people stood along the walls with the particular stillness of a room that already knows what it''s there to hear.

Forty-one households. Not every seat held a full household; some sent one, some sent two, a few sent nobody and would get the minutes relayed over the shared channel by evening. Teo counted the room the way she counted anything, out of habit more than need, and put the number somewhere near seventy adults and rather fewer children, most of the children still in school transit or asleep. She stood near the core-access wall, not at the front, because this wasn''t her meeting. She was there to answer questions about a schedule, not to make an argument. She had made her argument every Monday for three years, in paint, on the wall outside.

From the wall she could pick out most of the names that would matter before the night was over, the way she always could in this room. Priya Guðmundsen sat near the front with her wrist display angled slightly toward her own knee, the way people sat when they already knew which number in tonight''s meeting was theirs. Wen Castellanos stood rather than sat, arms folded, near the door he''d have to walk past to get home to deck four. Dagny Obuya sat alone near the back, upright, hands folded, the way she sat at every meeting Teo had ever seen her attend — present, attentive, giving away nothing. Almagre''s presence registered only as a faint, steady hum in the room''s lighting rig, keeping the space''s own trim without being asked, the automaton''s version of standing quietly against a wall.

Sigrun stood at the front without a podium, without notes, her wrist display dark. She was Icelandic-Brazilian, silver-haired, built like someone who had spent forty years fixing things with her hands before she ever fixed anything with a gavel, and she had chaired the co-op for six of those years by being the person nobody minded being told hard news by. She let the room settle on its own before she spoke, and when she did, her voice didn''t reach for anything.

"Two things tonight," she said. "I''ll give you both before anyone asks a question, because I want you hearing them together, not one used against the other."

She held up nothing — there was nothing to hold, the numbers lived on the wall and in every wrist display in the room — and gave them the first thing plainly. "Current altitude, three hundred seventy-eight meters. Teo''s schedule has us losing it at close to a meter a day, and the rate is not improving. At current trend, we cross three hundred twenty — The Low — inside the year. Before that line, Teo''s jettison program begins. Best estimate, thirty-seven days from tonight."

No one in the room looked surprised. That was the strangeness of it, Teo thought, standing against the wall: nothing in what Sigrun had just said was new to anyone. It had all been posted, all season, every Monday, in paint a hand-span tall. Knowing a thing and hearing it said out loud in a room full of your neighbors were not, it turned out, the same thing at all.

"Second," Sigrun said, and here her voice didn''t change, though the room''s did — a shift Teo felt more than heard, a held breath spreading bench to bench. "Three days ago, AshgraveMaterials Reclamation Division sent the co-op a written offer. I''m going to read it to you exactly as it came, because I don''t trust myself to say it better, and because nobody in this room should hear this secondhand."

She read it. All of it — the total, the per-household figure, the relocation clause, the appendix''s existence and where to find it — in the same flat, careful voice she''d used for the altitude number, so that by the time she reached Φ20,650 per household, it landed in the room with no more or less weight than three hundred seventy-eight meters had landed with a minute before. That was deliberate, Teo understood. Sigrun was laying two facts on the same table at the same height, refusing to let either one arrive dressed as the answer to the other.

When she finished, she let the silence hold for longer than most people would have dared.

"I''m not going to call a vote tonight," she said. "I''m not going to ask for a show of hands, and I''m not going to ask anyone to speak who isn''t ready to. This offer stays open through the co-op''s full deliberation. We''ll meet again. More than once, probably. Tonight I wanted you to have both numbers in the same room, at the same time, from the same voice, so that whatever you end up thinking, you thought it with the whole picture in front of you and not half of it."

She stepped back, not far, just enough to signal the floor was open, and the room did the thing rooms do after news like that: it didn''t speak first. Seventy adults looked at the number on nobody''s wrist display and the altitude nobody needed reminding of, and for a long moment nobody wanted to be the one whose voice broke the quiet Sigrun had built so carefully out of two hard facts laid flat.

Teo watched from the wall, already running, out of habit, the arithmetic nobody had asked her for yet: forty-one households, one number that stayed fixed no matter who spoke next, and a silence that would not, she already knew from years of watching rooms like this one, last much longer than it took for someone to do the math on what Φ20,650 meant to them specifically, out loud, in front of everyone.' WHERE Id='019F3AC8-397D-73CF-A2C6-B8F550E5EA5E';
UPDATE Beats SET [Text]=N'It was Priya who broke it, in the end, and she did it the way Teo had half-expected someone would: not with a speech, with a question aimed at the whole room instead of at Sigrun specifically, her hand raised the way a person raises a hand when they''ve already decided to speak and are only waiting for their own nerve to catch up.

"I want to ask something plainly," she said, standing, "because I think if I don''t, someone else will ask it less plainly, and I''d rather it came from me."

Sigrun nodded her forward without a word.

Priya was younger than Dagny, older than Teo, dark-haired, dressed in the kind of practical clothes that said she''d come straight from a shift rather than dressed for a meeting. Her voice held steady, but Teo, watching from the wall, saw the trim tell before the words did: one hand pressed flat against her own sternum, the gesture of someone holding a weight in place rather than gesturing.

"My daughter Kaja needs a corrective procedure on her neuretics integration," she said. "It''s not optional and it''s not cosmetic — it''s the cochlear feeds, and the window for it closes in a matter of months, not years. The fund I''ve built for it is short. Exactly short. Φ8,400 short, as of this week''s balance, and I''ve done the arithmetic enough times that I don''t need to check it again to say the number out loud in front of all of you."

Nobody in the room moved. This, too, Teo understood without needing to be told: Priya had done this on purpose, put a number this specific into a room where every other number tonight had been specific too, because a vague hardship could be waved past and an exact one couldn''t.

"I''m not going to pretend the offer solves everything," Priya went on. "I know what people will say about it — that it prices this bloc like it''s already dead, that it hands our home to a company that profits either way. I''ve heard myself think all of that this week. But Φ20,650 per household closes my daughter''s shortfall with room left over, and I don''t know how to stand in this room and pretend that isn''t the first thing I think about every time I look at the number on that wall outside." She paused, and when she went on her voice had dropped, not from uncertainty, from precision. "So I want to ask honestly, not as an accusation to anyone — is there another household in this room counting the same kind of shortfall against the same kind of clock? Because if there is, I think we should know that before anyone decides this is only my problem."

The silence that followed wasn''t the same silence as before. Teo had heard enough rooms to know the difference: the first quiet had been a room waiting to see who would speak. This one was a room doing arithmetic against its own life, in private, all at once. A few heads turned toward wrist displays that weren''t showing anyone else anything, the private reflex of checking a number that had nothing to do with the meeting and everything to do with it. Nobody answered Priya''s question aloud. Whether that meant no one else carried a shortfall like hers, or simply that no one else was ready to say so in front of seventy people, Teo couldn''t have told her, and didn''t try.

Kaja wasn''t in the room. Priya had said, once, weeks ago, in the ordinary way people mention their children to someone who fixes their water pressure, that her daughter was twelve and hated being talked about more than she hated almost anything, and tonight bore that out: no small figure at Priya''s side, no name invoked for sympathy beyond the bare fact of it. Priya had put the shortfall on the table and left the girl herself out of the room entirely, which struck Teo, watching, as its own kind of restraint — the kind that cost something to keep up.

Near the door, Wen hadn''t moved through any of it. His arms stayed folded, his weight settled back against the frame, and if Priya''s number had reached him the way it seemed to reach everyone else, nothing in his stance said so. Teo noticed the stillness the way she noticed a reading that refused to shift when everything around it moved — not nothing, just a different kind of load, held differently.

Sigrun let the quiet run its course before she spoke again. "Thank you, Priya," she said, and nothing else — no comfort, no agreement, no argument on the offer''s behalf, because that wasn''t the chair''s job either. She was there to hold the room level, not to tip it.

Teo watched Priya sit back down, the hand that had been pressed to her sternum now flat on her own knee, and thought, in the register she thought in whether she wanted to or not, that Priya had just done something close to what Teo did every Monday on the commons wall: put an honest number where everyone could see it and refused to soften it for the room''s comfort. The difference was that Teo''s number only ever subtracted. Priya''s, if the vote went her way, would be the first number in this whole slow business that added something back.

It was not, Teo thought, a small thing to have said out loud, in a room where saying it changed nothing about the shortfall itself and everything about who now knew it existed. She filed the number the way she filed everything that mattered — not on any ledger, just in the part of her that would carry it into every calculation from here forward, whether the co-op''s business ever asked her to or not.' WHERE Id='019F3AC8-397D-7CB6-966C-EAF661D744E9';
UPDATE Beats SET [Text]=N'Wen didn''t raise his hand. He simply pushed off from the doorframe he''d been leaning against all evening and let his own weight carry him a few steps into the room, and the room, which had spent the last several minutes turned toward Priya, turned toward him instead without needing to be asked.

"I''m not going to argue with what she said," he said, nodding once toward Priya without quite looking at her. "Her number''s real. I believe every part of it." He let that sit a second, the way a man lets a level settle before he trusts the bubble. "I want to put a different number next to it, so you all have both."

He didn''t reach for his wrist display. What he had to say didn''t live in a balance.

"Household 23. My grandfather bolted a machine shop into that floor forty years ago — 2186, if anyone wants the year exact. Two lathes, three dies, a bank of jigs he built by hand because the ones he could afford to buy weren''t square enough for what he needed. I''ve spent thirty of those forty years learning what he knew about calibrating them, and I''m not finished learning it. That shop isn''t furniture. It''s fixture. It''s bolted into the frame the same way the water main is bolted into the frame, and there isn''t a version of moving it that doesn''t mean starting thirty years of calibration over from a floor that''s never held those machines before."

He looked, finally, toward the front of the room, toward Sigrun, though what he said next was for everyone.

"I know what happens to fixture mass if this bloc sells. AshgraveMaterials doesn''t relocate machine shops. They strip them for the metal and call it certified salvage, and the number they''d give me for it wouldn''t buy back a single jig, because you can''t buy back thirty years of a man''s hands learning a machine. So when I say no to this offer, I''m not saying Priya''s shortfall isn''t real. I''m saying mine is real too, and mine doesn''t have a number that closes it, because what I''d be losing isn''t the kind of thing money was ever built to replace."

He didn''t explain further than that. He didn''t say why the shop couldn''t be dismantled and rebuilt somewhere else, floor by floor, jig by jig, given time and money and patience — and Teo, watching from the wall, understood without being told that he wasn''t going to, that the answer lived somewhere past arithmetic and he had no intention of walking the room there. Some numbers, in her experience, resisted being shown their own math. She kept that thought to herself. It wasn''t hers to press.

She had been in that shop twice for load readings, and both times she''d noticed the same thing: how quiet the machines sat when they weren''t running, how every surface Wen''s hand had touched in thirty years carried a particular kind of shine that no cleaning solvent put there. A jig held its calibration the way a frame held its coherence — invisibly, until someone asked it to bear weight, and then it either held or it didn''t. She didn''t say any of that aloud either. It wasn''t the room''s business, and it wasn''t, strictly, hers.

Near the back, Dagny hadn''t moved through any of it, her hands still folded, her face giving away nothing about which number she found more persuasive, if either. Teo had seen her sit through enough meetings by now to know that stillness wasn''t agreement and wasn''t disagreement. It was simply how the woman attended to things, the way some people listened with their whole bodies and others, like Dagny, listened by refusing to spend any part of themselves on being watched listening.

"That''s not a question," Sigrun said, quietly, when he''d finished — not a correction, an observation, the kind she made when she wanted a statement on the record as exactly what it was and nothing softer.

"No," Wen agreed. "It''s not."

He stepped back to the doorframe and folded his arms again, and the room, having heard two numbers now that didn''t fit in the same column — one that money could close and one that money couldn''t touch — settled into a different kind of quiet than either of the two that had come before. Teo felt the shape of it the way she felt a bloc settle after a jettison: not resolved, just redistributed, the argument''s weight sitting differently in the room than it had five minutes earlier.

Sigrun didn''t call for anyone else to speak. She let the two positions stand where they''d landed — Priya''s shortfall in plain sight, Wen''s refusal plain beside it, neither one erasing the other — and closed the evening the way she''d opened it, without softening either fact for the room''s comfort.

"We meet again before any decision," she said. "Nothing changes tonight. I wanted you hearing this from each other before you heard it from anyone secondhand."

The room broke apart slowly, the way rooms did after news that didn''t finish anything, only started something. Teo stayed against the wall a while longer, watching Priya gather her things without looking at anyone, watching Wen leave first through the door he''d been holding up all evening, and thought — in trim, because it was the only language honest enough to hold both of them at once — that she now had two loads on her ledger that would never balance against each other, no matter which way the frame finally settled.

Overhead, the lighting rig''s hum steadied as Almagre eased the common space back toward its resting draw, the automaton''s quiet, unremarked correction of a room that had just held seventy people''s weight and their attention both. Nobody thanked it. Nobody noticed it at all, which was, Teo thought, exactly how it was built to be noticed.' WHERE Id='019F3AC8-397D-79F7-B8CA-2B562EF072B5';
