using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using StreetSamurai.Core.Data;
using StreetSamurai.Core.Services;

namespace StreetSamurai.Cli;

/// <summary>
/// ss --audit-story --slug &lt;book-or-chapter-slug&gt; [--deep] [--model &lt;id&gt;] [--out &lt;path&gt;]
///
/// The "Player Piano" — one repeatable command that runs the full QA battery against a
/// node and emits a single consolidated scorecard. Book-aware: a book fans out into its
/// draft chapters; a lone chapter audits itself.
///
/// Tiers:
///   FREE  (always)  — DB census (population/tagging/scoring matrix + satellite counts),
///                     coverage rollup, plant-audit, prose-check. Zero API cost.
///   DEEP  (--deep)  — per-chapter examine-emotion + story-audit + diagnose-node + check-fidelity.
///                     These call the LLM/embeddings. Pair with --model to pick the tier
///                     (e.g. --model claude-haiku-4-5-20251001 for a cheap, non-rate-limited
///                     full pass). The override is restored when the run finishes.
///
/// Reuses the existing single-purpose CLI handlers (captured in-process) so this stays a
/// thin orchestrator, not a re-implementation. Output goes to stdout and, if --out is given,
/// to a markdown file.
/// </summary>
public static class AuditNodeCli
{
    public static async Task<int> RunAsync(IServiceProvider sp, string[] args)
    {
        var slug    = GetArg(args, "--slug");
        var deep    = args.Contains("--deep");
        var model   = GetArg(args, "--model");
        var outPath = GetArg(args, "--out");
        if (slug == null) { Console.Error.WriteLine("Usage: ss --audit-story --slug <slug> [--deep] [--model <id>] [--out <path>]"); return 2; }

        var dbFactory = sp.GetRequiredService<IDbContextFactory<StreetSamuraiDbContext>>();
        var monitor   = sp.GetRequiredService<WorkflowMonitorService>();

        await using var db = await dbFactory.CreateDbContextAsync();
        var root = await db.Nodes.AsNoTracking()
            .Where(s => s.Slug == slug || s.NodeCode == slug)
            .Select(s => new { s.Id, s.Title, s.Slug, s.Score, s.PreviousNodeId, s.Seed })
            .FirstOrDefaultAsync();
        if (root == null) { Console.Error.WriteLine($"Node not found: {slug}"); return 2; }

        var children = await db.Nodes.AsNoTracking()
            .Where(s => s.ParentNodeId == root.Id && s.Status == "draft")
            .OrderBy(s => s.SortKey)
            .Select(s => new ChapterRef(s.Id, s.Title, s.Slug, s.Score, s.Seed))
            .ToListAsync();
        var isBook   = children.Count > 0;
        var chapters = isBook ? children : [new ChapterRef(root.Id, root.Title, root.Slug, root.Score, root.Seed)];

        // A Seed shorter than this is just a title, not a bible anchor — check-fidelity
        // compares prose embeddings against it and would emit pure noise (157 false
        // "bible drift" findings in the first BCODA run). Gate fidelity on a real Seed.
        const int MinSeedForFidelity = 200;

        var sb = new StringBuilder();
        void W(string s = "") => sb.AppendLine(s);

        W($"# Node Audit — {root.Title} ({root.Slug})");
        W($"_Generated by `ss --audit-story`{(deep ? $", deep tier, model={model ?? "default"}" : ", free tier")}._");
        W();

        // ── SECTION 1: CENSUS ────────────────────────────────────────────────────
        W("## 1. Population / tagging / scoring census");
        W();
        W("| Ch | Title | Beats | Text | Desc | Struct | Tone | Score | EQ | Mentions |");
        W("|----|-------|-------|------|-----|--------|------|-------|----|----------|");

        var gaps = new List<string>();
        int totBeats = 0, totText = 0, totSyn = 0, totStruct = 0, totTone = 0, totScore = 0, totEq = 0, totMentionBeats = 0;

        foreach (var ch in chapters)
        {
            var stats = await CensusChapterAsync(db, ch.Id);
            totBeats += stats.Beats; totText += stats.Text; totSyn += stats.Syn; totStruct += stats.Struct;
            totTone += stats.Tone; totScore += stats.Scored; totEq += stats.Eq; totMentionBeats += stats.MentionBeats;
            W($"| {Trunc(ch.Title, 22)} | | {stats.Beats} | {stats.Text} | {stats.Syn} | {stats.Struct} | {stats.Tone} | {stats.Scored} | {stats.Eq} | {stats.MentionBeats} |");
        }
        W($"| **TOTAL** | | {totBeats} | {totText} | {totSyn} | {totStruct} | {totTone} | {totScore} | {totEq} | {totMentionBeats} |");
        W();

        if (totText < totBeats)  gaps.Add($"{totBeats - totText} beat(s) have no prose text.");
        if (totSyn < totBeats)   gaps.Add($"{totBeats - totSyn} beat(s) missing Description (degrades mode detection + pacing — backfill or generate).");
        if (totStruct < totBeats) gaps.Add($"{totBeats - totStruct} beat(s) missing StructureRole (derivable from position — deterministic backfill).");
        if (totEq == 0)          gaps.Add("EmotionalScore never populated (run --audit-story --deep, or ss --examine-emotion).");
        if (totMentionBeats < totBeats) gaps.Add($"{totBeats - totMentionBeats} beat(s) not entity-scanned (run ss --scan-entity-mentions).");

        // ── SECTION 2: EXISTING REVIEW DATA ──────────────────────────────────────
        W("## 2. Existing review ballots (already paid for)");
        W();
        W("| Title | Ballots | Avg | Flow |");
        W("|-------|---------|-----|------|");
        var scopeIds = chapters.Select(c => c.Id).Append(root.Id).ToList();
        var reviews = await db.NodeReviews.AsNoTracking()
            .Where(r => scopeIds.Contains(r.NodeId))
            .GroupBy(r => r.NodeId)
            .Select(g => new { NodeId = g.Key, Ballots = g.Count(), Avg = g.Average(x => x.Score), Flow = g.Average(x => (double?)x.FlowScore) })
            .ToListAsync();
        var titleById = chapters.ToDictionary(c => c.Id, c => c.Title);
        titleById[root.Id] = root.Title + " (book)";
        foreach (var r in reviews.OrderByDescending(x => x.NodeId == root.Id).ThenBy(x => titleById.GetValueOrDefault(x.NodeId)))
            W($"| {Trunc(titleById.GetValueOrDefault(r.NodeId, "?"), 30)} | {r.Ballots} | {r.Avg:F0} | {r.Flow:F0} |");
        W();
        var weakest = reviews.Where(r => r.NodeId != root.Id).OrderBy(r => r.Avg).Take(3)
            .Select(r => $"{titleById.GetValueOrDefault(r.NodeId)} ({r.Avg:F0}/{r.Flow:F0})").ToList();
        if (weakest.Count > 0) W($"**Weakest by raw ballot:** {string.Join("; ", weakest)}");
        W();

        // ── SECTION 3: FREE AUDITS ───────────────────────────────────────────────
        W("## 3. Free audits");
        W();
        var sections = new List<(string Name, int Exit)>();

        // Coverage (book-level rollup)
        var coverage = await monitor.GetNodeCoverageAsync(root.Id);
        W($"### Coverage — {coverage.TotalBeatsLogged} beats logged");
        foreach (var s in coverage.ServiceStats)
            W($"- {s.Service}: {(s.ApplicableCalls > 0 ? $"{s.ActivationRate:P0}" : "n/a")} ({s.ActiveCalls}/{s.ApplicableCalls})");
        if (coverage.Gaps.Count > 0) foreach (var g in coverage.Gaps) gaps.Add($"Coverage: {g}");
        W();

        // Plant-audit + prose-check per chapter (reuse handlers)
        W("### Plant/payoff + prose lint (per chapter)");
        W();
        foreach (var ch in chapters)
        {
            var (pExit, pOut) = await Capture(() => PlantPayoffCli.RunAsync(["--plant-audit", "--slug", ch.Slug, "--json"], sp));
            var (lExit, lOut) = await Capture(() => ProseCheckCli.RunAsync(["--prose-check", "--slug", ch.Slug, "--json"], sp));
            sections.Add(($"plant:{ch.Slug}", pExit));
            sections.Add(($"prose:{ch.Slug}", lExit));
            W($"- **{Trunc(ch.Title, 30)}** — plants: {ExitLabel(pExit)}, prose-lint: {ExitLabel(lExit)}");
        }
        W();

        // ── SECTION 4: DEEP AUDITS ───────────────────────────────────────────────
        SettingsService? settings = null;
        string? savedModel = null;
        if (deep)
        {
            W("## 4. Deep audits (LLM)");
            W();
            if (model != null)
            {
                settings = sp.GetRequiredService<SettingsService>();
                savedModel = settings.Model;
                settings.Model = model;
                W($"_Model override: `{model}` (restored to `{savedModel}` after run)._");
                W();
            }

            try
            {
                foreach (var ch in chapters)
                {
                    W($"### {ch.Title}");
                    var (eqExit, eqOut)   = await Capture(() => ExamineEmotionCli.RunAsync(["--examine-emotion", "--slug", ch.Slug, "--json"], sp));
                    var (auExit, auOut)   = await Capture(() => StoryAuditCli.RunAsync(["--story-audit", "--slug", ch.Slug, "--json"], sp));
                    var (dgExit, dgOut)   = await Capture(() => DiagnoseNodeCli.RunAsync(["--diagnose-story", "--slug", ch.Slug, "--json"], sp));
                    sections.Add(($"eq:{ch.Slug}", eqExit));
                    sections.Add(($"audit:{ch.Slug}", auExit));
                    sections.Add(($"diagnose:{ch.Slug}", dgExit));

                    var hasSeed = (ch.Seed?.Length ?? 0) >= MinSeedForFidelity;
                    var fdExit = 0; var fdOut = "(skipped — no Seed anchor ≥200 chars; fidelity would be noise)";
                    if (hasSeed)
                    {
                        (fdExit, fdOut) = await Capture(() => CheckFidelityCli.RunAsync(["--check-fidelity", "--slug", ch.Slug, "--json"], sp));
                        sections.Add(($"fidelity:{ch.Slug}", fdExit));
                    }
                    W($"- examine-emotion: {ExitLabel(eqExit)}  •  story-audit: {ExitLabel(auExit)}  •  diagnose: {ExitLabel(dgExit)}  •  fidelity: {(hasSeed ? ExitLabel(fdExit) : "—")}");
                    W();
                    W("<details><summary>raw json</summary>\n");
                    W("```json"); W(eqOut.Trim()); W(auOut.Trim()); W(dgOut.Trim()); W(fdOut.Trim()); W("```");
                    W("</details>"); W();
                }
            }
            finally
            {
                if (settings != null && savedModel != null) settings.Model = savedModel;
            }
        }

        // ── SECTION 5: SCORECARD + GAPS ──────────────────────────────────────────
        W("## 5. Scorecard");
        W();
        var blocking = sections.Count(s => s.Exit == 2);
        var advisory = sections.Count(s => s.Exit == 1);
        var clean    = sections.Count(s => s.Exit == 0);
        W($"- ✅ clean: {clean}   ⚠️ advisory: {advisory}   ❌ blocking: {blocking}   (across {sections.Count} checks)");
        W($"- Node score (clustered): {root.Score:F2}");
        W();
        W("## 6. Gaps & recommended actions");
        W();
        if (gaps.Count == 0) W("_No structural gaps detected._");
        else foreach (var g in gaps) W($"- {g}");
        W();

        var report = sb.ToString();
        Console.WriteLine(report);
        if (outPath != null)
        {
            await File.WriteAllTextAsync(outPath, report);
            Console.WriteLine($"\nReport written to {outPath}");
        }

        return blocking > 0 ? 2 : advisory > 0 ? 1 : 0;
    }

    private record ChapterRef(Guid Id, string Title, string Slug, double? Score, string? Seed);
    private record Census(int Beats, int Text, int Syn, int Struct, int Tone, int Scored, int Eq, int MentionBeats);

    private static async Task<Census> CensusChapterAsync(StreetSamuraiDbContext db, Guid chapterId)
    {
        var beats = await (from sb in db.BeatNodes.AsNoTracking()
                           join b in db.Beats.AsNoTracking() on sb.BeatId equals b.Id
                           where sb.NodeId == chapterId && sb.IsEnabled
                           select new { b.Id, b.Text, b.Description, b.StructureRole, b.EmotionalTone, b.Score, b.EmotionalScore }).ToListAsync();
        var ids = beats.Select(b => b.Id).ToList();
        var mentionBeats = await db.BeatEntityMentions.AsNoTracking()
            .Where(m => ids.Contains(m.BeatId)).Select(m => m.BeatId).Distinct().CountAsync();
        return new Census(
            Beats:        beats.Count,
            Text:         beats.Count(b => !string.IsNullOrEmpty(b.Text)),
            Syn:          beats.Count(b => !string.IsNullOrEmpty(b.Description)),
            Struct:       beats.Count(b => b.StructureRole != null),
            Tone:         beats.Count(b => b.EmotionalTone != null),
            Scored:       beats.Count(b => b.Score != null),
            Eq:           beats.Count(b => b.EmotionalScore != null),
            MentionBeats: mentionBeats);
    }

    private static async Task<(int Exit, string Output)> Capture(Func<Task<int>> run)
    {
        var origOut = Console.Out;
        var sw = new StringWriter();
        Console.SetOut(sw);
        int code;
        try { code = await run(); }
        catch (Exception ex) { sw.Write($"(handler threw: {ex.Message})"); code = 2; }
        finally { Console.SetOut(origOut); }
        return (code, sw.ToString());
    }

    private static string ExitLabel(int exit) => exit switch { 0 => "✅", 1 => "⚠️", _ => "❌" };
    private static string Trunc(string s, int max) => s.Length <= max ? s : s[..(max - 1)] + "…";

    private static string? GetArg(string[] args, string flag)
    {
        var i = Array.IndexOf(args, flag);
        return i >= 0 && i + 1 < args.Length ? args[i + 1] : null;
    }
}
