$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=Prose;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$Ch9NodeId = [guid]"019FA96C-A291-7DFA-B5F6-1BCA319ED9C1"
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'congenital-blindness-sin-question' = @{ title='A live theological question, not a rhetorical throwaway'; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 9:2. Keener documents that the disciples' question, whether the man's own sin or his parents' caused his congenital blindness, reflects a genuinely live theological option in Second Temple and early rabbinic Judaism rather than a naive or invented framing: alongside the standard reading of inherited guilt (a parent's sin visited on a child), later rabbinic tradition also speculated, building on texts like Genesis 25:22 (Jacob and Esau struggling within Rebekah's womb), that a fetus could itself act, and even sin, before birth — making `"this man himself,`" despite being unborn at the time of any wrongdoing, a coherent candidate for blame within that framework." }
'ezekiel-deuteronomic-retribution-tension' = @{ title='Two competing scripts for suffering'; body="D. A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids, MI: Wm. B. Eerdmans, 1991), commentary ad loc. John 9:2-3. Carson situates the disciples' dilemma against a real tension within Israel's own scriptures: Deuteronomy 5:9 and Exodus 20:5 describe God `"visiting the iniquity of the fathers upon the children,`" while Ezekiel 18:20 insists just as forcefully that `"the son shall not suffer for the iniquity of the father`" and that each person answers for their own sin alone. Second Temple Judaism had not resolved that tension into a single settled doctrine, which is precisely why the disciples can pose their either/or question as a genuine, open puzzle rather than a rhetorical setup." }
'jesus-rejects-retributive-framework' = @{ title="An answer that declines the premise"; body="D. A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids, MI: Wm. B. Eerdmans, 1991), commentary ad loc. John 9:3. Carson reads Jesus's reply, `"it was not that this man sinned, or his parents, but that the works of God might be displayed in him,`" as declining to adjudicate the disciples' retributive either/or at all, substituting a teleological purpose for a causal diagnosis. Mainstream commentary treats this as consistent with the wider Gospel tradition's suspicion of facile suffering-equals-punishment reasoning, comparable to Jesus's comment elsewhere about the Galileans killed by Pilate and those crushed by the falling tower in Siloam (Luke 13:1-5), where the same refusal to read catastrophe as targeted divine punishment recurs." }
'pliny-saliva-remedy' = @{ title='Spittle as recognized medicine in the ancient world'; body="Pliny the Elder, Natural History, Book 28 (Loeb Classical Library, trans. W. H. S. Jones, Cambridge, MA: Harvard University Press, 1963), sections on the medicinal properties of human saliva. Pliny catalogues a range of therapeutic and apotropaic uses ancient Mediterranean medicine attributed to human spittle, including its application to the eyes, reflecting a widely shared folk-medical framework in which saliva was not a strange or arbitrary healing agent but a recognized, commonly invoked remedy across the Greco-Roman world." }
'tacitus-suetonius-vespasian-saliva' = @{ title='The same Vespasian tradition, a familiar comparandum'; body="Cornelius Tacitus, Histories, Book 4, chapter 81 (Loeb Classical Library, trans. Clifford H. Moore, Cambridge, MA: Harvard University Press, 1931); Suetonius, Lives of the Caesars: Vespasian, section 7 (Loeb Classical Library, trans. J. C. Rolfe, Cambridge, MA: Harvard University Press, 1914). Both historians record, independently of each other and of any Christian source, that the emperor Vespasian was petitioned at Alexandria by a blind man asking that Vespasian moisten his eyes with spittle, and that the man reportedly recovered his sight; Suetonius adds a lame man healed by touch in the same episode. This is the same widely cited Vespasian-saliva tradition already noted as a comparandum for Gospel spittle-healings elsewhere in this project's treatment of the Synoptic tradition; it remains here what it was there — independent evidence that healing by spittle was a recognizable category of claim in this period, not proof of any specific healing's mechanism." }
'siloam-sent-etymology' = @{ title='A name the Gospel stops to translate'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary ad loc. John 9:7. John pauses his narrative to gloss the pool's Hebrew-derived name for a Greek-speaking audience: `"Siloam (which means Sent).`" Brown reads the gloss as deliberate theological wordplay rather than incidental translation, since `"sent`" (apostellein) is one of the Fourth Gospel's own recurring descriptions of Jesus's relationship to the Father who sent him; the man is, in effect, sent to the pool called Sent by the one whom the Gospel repeatedly calls the Sent One." }
'siloam-pool-excavation-crossref' = @{ title='The excavated pool behind the story'; body="Hershel Shanks, `"The Siloam Pool: Where Jesus Cured the Blind Man,`" Biblical Archaeology Review 31, no. 5 (September/October 2005). Building on the Second Temple-period stepped pool already established in this project's discussion of John 7, Shanks reports on archaeologists Ronny Reich and Eli Shukron's 2004 discovery of the actual pool complex, confirming a real, physically excavated first-century site of the kind this chapter's narrative sends the man born blind to wash in — a genuine archaeological anchor beneath this specific pericope, not merely the earlier one." }
'mishnah-shabbat-kneading-labor' = @{ title='Why making mud counted as work'; body="Mishnah, Shabbat 7:2 (trans. Herbert Danby, The Mishnah, Oxford: Clarendon Press, 1933). The Mishnah's list of the thirty-nine primary categories of labor forbidden on the Sabbath includes kneading (lash) among its enumerated forms of prohibited work. Mainstream commentary reads the Pharisees' objection in this chapter as resting on exactly this kind of category: mixing spittle and dust into mud (9:6) was itself a recognizable act of `"kneading,`" making Jesus's healing method a plausible Sabbath violation in the eyes of his strictest critics, independent of anything about the healing's result." }
'mishnah-yoma-life-threat-exception' = @{ title='The one exception that swallows the rule'; body="Mishnah, Yoma 8:6 (trans. Herbert Danby, The Mishnah, Oxford: Clarendon Press, 1933). The Mishnah states that any doubt about danger to life overrides the Sabbath — the classic rabbinic principle, later termed pikuach nefesh, permitting Sabbath law to be set aside to save a life. A chronic, non-life-threatening condition like lifelong blindness falls outside that exception under later rabbinic reasoning, which is precisely why the healing in this chapter could plausibly register to some observers as unnecessary, unforced labor rather than a justified emergency intervention." }
'aposynagogos-term-occurrences' = @{ title='A word that appears nowhere else in the New Testament'; body="Raymond E. Brown, An Introduction to the Gospel of John, ed. Francis J. Moloney (New York: Doubleday, 2003), discussion of the Johannine community's history and its conflict with the synagogue. Brown notes that aposynagogos, the term behind `"put out of the synagogue`" at 9:22, recurs only twice more in the entire New Testament, both later in this same Gospel (12:42; 16:2), and nowhere in the Synoptics, Paul, or Acts. That narrow, exclusively Johannine concentration is itself a data point mainstream scholarship weighs heavily: whatever historical experience stands behind the word, it appears to be this Gospel's own distinctive concern rather than a widely shared feature of the broader early Christian movement's memory." }
'martyn-two-level-drama' = @{ title='A drama read on two levels at once'; body="J. Louis Martyn, History and Theology in the Fourth Gospel, 3rd ed. (Louisville, KY: Westminster John Knox Press, 2003; 1st ed. 1968), using John 9 as the book's central case study. Martyn argues the chapter's aposynagogos detail is anachronistic as a feature of Jesus's own actual ministry setting — there is no independent evidence of an operative, formal synagogue policy specifically expelling confessors of Jesus as Messiah in the 20s-30s CE — and instead reflects the Johannine community's own later, historically real experience of exclusion from synagogue life, retrojected into the narrative present of Jesus's ministry. On Martyn's reading, the healed man's own escalating confrontation with the authorities doubles as a portrait of the Johannine community's own confrontation with the synagogue of its own day." }
'brown-community-beloved-disciple' = @{ title='Reconstructing a community from its own Gospel'; body="Raymond E. Brown, The Community of the Beloved Disciple (New York: Paulist Press, 1979), chapter on the Johannine community's history and its break with the synagogue. Brown draws directly on this chapter's expulsion scene, among other Johannine passages, to reconstruct a plausible history of the Gospel's own originating community: a Jewish-Christian group whose confession of Jesus's identity precipitated a real, painful separation from the wider synagogue community that had been their own religious home, an experience Brown argues left a deep imprint on how the Gospel itself narrates conflict and rejection." }
'von-wahlde-second-edition' = @{ title="A redactional layer with its own historical moment"; body="Urban C. von Wahlde, The Gospel and Letters of John, vol. 2: Commentary on the Gospel of John, Eerdmans Critical Commentary (Grand Rapids, MI: Wm. B. Eerdmans, 2010), introduction and commentary ad loc. John 9. Von Wahlde's source- and redaction-critical analysis of the Gospel's compositional layers associates the aposynagogos passages, including this chapter's, with what he identifies as a later editorial stage of the Gospel's growth, a stage he argues responds directly to an intensifying, historically datable conflict between the Johannine community and the synagogue — an independent redaction-critical line of argument that converges with Martyn's and Brown's community-history readings without depending on either." }
'birkat-haminim-yavneh-tradition' = @{ title="The Twelfth Benediction, and the question of its date"; body="J. Louis Martyn, History and Theology in the Fourth Gospel, 3rd ed. (Louisville, KY: Westminster John Knox Press, 2003), discussion of the Birkat ha-Minim. Rabbinic tradition credits Samuel the Small, at the academy of Yavneh under the patriarch Gamaliel II in the closing decades of the first century CE, with composing or revising the Twelfth Benediction of the daily Amidah prayer to include a curse against minim (sectarians or heretics), a formula Martyn's original thesis proposed as the specific mechanism generating John's aposynagogos passages — a benediction whose recitation a confessing Jewish Christian could not honestly complete." }
'kimelman-katz-critique' = @{ title="A tighter link than the evidence supports"; body="Reuven Kimelman, `"Birkat Ha-Minim and the Lack of Evidence for an Anti-Christian Jewish Prayer in Late Antiquity,`" in Jewish and Christian Self-Definition, vol. 2, ed. E. P. Sanders, A. I. Baumgarten, and Alan Mendelson (Philadelphia: Fortress Press, 1981); Steven T. Katz, `"Issues in the Separation of Judaism and Christianity after 70 C.E.: A Reconsideration,`" Journal of Biblical Literature 103, no. 1 (1984): 43-76. Both Kimelman and Katz independently challenge Martyn's original tight linkage of John's expulsion passages to the Birkat ha-Minim specifically, questioning the benediction's precise date, its original target, and whether any synagogue in this period possessed the centralized authority to enforce a uniform exclusion policy against Jewish Christians as a defined group. Their critique does not overturn the broader consensus that John 9 reflects some real, later conflict between the Johannine community and synagogue authorities — only the specific mechanism Martyn proposed for it, a caution mainstream scholarship has increasingly absorbed." }
'brown-seven-scene-structure' = @{ title='A play in seven scenes'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), introductory comments to chapter 9. Brown reads John 9 as a deliberately constructed drama unfolding across seven distinct scenes — Jesus and his disciples, the healing itself, the neighbors' dispute over the man's identity, the first Pharisaic hearing, the summoning of the parents, the second and final hearing ending in expulsion, and Jesus's return to find the man — with the healed man's own testimony growing steadily bolder at each turn while his interrogators' position hardens in the opposite direction. Brown treats the structure as a genuine piece of literary artistry, not merely a sequence of loosely connected reports." }
'isaiah-blind-eyes-messianic' = @{ title='Opened eyes as a messianic-age signal'; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 9:1-7, background discussion. Keener connects the healing to Isaiah's prophetic association of the messianic age with restored sight — `"the eyes of the blind shall be opened`" (Isaiah 35:5) and `"to open the eyes that are blind`" (Isaiah 42:7) — background that would have given a first-century Jewish audience reason to read a blind man's healing as a deliberate, theologically loaded sign rather than a bare wonder-story, in keeping with the Fourth Gospel's own consistent practice of presenting Jesus's healings as signs pointing beyond themselves." }
'fortna-signs-source-sixth-sign' = @{ title='The sixth sign, and a hypothesized earlier source'; body="Robert T. Fortna, The Fourth Gospel and Its Predecessor: From Narrative Source to Present Gospel (Philadelphia: Fortress Press, 1988), reconstruction of the Signs Gospel's narrative sequence. This healing occupies the sixth position in the traditional count of the Fourth Gospel's seven numbered signs, and Fortna's source-critical reconstruction of a hypothesized earlier Signs Gospel underlying John includes a version of this same narrative among its recovered episodes, consistent with the broader scholarly view that this chapter's core healing account is one of the Gospel's oldest traditional layers, onto which the lengthy interrogation scenes were subsequently built." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
John introduces the man abruptly: Jesus, "passing by," sees a man blind from birth, and his disciples ask the question that opens the chapter — "Rabbi, who sinned, this man or his parents, that he was born blind?" (9:1-2). Jesus refuses the premise outright: "It was not that this man sinned, or his parents, but that the works of God might be displayed in him." He adds that he and his disciples "must work the works of him who sent me while it is day," because "night is coming, when no one can work," and repeats his claim to be "the light of the world" (9:3-5). Then, without being asked, he spits on the ground, makes mud with the saliva, spreads it on the blind man's eyes, and tells him, "Go, wash in the pool of Siloam" (which means Sent). The man goes, washes, and comes back able to see (9:6-7).

Start with the question itself, because it is not the naive or invented framing a modern reader might assume. Second Temple and early rabbinic Judaism had not settled the theology of inherited guilt into one doctrine: alongside the standard reading that a parent's sin could be "visited... upon the children" (Deuteronomy 5:9), a rival scriptural voice insisted just as forcefully that "the son shall not suffer for the iniquity of the father" (Ezekiel 18:20) [[NOTE:ezekiel-deuteronomic-retribution-tension]]. Layered onto that unresolved tension was a further, more specific speculation, building on texts like Genesis 25:22's account of Jacob and Esau struggling inside Rebekah's womb, that a fetus could act, and even sin, before birth — making "this man himself" a coherent candidate for blame despite being unborn at the time of any wrongdoing [[NOTE:congenital-blindness-sin-question]]. The disciples are not inventing a strange puzzle; they are asking a live either/or that Israel's own scriptures had left genuinely open.

Jesus's answer is worth pausing on for what it declines to do. He does not resolve the disciples' either/or by picking a side — he declines the causal question altogether and substitutes a purpose for a diagnosis [[NOTE:jesus-rejects-retributive-framework]]. That move recurs elsewhere in the Synoptic tradition too, most notably when Jesus refuses to read the deaths of Galileans killed by Pilate, or of eighteen people crushed by a collapsing tower, as targeted divine punishment for greater sin (Luke 13:1-5) — the same refusal to treat catastrophe as a legible verdict shows up on both sides of the Synoptic/Johannine divide.

The healing method itself sits inside a recognizable ancient medical-folk framework rather than reading as an isolated oddity. Pliny the Elder catalogues a wide range of therapeutic uses ancient Mediterranean medicine attributed to human saliva, including direct application to the eyes — spittle was a commonly invoked remedy across the Greco-Roman world, not a strange or arbitrary choice [[NOTE:pliny-saliva-remedy]]. The single most famous parallel, already familiar from elsewhere in this project's treatment of the Synoptic healing tradition, is the emperor Vespasian's own reported spittle-cure of a blind man at Alexandria, recorded independently by both Tacitus and Suetonius; it remains here what it was there — solid evidence that healing-by-spittle was a recognized category of claim in this period, not proof of any particular healing's actual mechanism [[NOTE:tacitus-suetonius-vespasian-saliva]].

The destination Jesus names is not incidental either. John interrupts his own narrative to translate the pool's name for his Greek-speaking audience — "Siloam (which means Sent)" — a gloss mainstream commentary reads as deliberate wordplay rather than a stray etymological footnote, since "sent" is one of this Gospel's own recurring descriptions of Jesus's relationship to the Father who sent him [[NOTE:siloam-sent-etymology]]. And the pool itself, already established elsewhere in this project as a genuine, physically excavated Second Temple-period site, anchors this specific healing story in a real place a first-century Jerusalem beggar could actually have walked to and washed in [[NOTE:siloam-pool-excavation-crossref]].
'@

$beat2 = @'
The neighbors who knew the man as a beggar can't agree whether this is even the same person — "some said, 'It is he'; others said, 'No, but it is someone like him'" — until the man himself settles it: "I am the man" (9:8-9). Asked how his eyes were opened, he gives the same account plainly, and they bring him to the Pharisees, because Jesus had made the mud on a Sabbath (9:13-14). The Pharisees split: "This man is not from God, for he does not keep the Sabbath," say some; others ask, "How can a man who is a sinner do such signs?" Pressed for his own opinion, the man answers, "He is a prophet" (9:15-17). Unconvinced that he had ever really been blind, the authorities summon his parents, who confirm he is their son and was born blind, but go no further — "how he now sees we do not know, nor do we know who opened his eyes... he is of age; ask him" — because, John tells us plainly, "his parents said this because they feared the Jews, for the Jews had already agreed that if anyone should confess Jesus to be the Christ, he was to be put out of the synagogue" (9:18-23).

The Sabbath objection is not petty rule-mongering; it runs on real, recognizable categories of Jewish law. The Mishnah's list of the thirty-nine primary categories of forbidden Sabbath labor includes kneading, and mixing spittle with dust into mud is exactly the kind of act that reading would classify as kneading — making Jesus's healing method itself, independent of anything about the healing's result, a plausible Sabbath violation in the eyes of his strictest critics [[NOTE:mishnah-shabbat-kneading-labor]]. The standard rabbinic override for Sabbath law was danger to life, but a lifelong, non-emergency condition like congenital blindness falls well outside that exception — which is precisely why some observers could regard this specific healing as unnecessary, unforced labor rather than a justified emergency intervention [[NOTE:mishnah-yoma-life-threat-exception]].

The single most historically loaded detail in the whole chapter, though, is the throwaway explanatory clause about the parents' fear. The Greek word behind "put out of the synagogue," aposynagogos, occurs nowhere else in the entire New Testament outside this Gospel — not in the Synoptics, not in Paul, not in Acts — and recurs only twice more, both later in John itself (12:42; 16:2) [[NOTE:aposynagogos-term-occurrences]]. Mainstream Johannine scholarship, following J. Louis Martyn's classic study, reads this as anachronistic on its own narrative terms: there is no independent evidence that a formal, operative synagogue policy specifically expelling confessors of Jesus as Messiah existed during Jesus's own actual ministry in the 20s-30s CE. What the detail much more plausibly reflects is the Johannine community's own later, historically real experience of expulsion from synagogue life, retrojected into the narrative present of a story ostensibly set decades earlier [[NOTE:martyn-two-level-drama]]. On this reading the parents are not merely minor characters covering themselves; they are a window straight through the narrative surface into the Gospel's own actual composition-era conflict.
'@

$beat3 = @'
The authorities call the man back a second time. "Give glory to God," they tell him. "We know that this man is a sinner." His reply has become one of the most quoted lines in the Gospel: "Whether he is a sinner I do not know. One thing I know, that though I was blind, now I see" (9:24-25). Asked yet again for the details, his patience runs out: "I have told you already, and you would not listen. Why do you want to hear it again? Do you also want to become his disciples?" They revile him — "you are his disciple, but we are disciples of Moses... we do not know where this man comes from" — and the man escalates further still, marveling that they can't place the origin of someone who has just done something "never heard of since the world began," opening the eyes of a man born blind, and insisting that God does not listen to sinners, only to those devout and obedient, so that "if this man were not from God, he could do nothing." They answer, "You were born in utter sin, and would you teach us?" and "cast him out" (9:26-34).

Read straight through, the chapter's structure is not incidental to its argument. Raymond Brown's classic reading treats John 9 as a deliberately built drama in seven scenes — Jesus and the disciples, the healing, the neighbors' dispute, the first Pharisaic hearing, the parents' testimony, this second and final hearing, and Jesus's return to the man — with the healed man's own confidence climbing at every turn while his interrogators' position hardens in exactly the opposite direction [[NOTE:brown-seven-scene-structure]]. That escalating shape is itself a piece of literary craft, not merely a report of events in the order they happened.

The expulsion that closes the scene is where the chapter's redaction-critical stakes are highest. Brown's own reconstruction of the Johannine community's history draws directly on this scene, among others, to argue that the Gospel's originating Jewish-Christian community suffered a real, painful separation from the wider synagogue that had been their own religious home [[NOTE:brown-community-beloved-disciple]]. Urban von Wahlde's independent source- and redaction-critical analysis of the Gospel's compositional layers reaches a compatible conclusion by a different route, associating the aposynagogos material with a later editorial stage responding to an intensifying, historically situated conflict between the Johannine community and the synagogue [[NOTE:von-wahlde-second-edition]].

Martyn's original thesis proposed a specific mechanism for that conflict: the Birkat ha-Minim, the Twelfth Benediction of the daily Amidah prayer, which rabbinic tradition credits Samuel the Small with revising at the academy of Yavneh, under the patriarch Gamaliel II, to include a curse against minim — sectarians or heretics — a formula a confessing Jewish Christian could not honestly recite [[NOTE:birkat-haminim-yavneh-tradition]]. More recent scholarship has significantly complicated that specific link. Reuven Kimelman and, separately, Steven Katz have each challenged the benediction's precise date, its original target, and whether any first-century synagogue possessed the kind of centralized authority needed to enforce a uniform exclusion policy against Jewish Christians as a defined group [[NOTE:kimelman-katz-critique]]. Their critique does not undo the broader, still-mainstream reading that this chapter encodes some real later conflict between the Johannine community and synagogue authorities — only Martyn's specific proposed mechanism for it, a genuine scholarly walk-back worth stating plainly rather than passing over.
'@

$beat4 = @'
Jesus, hearing the man has been cast out, finds him and asks, "Do you believe in the Son of Man?" "And who is he, sir, that I may believe in him?" the man asks. "You have seen him, and it is he who is speaking to you." "Lord, I believe," the man says, and worships him. Jesus then states the chapter's thesis outright: "For judgment I came into this world, that those who do not see may see, and those who see may become blind." Some nearby Pharisees ask, "Are we also blind?" and Jesus answers that if they were blind they would have no guilt, "but now that you say, 'We see,' your guilt remains" (9:35-41).

The man's arc across the whole chapter lands here. He moves from a beggar defending his own bare identity ("I am the man," 9:9) to a plain, repeated witness of what happened to him, to a confident theological arguer capable of out-reasoning trained authorities ("if this man were not from God, he could do nothing," 9:33), and finally to worship — the fullest confession the chapter offers, capping the same escalating structure already visible in the interrogation scenes themselves [[NOTE:brown-seven-scene-structure]].

The healing's specific content, restored sight rather than some other affliction, is not a neutral narrative choice either. Isaiah ties the coming messianic age directly to restored vision — "the eyes of the blind shall be opened" (Isaiah 35:5), "to open the eyes that are blind" (Isaiah 42:7) — background that would have given a first-century Jewish audience reason to read this healing as a deliberately loaded sign rather than a bare wonder-story [[NOTE:isaiah-blind-eyes-messianic]]. This account also occupies the sixth position in the traditional count of John's seven numbered signs, and Robert Fortna's source-critical reconstruction of a hypothesized earlier Signs Gospel underlying John's present text includes a version of this same healing among its recoverable episodes — consistent with the broader scholarly view that the bare healing narrative is one of the oldest layers in this chapter, with the lengthy interrogation scenes built onto it later [[NOTE:fortna-signs-source-sixth-sign]].

The chapter's closing exchange states its own argument as plainly as the text ever states anything: physical blindness healed, moral and spiritual blindness exposed in exactly the people most certain they already see clearly. That is the Gospel's own literary and theological payoff, not a claim external evidence could confirm or disconfirm — but everything examined above, from the theology behind the disciples' opening question to the community history behind the parents' fear, sits underneath that closing irony as its real historical scaffolding.
'@

$beats = @($beat1, $beat2, $beat3, $beat4)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'THE MAN BORN BLIND' = "The unnamed central figure of this chapter (9:1-41), blind from birth and healed by Jesus with mud made from spittle and dust, then sent to wash in the Pool of Siloam (9:6-7). His testimony grows steadily bolder across the chapter's escalating interrogation scenes [[NOTE:brown-seven-scene-structure]] — from a beggar merely defending his own identity (`"I am the man,`" 9:9) to a confident theological arguer (`"if this man were not from God, he could do nothing,`" 9:33) to, finally, a worshiper (`"Lord, I believe,`" 9:38). Like the Samaritan woman at the well and the woman caught in adultery elsewhere in John, he is never given a name."
'APOSYNAGOGOS (SYNAGOGUE EXPULSION)' = "The Greek term (literally `"put out of the synagogue`") used at 9:22 for the fate threatening anyone who confesses Jesus as the Christ, and repeated at 12:42 and 16:2 — the word's only three New Testament occurrences, all in John [[NOTE:aposynagogos-term-occurrences]]. Mainstream Johannine scholarship, following J. Louis Martyn, reads the detail as one of the most historically significant in the whole Gospel: not a plausible feature of Jesus's own actual ministry setting, but a retrojection of the Johannine community's own later, painful experience of exclusion from synagogue life [[NOTE:martyn-two-level-drama]]."
'BIRKAT HA-MINIM ("BLESSING" AGAINST HERETICS)' = "The traditional Twelfth Benediction of the Jewish daily prayer (the Amidah), reportedly composed or revised at the rabbinic academy of Yavneh under Samuel the Small in the late first century CE to include a curse against minim (`"heretics`" or sectarians) [[NOTE:birkat-haminim-yavneh-tradition]]. J. Louis Martyn proposed this benediction as the specific historical mechanism behind John's aposynagogos passages; more recent scholarship has significantly complicated that tight link, questioning both the benediction's early date and whether it was ever aimed specifically, or effectively, at excluding Jewish Christians as such [[NOTE:kimelman-katz-critique]]."
'TWO-LEVEL DRAMA (JOHANNINE REDACTION CRITICISM)' = "J. Louis Martyn's influential reading method for the Fourth Gospel, which treats episodes like the healing of the man born blind as operating simultaneously on two temporal levels — the level of Jesus's own historical ministry, and the level of the Johannine community's later experience of conflict with and expulsion from synagogue life, projected back into the narrative's dramatic present [[NOTE:martyn-two-level-drama]]. Raymond E. Brown's related reconstruction of the Johannine community's own history draws heavily on the same passages [[NOTE:brown-community-beloved-disciple]]."
'SEVEN-SCENE STRUCTURE OF JOHN 9' = "Raymond E. Brown's literary observation that the healing of the man born blind is composed as a tightly constructed drama unfolding across seven scenes — Jesus and the disciples, the healing itself, the neighbors' dispute, the first Pharisaic interrogation, the parents' testimony, the second interrogation and expulsion, and Jesus's return to the man — with the man's own testimony escalating in confidence at each turn while the authorities' position hardens in the opposite direction [[NOTE:brown-seven-scene-structure]]."
'J. LOUIS MARTYN' = "Twentieth-century New Testament scholar whose History and Theology in the Fourth Gospel (1968; 3rd ed. 2003) uses John 9 as its central case study for reading Johannine narrative as a `"two-level drama`" — reflecting both Jesus's own ministry and the later, separate historical experience of the Gospel's own community [[NOTE:martyn-two-level-drama]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum — $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch9NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "J. Louis Martyn" "j-louis-martyn" "character" "New Testament scholar whose two-level drama thesis reads John 9's synagogue-expulsion detail as reflecting the Johannine community's own later historical experience."
Seed-Entity "Aposynagogos (Synagogue Expulsion)" "aposynagogos-synagogue-expulsion" "vocabulary" "Greek term for formal expulsion from the synagogue, appearing in the New Testament only in John (9:22; 12:42; 16:2), central to Johannine redaction-critical scholarship."
Seed-Entity "Birkat ha-Minim (Blessing Against Heretics)" "birkat-ha-minim" "vocabulary" "Traditional Twelfth Benediction associated with the Yavneh academy, historically proposed as a mechanism for excluding Jewish Christians from synagogue life in the late first century CE; the link is contested in recent scholarship."
Seed-Entity "Two-Level Drama (Johannine Redaction Criticism)" "two-level-drama-johannine" "vocabulary" "J. Louis Martyn's reading method treating Johannine narratives as operating simultaneously on the level of Jesus's own ministry and the level of the evangelist's later community history."
Seed-Entity "Seven-Scene Structure of John 9" "seven-scene-structure-john-9" "vocabulary" "Raymond E. Brown's literary observation that John 9 is composed as a tightly constructed drama in seven scenes with escalating interrogation."

$conn.Close()
Write-Host "DONE Chapter 9."
