$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"
$Ch21NodeId = [guid]"019FA96D-6C8A-712C-AB07-9F831ADF857D"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
# HARDENED: guard against non-numeric leading tokens (e.g. the stray TEST_PROBE_DELETE_ME row) so a
# single malformed Notes row can't crash the whole insert with a CAST/CHARINDEX exception.
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'john-21-epilogue-status-crossref' = @{ title='An epilogue, building on chapter 20''s own ending'; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), introductory section to chapter 21; D. Moody Smith, John, Abingdon New Testament Commentaries (Nashville: Abingdon Press, 1999), introductory comments on chapter 21. As already flagged where 20:30-31 was examined as the Gospel's own likely original closing statement of purpose, the very widely (though not absolutely universally) held scholarly judgment is that chapter 21 is a later-added epilogue appended to a Gospel that once ended at 20:31. This chapter goes further into why: not one line of argument but several converging ones, examined beat by beat below." }
'stylistic-shift-sons-of-zebedee' = @{ title='A change in hand, and a naming the rest of the Gospel never uses'; body="C.K. Barrett, The Gospel According to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 21:1-14. Barrett catalogs small but real differences in vocabulary and connective style between chapter 21 and chapters 1-20 (including the reintroduction of the disciples by a formal roll call, 21:2, after twenty chapters that assumed the reader already knew who was present). One detail is easy to miss and hard to explain away: 'the sons of Zebedee' (21:2) is the only place in the entire Fourth Gospel that James and John are identified this way at all — unlike the Synoptic Gospels, John's first twenty chapters never name James or John son of Zebedee individually or as a pair, making their sole appearance under this Synoptic-style label a genuine stylistic outlier rather than a minor curiosity." }
'luke-5-catch-doublet' = @{ title='A catch of fish that has already happened once, elsewhere'; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 21:1-14, comparative discussion of Luke 5:1-11. Brown lays out the extensive overlap between this scene and Luke's story of Peter's call to discipleship: a night of fruitless fishing, a word from Jesus that fills the net, Peter's own overwhelmed reaction, and a resulting call to a new vocation. The same kind of doublet/tradition-relocation question already modeled earlier in this campaign for the competing anointing accounts applies here: two Gospel traditions plausibly draw on one remembered core event, relocated by each evangelist to do different narrative work — Luke placing it at the start of Peter's discipleship, John placing a version of it after the resurrection as the occasion for Peter's restoration." }
'net-not-torn-symbolism' = @{ title='A net that holds, where Luke''s nets gave way'; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 21:11. Luke's version of the miraculous catch specifies that the nets were tearing under the weight of the fish (Luke 5:6); John's version specifies the opposite — 'although there were so many, the net was not torn' (21:11). Brown and others read this small, precise contrast as a deliberate compositional choice rather than an incidental detail, with the unbroken net standing as a plausible symbol for a church able to hold every kind of catch, every kind of convert, without splitting — though, as with most Johannine symbolism, the text itself never states the equation outright, and the detail could equally be a vividly remembered fact of an actual catch." }
'ch21-community-concerns' = @{ title='A chapter written to settle two live community questions'; body="Urban C. von Wahlde, The Gospel and Letters of John, Eerdmans Critical Commentary, 3 vols. (Grand Rapids: Eerdmans, 2010), vol. 2, commentary on John 21. Von Wahlde reads chapter 21's two main concerns — establishing Peter's ongoing pastoral authority over the flock (21:15-17) and clarifying what has become of the Beloved Disciple (21:20-23) — as addressing practical, urgent matters of church leadership and community memory at a moment somewhat later than the Gospel's original composition, rather than advancing the climactic theological purpose-statement already delivered in 20:30-31. A Gospel that has just declared its purpose accomplished does not typically need two more chapters of institutional business unless something has changed in the interval." }
'jerome-153-species-oppian' = @{ title='Jerome''s zoological explanation'; body="Jerome, Commentary on Ezekiel, Book 14 (on Ezekiel 47:9-12), citing Oppian, Halieutica (a Greek didactic poem on fishing, 2nd century CE); discussed in Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 21:11. Jerome reports a claim, which he attributes to ancient writers on the nature of fish including Oppian, that there were exactly one hundred fifty-three species of fish in the sea — making the net's catch of exactly that number a symbol of the church's evangelistic net eventually drawing in every kind, every nation, of humanity. Whether Oppian or any ancient source actually asserts a fixed count of 153 fish species is itself disputed by modern commentators working from the surviving text of the Halieutica." }
'augustine-153-triangular-number' = @{ title='Augustine''s arithmetic'; body="Augustine of Hippo, Tractates on the Gospel of John, Tractate 122, section 8, in John W. Rettig, trans., St. Augustine: Tractates on the Gospel of John 112-124, Fathers of the Church vol. 92 (Washington, DC: Catholic University of America Press, 1994). Augustine offers a different, purely numerological solution: 153 is the sum of every whole number from 1 to 17 (a 'triangular number'), and 17 is itself the sum of 10 (the Law, as in the Ten Commandments) and 7 (the Spirit, as in the sevenfold gifts of Isaiah 11:2) — so that 153 encodes the totality of everyone saved by grace fulfilling the Law through the Spirit. The arithmetic is correct; whether John or his epilogist intended anyone to run it is a separate question Augustine's text does not itself address." }
'153-no-scholarly-consensus' = @{ title='A great deal of ingenuity, no agreed answer'; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 21:11. Keener surveys the long history of proposed symbolic readings of 153 — Jerome's fish-species count, Augustine's triangular number, various gematria proposals built on the numerical value of Hebrew or Greek names (including 'Simon,' 'the sons of God,' and other candidates) — and concludes that none of them commands anything close to scholarly consensus even after many centuries of proposals. Keener's own judgment, shared by a good number of other commentators, is that the number may simply be a remembered, vivid, concrete detail of an actual catch of fish — the kind of oddly specific number an eyewitness account naturally accumulates — rather than a code requiring decoding at all." }
'agape-phileo-older-distinction-view' = @{ title='The older popular reading: two different loves'; body="Richard Chenevix Trench, Synonyms of the New Testament, 9th ed. (London: Macmillan and Company, 1880), entry distinguishing agapao and phileo. Trench's influential nineteenth-century study of New Testament Greek synonyms argues for a real, load-bearing distinction between agapao (a supposedly higher, willed, self-giving divine love) and phileo (a lesser, warmer, friendship-level affection), a reading later popularized further in preaching and some twentieth-century devotional and scholarly writing. Applied to John 21:15-17, this older view reads Jesus's first two questions ('do you agapao me') as asking for a love Peter cannot yet honestly claim, so Peter answers each time with the lesser phileo — until Jesus's third question drops to Peter's own level ('do you phileo me'), which is why Peter is grieved: not simply at being asked a third time, but at being met where he actually stands." }
'agape-phileo-stylistic-variation-view' = @{ title='The more widely held view now: stylistic variation, not a doctrine'; body="D.A. Carson, Exegetical Fallacies, 2nd ed. (Grand Rapids: Baker Book House, 1996), chapter 1 ('Word-Study Fallacies'), discussing John 21:15-17 as a case study; compare C.K. Barrett, The Gospel According to St John, 2nd ed. (Philadelphia: Westminster Press, 1978), and Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), both commentary ad loc. John 21:15-17. Carson treats the rigid agapao/lesser-phileo reading as a textbook example of over-reading a claimed semantic distinction onto words a single author elsewhere uses interchangeably — pointing out that John's Gospel freely alternates both verbs for the Father's love of the Son, for Jesus's love of Lazarus, and for the Beloved Disciple's own title, without any evident difference in weight. Barrett and Brown, working independently as commentators, reach compatible conclusions: John's fondness for elegant variation (a recognized feature of his prose style generally) is a simpler, better-attested explanation than a doctrinal ladder Peter climbs mid-conversation. This stylistic-variation reading is presently more widely held among Johannine specialists than the older distinction reading, though the matter has not been settled with anything like unanimity, and capable scholars continue to argue both sides." }
'threefold-restoration-mirrors-denial' = @{ title='Three questions answering three denials'; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 21:15-17, cross-referenced to 18:15-18 and 18:25-27. The threefold structure of Jesus's questioning here is too exact to read as coincidental: Peter denied Jesus three times around a charcoal fire in the high priest's courtyard (18:18 names the coal fire specifically), and he is restored three times here, at another charcoal fire (21:9), with each affirmation of love answered by a specific pastoral commission. The parallel is a clear, intentional piece of literary architecture, whichever hand composed it — a wound counted out and then, one count at a time, undone." }
'peter-death-prediction-vaticinium-ex-eventu' = @{ title='A prophecy that already came true by the time it was written down'; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray, R.W.N. Hoare, and J.K. Riches (Philadelphia: Westminster Press, 1971 [German original 1941]), commentary ad loc. John 21:18-19; Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 21:19. The narrator's own aside — 'this he said to show by what death he was to glorify God' (21:19) — is about as direct a signal as a Gospel writer gives that a prediction is being explained after its fulfillment. By the time John's Gospel reached its present form, decades after the crucifixion, Peter's death was already an established fact known to the Johannine community; Bultmann and Brown both treat this passage as one of the clearer cases in the Gospel of a prophecy composed with hindsight (a vaticinium ex eventu), its vague, gestural language about stretched-out hands and being led where Peter would rather not go read backward from a known outcome rather than forward from an unknown future." }
'tertullian-peter-crucifixion' = @{ title='Tertullian ties the prophecy to a Roman death'; body="Tertullian, Scorpiace ('Antidote for the Scorpion''s Sting'), chapter 15 (early third century CE); see also Bart D. Ehrman, Peter, Paul, and Mary Magdalene: The Followers of Jesus in History and Legend (Oxford: Oxford University Press, 2006), chapters on the traditions of Peter's death. Tertullian, writing more than a century after the events, connects Peter's martyrdom at Rome to a passion 'like his Lord's,' a reading commentators generally take to be drawing on this Gospel's own prediction of a stretching-out of hands. The Gospel text itself, notably, does not specify crucifixion, still less an inverted crucifixion — only Tertullian and later sources supply that detail, extrapolating from language John's text leaves deliberately gestural." }
'eusebius-origen-inverted-crucifixion' = @{ title='The upside-down detail, a further century on'; body="Eusebius of Caesarea, Ecclesiastical History, Book 3, chapter 1, section 2 (early fourth century CE), citing Origen (early third century CE) as his source. Eusebius preserves Origen's report that Peter, arriving at Rome, was crucified head downward at his own request, judging himself unworthy to die in the same posture as his Lord. This detail — now the standard popular image of Peter's death — rests on a chain of attribution running from Origen through Eusebius, more than a century and a half after the event it describes, considerably later than the Gospel text it is often read alongside." }
'acts-of-peter-quo-vadis' = @{ title='The fuller legend: Quo Vadis, Domine?' ; body="Acts of Peter (Martyrdom of Peter), an apocryphal text of the late second century CE, in Wilhelm Schneemelcher, ed., New Testament Apocrypha, vol. 2: Writings Relating to the Apostles; Apocalypses and Related Subjects, rev. ed., trans. R. McL. Wilson (Cambridge: James Clarke & Co. / Louisville: Westminster John Knox Press, 1992), Martyrdom of Peter sections. The apocryphal Acts of Peter supplies the famous 'Quo Vadis, Domine?' ('Where are you going, Lord?') legend: Peter, fleeing Rome to escape execution, meets a vision of Jesus walking toward the city, and turns back to accept his own death, which the text narrates as an inverted crucifixion by Peter's own request. None of this appears in John's Gospel; it belongs to a separate, later, and explicitly non-canonical tradition elaborating on the same terse prediction in 21:18-19." }
'beloved-disciple-death-internal-evidence' = @{ title='The rumor that gives away the epilogue''s real occasion'; body="Urban C. von Wahlde, The Gospel and Letters of John, Eerdmans Critical Commentary, 3 vols. (Grand Rapids: Eerdmans, 2010), vol. 2, commentary on John 21:20-23; R. Alan Culpepper, Anatomy of the Fourth Gospel: A Study in Literary Design (Philadelphia: Fortress Press, 1983), discussion of the Beloved Disciple's narrative function. The narrator goes out of its way to correct a rumor that had spread among 'the brothers' that the Beloved Disciple would not die before Jesus's return — carefully clarifying that Jesus had only said a conditional 'if it is my will that he remain.' A community does not generate and then anxiously correct a rumor about whether a particular person will die unless that person has, in fact, recently died, unsettling an expectation people had actually held. Von Wahlde and Culpepper both treat this as strong internal evidence that the Beloved Disciple — an aged, presumably original eyewitness-generation figure closely tied to this Gospel's origins — had died relatively recently before this chapter was written, a genuinely significant data point for dating the epilogue to that specific moment in the Johannine community's life." }
'colophon-ancient-authenticating-postscript' = @{ title='The colophon as a recognized ancient genre'; body="R. Alan Culpepper, Anatomy of the Fourth Gospel: A Study in Literary Design (Philadelphia: Fortress Press, 1983), discussion of the Gospel's narrative closure and the function of 21:24-25. Ancient books commonly closed with a colophon — a scribal or editorial notice naming (or vouching for) the work's source and authenticity, sometimes added by a hand other than the main author's. John 21:24 ('This is the disciple who is bearing witness about these things, and who has written these things, and we know that his testimony is true') functions exactly this way: a communal 'we' vouching for an individual 'he,' a structure that itself suggests a voice distinct from the eyewitness being vouched for, closing the book much as an ancient editor or amanuensis might certify a completed manuscript." }
'authorship-question-eyewitness-claim' = @{ title='What the claim establishes, and what it does not'; body="Raymond E. Brown, The Community of the Beloved Disciple (New York: Paulist Press, 1979); R. Alan Culpepper, John, the Son of Zebedee: The Life of a Legend (Columbia: University of South Carolina Press, 1994; reprint Eugene, OR: Wipf and Stock, 2000). The colophon's claim — that an eyewitness disciple stands behind this Gospel's testimony — is a claim about the tradition's origin, not a modern authorial byline, and the Gospel itself never names this disciple outright; the traditional identification with John the son of Zebedee is a second-century inference (associated with figures like Irenaeus), not a claim John 21:24 makes explicitly. Brown's and Culpepper's separate studies both conclude that a real eyewitness figure plausibly stands somewhere behind the Johannine tradition's origin and distinctive first-person texture, while the precise chain connecting that figure to the finished text in front of a reader — who wrote which words, when, and how many hands intervened — remains a genuinely open historical question the text's own claim cannot, by itself, settle." }
'ehrman-authorship-skepticism' = @{ title='A more skeptical assessment of the traditional attribution'; body="Bart D. Ehrman, Jesus, Interrupted: Revealing the Hidden Contradictions in the Bible (And Why We Don't Know About Them) (New York: HarperOne, 2009), chapter on the authorship of the Gospels. Ehrman represents a more skeptical strand of mainstream scholarship, arguing that none of the four canonical Gospels names its own author within its main narrative (the titles were added later), that the Greek-literate, theologically sophisticated composition of John's Gospel sits uneasily with what is independently known about a Galilean fisherman's likely education and language, and that a communal editorial process — of the kind chapter 21 itself half-reveals with its 'we know' — fits the evidence at least as well as a single eyewitness author writing in his own hand. This view is a genuine minority-to-contested position within the wider field rather than a fringe one, and it sits alongside, rather than simply overturning, the more moderate view represented by Brown and Culpepper above." }
'no-manuscript-omits-chapter-21' = @{ title='A literary judgment, not a text-critical one'; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), introductory section to chapter 21; textual apparatus of the Nestle-Aland Novum Testamentum Graece for John 21. It is worth being precise about the kind of evidence the 'added epilogue' judgment actually rests on. No surviving Greek manuscript of John's Gospel lacks chapter 21, and none preserves any trace of a version ending at 20:31; the epilogue theory is a literary-critical and compositional judgment about seams, style, and theme, not a text-critical one resting on manuscript variants. Whatever process produced chapter 21, it had already happened by the time of our earliest surviving copies of the finished Gospel." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
Some of the disciples are back in Galilee. Simon Peter, Thomas, Nathanael, the two sons of Zebedee, and two other unnamed disciples are together at the Sea of Tiberias when Peter announces he is going fishing; the rest go with him, and they catch nothing all night. At daybreak a figure stands on the shore, unrecognized, and tells them to cast the net on the boat's right side — they do, and the catch is too large to haul back in. The Beloved Disciple is the one who says it first: "It is the Lord." Peter puts on his outer garment and throws himself into the water to reach him; the others bring the boat in, dragging the net, one hundred fifty-three large fish inside it, the net itself not torn despite the weight. On shore they find a charcoal fire already laid, with fish and bread on it, and Jesus tells them to bring some of what they've just caught. They eat breakfast together. None of them dares ask him who he is; they know it is the Lord (21:1-14).

Whether chapter 21 was part of the Gospel's original design or a later addition has already come up in these notes, where 20:30-31 was flagged as reading like the book's own intended closing statement of purpose. This chapter is the place to go further into why that judgment is so widely shared. Part of the case is stylistic: commentators catalog small shifts in vocabulary and connective habit between this chapter and what precedes it, including a formal reintroduction of the cast — "Simon Peter, Thomas called the Twin, Nathanael... the sons of Zebedee" — as though the reader needs reminding who these people are, twenty chapters in [[NOTE:stylistic-shift-sons-of-zebedee]]. That naming turns up a genuine oddity on its own terms: nowhere else in this Gospel are James and John identified as "the sons of Zebedee." The Fourth Gospel, unlike the Synoptics, otherwise never uses that label at all.

Part of the case is a familiar shape: a night of empty nets, a stranger's instruction, a catch too large to manage, and an overwhelmed response from Peter — all of which has already happened once before, in Luke's account of Peter's original call to discipleship (Luke 5:1-11) [[NOTE:luke-5-catch-doublet]]. The same kind of question already modeled earlier in this campaign for the competing anointing traditions applies here just as directly: two Gospels plausibly preserve one remembered core event, relocated to do different work in each writer's design — an origin story in Luke, a restoration story in John. One precise difference between the two versions is worth sitting with rather than explaining away: Luke's nets tear under the weight of the catch; John's, pointedly, do not [[NOTE:net-not-torn-symbolism]].

And then there is the number itself. One hundred fifty-three is an oddly, memorably specific figure for a Gospel to report, and it has drawn some of the most inventive exegesis in the whole New Testament without ever landing on an agreed answer. Jerome, citing the Greek fishing poem Halieutica by the naturalist-poet Oppian, reports a claim that ancient writers on marine life counted exactly one hundred fifty-three species of fish in the sea — making the catch a symbol of an evangelistic net eventually gathering in every kind of person, everywhere [[NOTE:jerome-153-species-oppian]]. Augustine takes a different, purely mathematical route: 153 is the sum of every whole number from 1 to 17, and 17 is 10 (the Law) plus 7 (the Spirit) — the totality of everyone saved by grace fulfilling the Law through the Spirit [[NOTE:augustine-153-triangular-number]]. Centuries of further proposals, including various gematria readings built on the numerical value of names, have added still more candidate solutions. What they have not done, as modern commentary surveys of the whole history candidly report, is produce anything like a scholarly consensus — and it remains entirely possible that 153 is simply a vivid, concrete, remembered number from an actual catch of fish, the kind of oddly specific detail that eyewitness memory naturally keeps, without needing to be decoded as a symbol at all [[NOTE:153-no-scholarly-consensus]].
'@

$beat2 = @'
Jesus asks Simon Peter, three times, some version of "Simon, son of John, do you love me more than these?" Each time Peter answers that Jesus knows he loves him, and each time Jesus responds with a pastoral charge — "feed my lambs," "tend my sheep," "feed my sheep." Peter is grieved that Jesus asks a third time (21:15-17).

The exchange is famous for its Greek, and famously argued over. Across the three questions, Jesus's verb shifts from agapao to phileo, and Peter answers with phileo each time. An older, once-popular reading — associated with nineteenth-century philology and carried into a good deal of twentieth-century preaching — treats this as theologically load-bearing: agapao names a higher, willed, self-giving divine love that Peter, still raw from his denial, cannot yet honestly claim, so he answers instead with the lesser, warmer phileo, until Jesus's own third question drops to meet him at phileo — which is why, on this reading, Peter is hurt not simply by repetition but by being met exactly where he stands [[NOTE:agape-phileo-older-distinction-view]]. The view now more widely held among Johannine specialists runs the other way: this Gospel elsewhere uses agapao and phileo interchangeably — for the Father's love of the Son, for Jesus's love of Lazarus, even for the title of the Beloved Disciple himself — with no discernible difference in weight, and treating the two verbs here as a doctrinal ladder Peter climbs mid-conversation reads far more theology into ordinary Greek stylistic variation than the language will bear. This second view is presently the more widely held position among specialists in Johannine Greek, though it has not achieved anything close to unanimous agreement, and capable scholars continue to defend the older distinction as well [[NOTE:agape-phileo-stylistic-variation-view]].

Whichever reading of the verbs one takes, the scene's larger architecture is unmistakable and, on this point, not seriously contested: three questions answering three denials, the second charcoal fire of this Gospel (21:9) recalling the first one Peter warmed himself at in the high priest's courtyard (18:18), each affirmation of love met with a specific charge to shepherd. It reads as a wound counted out exactly, then undone one count at a time [[NOTE:threefold-restoration-mirrors-denial]].
'@

$beat3 = @'
Jesus tells Peter that when he was young he dressed himself and went where he wished, but that when he is old, another will dress him and carry him where he does not wish to go — language the narrator explains was said "to show by what death he was to glorify God" — and then says simply, "Follow me." Peter turns, sees the Beloved Disciple following, and asks, "Lord, what about this man?" Jesus answers, "If it is my will that he remain until I come, what is that to you? You follow me." The narrator adds that this saying spread among the brothers as a claim that this disciple would not die — but corrects the record: Jesus did not say he would not die, only "if it is my will that he remain until I come, what is that to you?" (21:18-23).

The narrator's own aside about "by what death" is about as plainly as a Gospel writer signals that a prediction is being explained after the fact rather than made in advance of it. By the time this chapter reached its present form, decades after the crucifixion, Peter's death was already a known fact within the Johannine community, and the language here — vague on method, specific on the loss of control — reads as a prophecy composed with the benefit of hindsight [[NOTE:peter-death-prediction-vaticinium-ex-eventu]]. The Gospel text itself, notably, never says how Peter died. That detail comes later: Tertullian, writing at the start of the third century, ties Peter's death at Rome to a passion "like his Lord's" [[NOTE:tertullian-peter-crucifixion]]; a century after that, Eusebius preserves a report from Origen that Peter was crucified head downward, at his own request, judging himself unworthy of his Lord's own posture [[NOTE:eusebius-origen-inverted-crucifixion]]; and the apocryphal Acts of Peter supplies the fuller, non-canonical legend of Peter fleeing Rome, meeting a vision of Jesus on the road, and turning back to face his death — the famous "Quo Vadis, Domine?" scene [[NOTE:acts-of-peter-quo-vadis]]. None of that later elaboration is in John's own text; the Gospel itself stops at gesture, not method.

The correction about the Beloved Disciple is, if anything, the more historically telling detail in this whole chapter. A community does not need to generate, and then anxiously walk back, a rumor about whether a specific person will die before some larger event — unless that person has, in fact, just died, unsettling something people had genuinely believed. Read this way, the care the narrator takes to correct the record is strong internal evidence that the Beloved Disciple, an aged member of the eyewitness generation closely tied to this Gospel's own origin, had died not long before this chapter was written, addressing a real and current anxiety in the community rather than a hypothetical one [[NOTE:beloved-disciple-death-internal-evidence]]. Together with the stylistic seams and the pastoral concerns already noted, this is a second, independent line of evidence for locating chapter 21's composition at a somewhat later moment in the Johannine community's life than the Gospel's original climax at 20:30-31.
'@

$beat4 = @'
The book closes: "This is the disciple who is bearing witness about these things, and who has written these things, and we know that his testimony is true. Now there are also many other things that Jesus did. Were every one of them to be written, I suppose that the world itself could not contain the books that would be written" (21:24-25).

These closing lines are a colophon — a recognized genre in ancient book production, a scribal or editorial notice vouching for a completed work's source and reliability, sometimes written by a hand distinct from the main text's own author [[NOTE:colophon-ancient-authenticating-postscript]]. The structure itself is a clue: a communal "we" stands behind an individual "he," vouching for a testimony rather than simply presenting it, in a way most ancient readers would have recognized as an editorial certification closing out a finished manuscript. The claim being certified is a real and significant one — that an eyewitness disciple stands behind this Gospel's testimony — but it is a claim about a tradition's origin, not a modern signature; the text itself never names this disciple, and the familiar identification with John the son of Zebedee is a later, second-century inference layered onto a text that does not make it explicitly. Careful studies of the question conclude that a real eyewitness figure plausibly does stand behind the Johannine tradition's distinctive voice and detail, while the precise chain from that figure to the finished book in front of any reader — who actually set down which words, across how much time, through how many hands — remains genuinely open [[NOTE:authorship-question-eyewitness-claim]]. A more skeptical strand of current scholarship goes further, questioning whether the traditional attribution to a Galilean fisherman sits comfortably at all with this Gospel's fluent, theologically sophisticated Greek, and proposing that a communal editorial process — of exactly the kind this very colophon half-admits with its own "we know" — may fit the evidence at least as well [[NOTE:ehrman-authorship-skepticism]]. It is worth being exact about what kind of judgment underlies all of this: no surviving manuscript of John lacks this ending, and none preserves any trace of a version stopping at chapter 20; whatever process produced these final verses, it had already happened by the time of our earliest surviving copies [[NOTE:no-manuscript-omits-chapter-21]].

That is close to as far as the evidence goes, and it seems right to let it stand there rather than push it further in either direction. The Fourth Gospel's own closing claim is neither a blank check for uncritical confidence nor a claim the evidence dismantles outright: an actual eyewitness tradition, an actual community that shaped and preserved and eventually closed the book around that tradition, and a real, unresolved gap between the two that honest reading has to leave open. Across four Gospels now examined this way, that gap — between what a text claims for itself and what independent evidence can confirm — has turned out to be the single most durable, recurring feature of the whole set of documents, and the most honest place for a history of them to end.
'@

$beats = @($beat1, $beat2, $beat3, $beat4)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'153 FISH (SYMBOLIC INTERPRETATIONS)' = "The exact catch reported at John 21:11, the subject of a long and genuinely inconclusive history of proposed symbolic decodings: Jerome's claim (citing Oppian's Halieutica) that ancient writers counted 153 fish species, making the catch a figure for universal evangelism [[NOTE:jerome-153-species-oppian]]; Augustine's numerological reading via the triangular sum of 1 through 17 [[NOTE:augustine-153-triangular-number]]; and assorted gematria proposals built on the numeric value of names. No reading commands scholarly consensus, and the number may simply be a concrete, remembered detail of a real catch [[NOTE:153-no-scholarly-consensus]]."
'AGAPAO AND PHILEO (LOVE VERBS IN JOHN 21)' = "The two Greek verbs for love that alternate across Jesus's three questions to Peter and Peter's three answers (21:15-17). An older, once-popular reading treats the alternation as marking a real distinction between a higher divine love (agapao) and a lesser friendship-love (phileo) that Peter cannot yet claim [[NOTE:agape-phileo-older-distinction-view]]; the view now more widely held among Johannine specialists treats the alternation as stylistic variation, since this Gospel uses both verbs interchangeably elsewhere without a clear difference in weight — though the matter is not settled with unanimity on either side [[NOTE:agape-phileo-stylistic-variation-view]]."
'CHARCOAL FIRE (JOHN 21:9)' = "The fire on the shore where the risen Jesus has already prepared breakfast (21:9), the second of exactly two charcoal fires named in this Gospel — the first being the fire in the high priest's courtyard where Peter warmed himself while denying Jesus three times (18:18). Commentators read the recurrence of this specific, unusual detail (charcoal fires are named nowhere else in the New Testament) as a deliberate literary signal tying Peter's threefold restoration here to his threefold denial there [[NOTE:threefold-restoration-mirrors-denial]]."
'JOHANNINE EPILOGUE (JOHN 21)' = "The scholarly term for this chapter's widely held status as a later addition appended after the Gospel's original closing statement of purpose at 20:30-31, argued from a convergence of stylistic shifts, a reintroduced doublet tradition, and a chapter-long concern with church-community matters (Peter's authority, the Beloved Disciple's fate) that read as addressing a somewhat later moment in the Johannine community's life [[NOTE:john-21-epilogue-status-crossref]] [[NOTE:ch21-community-concerns]]. The judgment rests entirely on literary and compositional grounds; no surviving manuscript of John omits the chapter [[NOTE:no-manuscript-omits-chapter-21]]."
'PETER''S DEATH PREDICTION (JOHN 21:18-19)' = "Jesus's cryptic words to Peter about being dressed and carried where he does not wish to go in his old age, explained by the narrator as indicating 'by what death he was to glorify God' (21:19). Read by close to the full range of scholarship as a prediction composed after its own fulfillment, since Peter's actual death was already known to the Johannine community by the time this chapter was written [[NOTE:peter-death-prediction-vaticinium-ex-eventu]]. Later tradition — Tertullian, then Origen via Eusebius, then the apocryphal Acts of Peter — supplies the specific detail of an inverted crucifixion at Rome that the Gospel text itself never states [[NOTE:tertullian-peter-crucifixion]] [[NOTE:eusebius-origen-inverted-crucifixion]] [[NOTE:acts-of-peter-quo-vadis]]."
'TERTULLIAN' = "North African Christian writer (c. 155-220 CE), among the earliest sources to connect Peter's martyrdom at Rome to a passion resembling his Lord's, a reading commentators take as drawing on John 21:18's prediction, though writing more than a century after the events he describes [[NOTE:tertullian-peter-crucifixion]]."
'ACTS OF PETER (MARTYRDOM OF PETER)' = "A late second-century CE apocryphal text, not part of the New Testament canon, that supplies the fuller legendary account of Peter's death at Rome, including the famous 'Quo Vadis, Domine?' ('Where are you going, Lord?') scene and Peter's request to be crucified head downward. None of this narrative detail appears in John's Gospel itself, which stops at a gestural prediction [[NOTE:acts-of-peter-quo-vadis]]."
'COLOPHON (JOHN 21:24-25)' = "The Gospel's closing two verses, identifying the Beloved Disciple as the witness and writer behind this Gospel's testimony ('we know that his testimony is true') and closing with the hyperbolic claim that the world itself could not contain a full record of Jesus's deeds. A recognized genre of ancient book-closing, in which an editorial 'we' certifies a completed manuscript's source — raising, without settling, the real question of exactly how this Gospel's eyewitness-testimony claim relates to the finished text a reader holds [[NOTE:colophon-ancient-authenticating-postscript]] [[NOTE:authorship-question-eyewitness-claim]] [[NOTE:ehrman-authorship-skepticism]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum - $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch21NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "153 Fish (Symbolic Interpretations)" "153-fish-symbolic-interpretations" "vocabulary" "The exact catch of John 21:11; a long, inconclusive history of proposed symbolic decodings (Jerome, Augustine, gematria) with no scholarly consensus."
Seed-Entity "Tertullian" "tertullian" "character" "North African Christian writer (c. 155-220 CE); earliest source connecting Peter's martyrdom at Rome to John 21:18's prediction (Scorpiace 15)."
Seed-Entity "Acts of Peter (Martyrdom of Peter)" "acts-of-peter-martyrdom-of-peter" "vocabulary" "Late second-century CE apocryphal text supplying the 'Quo Vadis, Domine?' legend and Peter's inverted crucifixion; not part of the New Testament canon."
Seed-Entity "C.K. Barrett" "c-k-barrett" "character" "Twentieth-century British New Testament scholar; author of the standard critical commentary The Gospel According to St John (2nd ed. 1978)."
Seed-Entity "D.A. Carson" "d-a-carson" "character" "New Testament scholar; author of the Pillar commentary on John (1991) and Exegetical Fallacies (1996), the latter a standard critique of over-reading Greek synonym distinctions."
Seed-Entity "Urban C. von Wahlde" "urban-c-von-wahlde" "character" "New Testament scholar; author of the three-volume Eerdmans Critical Commentary The Gospel and Letters of John (2010), noted for detailed compositional-layer analysis."
Seed-Entity "R. Alan Culpepper" "r-alan-culpepper" "character" "New Testament scholar; author of Anatomy of the Fourth Gospel (1983), a foundational narrative-critical study of John, and John, the Son of Zebedee (1994)."
Seed-Entity "D. Moody Smith" "d-moody-smith" "character" "New Testament scholar; author of The Theology of the Gospel of John (1995) and the Abingdon New Testament Commentary on John (1999)."
Seed-Entity "Richard Chenevix Trench" "richard-chenevix-trench" "character" "Nineteenth-century Anglican scholar; author of Synonyms of the New Testament (1880), source of the influential older agapao/phileo distinction reading."

$conn.Close()
Write-Host "DONE Chapter 21 (John)."
