$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=Prose;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"
$Ch12NodeId = [guid]"019FA96C-D64E-70A6-BCC4-7027871C0FB3"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
# Hardened max-note-number derivation (the template's own query crashes on any Notes-node row whose
# text contains no space character at all before the first space; this version guards both the
# "no space found" case and the "leading token isn't purely numeric" case).
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'anointing-mark-matthew-parallel' = @{ title='The anointing at Simon the leper''s house'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary ad loc. John 12:1-8. Brown lays the Johannine anointing directly alongside Mark 14:3-9 and its close parallel Matthew 26:6-13, where an unnamed woman anoints Jesus's head (not his feet) with costly ointment in the house of Simon the leper at Bethany, and unnamed disciples (Matthew) or those present (Mark) object to the waste; John's version keeps the place-name Bethany and the price estimate but relocates the anointing to the feet, names the woman as Mary, and narrows the objection to a single named disciple, Judas." }
'anointing-luke-parallel' = @{ title='A third anointing, earlier and elsewhere'; body="Joseph A. Fitzmyer, The Gospel According to Luke I-IX, Anchor Bible vol. 28 (Garden City, NY: Doubleday & Company, 1981), commentary ad loc. Luke 7:36-50. Luke places a woman's anointing of Jesus's feet at a different point in the ministry entirely, during the Galilean period rather than the run-up to the final Passover, in the house of a Pharisee named Simon rather than Bethany, and makes the woman's tears and her unnamed sinfulness, not burial preparation, the point of the story, which ends in a pronouncement about forgiveness rather than a comment on Jesus's coming death." }
'anointing-tradition-count-debate' = @{ title='One tradition, two, or three?'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), excursus on the anointing accounts, commentary ad loc. John 12:1-8. Brown lays out, without forcing a verdict, the genuine range of scholarly positions: that all three (or four, counting Mark and Matthew separately) accounts stem from a single underlying incident retold with diverging details; that two originally distinct traditions, a Bethany burial-anointing and a Galilean sinful-woman story, have been partly conflated in transmission; or that the evangelists preserve three genuinely separate incidents in Jesus's ministry. The name (Mary), the place (Bethany), and the theme (burial) that John shares with Mark and Matthew but not Luke are the strongest arguments for treating John and the Synoptic Bethany story as variants of one tradition, while Luke's version is the hardest of the three to reconcile with the others." }
'john-12-7-burial-tense-textual-variant' = @{ title='What exactly did Jesus tell her to do?'; body="Bruce M. Metzger, A Textual Commentary on the Greek New Testament, 2nd ed. (Stuttgart: Deutsche Bibelgesellschaft / United Bible Societies, 1994), ad loc. John 12:7; see also the Nestle-Aland Novum Testamentum Graece textual apparatus at the same verse. The Greek of Jesus's reply to Judas is genuinely awkward, a construction that can be rendered either as a command to let Mary keep the remaining perfume for a future burial, or as a statement that she has, in effect, already kept and used it for that purpose; translations split accordingly, comparing the King James Version's ``against the day of my burying hath she kept this'' with the New Revised Standard Version's ``she bought it so that she might keep it for the day of my burial.'' Both the grammar and the manuscript tradition leave room for more than one defensible English rendering." }
'judas-aside-johannine-only' = @{ title='A thief, by the narrator''s own account'; body="Bart D. Ehrman, The New Testament: A Historical Introduction to the Early Christian Writings, 7th ed. (New York: Oxford University Press, 2019), chapter on the Gospel of John. Ehrman notes that John's Gospel consistently sharpens Judas's characterization well beyond anything in the Synoptics: Mark and Matthew's parallel scene has unnamed disciples object to the waste with no suggestion of dishonesty, while John alone names Judas as the objector and alone supplies the narrator's aside that he raised the objection ``not because he cared about the poor, but because he was a thief, and having charge of the moneybag he used to help himself to what was put into it'' (12:6). No Synoptic source shares this detail, which reads as a distinctively Johannine narrative and theological choice, deepening Judas's villainy well before the betrayal itself, rather than an independently attested strand of shared early tradition." }
'judas-glossokomon-money-box' = @{ title='The word for the box itself'; body="C.K. Barrett, The Gospel According to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 12:6 and 13:29. The Greek term John uses, glossokomon, originally denoted a small case for the reed mouthpieces of wind instruments before broadening to mean any small box or chest; John uses it twice for the group's common purse, once here and again at 13:29, the only two occurrences of the word anywhere in the New Testament, both tied to Judas's custodianship of it." }
'zechariah-9-9-fulfillment-citation' = @{ title='A citation, not a straight quotation'; body="Carol L. Meyers and Eric M. Meyers, Haggai, Zechariah 9-14: A New Translation with Introduction and Commentary, Anchor Bible vol. 25C (New York: Doubleday, 1993), commentary ad loc. Zechariah 9:9. John's citation (``Fear not, daughter of Zion; behold, your king is coming, sitting on a donkey's colt,'' 12:15) is not a verbatim reproduction of Zechariah 9:9 in either the Hebrew or the Greek Septuagint text: the opening ``fear not'' is not in Zechariah 9:9 at all (it echoes Zephaniah 3:16 and Isaiah 40:9 instead), while Zechariah's own fuller line describing the king as righteous, victorious, and humble is dropped. The Meyerses' commentary situates Zechariah 9:9 within a Persian-period vision of a peaceable, non-military royal entry, a king riding a donkey rather than a war-horse, which is precisely the contrast John's citation is built to draw out." }
'donkey-colt-synoptic-mount-detail' = @{ title='One animal or two?'; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans / Leicester: Inter-Varsity Press, 1991), commentary ad loc. John 12:14-15. Mark, Luke, and John all describe Jesus mounting a single animal, a young donkey or colt. Matthew's version (21:2-7), read very literally, has Jesus riding two animals at once, a donkey and a colt together, which mainstream commentary widely explains as Matthew woodenly literalizing the synonymous Hebrew poetic parallelism of Zechariah 9:9 (``on a donkey, on a colt, the foal of a donkey''), a single animal described twice in two parallel phrases, into two separate animals. John's version, like Mark's and Luke's, keeps to one." }
'sanders-entry-historical-plausibility' = @{ title='Why historians take some version of this seriously'; body="E.P. Sanders, Jesus and Judaism (Philadelphia: Fortress Press, 1985), chapter on the Temple action and its aftermath. Sanders, whose own primary argument concerns Jesus's action in the Temple rather than the entry itself, treats some kind of deliberate, symbolically loaded arrival in Jerusalem shortly before Passover as historically plausible, precisely because it helps explain, in ordinary cause-and-effect terms, why the authorities moved against Jesus at that specific festival rather than at any other point in his ministry: a public gesture readable as a messianic claim, arriving in a city swollen with Passover pilgrims under close Roman and priestly watch, supplies exactly the kind of provocation historians look for to make the arrest and execution intelligible as a real sequence of events rather than a purely theological construction." }
'josephus-passover-pilgrim-numbers' = @{ title='How big were Passover crowds, really?'; body="Flavius Josephus, The Jewish War, Book 6, section 9.3 (paragraphs 420-425) (Loeb Classical Library, trans. H. St. J. Thackeray, Cambridge, MA: Harvard University Press). Josephus reports a census taken under the procurator Cestius by counting paschal lambs sacrificed at a single Passover and multiplying by the minimum party size required to eat one, arriving at a figure historians overwhelmingly regard as rhetorical exaggeration rather than a literal headcount; even discounted heavily, the account confirms that Jerusalem's Passover pilgrim crowds were, by any standard, enormous, which is the relevant backdrop for weighing how large and how visible a public entry into the city plausibly could have been." }
'crowd-size-caution' = @{ title='Amplification is also a real possibility'; body="John P. Meier, A Marginal Jew: Rethinking the Historical Jesus, Volume Two: Mentor, Message, and Miracles (New York: Doubleday, 1994), discussion of criteria for assessing crowd reactions in the Gospel tradition. Meier cautions that while some public entry into Jerusalem before Passover is plausible, the specific scale and unanimity of crowd acclaim described in all four Gospels, palm branches, a whole city's welcome, explicit royal and messianic titles shouted aloud, may reflect the Evangelists' retrospective theological amplification of a smaller, more ambiguous event, since a demonstration of the scale described would itself have been a natural trigger for immediate Roman intervention, which none of the Gospels reports happening on the spot." }
'pharisees-world-gone-after-him-irony' = @{ title='A complaint that turns out to be true'; body="Urban C. von Wahlde, The Gospel and Letters of John, Volume 2: Commentary on the Gospel of John, Eerdmans Critical Commentary (Grand Rapids: Eerdmans, 2010), commentary ad loc. John 12:19. Von Wahlde reads the Pharisees' exasperated ``the world has gone after him'' as a characteristic piece of Johannine irony: characters within the story speak truer than they know, since the scene that follows immediately, Greeks from beyond Israel asking to see Jesus, begins to make good, quite literally, on the complaint the Pharisees intend only as hyperbole." }
'greeks-hellenes-godfearers-not-mission' = @{ title='Who were the Greeks at the feast?'; body="Craig S. Keener, The Gospel of John: A Commentary, vol. 2 (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 12:20-22. Keener identifies the Greeks (Hellenes, not Hellenists, i.e. not Greek-speaking Jews) most plausibly as Gentile God-fearers or proselytes attending the Jerusalem festival, sympathizers with Judaism drawn to its monotheism and ethics who worshiped at the Temple's outer precincts without full conversion, comparable to figures like the centurion Cornelius in Acts 10. Their appearance is not best read as an anachronistic first-century missionary scene planted into Jesus's own lifetime, but as a narrative signal, timed deliberately by the Evangelist, that the hour about to be announced concerns a mission reaching beyond Israel." }
'hour-has-come-johannine-motif' = @{ title='The hour, finally arrived'; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray et al. (Philadelphia: Westminster Press, 1971; German original 1941), commentary ad loc. John 12:23. Bultmann traces the hour as one of John's principal structural motifs, repeatedly deferred earlier in the Gospel (``his hour had not yet come,'' 2:4, 7:30, 8:20) and here, for the first time, declared to have arrived; Bultmann and much subsequent commentary treat this declaration as the hinge on which the Gospel's whole architecture turns, from a Book of Signs addressed to the world into the Passion material addressed to the disciples." }
'grain-of-wheat-synoptic-saying-parallel' = @{ title='A saying with Synoptic cousins'; body="John P. Meier, A Marginal Jew: Rethinking the Historical Jesus, Volume Two: Mentor, Message, and Miracles (New York: Doubleday, 1994), discussion of the paradoxical life-and-death sayings; compare D. Moody Smith, John, Abingdon New Testament Commentaries (Nashville: Abingdon Press, 1999), commentary ad loc. John 12:24-25. The saying ``whoever loves his life loses it, and whoever hates his life in this world will keep it for eternal life'' (12:25) has clear, independently worded counterparts in the Synoptic tradition: ``whoever would save his life will lose it, and whoever loses his life for my sake... will save it'' (Mark 8:35; similarly Matthew 16:25, Luke 9:24) and ``whoever finds his life will lose it, and whoever loses his life for my sake will find it'' (Matthew 10:39; Luke 17:33). Smith treats a saying attested across John and multiple Synoptic settings with different wording as a meaningful mark of an early, durable tradition, even though John alone attaches it to the image of a grain of wheat falling into the earth." }
'voice-from-heaven-parallel-scenes' = @{ title='A heavenly voice, out of season'; body="C.K. Barrett, The Gospel According to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 12:28-30; compare Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray et al. (Philadelphia: Westminster Press, 1971), ad loc. the same verses. John's Gospel narrates neither a heavenly voice at Jesus's baptism (contrast Mark 1:11 and parallels) nor a Transfiguration scene at all (contrast Mark 9:2-8 and parallels), the two moments where the Synoptics do record a voice from heaven; this is the only place in John where one occurs. Barrett and Bultmann both note the scene's structural resemblance to the Synoptic voice-from-heaven episodes and have suggested John may preserve a compressed or relocated echo of that same broader tradition rather than an unrelated, freestanding Johannine invention, though the comparison remains a resemblance, not a proven literary dependence." }
'isaiah-53-1-suffering-servant-citation' = @{ title='Who has believed our report'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary ad loc. John 12:37-38. The narrator's first proof-text for persistent unbelief despite the signs is Isaiah 53:1 (``Lord, who has believed what he heard from us, and to whom has the arm of the Lord been revealed?''), drawn from the same Suffering Servant poem (Isaiah 52:13-53:12) that early Christian writers elsewhere read as predicting a suffering messiah; Paul quotes the identical verse for a comparable purpose at Romans 10:16, evidence that this specific Isaian text had an established use in early Christian argument about Israel's unbelief well before or alongside John's own use of it." }
'isaiah-6-10-hardening-citation' = @{ title='Blinded eyes, hardened hearts'; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans / Leicester: Inter-Varsity Press, 1991), commentary ad loc. John 12:39-41. The second citation, Isaiah 6:10 (``He has blinded their eyes and hardened their heart... lest they see with their eyes and understand with their heart, and turn, and I would heal them''), is among the most frequently reused Old Testament texts anywhere in the New Testament for explaining unbelief; it also appears at Mark 4:12 and parallels, and again at Acts 28:26-27 and Romans 11:8, making it one of the clearest examples in the New Testament of a single prophetic text put to sustained theological work across independent authors and settings, each reading Israel's own scripture as having anticipated its own resistance to the gospel." }
'martyn-two-level-synagogue-expulsion' = @{ title='Whose fear of expulsion, Jesus''s contemporaries or John''s?'; body="J. Louis Martyn, History and Theology in the Fourth Gospel, 3rd ed. (Louisville, KY: Westminster John Knox Press, 2003; originally published 1968), foundational study of the Gospel's two-level drama. Martyn's influential and widely debated thesis reads the note that ``many even of the authorities believed in him, but... did not confess it... for fear that they would be put out of the synagogue'' (12:42) as reflecting not only, or even primarily, the situation of Jesus's own lifetime, but the later, harder conflict between John's own late-first-century Christian community and the local synagogue from which it had been or was being expelled, a conflict John is thought to project back onto the narrated events of Jesus's ministry. Subsequent scholarship has nuanced and in places challenged the specifics of Martyn's reconstruction, but the basic observation that this verse speaks to a real, painful separation between synagogue and church remains widely shared." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
Six days before Passover, John says, Jesus comes to Bethany, to the house where Lazarus — the man he raised from the dead — lives with his sisters. Martha serves the meal; Mary takes a pound of expensive perfume, pure nard, anoints Jesus's feet with it, and wipes them with her hair, filling the house with its fragrance. Judas Iscariot — identified again by the narrator as the one about to betray Jesus — objects that the perfume could have been sold for three hundred denarii and given to the poor; the narrator adds, in his own voice, that Judas said this not because he cared about the poor but because he was a thief who used to help himself to what was put in the money bag he carried. Jesus tells him to leave her alone, that she has kept it for the day of his burial, and adds that the poor will always be with them but he himself will not always be there. Meanwhile a large crowd, learning Jesus is at Bethany, comes out not only to see him but to see Lazarus, whom he raised from the dead; the chief priests, for their part, resolve to kill Lazarus too, since his very existence as a living, walking sign is drawing people to believe in Jesus (12:1-11).

The anointing itself is one of the more genuinely contested pieces of Synoptic comparison in the Gospels, because it is not John's alone. Mark and Matthew both place a strikingly similar scene at Bethany shortly before Passover — an unnamed woman anointing Jesus, at the house of a man named Simon, with onlookers objecting to the cost — but their version anoints his head, not his feet, and their objectors are unnamed disciples in general, not Judas by name [[NOTE:anointing-mark-matthew-parallel]]. Luke, meanwhile, tells a story that shares the feet-anointing and the name Simon but almost nothing else: a different woman entirely, explicitly sinful rather than named, at the house of a Pharisee rather than in Bethany, set early in the Galilean ministry rather than days before the Passion, and ending on a pronouncement about forgiven sin rather than a comment about burial [[NOTE:anointing-luke-parallel]]. Historical-critical scholarship treats this as a live, unresolved question rather than a settled one: one underlying incident refracted three ways, two originally separate traditions partly merged, or three genuinely distinct events — the shared name, place, and burial theme linking John most closely to Mark and Matthew, with Luke's version the hardest of the three to reconcile [[NOTE:anointing-tradition-count-debate]]. Even Jesus's own reply to Judas carries a small, real translation puzzle: the Greek can be read either as an instruction to let Mary keep what perfume remains for a future burial, or as an observation that she has, in using it now, already in effect kept it for that purpose — which is why English translations diverge on the exact wording of his answer [[NOTE:john-12-7-burial-tense-textual-variant]].

Judas's characterization here is worth pausing on for what it reveals about how John tells a story compared to the Synoptics. No other Gospel names Judas as the objector in this scene, and none of them carries any hint that his objection was insincere; the theft accusation, and the detail that he regularly helped himself from the group's funds, appears nowhere outside John [[NOTE:judas-aside-johannine-only]]. That's not evidence the detail is false — but it is evidence that this is a distinctively Johannine narrative and theological choice, deepening Judas's villainy well ahead of the betrayal scene, rather than a fact independently preserved by more than one early source. Even the word John uses for the money bag itself, glossokomon, is a small philological curiosity: originally a case for reed instrument mouthpieces before it came to mean any small box, and used in the entire New Testament only here and once more, at 13:29 — both times naming Judas as the one who carries it [[NOTE:judas-glossokomon-money-box]].
'@

$beat2 = @'
The next day, the crowd that has come up for the feast, hearing Jesus is on his way into Jerusalem, takes palm branches and goes out to meet him, shouting "Hosanna! Blessed is he who comes in the name of the Lord, even the King of Israel!" Jesus finds a young donkey and sits on it, and the narrator steps in directly to tell readers why: this fulfills the prophecy, "Fear not, daughter of Zion; behold, your king is coming, sitting on a donkey's colt." The narrator adds that the disciples themselves didn't understand the connection to Scripture at the time; only after Jesus was glorified did they remember that this had been written of him and had been done to him. The crowd that had been with Jesus at Lazarus's tomb keeps bearing witness to what they saw, which is why so much of the crowd comes out to meet him — prompting the Pharisees to say to one another, in something close to despair, "You see that you are gaining nothing. Look, the world has gone after him" (12:12-19).

The narrator's citation is worth reading closely rather than taking as a simple lift, because it isn't one. Zechariah 9:9 does describe a king "humble, and mounted on a donkey, on a colt, the foal of a donkey" — but John's opening line, "fear not, daughter of Zion," isn't in Zechariah 9:9 at all; it echoes language from Zephaniah 3:16 and Isaiah 40:9 instead, spliced onto the Zechariah image, while Zechariah's own fuller description of the king as righteous and victorious as well as humble is left out entirely [[NOTE:zechariah-9-9-fulfillment-citation]]. The underlying image itself — a king riding a donkey rather than a war-horse into his capital — is part of a Persian-period vision of peaceable, non-military kingship, which is exactly the contrast the Gospel's citation is built to draw [[NOTE:zechariah-9-9-fulfillment-citation]]. A related, genuinely interesting Synoptic wrinkle sits one Gospel over from John: Mark, Luke, and John all have Jesus mount a single animal, but Matthew's version, read literally, has him riding two animals at once — widely explained in mainstream commentary as Matthew over-literalizing the Hebrew poetic parallelism of Zechariah 9:9, which describes one animal twice in two parallel phrases, into two separate donkeys [[NOTE:donkey-colt-synoptic-mount-detail]].

Historical Jesus scholarship treats some version of this scene — a deliberate, symbolically loaded entry into Jerusalem shortly before Passover — as among the more historically probable episodes behind the Gospels, not because the crowd's precise words are verifiable but because it helps explain, in ordinary cause-and-effect terms, why the authorities moved against Jesus at that specific festival and not at some other point in his ministry [[NOTE:sanders-entry-historical-plausibility]]. Jerusalem's Passover crowds were, on any accounting, immense — Josephus reports a census that (however inflated its final number) confirms enormous pilgrim traffic at the feast — so a public, readable-as-messianic gesture arriving into that crowd, under close Roman and priestly watch, is exactly the kind of provocation historians look for [[NOTE:josephus-passover-pilgrim-numbers]]. What's less secure is the specific scale and unanimity the Gospels describe: a whole city turning out, explicit royal titles shouted aloud by name, with no report of any on-the-spot Roman response to a demonstration of that size — a gap some historians read as retrospective theological amplification of a smaller, more ambiguous event [[NOTE:crowd-size-caution]]. And the Pharisees' own complaint carries an irony the narrator seems to want readers to catch: "the world has gone after him" is meant as hyperbole, and the very next scene — Greeks from outside Israel coming to see Jesus — begins to make it literally true [[NOTE:pharisees-world-gone-after-him-irony]].
'@

$beat3 = @'
Among those who had come up to worship at the feast are some Greeks; they approach Philip, who is from Bethsaida in Galilee, asking to see Jesus. Philip tells Andrew, and the two of them together tell Jesus. Jesus doesn't answer them directly but announces instead that the hour has come for the Son of Man to be glorified, and moves into an extended discourse: a grain of wheat must fall into the earth and die in order to bear much fruit; whoever loves his life loses it, and whoever hates his life in this world will keep it for eternal life; whoever serves Jesus must follow him, and the Father will honor whoever serves him. Jesus says his own soul is troubled, wonders aloud whether to ask the Father to save him from this hour, and then answers his own question — it was for this very purpose that he has come to this hour — and asks the Father instead to glorify his name. A voice answers from heaven: "I have both glorified it, and will glorify it again." The crowd standing there, hearing it, says it thundered; others say an angel has spoken to him. Jesus tells them the voice came for their sake, not his, and that now is the judgment of this world, that the ruler of this world will be driven out, and that when he is lifted up from the earth he will draw all people to himself — a line the narrator glosses directly as pointing to the specific kind of death Jesus was going to die (12:20-33).

The Greeks deserve a beat of their own, since the word John uses, Hellenes, is not the word he'd use for Greek-speaking Jews (Hellenistai); these are Gentiles. The most plausible historical identification is not an anachronistic missionary scene planted into Jesus's own lifetime but a recognized first-century category: God-fearing Gentile sympathizers or proselytes, drawn to Jewish monotheism and ethics, who attended festival worship at the Temple's outer precincts without undergoing full conversion, comparable to figures like the centurion Cornelius in Acts [[NOTE:greeks-hellenes-godfearers-not-mission]]. Their arrival functions less as an event to be verified than as a narrative signal, timed deliberately, that the mission the Gospel keeps gesturing toward is one that reaches past Israel entirely.

"The hour has come" is also worth flagging as more than a passing phrase. Twice earlier in the Gospel the narrator has said explicitly that Jesus's hour "had not yet come" (2:4, 7:30, and again in substance at 8:20); this is the first place it's declared to have arrived, and commentary on John's overall structure treats the turn as a hinge, the Gospel's pivot from material addressed to the world at large into material addressed specifically to the disciples [[NOTE:hour-has-come-johannine-motif]]. The grain-of-wheat saying that follows immediately has real Synoptic cousins, even if only John dresses it in agricultural imagery: the paradox that loving one's life loses it while giving it up preserves it echoes, in different wording, both Mark 8:35 (with parallels in Matthew and Luke) and Matthew 10:39 (paralleled in Luke 17:33) — a saying attested with independent wording across John and multiple Synoptic settings, which is exactly the kind of cross-source spread historical-Jesus scholarship treats as a mark of an old and durable tradition [[NOTE:grain-of-wheat-synoptic-saying-parallel]]. The voice from heaven, finally, is a genuine outlier within John's own Gospel: John records no heavenly voice at Jesus's baptism and includes no Transfiguration scene at all, the two moments where the Synoptics do narrate one; this is the only such voice anywhere in the Fourth Gospel, and its structural resemblance to those absent Synoptic scenes has led some commentators to read it as a compressed or relocated echo of that same broader tradition, though that remains a resemblance rather than a demonstrated borrowing [[NOTE:voice-from-heaven-parallel-scenes]].
'@

$beat4 = @'
The crowd presses back: how can the Son of Man be "lifted up" if the Christ is supposed to remain forever? Jesus answers only that the light is with them a little longer, and that they should walk while they have it, before darkness overtakes them; he then departs and hides himself from them. At this point John steps fully into his own authorial voice to explain why, despite everything Jesus has done, the crowds still would not believe: so that the word of Isaiah the prophet might be fulfilled, "Lord, who has believed what he heard from us, and to whom has the arm of the Lord been revealed?" — and again, "He has blinded their eyes and hardened their heart, lest they see with their eyes and understand with their heart, and turn, and I would heal them" — words the narrator says Isaiah spoke because he saw Jesus's glory. And yet, John adds at once, many even of the authorities believed in Jesus, but did not confess it for fear of the Pharisees, lest they be put out of the synagogue, since they loved human praise more than the praise that comes from God. The chapter closes with a summary discourse in which Jesus cries out that whoever believes in him believes in the one who sent him, that he came as light into the world so that no one who believes in him need remain in darkness, and that he did not come to judge the world but to save it — though his own words will judge whoever rejects them on the last day, because he has spoken only what the Father commanded him to say (12:34-50).

The two Isaiah citations are worth engaging directly rather than reading past, because the narrator is doing something unusually bold with them: not just quoting Scripture as Jesus's own words do elsewhere, but offering his own theological explanation, in his own voice, for why real unbelief persisted in the face of real signs. The first citation, Isaiah 53:1 ("who has believed what he heard from us"), is drawn from the Suffering Servant poem that early Christian writers elsewhere read as foretelling a suffering messiah; Paul quotes the identical verse for a comparable purpose in Romans, evidence the text already carried this specific apologetic use in early Christian argument before or alongside John's own citation of it [[NOTE:isaiah-53-1-suffering-servant-citation]]. The second, Isaiah 6:10's language of blinded eyes and hardened hearts, is one of the single most reused Old Testament passages anywhere in the New Testament for explaining unbelief, turning up independently in Mark's parable discourse and again in Acts and Romans — a striking case of one prophetic text doing sustained theological work across authors who otherwise show little sign of copying from one another [[NOTE:isaiah-6-10-hardening-citation]].

The note about secret believers among "the authorities" carries its own historical-critical weight. A very influential line of scholarship reads the fear of synagogue expulsion described here less as a plain report of conditions during Jesus's own ministry and more as a reflection of the later, harder split between John's own late-first-century Christian community and the synagogue it had been, or was being, pushed out of — a real conflict of the Gospel's own composition-era that the Evangelist is thought to have projected back onto the narrated events of Jesus's lifetime [[NOTE:martyn-two-level-synagogue-expulsion]]. That reading has been refined and in places challenged since it was first proposed, but the underlying observation — that this verse names a genuine, painful rupture between synagogue and church — has held up well across the debate. The chapter's closing lines, in any case, function as a summary of everything John's "Book of Signs" has been building toward: judgment not as an external verdict imposed later, but as the built-in consequence of how a person has already met the light.
'@

$beats = @($beat1, $beat2, $beat3, $beat4)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'ZECHARIAH (PROPHET)' = "A postexilic Judean prophet, active c. 520-518 BCE per the book of Zechariah's own superscriptions, whose oracle envisioning a king entering Jerusalem ``humble, and mounted on a donkey, on a colt, the foal of a donkey'' (Zechariah 9:9) the narrator explicitly cites as fulfilled by Jesus's entry into Jerusalem on a donkey's colt (12:14-15). John's quotation is a loose paraphrase rather than a verbatim reproduction of either the Hebrew or the Greek Septuagint text [[NOTE:zechariah-9-9-fulfillment-citation]]."
'ANOINTING AT BETHANY (SYNOPTIC PARALLELS)' = "The account of Mary of Bethany anointing Jesus's feet with a pound of costly nard six days before Passover (12:1-8) sits alongside two other Gospel anointing stories sharing some but not all of its details: an anointing of Jesus's head by an unnamed woman at Simon the leper's house in Bethany shortly before Passover in Mark 14:3-9 and Matthew 26:6-13 [[NOTE:anointing-mark-matthew-parallel]], and an anointing of Jesus's feet by an unnamed sinful woman at the house of a different Simon (a Pharisee), set much earlier in the ministry in a different location altogether, in Luke 7:36-50 [[NOTE:anointing-luke-parallel]]. Whether all three accounts render one underlying incident, two partly conflated traditions, or three genuinely separate anointings remains a genuinely open, well-studied question rather than a settled one [[NOTE:anointing-tradition-count-debate]]."
'TRIUMPHAL ENTRY (JOHN 12:12-19)' = "Jesus's arrival in Jerusalem the day after the Bethany dinner, greeted by a crowd waving palm branches and shouting ``Hosanna,'' mounted on a young donkey in a scene the narrator explicitly ties to Zechariah 9:9 [[NOTE:zechariah-9-9-fulfillment-citation]]. Some version of a deliberate, symbolically loaded entry into the city just before Passover is widely regarded among historical-Jesus scholars as one of the more historically plausible episodes behind the Gospel accounts, since it helps explain the timing of the authorities' later move against Jesus [[NOTE:sanders-entry-historical-plausibility]], even though the crowd's scale and unanimity as narrated may reflect later theological amplification [[NOTE:crowd-size-caution]]."
'GREEKS (HELLENES) AT THE FEAST' = "Gentile visitors to the Jerusalem Passover festival who approach the disciple Philip asking to see Jesus (12:20-22), most plausibly identified as God-fearing sympathizers or proselytes drawn to Jewish worship rather than full converts, and not best read as an anachronistic missionary scene inserted into Jesus's own lifetime [[NOTE:greeks-hellenes-godfearers-not-mission]]. Their request is the narrative trigger for Jesus's declaration that ``the hour has come'' [[NOTE:hour-has-come-johannine-motif]]."
'VOICE FROM HEAVEN (JOHN 12:28-29)' = "A voice answering Jesus's prayer to the Father to ``glorify your name,'' heard by the crowd standing by as either thunder or an angel speaking (12:28-29). It is the only heavenly voice recorded anywhere in the Fourth Gospel, which narrates neither a baptismal voice (contrast Mark 1:11) nor a Transfiguration scene at all, prompting some commentators to read the episode as a relocated or compressed echo of that wider Synoptic tradition rather than a freestanding Johannine invention [[NOTE:voice-from-heaven-parallel-scenes]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum - $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch12NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "Anointing at Bethany (Synoptic Parallels)" "anointing-at-bethany-synoptic-parallels" "vocabulary" "The Mary-of-Bethany foot-anointing of Jesus six days before Passover (John 12:1-8), compared against the Mark/Matthew head-anointing at Simon the leper's house and the Luke 7:36-50 sinful-woman story."
Seed-Entity "Triumphal Entry" "triumphal-entry" "vocabulary" "Jesus's symbolically loaded entry into Jerusalem on a donkey's colt shortly before Passover, narrated in all four Gospels and tied by John explicitly to Zechariah 9:9."
Seed-Entity "Greeks (Hellenes) at the Feast" "greeks-hellenes-at-the-feast" "vocabulary" "Gentile God-fearers or proselytes who approach Philip at the Jerusalem Passover festival asking to see Jesus (John 12:20-22), narrative trigger for the 'hour has come' discourse."
Seed-Entity "Voice from Heaven (John 12:28-29)" "voice-from-heaven-john-12" "vocabulary" "The heavenly voice answering Jesus's prayer to glorify the Father's name, heard by the crowd as thunder or an angel; the only such voice recorded in John's Gospel."

$conn.Close()
Write-Host "DONE Chapter 12."
