$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$Ch11NodeId = [guid]"019FA96C-C4E0-73D8-8776-231EE5C145F8"
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'lazarus-illness-glory-of-god-delay' = @{ title='A delay explained as theology, not neglect'; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), commentary ad loc. John 11:4-6. Carson and the mainstream commentary tradition read Jesus's declaration that the illness is `"for the glory of God`" and his deliberate two-day delay (11:6) as a programmatic Johannine framing device rather than a report of ordinary human hesitation: the narrator wants the reader to see the coming sign, before it happens, as revelatory rather than accidental, the same pattern already established at the healing of the man born blind (9:3)." }
'bethany-near-jerusalem-fifteen-stadia' = @{ title='Fifteen stadia from Jerusalem'; body="Jerome Murphy-O'Connor, The Holy Land: An Oxford Archaeological Guide from Earliest Times to 1700, 5th ed. (Oxford: Oxford University Press, 2008), entry on Bethany. John's own geographical note that Bethany was `"about two miles`" (literally fifteen stadia) from Jerusalem (11:18) matches the real distance to the village now called al-Eizariya (`"place of Lazarus`" in Arabic), on the eastern slope of the Mount of Olives; Murphy-O'Connor's guide catalogs a tradition, attested from at least the fourth century, locating Lazarus's tomb there, though the tomb shown to pilgrims today has been substantially rebuilt and altered since antiquity." }
'thomas-die-with-him-characterization' = @{ title='Thomas before Thomas is famous for doubting'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary ad loc. John 11:16. Brown notes that Thomas's `"Let us also go, that we may die with him`" is the character's first speaking appearance in the Gospel, establishing a loyal-but-uncomprehending fatalism well before his more famous scene of doubt at the resurrection appearances (20:24-29); commentators generally read the two scenes together as a single, consistent Johannine character arc rather than as unrelated incidents." }
'four-days-dead-soul-lingers-rabbinic' = @{ title='Why the fourth day mattered'; body="Craig S. Keener, The Gospel of John: A Commentary, vol. 2 (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 11:39. Keener catalogs the later rabbinic tradition, recorded in sources including Leviticus Rabbah 18:1 and Ecclesiastes Rabbah 12:6, that a departed soul was believed to linger near its body for three days hoping to return, after which the body was understood to begin visible decay and any hope of resuscitation was considered closed; John's insistence that Lazarus had been dead four full days (11:17, 11:39) functions within this popular belief-world to rule out any suspicion of resuscitation from a merely apparent death." }
'martha-confession-christ-son-of-god' = @{ title='A confession usually given to Peter'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary ad loc. John 11:27. Brown observes that Martha's declaration, `"I believe that you are the Christ, the Son of God, who is coming into the world,`" is couched in language strikingly close to the confession the Synoptic Gospels give to Peter at Caesarea Philippi (Matthew 16:16); rather than treating this as coincidence, the mainstream commentary tradition reads it as a deliberate Johannine choice to place the Gospel's clearest full christological confession in the mouth of a woman, ahead of the male disciples." }
'jesus-wept-dakryo-verb' = @{ title='Two different words for weeping in the same scene'; body="C.K. Barrett, The Gospel according to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 11:33, 35. Barrett notes that the Greek text uses two different verbs for weeping within the space of a few verses: Mary and the accompanying mourners are described with klaio, the ordinary word for audible, public lamentation (11:33), while Jesus's own response two verses later uses the rarer dakryo, a quieter, more restrained word for shedding tears (11:35) — the shortest verse in most English translations. The word choice is not incidental; commentators debate whether it signals private grief held apart from the surrounding public wailing, or simply variatio, an evangelist's stylistic avoidance of repeating the same verb twice." }
'jesus-deeply-moved-troubled-embrimaomai' = @{ title='Anger, revulsion, or grief? A disputed verb'; body="C.K. Barrett, The Gospel according to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 11:33, 38. The verb translated `"deeply moved`" (embrimaomai) ordinarily carries a connotation of anger, snorting, or indignation rather than sorrow, and John uses it twice in this scene (11:33, 38); Barrett and the wider commentary tradition are divided over whether the emotion in view is Jesus's anger at unbelief and at death's power itself, or whether the term has been softened here toward simple emotional agitation — a genuine translation and interpretive crux the English `"deeply moved in spirit and troubled`" only partly resolves." }
'synoptic-silence-bultmann-ehrman' = @{ title="John's greatest miracle, absent from Mark, Matthew, and Luke"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971), commentary on John 11:1-44; see also Bart D. Ehrman, Jesus, Interrupted: Revealing the Hidden Contradictions in the Bible (New York: HarperOne, 2009), chapter on the differences among the Gospels. Bultmann reads the Lazarus narrative as a theological composition built by the evangelist around inherited symbolic material rather than a report of an actual event, and Ehrman treats its total absence from Mark, Matthew, and Luke — despite being, on John's own telling, the single event that precipitates the formal decision to kill Jesus (11:53) — as a strong indicator that the story did not circulate in the tradition available to the Synoptic authors." }
'brown-argument-from-silence-caution' = @{ title='Silence is not, by itself, proof'; body="Raymond E. Brown, The Gospel According to John I-XII, Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), introductory discussion preceding the commentary on John 11. Brown, more cautiously, argues that an argument from Synoptic silence is not on its own decisive: the Synoptic Gospels' coverage of Jesus's Judean ministry, as opposed to the Galilean material that dominates Mark and the bulk of Matthew and Luke, is comparatively thin to begin with, and each evangelist selects and omits material according to distinct compositional purposes, so the absence of a Judean-based story from Galilee-centered sources need not by itself indicate the story was invented." }
'luke-16-parable-name-coincidence' = @{ title='The same name, twice, in two different genres'; body="C.K. Barrett, The Gospel according to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 11:1. Barrett notes the striking coincidence that the only other Lazarus named anywhere in the canonical Gospels is the beggar in Jesus's parable of the rich man and Lazarus (Luke 16:19-31) — a parable that itself turns on a rich man begging that Lazarus be sent back from the dead to warn his brothers, and being refused, since `"they will not be convinced even if someone rises from the dead`" (Luke 16:31). Some scholars, Bultmann among them, have proposed the Johannine narrative developed out of this Lukan parable material; others regard the shared name as coincidental, since Lazarus (from the Hebrew Eleazar, `"God has helped`") was a common contemporary Jewish name." }
'signs-source-hypothesis-fortna' = @{ title='A hypothetical earlier miracle-collection'; body="Robert T. Fortna, The Fourth Gospel and Its Predecessor: From Narrative Source to Present Gospel (Philadelphia: Fortress Press, 1988). Fortna's reconstruction of a hypothetical pre-Johannine `"Signs Source`" — a numbered collection of miracle stories the evangelist is theorized to have inherited and then reworked with extended theological discourse — treats the Lazarus story as a strong candidate for inclusion in that earlier source, on the theory that a core miracle account circulated independently before John's surrounding discourse material was added around it; the hypothesis remains widely discussed but is not a consensus position." }
'meier-marginal-jew-lazarus-historicity' = @{ title='The most sustained scholarly argument on the question'; body="John P. Meier, A Marginal Jew: Rethinking the Historical Jesus, Volume Two: Mentor, Message, and Miracles (New York: Doubleday, 1994), excursus on the raising of Lazarus. Meier devotes an extended, methodical treatment to the Lazarus narrative specifically because of its evidential weight for historical-Jesus research, concluding that while some substratum tradition involving Jesus and a resuscitation-type action at Bethany plausibly lies behind the story, the developed narrative as it stands in John 11 — with its extended dialogue, staged four-day delay, and explicit causal link to the crucifixion — bears heavy marks of Johannine theological composition, making any confident historical reconstruction of the underlying event unusually difficult." }
'stench-four-days-decomposition-realism' = @{ title="'By this time there will be a bad odor'"; body="Craig S. Keener, The Gospel of John: A Commentary, vol. 2 (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 11:39. Keener reads Martha's blunt objection to opening the tomb — rendered `"Lord, by this time there will be a bad odor, for he has been dead four days,`" or, in the King James Version's memorably direct phrasing, `"he stinketh`" — as a detail placed in the narrative specifically to close off any reading of Lazarus's death as a coma, swoon, or premature burial; the text goes out of its way to insist, through its own characters, that ordinary decomposition had already begun." }
'caiaphas-historical-office-josephus' = @{ title='An unusually long eighteen-year tenure'; body="Flavius Josephus, Jewish Antiquities, Book 18, sections 33-35 and 95 (Loeb Classical Library, trans. Louis H. Feldman, Cambridge, MA: Harvard University Press, 1965). Josephus records that Joseph Caiaphas was appointed high priest by the Roman prefect Valerius Gratus around 18 CE and was removed from office by the legate Vitellius around 36 CE, a roughly eighteen-year tenure that is strikingly long by the standard of the office in this period, when high priests were typically replaced every few years; historians generally read the length of Caiaphas's tenure as reflecting a stable, cooperative working relationship with Rome, spanning the entirety of Pontius Pilate's own prefecture (26-36 CE)." }
'caiaphas-ossuary-1990-discovery' = @{ title='A named ossuary from a first-century tomb'; body="Zvi Greenhut, 'Burial Cave of the Caiaphas Family,' Biblical Archaeology Review 18, no. 5 (1992): 29-36. In 1990, construction work in Jerusalem's Peace Forest (North Talpiot) uncovered a first-century burial cave containing twelve ossuaries, one of them elaborately decorated and inscribed twice with the name `"Yehosef bar Qafa`" (Joseph, son of Caiaphas); Greenhut, who directed the excavation, and the broader scholarly consensus that followed identify the ossuary as very likely belonging to the high priest named in the Gospels, making it a rare case of probable direct archaeological corroboration of a named New Testament figure." }
'unwitting-prophecy-johannine-irony-culpepper' = @{ title="A prophecy the prophet doesn't know he's making"; body="R. Alan Culpepper, Anatomy of the Fourth Gospel: A Study in Literary Design (Philadelphia: Fortress Press, 1983), discussion of Johannine irony. Culpepper's landmark literary study of the Fourth Gospel treats the narrator's explicit aside at 11:51-52 — that Caiaphas `"did not say this of his own accord`" but `"prophesied`" that Jesus would die for the nation, and not for the nation only, without understanding the deeper truth of his own words — as one of the clearest instances of the Gospel's recurring irony device, in which a character's words carry a true meaning invisible to the speaker but plainly signaled to the reader by the narrator standing outside the scene." }
'sanhedrin-synoptic-parallel-mark-14' = @{ title='The same plot, a different trigger'; body="Mark 14:1-2 and Matthew 26:3-5 record chief priests and elders (Matthew specifically naming Caiaphas's residence) conspiring to arrest and kill Jesus in the days before Passover, but neither Synoptic account gives any reason for the timing beyond general hostility and fear of a crowd disturbance during the feast. John's version supplies a specific narrative trigger — the raising of Lazarus and the popular response it provokes (11:45-48) — that is entirely absent from the Synoptic accounts of the same underlying decision, a further data point in the wider debate over how much of John's causal framework for the Passion reflects independent historical memory versus the evangelist's own narrative architecture." }
'ephraim-location-identification' = @{ title='A retreat to an uncertain village'; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), commentary ad loc. John 11:54. Carson notes that the Ephraim to which Jesus withdraws is most often identified with the modern village of et-Taiyibeh, roughly twenty kilometers northeast of Jerusalem near the edge of the Judean wilderness, an identification going back to Eusebius's fourth-century Onomasticon; the site has not been independently confirmed by excavation specific to this Gospel event, and some caution is warranted before treating the identification as more than a well-informed ancient guess." }
'fredriksen-romans-will-come-anxiety' = @{ title="Real Roman-era anxiety behind the council's fear"; body="Paula Fredriksen, Jesus of Nazareth, King of the Jews: A Jewish Life and the Emergence of Christianity (New York: Alfred A. Knopf, 1999). Fredriksen situates the Sanhedrin's stated fear in this chapter — `"If we let him go on like this, everyone will believe in him, and the Romans will come and take away both our place and our nation`" (11:48) — within the real, well-documented Roman practice of holding local ruling councils responsible for maintaining order during pilgrimage festivals, when Jerusalem's population swelled and any crowd disturbance around a popular figure carried a genuine risk of Roman military intervention and reprisal against the city's governing elite." }
'von-wahlde-lazarus-composition-history' = @{ title='A late link, added to bind two halves of the Gospel'; body="Urban C. von Wahlde, The Gospel and Letters of John, vol. 2, Eerdmans Critical Commentary (Grand Rapids: Eerdmans, 2010), commentary on John 11. Von Wahlde's compositional-stratigraphy analysis of the Fourth Gospel places the Lazarus narrative among the latest material added to the text, arguing that its heavy causal weight — explicitly supplying the reason the authorities decide to kill Jesus (11:53) — was assigned to the passage precisely because it was composed, at a late editorial stage, to bridge the Gospel's 'Book of Signs' (chapters 1-12) to its Passion narrative, rather than surviving intact from an early layer of tradition." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
Word reaches Jesus that Lazarus of Bethany is ill — the sisters' message is spare and pointed: "Lord, he whom you love is ill." Jesus's answer is the strangest thing said in the whole scene, spoken before Lazarus has even died: "This illness does not lead to death; it is for the glory of God, so that the Son of God may be glorified through it." And then, having said that, he does not go. He stays where he is two more days before finally telling the disciples, "Let us go to Judea again" — over their open alarm, since the last time he was there, the Judeans had tried to stone him. Thomas, resigned rather than hopeful, tells the others: "Let us also go, that we may die with him" (11:1-16).

The delay is worth pausing on before anything else, because the text doesn't read like ordinary hesitation or a crowded schedule. Jesus states outright, in advance, why the illness has happened and what it is for [[NOTE:lazarus-illness-glory-of-god-delay]]. That is a narrator's move as much as a character's: the reader is being told, before the miracle occurs, to see it as revelation rather than accident — exactly the same interpretive signpost John planted at the healing of the man born blind, where the disciples' question about whose sin caused the blindness is answered "that the works of God might be displayed in him" (9:3). Two full days pass with Lazarus dying and Jesus, by his own account, deliberately not yet moving.

Bethany itself is a real, locatable place, and John is precise about it: "about two miles" from Jerusalem, fifteen stadia in the Greek (11:18) [[NOTE:bethany-near-jerusalem-fifteen-stadia]]. The distance checks out against the modern village on the eastern slope of the Mount of Olives, still called al-Eizariya — Arabic for "place of Lazarus," a name the site has carried since long before anyone thought to ask a historian whether the story behind it was true.

Thomas gets his first line of dialogue in this scene, and it isn't doubt — it's a grim, loyal fatalism, volunteering to walk into the same danger that has the other disciples frightened [[NOTE:thomas-die-with-him-characterization]]. Read against his far more famous scene nine chapters later, refusing to believe the resurrection until he can put his hand in the wound, the two moments cohere: a disciple whose commitment runs through his hands and his willingness to die, never through easy trust in a report.
'@

$beat2 = @'
By the time Jesus arrives, Lazarus has been in the tomb four days. Martha, hearing he is coming, goes out to meet him while Mary stays seated at the house; her opening line is a confrontation, not a greeting: "Lord, if you had been here, my brother would not have died. But even now I know that whatever you ask from God, God will give you." Jesus tells her, "Your brother will rise again," and when she deflects it into the safe, general hope of "the resurrection on the last day," he answers with one of the Gospel's defining claims: "I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live." Martha's reply is the fullest confession of faith any character makes in this Gospel: "I believe that you are the Christ, the Son of God, who is coming into the world" (11:17-27).

The four-day detail is not incidental stage-dressing. Later rabbinic sources record a popular belief that a departed soul lingers near its body for three days, hoping to return, before departing for good once decay visibly sets in [[NOTE:four-days-dead-soul-lingers-rabbinic]]. Within that belief-world, three days dead leaves room for doubt — a soul might still come back, a death might still be reversible, the way it almost is in a few other ancient resuscitation stories. Four days closes that door inside the story's own logic: whatever is about to happen next cannot be waved off as a body prematurely declared dead.

Martha's confession deserves its own scrutiny, because its wording is not generic praise — it echoes, almost word for word, the confession the Synoptic Gospels give to Peter at Caesarea Philippi: "You are the Christ, the Son of the living God" (Matthew 16:16) [[NOTE:martha-confession-christ-son-of-god]]. That a woman, not one of the Twelve, speaks the Fourth Gospel's clearest full statement of who Jesus is, is very unlikely to be an accident of storytelling; the mainstream reading treats it as a deliberate Johannine choice, made at the exact narrative moment the Gospel needs its christology stated in full before the miracle that will prove it.
'@

$beat3 = @'
Martha goes back for Mary, telling her privately that "the Teacher is here and is calling for you." Mary rises quickly and goes to him, falls at his feet, and says the identical line Martha opened with: "Lord, if you had been here, my brother would not have died." Seeing her weeping, and the Judeans who had come with her weeping too, Jesus is described as "deeply moved in his spirit and greatly troubled." He asks where they have laid him, and they answer, "Lord, come and see." Then comes the shortest verse in most English Bibles: "Jesus wept." The onlookers split in their reading of it — some say, "See how he loved him," others ask, pointedly, "Could not he who opened the eyes of the blind man also have kept this man from dying?" (11:28-37).

The two reactions of weeping in this scene are not described with the same word, and the difference is easy to miss in translation. Mary and the surrounding mourners are weeping with klaio, the ordinary Greek verb for loud, public lamentation; two verses later, Jesus's own tears are described with the rarer, quieter dakryo [[NOTE:jesus-wept-dakryo-verb]]. Whether that word choice is meant to isolate Jesus's private grief from the noise around him, or is simply an evangelist avoiding the same verb twice, is a live interpretive question — but it is a real textual distinction, not something modern readers have projected backward onto the Greek.

"Deeply moved" is its own puzzle. The verb behind it, embrimaomai, ordinarily carries a sense of anger, or even something closer to a snort of indignation, and John uses it twice in the space of five verses (11:33, 38) [[NOTE:jesus-deeply-moved-troubled-embrimaomai]]. Commentators are genuinely divided over what emotion the term is doing work for here — anger at unbelief, anger at death itself as an enemy, or a term softened by the evangelist toward ordinary grief — and the English rendering "deeply moved in spirit and troubled" smooths over a real ambiguity in the underlying word rather than resolving it.
'@

$beat4 = @'
They come to the tomb, a cave with a stone laid across it. Jesus orders the stone taken away; Martha, practical to the last, objects that after four days there will be a smell. Jesus prays aloud — not, he says, because he needs to, but "on account of the people standing here, that they may believe that you sent me" — and then cries out in a loud voice, "Lazarus, come out." The dead man comes out, still bound hand and foot in burial wrappings, his face wrapped in a cloth. Jesus tells the crowd, "Unbind him, and let him go" (11:38-44).

This is, on any accounting, John's single greatest miracle — his most narratively consequential sign, explicitly the event that (a few verses later) triggers the authorities' formal decision to kill Jesus. And it appears nowhere in Mark, Matthew, or Luke. That silence is genuinely striking, and mainstream scholarship does not agree on what to make of it. Bultmann reads the Lazarus narrative as a theological composition, built by the evangelist out of inherited symbolic material rather than transmitted as reported history, and Bart Ehrman treats the story's total absence from the Synoptics — despite its supposedly enormous public impact — as strong evidence it was not part of the tradition available to Mark, Matthew, or Luke [[NOTE:synoptic-silence-bultmann-ehrman]]. Raymond Brown counsels more caution: an argument from silence is not decisive by itself, since the Synoptics' coverage of Jesus's Judean ministry (as opposed to the Galilean material that dominates all three) is comparatively thin to begin with, and each evangelist selected material for his own purposes [[NOTE:brown-argument-from-silence-caution]]. Both positions are represented in serious scholarship; nothing in the surviving evidence settles the argument outright, and the honest position is to weigh it rather than declare a verdict.

One thread in that debate is worth naming on its own: the only other Lazarus anywhere in the canonical Gospels is the beggar in Jesus's parable of the rich man and Lazarus, unique to Luke (16:19-31) — a parable that ends with the rich man begging that Lazarus be sent back from the dead to warn his brothers, and being refused, because "they will not be convinced even if someone rises from the dead." Some scholars have proposed the Johannine narrative grew out of this Lukan parable material; others treat the shared name as coincidence, since Lazarus was a common Jewish name in the period [[NOTE:luke-16-parable-name-coincidence]]. Separately, source critics working on a hypothetical earlier "Signs Source" underlying John's Gospel have argued a core miracle account here may have circulated independently before the evangelist's extended dialogue was built around it [[NOTE:signs-source-hypothesis-fortna]], and Urban von Wahlde's compositional analysis places the whole Lazarus narrative among the latest material added to the Gospel, assigned its heavy causal weight — explicitly triggering the plot to kill Jesus — precisely because it was written to bridge the Gospel's first half to its Passion narrative [[NOTE:von-wahlde-lazarus-composition-history]]. John P. Meier's extended, methodical treatment of the question concludes that some real substratum tradition of Jesus and a resuscitation-type act at Bethany plausibly lies behind the story, while the fully developed narrative as it stands bears heavy marks of Johannine theological composition — which is to say, even the most historically cautious mainstream verdict does not simply hand the story over as straightforward reportage [[NOTE:meier-marginal-jew-lazarus-historicity]].

Martha's objection about the smell is not throwaway realism, either. It functions inside the story to foreclose any reading of Lazarus's death as a coma or a premature burial: the text insists, through its own most practical-minded character, that ordinary decomposition had already begun before anything happens [[NOTE:stench-four-days-decomposition-realism]]. Whatever else this scene is doing theologically, it is not leaving itself an escape hatch into "he wasn't really dead."
'@

$beat5 = @'
Many of the Judeans who had come with Mary, having seen what Jesus did, believe in him — but others go straight to the Pharisees and report it. The chief priests and Pharisees convene the Sanhedrin: "What are we to do? For this man performs many signs. If we let him go on like this, everyone will believe in him, and the Romans will come and take away both our place and our nation." Caiaphas, high priest that year, cuts through the council's indecision: "You know nothing at all. Nor do you understand that it is better for you that one man should die for the people, not that the whole nation should perish." The narrator immediately reframes the line: Caiaphas did not say this of his own accord, but, as high priest that year, unknowingly prophesied that Jesus would die for the nation — and not for the nation only, but to gather into one the scattered children of God. From that day on, the council makes its plan to kill him. Jesus stops moving openly among the Judeans and withdraws with his disciples to a town called Ephraim, near the wilderness, staying there as Passover approaches while the crowds in Jerusalem wonder aloud whether he will come to the feast at all, and the chief priests and Pharisees issue orders that anyone who knows where he is should report it (11:45-57).

Caiaphas is not a narrative invention grafted onto the Gospel; he is a documented historical office-holder. Josephus records that Joseph Caiaphas was appointed high priest around 18 CE by the Roman prefect Valerius Gratus and removed from office around 36 CE by the legate Vitellius — a roughly eighteen-year tenure that is unusually long for the office in this period, and one that spans the entirety of Pontius Pilate's own prefecture, which historians generally read as reflecting a stable, cooperative working relationship between the two men and with Rome more broadly [[NOTE:caiaphas-historical-office-josephus]]. The archaeological record adds a rare, concrete point of contact: in 1990, construction work in Jerusalem uncovered a first-century burial cave containing an elaborately decorated ossuary inscribed twice with the name "Yehosef bar Qafa" — Joseph, son of Caiaphas — which the excavator and the scholarly consensus since have identified as very likely belonging to this same high priest, a genuine case of physical corroboration for a named figure in the Gospels [[NOTE:caiaphas-ossuary-1990-discovery]].

The narrator's own comment on Caiaphas's words — that he spoke better than he knew, prophesying without understanding his own prophecy — is a deliberate literary device, not an incidental aside. It is one of the clearest instances of Johannine irony in the whole Gospel: a character's words carrying a true meaning invisible to the speaker but plainly flagged to the reader by a narrator standing just outside the scene [[NOTE:unwitting-prophecy-johannine-irony-culpepper]]. The council's fear driving the whole scene is also historically grounded rather than paranoid invention: Rome held local ruling councils responsible for order during pilgrimage festivals, when Jerusalem's population swelled and any crowd disturbance around a popular figure carried real risk of Roman military reprisal against the city's own governing elite [[NOTE:fredriksen-romans-will-come-anxiety]]. And the Sanhedrin plot itself has a Synoptic parallel that lacks John's specific trigger: Mark and Matthew both record chief priests and elders conspiring to kill Jesus in the days before Passover, but neither names any precipitating event — only John supplies the raising of Lazarus as the reason the timing accelerates [[NOTE:sanhedrin-synoptic-parallel-mark-14]]. Ephraim, where Jesus withdraws to wait it out, is usually identified with the modern village of et-Taiyibeh northeast of Jerusalem, an identification resting on a fourth-century geographical reference rather than on any excavation tied specifically to this Gospel scene [[NOTE:ephraim-location-identification]].
'@

$beats = @($beat1, $beat2, $beat3, $beat4, $beat5)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'LAZARUS OF BETHANY' = "The brother of Martha and Mary of Bethany, introduced in this chapter as gravely ill (11:1-3) and later raised from death after four days in the tomb (11:38-44), the climactic sign of the first half of John's Gospel. His story appears nowhere in Mark, Matthew, or Luke, a genuine and much-discussed gap in the tradition [[NOTE:synoptic-silence-bultmann-ehrman]] [[NOTE:brown-argument-from-silence-caution]]; the only other Lazarus named in the canonical Gospels is the beggar of Jesus's parable in Luke 16:19-31, a coincidence some scholars read as more than coincidental [[NOTE:luke-16-parable-name-coincidence]]. He returns as a living witness to Jesus's power in the following chapter's dinner at Bethany (12:1-11), where the chief priests are reported plotting to kill him too, precisely because his continued presence keeps drawing believers."
'MARTHA' = "A resident of Bethany, sister of Mary and Lazarus, introduced here confronting Jesus on the road into the village — `"Lord, if you had been here, my brother would not have died`" — and then offering, in reply to his declaration `"I am the resurrection and the life,`" one of the Gospel's clearest full confessions of faith: `"I believe that you are the Christ, the Son of God, who is coming into the world`" (11:21-27) [[NOTE:martha-confession-christ-son-of-god]]. She reappears serving the meal at the following chapter's Bethany dinner (12:2)."
'MARY OF BETHANY' = "Sister of Martha and Lazarus, identified by the narrator on her first mention here as the same Mary `"who anointed the Lord with ointment and wiped his feet with her hair`" (11:2) — a scene John has not yet told and narrates only in the following chapter (12:1-8), a detail commentators take as evidence the evangelist assumed his audience already knew her story. In this chapter she stays seated at home until summoned, then falls at Jesus's feet with the same words Martha used and weeps openly among the gathered mourners (11:28-33)."
'CAIAPHAS' = "Joseph Caiaphas, high priest presiding over the Sanhedrin session convened after Lazarus's raising (11:47-53), who silences the council's indecision with the argument that it is `"better... that one man should die for the people, not that the whole nation should perish`" — words the narrator immediately reframes as an unwitting prophecy of the crucifixion's meaning (11:51-52) [[NOTE:unwitting-prophecy-johannine-irony-culpepper]]. Josephus records his roughly eighteen-year tenure as high priest (c. 18-36 CE), spanning the entirety of Pontius Pilate's prefecture [[NOTE:caiaphas-historical-office-josephus]]; an inscribed ossuary discovered in Jerusalem in 1990 is widely identified as belonging to his family [[NOTE:caiaphas-ossuary-1990-discovery]]. He returns to preside over Jesus's Sanhedrin hearing in the Passion narrative."
'EPHRAIM' = "The town to which Jesus withdraws with his disciples after the Sanhedrin's formal decision to kill him, staying there until the approach of Passover draws him back toward Jerusalem (11:54-57). Most commonly identified with the modern village of et-Taiyibeh northeast of Jerusalem, near the edge of the Judean wilderness, an identification resting on Eusebius's fourth-century Onomasticon rather than on excavation tied specifically to this Gospel event [[NOTE:ephraim-location-identification]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum — $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch11NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
# None required: Jesus, Lazarus of Bethany, Martha, Mary of Bethany, Caiaphas, Thomas, Sanhedrin,
# Bethany (near Jerusalem), and Ephraim are all already present in the GSPL entity catalog.

$conn.Close()
Write-Host "DONE Chapter 11."
