$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA01D-FA22-76C6-976C-3EA4F4D54A14"
$GlossaryNodeId = [guid]"019FA026-3758-7A57-AF65-EC1DB4303EF3"
$Ch24NodeId = [guid]"019FA073-292F-7D88-973F-2FB76C93F677"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA01D-FA22-76C6-976C-3EA4F4D54A14' AND bn.IsEnabled=1")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA026-3758-7A57-AF65-EC1DB4303EF3' AND bn.IsEnabled=1")
$maxChapterSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA073-292F-7D88-973F-2FB76C93F677' AND bn.IsEnabled=1")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA01D-FA22-76C6-976C-3EA4F4D54A14' AND bn.IsEnabled=1 AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey MaxChapterSortKey=$maxChapterSortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'josephus-siege-eyewitness' = @{ title='Josephus at the siege, an eyewitness historian'; body="Flavius Josephus, The Jewish War, Loeb Classical Library, trans. H. St. J. Thackeray, vols. II-III (Cambridge, MA: Harvard University Press, 1927-1928), Books 5-7. Josephus was present at the siege of Jerusalem in 70 CE, attached to the Roman command staff of the general, and future emperor, Titus after his own capture earlier in the war. His Jewish War, completed within roughly a decade of the events it narrates, is the single most detailed ancient account of the siege and destruction, and the source virtually every modern history of the war draws on, a genuinely independent, non-Christian check on what actually happened to the Temple, whatever one concludes about when the Gospels themselves were written." }
'josephus-temple-burning-titus-reluctance' = @{ title="The Temple's burning, against Caesar's own wishes"; body="Flavius Josephus, The Jewish War 6.236-266 (Loeb Classical Library, trans. H. St. J. Thackeray). Josephus reports that Titus convened a council of his senior officers to debate the Temple building's fate and that his own stated preference was to spare it, but that in the chaos of the final assault a soldier flung a firebrand through a window and the blaze outran every officer's ability to stop it. Josephus states plainly that the sanctuary was destroyed against Caesar's own wishes (6.266). Whether that reported reluctance is sober reporting or flattery of the emperor under whom Josephus later wrote, the passage is itself independent testimony that no one close to the events disputed that the Temple burned, only whose decision it had been." }
'titus-future-emperor-context' = @{ title="The general who leveled the Temple, later Rome's emperor"; body="Suetonius, Lives of the Caesars: Titus 4-5 (Loeb Classical Library, trans. J. C. Rolfe, Cambridge, MA: Harvard University Press, 1914); compare Josephus, The Jewish War 6.316-322. Titus Flavius Vespasianus commanded the Roman siege of Jerusalem as a general acting under his father, the emperor Vespasian, and became emperor himself in 79 CE, reigning until his death in 81 CE. The man who ordered the Temple complex's final leveling is thus independently documented under his own later, better-known imperial title, the same future emperor Titus of the standard historical record." }
'josephus-final-razing-not-one-stone' = @{ title="The final razing, three towers spared, everything else to the ground"; body="Flavius Josephus, The Jewish War 7.1-4 (Loeb Classical Library, trans. H. St. J. Thackeray; see also the Whiston translation, Wars of the Jews 7.1.1). Once the city had fallen, Josephus reports that Titus ordered the entire city and Temple complex demolished, sparing only three fortress towers, Phasael, Hippicus, and Mariamme, and a stretch of the western wall, kept standing so a Roman garrison would have a camp and so later visitors could see for themselves how formidable a city Roman arms had subdued. Everything else, in Josephus's own account, was leveled so thoroughly that nothing was left to make anyone who came there afterward believe the site had ever been inhabited. Read next to that specific description, Matthew's not one stone will be left upon another (24:2) is not rhetorical inflation of an ordinary military defeat; it names, close to literally, what Roman siege engineers were capable of doing to a city they intended to erase." }
'josephus-portents-before-fall' = @{ title="Josephus's own catalogue of omens before the fall"; body="Flavius Josephus, The Jewish War 6.288-300 (Loeb Classical Library, trans. H. St. J. Thackeray). Independent of anything in Matthew, Mark, or any Christian source, Josephus catalogs a set of portents he says preceded the Temple's fall: a star shaped like a sword standing over the city for a year, a light shining around the altar at night, a cow giving birth to a lamb inside the Temple court, the massive eastern gate swinging open on its own, phantom armies and chariots seen moving through the clouds at sunset, and, most famously, a priest at Pentecost hearing a voice from within the sanctuary itself saying, We are departing hence. Josephus offers all of this as sober history, not literary flourish. Whatever one makes of the reports themselves, they show that Jewish witnesses to the same disaster independently reached for the same genre, portents announcing a coming doom, that this discourse's own sign-language draws on, with no dependence on Matthew's text or on Christian tradition." }
'vaticinium-ex-eventu-device' = @{ title="Vaticinium ex eventu, prophecy written after the fact"; body="The Latin phrase means, literally, prophecy from the outcome: a recognized device in ancient historical and apocalyptic writing in which a text sets a narrator's words inside an earlier time frame, then has that narrator predict, often in striking and accurate detail, events that had already happened by the time the text was actually composed. See John J. Collins, Daniel: A Commentary on the Book of Daniel, Hermeneia (Minneapolis: Fortress Press, 1993), introduction and commentary on chapters 10-12. Collins and the mainstream critical consensus read Daniel 11:2-39 as exactly this kind of retrospective prediction, accurate in fine-grained detail through the reign of Antiochus IV Epiphanes because it was written under Antiochus, then trailing into a genuinely unfulfilled prediction of his death at 11:40-45, the internal seam scholars use to date Daniel's actual composition to the 160s BCE crisis rather than the Babylonian exile it depicts." }
'davies-allison-post-70-majority' = @{ title="The majority case for a post-70 CE discourse"; body="W. D. Davies and Dale C. Allison Jr., Matthew 19-28, International Critical Commentary (Edinburgh: T&T Clark, 1997), commentary on Matthew 24:1-35. Davies and Allison lay out the majority critical-scholarship position that this discourse's close, sustained correspondence to the actual course of the Jewish War, the encirclement of Jerusalem, the flight of the Judean population, false messianic claimants, the Temple's desecration and fall, is most economically explained if Matthew's version of the discourse was composed with 70 CE's outcome already known, sharpening a shorter and more general apocalyptic saying of Jesus into the specific shape the war had actually taken." }
'pre-70-conservative-case' = @{ title="The minority case for a genuine, pre-70 CE prediction"; body="D. A. Carson, Matthew, in The Expositor's Bible Commentary, rev. ed., vol. 9 (Grand Rapids: Zondervan, 2010), commentary on Matthew 24:1-35; see also Craig L. Blomberg, Matthew, New American Commentary vol. 22 (Nashville: Broadman & Holman, 1992), commentary ad loc. Carson and Blomberg represent a substantial body of more conservative and evangelical scholarship arguing the discourse's specificity does not by itself prove after-the-fact composition: a first-century Jewish prophet steeped in Israel's own apocalyptic tradition, they argue, needed no privileged knowledge of the war's actual course to anticipate a Roman siege, given how visibly Judea's political situation under Rome was already deteriorating in the decades before it. This school generally argues for an earlier date for the whole Gospel on separate grounds as well, making the case a genuine minority dissent within the wider near-consensus, not merely an assertion made without argument." }
'daniel-antiochus-original-referent' = @{ title="Daniel's own abomination of desolation, Antiochus IV Epiphanes, 167 BCE"; body="John J. Collins, Daniel: A Commentary on the Book of Daniel, Hermeneia (Minneapolis: Fortress Press, 1993), commentary on Daniel 9:27, 11:31, and 12:11; compare 1 Maccabees 1:54-59. The mainstream critical consensus reads the abomination of desolation in Daniel as referring to a specific, dated, independently attested event: the Seleucid king Antiochus IV Epiphanes's erection of a pagan altar, almost certainly dedicated to Zeus Olympios, directly on top of the Jerusalem Temple's own altar of burnt offering in December of 167 BCE, followed by the sacrifice of pigs and the suppression of Jewish law, the desecration that touched off the Maccabean revolt. That background is developed at length elsewhere in this project's discussion of the Feast of Dedication in the Gospel of John's account of Hanukkah; it needs only the headline here: Daniel's phrase already had one specific, fulfilled, checkable referent centuries before this chapter has Jesus invoke it." }
'prophecy-reapplication-pattern' = @{ title="Recycling an old prophecy for a new crisis"; body="Craig A. Evans, Abomination of Desolation, in Dictionary of New Testament Background, ed. Craig A. Evans and Stanley E. Porter (Downers Grove, IL: InterVarsity Press, 2000), 2-3. Evans documents that Second Temple Jewish and early Christian writers routinely reapplied Daniel's abomination of desolation language to whatever fresh threat of Temple desecration their own generation actually faced: to Pompey's forced entry into the Temple's Holy of Holies in 63 BCE, to the emperor Caligula's attempt to install his own statue in the sanctuary around 40 CE, and here, in Matthew 24:15, to a future desecration this chapter's audience is told to watch for and flee from immediately. An older, authoritative prophecy, reread and reapplied to a new crisis its original author never had in view, is a documented and recurring pattern in how this literature actually worked across several centuries, not a novelty invented for this Gospel." }
'this-generation-near-reading' = @{ title="This generation, the straightforward near-term reading"; body="W. D. Davies and Dale C. Allison Jr., Matthew 19-28, International Critical Commentary (Edinburgh: T&T Clark, 1997), excursus on Matthew 24:34. Taken at face value, this generation (he genea haute) in Matthew's own usage elsewhere (11:16; 12:41-42, 45; 23:36) denotes a cohort of people alive at one time, Jesus's own contemporaries, not some distant future cohort, and the standard critical commentary on Matthew treats this as the most natural reading of 24:34 on its own grammar, tying the discourse's events to a horizon of decades rather than centuries. Read plainly, that horizon is satisfied by the actual fall of Jerusalem some thirty-odd years later, within the lifetime of people who could have heard Jesus teach, part of why some scholars read this specific verse as evidence that the saying, at least, was originally only ever about 70 CE, whatever cosmic-sounding imagery now surrounds it in the discourse as it stands." }
'this-generation-alternate-reading' = @{ title="This generation, alternate readings"; body="R. T. France, The Gospel of Matthew, New International Commentary on the New Testament (Grand Rapids: Eerdmans, 2007), commentary on Matthew 24:34; see also D. A. Carson, Matthew, in The Expositor's Bible Commentary, rev. ed., vol. 9 (Grand Rapids: Zondervan, 2010), ad loc. Other commentators note that Greek genea can also carry a qualitative sense, a generation or kind of people rather than strictly a thirty-year cohort, and read Jesus as characterizing a persistently unbelieving type of people across time rather than dating an event to a fixed calendar window; still others propose that verse 34 originally covered only the signs described earlier in the chapter, the Temple's fall included, while the more cosmic imagery just before it addresses a separate and later horizon, letting a near and a far referent coexist inside one discourse without contradiction. No reading commands anything close to consensus, and the crux is argued in earnest across the confessional spectrum of Matthew's modern interpreters." }
'noah-flood-judgment-context' = @{ title="Swept away, the flood sets the valence for taken"; body="Matthew 24:37-39 states plainly what happened to all the people of Noah's generation, who were eating and drinking, marrying and giving in marriage right up until the flood came and swept them all away, language of destruction, not rescue. Verses 40-41 then apply the same two-outcome structure to two men in a field and two women grinding at a mill, one taken and one left, with the flood comparison offered as the passage's own stated interpretive key (so will be the coming of the Son of Man, 24:39). Read inside that frame, the ones swept away by the flood are the ones judged, and the ones left behind, Noah and his household, safe in the ark, are the ones spared, which by the passage's own declared analogy would make taken the fate to dread, not the fate to hope for." }
'taken-judgment-vs-ambiguity-reading' = @{ title="Taken, judgment, or a genuine ambiguity"; body="N. T. Wright, Jesus and the Victory of God, Christian Origins and the Question of God vol. 2 (Minneapolis: Fortress Press, 1996), 365-366. Wright reads the taken of Matthew 24:40-41 as taken away in judgment, consistent with the Noah comparison Jesus has just drawn and with Wright's broader argument that this discourse describes the Temple's coming judgment rather than a removal of believers to safety. Other commentators note the underlying Greek verb, paralambano, to take to oneself, is capable of a rescue sense elsewhere in Matthew's own birth narrative, where Joseph repeatedly takes Mary or the child to safety (1:20, 24; 2:13-14, 20-21), and regard the verse's precise force here as more genuinely ambiguous than either popular reading admits, since the text never states where the taken person goes or why." }
'dispensationalist-rapture-origin' = @{ title="The rapture reading, a nineteenth-century theological framework"; body="Timothy P. Weber, Living in the Shadow of the Second Coming: American Premillennialism, 1875-1925 (Chicago: University of Chicago Press, 1979; rev. ed., Grand Rapids: Zondervan, 1983), chapter 1. Weber traces the popular reading of passages like Matthew 24:40-41 as describing believers suddenly raptured to safety while the unbelieving are left behind for judgment to the dispensationalist theology developed by the Anglo-Irish minister John Nelson Darby within the Plymouth Brethren movement beginning in the 1830s, later popularized across America through the widely circulated Scofield Reference Bible (1909). That reading reverses the valence this chapter's own Noah comparison establishes: in Genesis and in Matthew's stated analogy alike, it is the ones swept away, or taken, who perish, and the ones left behind who survive, making left behind theology a real, checkable case of a comparatively recent theological system reading a passage against the immediate context the passage itself supplies." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
The chapter's opening claim (that the Temple would be leveled so completely that "not one stone will be left here upon another," 24:2) is corroborated at two distinct moments in Josephus's own narrative of the siege, and the two are worth separating, because they carry different implications for how deliberate the destruction actually was.

The first moment is the Temple building's own burning, already dated in this chapter to the tenth or ninth of the Jewish month of Av in 70 CE. Josephus's fuller account of that day complicates any picture of a straightforwardly ordered demolition: he reports that Titus convened his senior officers beforehand specifically to debate the sanctuary's fate, that his own stated preference was to spare it, and that in the chaos of the final assault a soldier flung a firebrand through a window and the fire outran every officer's ability to control it. Josephus states outright that the Temple burned against Caesar's own wishes [[NOTE:josephus-temple-burning-titus-reluctance]]. Whether that reported reluctance is sober reporting or flattery of the emperor under whom Josephus later wrote his history, it is itself a data point: even the historian closest to the events, writing for a patron with every incentive to be exonerated, describes the Temple's actual burning as something that got away from Roman command rather than a plan executed on schedule [[NOTE:josephus-siege-eyewitness]].

The second moment is the deliberate leveling of the wider city that followed, once the Temple mount and the Upper City had both fallen. Here Josephus is unusually precise about what was spared and what was not: three fortress towers, Phasael, Hippicus, and Mariamme, plus a stretch of the western wall, kept standing expressly so a Roman garrison would have a camp and so later visitors could see for themselves how formidable a city Rome had actually subdued. Everything else was leveled so thoroughly that nothing was left to make anyone who came there afterward believe the site had ever been inhabited [[NOTE:josephus-final-razing-not-one-stone]]. Read next to that specific description, "not one stone" is not rhetorical inflation of an ordinary military defeat; it names, close to literally, what Roman siege engineers were capable of doing to a city they intended to erase.

One further Josephus passage is worth adding here on its own terms, independent of anything Matthew or Mark say about signs. Josephus catalogs a set of portents he says preceded the war's final catastrophe: a star shaped like a sword standing over the city for a year, a light shining around the altar at night, a cow giving birth to a lamb inside the Temple court, the massive eastern gate swinging open on its own, phantom armies and chariots seen moving through the clouds at sunset, and, most famously, a priest at Pentecost hearing a voice from within the sanctuary itself saying, "We are departing hence" [[NOTE:josephus-portents-before-fall]]. Josephus offers all of this as sober history, not literary flourish. Whatever one makes of the reports themselves, they show that Jewish witnesses to the same disaster independently reached for the same genre — portents announcing a coming doom — that this very discourse is built from, with no dependence on Matthew's text or on Christian tradition. The general who ordered the city's final leveling, worth noting in passing, was not yet emperor when he commanded the siege, but became Rome's actual ruler within nine years of it [[NOTE:titus-future-emperor-context]].
'@

$beat2 = @'
The near-unanimous post-70 CE dating already noted for this Gospel rests on more than the Temple prediction turning out accurate — it rests on a specific, recognized category of ancient literary composition worth naming precisely, because the name explains what "near-unanimous" actually means as a historical argument rather than as a headcount. Vaticinium ex eventu, Latin for "prophecy from the outcome," describes a text that places a narrator's words inside an earlier time frame, then has that narrator foretell, often with striking specificity, events that had already happened by the time the text was actually written [[NOTE:vaticinium-ex-eventu-device]]. Daniel's own visions supply the textbook case: chapters 10 through 12 forecast the political maneuvering of Alexander's successor kingdoms in accurate, blow-by-blow detail all the way up to the reign of Antiochus IV Epiphanes, then abruptly go wrong describing his death, the seam scholars use to date Daniel's actual composition to the 160s BCE crisis it was written to address, centuries after the Babylonian exile the book claims as its setting.

The standard critical commentary on Matthew applies the same logic to this chapter: the Olivet discourse's close, sustained correspondence to the siege's actual course (the encirclement, the refugees, the false messianic claimants, the desecration, the fall) is most economically explained if Matthew's version was written with 70 CE's real outcome already known, sharpening a shorter and more general saying of Jesus into the specific shape the war had actually taken [[NOTE:davies-allison-post-70-majority]].

That is the majority position, not a unanimous one. A real and substantial body of more conservative and evangelical scholarship argues the specificity proves less than critics assume: a first-century Jewish prophet steeped in Israel's own apocalyptic tradition needed no privileged knowledge of the war's actual course to anticipate a Roman siege, given how visibly Judea's political trajectory under Rome was already deteriorating in the decades before it, and this school generally argues for an earlier date for the whole Gospel on separate grounds as well [[NOTE:pre-70-conservative-case]]. This chapter's own summary of the dating question, above, is accurate as a description of where most scholarship actually sits; it is worth being precise that "near" is doing real work in that sentence, and that a genuine, seriously argued minority dissent exists rather than a token one.
'@

$beat3 = @'
Verse 15 names its own source: "when you see the abomination of desolation spoken of by the prophet Daniel, standing in the holy place" (24:15). That phrase did not originate with Jesus or Matthew, and in Daniel's own book it was not a prediction about some unseen future — it described a desecration Daniel's original audience had already lived through. The mainstream critical reading of Daniel identifies the abomination of desolation with a specific, dated, independently attested event: the Seleucid king Antiochus IV Epiphanes's erection of a pagan altar, almost certainly dedicated to Zeus Olympios, directly on top of the Jerusalem Temple's own altar of burnt offering in December of 167 BCE, followed by the sacrifice of pigs and the suppression of Jewish law, the desecration that touched off the Maccabean revolt [[NOTE:daniel-antiochus-original-referent]]. That background, along with the wider Antiochus material and the festival it produced, is developed at length elsewhere in this project's discussion of the Feast of Dedication in the Gospel of John's account of Hanukkah; it needs only the headline here: Daniel's phrase already had one specific, fulfilled, checkable referent, centuries before this chapter has Jesus invoke it.

What this chapter does with that phrase is itself a recognized and well-attested move, not a novelty invented for the Gospel. Second Temple Jewish and early Christian writers routinely reapplied Daniel's abomination of desolation language to whatever fresh threat of Temple desecration their own generation actually faced: to Pompey's forced entry into the Temple's Holy of Holies in 63 BCE, to the emperor Caligula's attempt to install his own statue in the sanctuary around 40 CE, and here, in Matthew 24:15, to a future desecration this chapter's own audience is told to watch for and flee from immediately [[NOTE:prophecy-reapplication-pattern]]. An older, authoritative prophecy, reread and reapplied to a new crisis its original author never had in view, is a documented pattern of how this literature actually worked across several centuries — a different, and more checkable, claim than asking whether the specific future desecration Matthew has in mind ever in fact arrived.
'@

$beat4 = @'
The scope debate already flagged for this discourse (whether it describes only the Jerusalem catastrophe, only a more distant final judgment, or both at once) has a specific linguistic hinge worth isolating on its own: what Matthew's Greek actually means by "this generation" (he genea haute) in the closing claim that "this generation will not pass away until all these things take place" (24:34). Taken at face value, genea in Matthew's own usage elsewhere denotes a cohort of people alive at one time, Jesus's own contemporaries rather than some distant future cohort, and the standard critical commentary on Matthew treats this as the most natural reading of 24:34 on its own grammar, tying the discourse's events to a horizon of decades rather than centuries [[NOTE:this-generation-near-reading]]. Read plainly, that horizon is satisfied by the actual fall of Jerusalem roughly thirty years later, within the lifetime of people who could have heard Jesus teach — part of why some scholars read this specific verse as evidence that the saying, at least, was originally only ever about 70 CE, whatever cosmic-sounding imagery now surrounds it in the discourse as it stands.

That is not the only reading in circulation, and the alternatives deserve to be named rather than waved off. Some commentators note that Greek genea can also carry a qualitative sense, a generation or kind of people rather than strictly a thirty-year cohort, and read Jesus as characterizing a persistently unbelieving type of people across time rather than dating an event to a fixed calendar window; others propose that verse 34 originally covered only the signs described earlier in the chapter, the Temple's fall included, while the more cosmic imagery just before it addresses a separate and later horizon, letting a near and a far referent coexist inside one discourse without contradiction [[NOTE:this-generation-alternate-reading]]. No reading commands anything close to consensus, and the crux is argued in earnest across the confessional spectrum of Matthew's modern interpreters — a genuinely open question, not a solved one dressed up as a debate.
'@

$beat5 = @'
Later in the same discourse, past where this chapter's dating discussion stops, the imagery turns to two people at ordinary daily labor: "then two men will be in the field; one will be taken and one left. Two women will be grinding at the mill; one will be taken and one left" (24:40-41). Twentieth- and twenty-first-century popular Christian culture, the Left Behind novels and films chief among its exports, has made this the proof text for a rapture: believers suddenly removed to safety while the unbelieving remain behind for tribulation. The passage's own stated context argues the opposite valence.

Verses 37 through 39, immediately preceding, spell out the comparison Jesus says the two-men-and-two-women image is illustrating: in Noah's day people were "eating and drinking, marrying and giving in marriage," right up until "the flood came and swept them all away" — and "so will be the coming of the Son of Man." Being swept away by the flood is annihilation, not rescue; the ones spared are the ones left behind, safe with Noah in the ark. By the passage's own declared analogy, then, "taken" parallels the fate of the ones the flood swept away, and "left" parallels the fate of Noah's household who survived [[NOTE:noah-flood-judgment-context]]. One influential scholarly reading of the passage takes "taken" this way explicitly, taken in judgment, consistent with the flood comparison Jesus has just drawn, though other commentators note the underlying Greek verb is capable of a rescue sense elsewhere in Matthew's own birth narrative, and regard the verse's precise force here as more genuinely ambiguous than either popular reading admits, since the text never states where the taken person goes or why [[NOTE:taken-judgment-vs-ambiguity-reading]].

The rapture framework that reverses this reading is not an ancient interpretation recovered from the early church; it is a specific, datable nineteenth-century theological system, developed by the Anglo-Irish minister John Nelson Darby within the Plymouth Brethren movement beginning in the 1830s and popularized across America decades later through the widely circulated Scofield Reference Bible (1909) [[NOTE:dispensationalist-rapture-origin]]. Whatever one makes of the theology on its own terms, it is a real, checkable historical claim that a comparatively recent theological system read this specific passage against the valence its own immediate context establishes: swept away, or taken, as the fate to dread; left behind as the fate of the survivors — rather than recovering an interpretation already present in the text or in the centuries of Christian reading that came before it.
'@

$beats = @($beat1, $beat2, $beat3, $beat4, $beat5)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'VATICINIUM EX EVENTU (PROPHECY AFTER THE FACT)' = "Latin for prophecy from the outcome: a recognized ancient literary device in which a text places words of prediction in the mouth of an earlier narrator or prophet, describing, often in precise detail, events that had already occurred by the time the text was actually composed. Daniel 10-12 is the textbook biblical example, accurate in fine detail through the reign of Antiochus IV Epiphanes, then wrong about his death, the seam scholars use to date Daniel's actual composition to the 160s BCE [[NOTE:vaticinium-ex-eventu-device]]. The majority critical reading of this chapter's Olivet discourse treats it as a New Testament instance of the same device, sharpening a shorter saying of Jesus into the specific shape the Jewish War of 66-70 CE actually took [[NOTE:davies-allison-post-70-majority]]; a minority of conservative and evangelical scholars dissent, arguing the specificity does not require after-the-fact composition [[NOTE:pre-70-conservative-case]]."
'THIS GENERATION (MATTHEW 24:34 INTERPRETIVE CRUX)' = "The closing claim of the Olivet discourse's first half, this generation will not pass away until all these things take place (24:34), turns on what Matthew's Greek genea, generation, means here. A straightforward reading ties the described events to the lifespan of Jesus's own contemporaries, a horizon the actual fall of Jerusalem in 70 CE satisfies precisely [[NOTE:this-generation-near-reading]]. Other readings take genea in a qualitative sense, a generation or kind of people, or propose the verse originally covered only the near-term signs of verses 4-28 while the cosmic imagery of verses 29-31 addresses a separate, later horizon [[NOTE:this-generation-alternate-reading]]. The crux remains genuinely open and is argued in earnest across the confessional spectrum of Matthew's interpreters, not a settled question with an agreed answer."
'ABOMINATION OF DESOLATION (DANIEL''S REAPPLIED PROPHECY)' = "The phrase Jesus cites from the prophet Daniel (24:15) as the sign to flee Judea. In Daniel's own book, the mainstream critical reading identifies the phrase with a specific, already-fulfilled historical event: the Seleucid king Antiochus IV Epiphanes's erection of a pagan altar on the Jerusalem Temple's own altar in December 167 BCE, the desecration that touched off the Maccabean revolt [[NOTE:daniel-antiochus-original-referent]] (see DANIEL; THE TEMPLE). Matthew 24:15 reapplies that older, already-fulfilled prophetic language to a different, future desecration, a documented pattern of Second Temple and early Christian scriptural interpretation, also attested for Pompey's forced entry into the Holy of Holies in 63 BCE and Caligula's attempted statue installation around 40 CE, not a usage invented for this Gospel [[NOTE:prophecy-reapplication-pattern]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum - $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = $maxChapterSortKey
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch24NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "John Nelson Darby" "john-nelson-darby" "character" "Anglo-Irish minister (1800-1882), father of dispensationalism and the pretribulation rapture doctrine, developed within the Plymouth Brethren movement beginning in the 1830s."
Seed-Entity "Vaticinium Ex Eventu" "vaticinium-ex-eventu" "vocabulary" "Latin for prophecy from the outcome: a recognized ancient literary device in which a predictive text is composed after the predicted events have already occurred, central to the Matthew 24 dating debate and to Daniel 10-12."

$conn.Close()
Write-Host "DONE Matthew Chapter 24 depth pass."
