$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"
$Ch19NodeId = [guid]"019FA96D-4B04-7A19-B374-9FFEAD467C48"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
# Hardened: guard against non-numeric leading-token rows (e.g. stray TEST_PROBE_DELETE_ME row) that would
# otherwise crash the template's naive CAST(LEFT(...)) derivation.
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'roman-scourging-flagellation' = @{ title="Scourging before crucifixion, a standard Roman prelude"; body="Raymond E. Brown, The Death of the Messiah: From Gethsemane to the Grave, Anchor Bible Reference Library, 2 vols. (New York: Doubleday, 1994), vol. 1, commentary on the scourging pericope (Mark 15:15 par.; John 19:1). Brown documents Roman flagellation (verberatio) as a standard, brutally severe legal prelude to crucifixion, distinguished from the lighter chastisement (castigatio) sometimes used as a stand-alone punishment; John's placement of the scourging before Pilate's declarations of innocence, rather than immediately before the crucifixion order as in Mark, is widely read as part of a failed attempt by Pilate to satisfy the crowd with a lesser punishment." }
'crown-purple-robe-mock-enthronement' = @{ title="A soldiers' game: crown, robe, mock homage"; body="Raymond E. Brown, The Death of the Messiah, vol. 1, commentary ad loc. John 19:2-3. Brown reads the crown of thorns, purple robe, and mock salute (Hail, King of the Jews) as a soldiers' improvised parody of the ceremonial homage paid to a Roman emperor or client king, a form of occupying-army cruelty attested elsewhere in the ancient world as entertainment at a condemned prisoner's expense rather than a detail invented for this Gospel alone." }
'ecce-homo-johannine-irony' = @{ title='"Behold the man" as Johannine double meaning'; body="C. K. Barrett, The Gospel According to St John: An Introduction with Commentary and Notes on the Greek Text, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 19:5. Barrett reads Pilate's 'Behold the man' (Ecce homo) as characteristic Johannine irony: Pilate intends only to present a beaten, harmless-looking prisoner in order to head off the death penalty, while John's readers are invited to hear a deeper statement about the incarnate Word standing exposed before the world that made him." }
'pilate-historical-portrait' = @{ title="Pilate on trial: the historical governor versus John's Pilate"; body="Helen K. Bond, Pontius Pilate in History and Interpretation, Society for New Testament Studies Monograph Series 100 (Cambridge: Cambridge University Press, 1998), chapters on the Gospel portraits and the non-Christian sources. Bond's study of Pilate across Josephus, Philo, and the Gospels finds a governor in the independent sources (prefect of Judea, 26-36 CE) willing to use lethal force against provincial unrest with little patience for local sensitivities; John's Pilate, by contrast, is unusually legally scrupulous, repeatedly declaring 'I find no guilt in him' and probing questions of truth and kingship, a characterization Bond and other commentators read as more theologically shaped than the blunter Pilate of Josephus and Philo, though not necessarily incompatible with it inside one encounter." }
'power-from-above-theological-reading' = @{ title='"No power over me unless given from above"'; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G. R. Beasley-Murray (Philadelphia: Westminster Press, 1971), commentary ad loc. John 19:11. Bultmann reads Jesus's answer to Pilate, that Pilate's authority over him has been granted from above, as a characteristically Johannine claim that even Rome's coercive power operates only within the larger sovereignty of God's plan, subordinating the political drama on the page to the Gospel's larger theological argument about where authority actually originates." }
'friend-of-caesar-political-charge' = @{ title='"Friend of Caesar" as a real political threat'; body="Raymond E. Brown, The Death of the Messiah, vol. 1, commentary ad loc. John 19:12; see also Helen K. Bond, Pontius Pilate in History and Interpretation (Cambridge: Cambridge University Press, 1998), discussion of Pilate's political vulnerability under Tiberius. Brown and Bond both note that friend of Caesar (amicus Caesaris) was a real, valuable status for a provincial governor to hold, and that a charge of protecting a rival king carried genuine career risk for a prefect already operating without the political cover of his former patron Sejanus, who had fallen from power around 31 CE; the crowd's threat plays on a real vulnerability rather than an empty rhetorical flourish." }
'gabbatha-lithostrotos-location-debate' = @{ title="Gabbatha/Lithostrotos: which pavement, which building?"; body="Shimon Gibson, The Final Days of Jesus: The Archaeology of the Crucifixion (New York: HarperOne, 2009), chapter on the Praetorium and the site of the trial. Gibson surveys the long-running scholarly disagreement over where Pilate's judgment seat on the Stone Pavement (Gabbatha) actually stood, traditionally located at the Antonia Fortress northwest of the Temple Mount but argued by a number of archaeologists and historians, Gibson among them, to more plausibly have been at Herod the Great's palace on the city's western hill, where Pilate is more likely to have resided during festival visits; no inscription or excavated pavement has settled the question conclusively." }
'johannine-passover-chronology-crux' = @{ title="Which day is Passover? The Synoptic-Johannine calendar problem"; body="Raymond E. Brown, The Death of the Messiah, vol. 1, appendix on the chronology of the Passion; see also D. Moody Smith, John, Abingdon New Testament Commentaries (Nashville: Abingdon Press, 1999), introduction on Johannine chronology. John repeatedly places Jesus's crucifixion on the day of preparation for the Passover (19:14, 19:31, 19:42), meaning Jesus dies at the same hour the Passover lambs are being slaughtered in the Temple, one day earlier than the Synoptic Gospels, which depict the Last Supper itself as a Passover meal and the crucifixion as falling on Passover day. Brown and the broader commentary tradition treat this as a genuine, unresolved chronological disagreement between John and the Synoptics rather than a harmonizable detail, one many scholars read as reflecting John's deliberate theological interest in aligning Jesus's death with the Passover lamb." }
'sixth-hour-third-hour-discrepancy' = @{ title="The sixth hour and the third hour: a specific numerical conflict"; body="Bart D. Ehrman, Jesus, Interrupted: Revealing the Hidden Contradictions in the Bible (New York: HarperOne, 2009), chapter on discrepancies in the Passion narratives. Ehrman highlights that John places Pilate's sentencing about the sixth hour (19:14, roughly noon), while Mark states Jesus was already crucified at the third hour (Mark 15:25, roughly nine in the morning), a straightforward numerical conflict between the two Gospels' timelines that proposed harmonizations, a different hour-reckoning system or a copyist's error, have not resolved to universal scholarly agreement." }
'patibulum-cross-carrying-practice' = @{ title="Carrying the crossbeam: Roman practice and a possible discrepancy"; body="Martin Hengel, Crucifixion in the Ancient World and the Folly of the Message of the Cross, trans. John Bowden (Philadelphia: Fortress Press, 1977), chapters on Roman crucifixion procedure. Hengel's landmark study documents that condemned prisoners typically carried only the crossbeam (patibulum), not the full upright, to the execution site, where a permanent post was often already fixed in the ground; John's report that Jesus went out bearing his own cross (19:17) is consistent with this practice, though it stands in apparent tension with the Synoptic tradition (Mark 15:21 par.) that Simon of Cyrene was compelled to carry the cross for Jesus, a divergence commentators explain variously as complementary stages of the march or as an outright discrepancy between traditions." }
'givat-hamivtar-yehohanan-discovery' = @{ title="Givat ha-Mivtar: the only skeleton of a crucified man ever found"; body="Vassilios Tzaferis, 'Crucifixion: The Archaeological Evidence,' Biblical Archaeology Review 11, no. 1 (January/February 1985): 44-53; Joseph Zias and Eliezer Sekeles, 'The Crucified Man from Giv'at ha-Mivtar: A Reappraisal,' Israel Exploration Journal 35 (1985): 22-27. In 1968 an ossuary excavated at Givat ha-Mivtar in northeast Jerusalem was found to contain the remains of a man, identified by the ossuary's own inscription as Yehohanan, whose right heel bone was still pierced by an iron nail bent at the tip, with fragments of olive wood adhering to it, the only direct skeletal evidence of first-century Roman crucifixion recovered anywhere. Zias and Sekeles's 1985 reassessment corrected several details of the excavator's original 1970 reconstruction, including the position of the nail and legs, concluding the nail had been driven sideways through the heel bones from each side rather than through both feet together, and that a small supporting block of wood may have been used to keep the victim from tearing free of the nail under his own weight, physical confirmation, decades after the fact, of crucifixion mechanics the Gospels themselves never describe in technical detail." }
'titulus-inscription-practice' = @{ title="The titulus: Rome's own signage for a crime"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:19-22. Brown situates the placard naming the condemned man's charge (titulus) as attested, documented Roman execution practice, meant to publicize the offense as a deterrent to onlookers rather than a uniquely Christian narrative invention; John alone among the Gospels records the chief priests' objection to its wording (Do not write, The King of the Jews, but, This man said, I am King of the Jews) and Pilate's flat refusal to amend it (What I have written I have written), a small exchange commentators read as a final, deliberately ironic assertion of authority by a governor who has just been maneuvered into an execution he did not want." }
'psalm-22-passion-typology' = @{ title="Psalm 22 under the cross: a shared Passion source-text"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:23-24, and excursus on the use of Psalm 22 across the Passion narratives. Brown traces how Psalm 22, a lament psalm depicting a righteous sufferer surrounded by mockers who divide my garments among them, and for my clothing they cast lots (Psalm 22:18), supplies concrete narrative details across all four Gospels' Passion accounts, the mockery, the wagging heads, the thirst, and here the garment-division, a pattern of scriptural shaping shared with the Synoptics rather than unique to John, which the commentary tradition treats as evidence of the early church reading the crucifixion through an inherited scriptural lens as much as via straightforward eyewitness reportage." }
'women-at-cross-three-or-four-question' = @{ title="Three women or four? A real grammatical fork"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:25, extended note on the identity and number of the women. The Greek of John 19:25 lists, without a clarifying comma in the original manuscripts, his mother, and his mother's sister, Mary the wife of Clopas, and Mary Magdalene, a sequence commentators including Brown read as genuinely ambiguous between three women, if his mother's sister and Mary the wife of Clopas name the same person, and four, if they name two different women; the case for four is often supported by the practical unlikelihood of two sisters sharing the same name, while the case for three notes John's habit of leaving figures unnamed relative to Jesus, here his mother's sister, which would otherwise leave an entirely anonymous fourth woman. No manuscript punctuation or external evidence resolves the question either way." }
'tetelestai-commercial-term' = @{ title='"It is finished": a receipt-word from the papyri'; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 19:30. Keener notes that the Greek verb behind it is finished (tetelestai) is documented in surviving commercial papyri as a technical term written on a bill or receipt to mark a debt as fully paid, a usage some commentators weigh as adding a paid-in-full financial resonance to Jesus's final word alongside its more common reading as a simple declaration of completion; other scholars regard the papyri usage as too widespread and generic a sense of the verb, finished, completed, accomplished, to bear that specific theological weight on its own, so the commercial-receipt reading remains a genuinely disputed emphasis rather than a settled point." }
'crurifragium-leg-breaking-practice' = @{ title="Crurifragium: breaking the legs to end it faster"; body="John Granger Cook, Crucifixion in the Mediterranean World, Wissenschaftliche Untersuchungen zum Neuen Testament 327 (Tubingen: Mohr Siebeck, 2014), chapter on Roman execution procedure and its variants. Cook documents crurifragium, the deliberate breaking of the lower legs, as an attested Roman practice for accelerating death on the cross, removing the victim's ability to push upward on his legs to relieve pressure on the chest and permitting death by asphyxiation within a much shorter span; the Givat ha-Mivtar skeleton itself shows evidence some scholars have read as consistent with a sharp blow to the lower leg, offering rare physical corroboration of a practice John's Gospel describes being applied to the two men crucified alongside Jesus (19:31-32)." }
'blood-and-water-sacramental-reading' = @{ title="Blood and water read sacramentally"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:34-35. Brown traces a patristic-era interpretive tradition, associated with figures including Augustine of Hippo, reading the blood and water flowing from the pierced side as a symbolic double reference to the church's two central sacraments, the blood to the Eucharist, the water to baptism, a reading with deep roots in early Christian exegesis but resting on theological inference rather than anything the Johannine text states explicitly." }
'blood-and-water-medical-reading' = @{ title="Blood and water read medically"; body="William D. Edwards, Wesley J. Gabel, and Floyd E. Hosmer, 'On the Physical Death of Jesus Christ,' Journal of the American Medical Association 255, no. 11 (March 21, 1986): 1455-1463. This frequently cited forensic-medical analysis proposes that the blood and water of John 19:34 is consistent with a post-mortem separation of clotted red-cell blood from serum, or with pleural and pericardial fluid released by a spear thrust into the chest cavity of a body that had already died, a physiological reading offered as a plausible naturalistic account of the detail rather than a claim that it proves the Gospel's report accurate in every particular." }
'fulfillment-citations-exodus-zechariah' = @{ title="Two proof-texts, one moment: the unbroken bones and the pierced one"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:36-37; D. Moody Smith, John, Abingdon New Testament Commentaries (Nashville: Abingdon Press, 1999), commentary on the same verses. John cites two scriptural fulfillments back to back: not a bone of him shall be broken, drawn from the Passover lamb regulations of Exodus 12:46 and Numbers 9:12, explicitly folding Jesus's death into the Passover-lamb typology the Gospel has built since John the Baptist's opening Behold, the Lamb of God (1:29); and they will look on him whom they have pierced, from Zechariah 12:10, read by the Gospel as fulfilled in the spear-thrust itself. Brown and Smith both note the citations function as retrospective theological interpretation layered onto the narrated events rather than predictions verified by neutral, external record." }
'eyewitness-aside-source-criticism' = @{ title="The narrator swears to it: a signed aside"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G. R. Beasley-Murray (Philadelphia: Westminster Press, 1971), commentary ad loc. John 19:35; Urban C. von Wahlde, The Gospel and Letters of John, 3 vols., Eerdmans Critical Commentary (Grand Rapids: Eerdmans, 2010), discussion of the redactional layers around the eyewitness testimony. John 19:35 breaks the narrative's normal third-person voice to insist directly on the reliability of he who saw this, a stylistic interruption source critics including Bultmann and von Wahlde read as marking a seam in the text's composition history, whether an editorial addition by a later hand vouching for a source, or the author's own uncharacteristic direct appeal to eyewitness authority at the Gospel's most theologically weighted moment." }
'joseph-arimathea-nicodemus-historicity' = @{ title="A named, out-of-the-way burial detail"; body="John P. Meier, A Marginal Jew: Rethinking the Historical Jesus, Volume One (New York: Doubleday, 1991), discussion of the criteria of authenticity as applied to the Passion narrative's burial account; see also E. P. Sanders, The Historical Figure of Jesus (London: Penguin Books, 1993), chapter on the crucifixion and burial. Both Meier and Sanders treat the specific, named figure of Joseph of Arimathea, a Sanhedrin member acting counter to his own council's decision, appearing in all four Gospels with independent narrative details, as more plausibly historical than invented outright, on the logic that early Christians had little motive to credit an obscure member of the body that had condemned Jesus with the burial if it were not remembered that way; Nicodemus's added role is unique to John and does not carry the same multiple-Gospel attestation." }
'seventy-five-pounds-royal-spices' = @{ title="A hundred pounds of spice: too much for an ordinary burial"; body="Raymond E. Brown, The Death of the Messiah, vol. 2, commentary ad loc. John 19:39-40. Brown notes that the roughly seventy-five Roman pounds, about a hundred English pounds, of myrrh and aloes John records Nicodemus bringing is an extravagant quantity, far beyond what an ordinary burial required, and points to the parallel of 2 Chronicles 16:14, where a comparably large mass of spices marks the burial of King Asa, a detail Brown and other commentators read as a deliberate honor-signal within the narrative, quietly asserting royal-scale reverence for Jesus's body even as the surrounding scene depicts a rushed, improvised burial before sundown." }
'jewish-burial-archaeology-second-temple' = @{ title="Linen, spices, a rock-cut tomb: burial practice archaeology can confirm"; body="Jodi Magness, Stone and Dung, Oil and Spit: Jewish Daily Life in the Time of Jesus (Grand Rapids: Eerdmans, 2011), chapter on Jewish burial practices in Second Temple-period Jerusalem. Magness's synthesis of excavated Jerusalem-area tombs from this period confirms the basic burial customs John describes, wrapping a body in linen cloths, packing it with aromatic spices, and laying it in a rock-cut chamber tomb, as consistent with well-documented first-century Jewish practice, a point of general, though not universal, scholarly agreement that the burial account's basic mechanics are historically plausible, a separate question from, and not evidence resolving, the later and far more contested claims about the tomb's discovery empty." }
'crucifixion-burial-denial-debate' = @{ title="Did the Romans normally deny crucified bodies burial?"; body="John Dominic Crossan, Jesus: A Revolutionary Biography (San Francisco: HarperSanFrancisco, 1994), chapter on the crucifixion and burial, arguing that Roman practice generally left crucified bodies exposed as a continuing deterrent and that Jesus's body was more likely abandoned or scavenged than buried in a tomb; compare Craig A. Evans, 'Jewish Burial Traditions and the Resurrection of Jesus,' Journal for the Study of the Historical Jesus 3, no. 2 (2005): 233-248, responding that Roman administrators frequently permitted burial of executed provincials, particularly around Jewish festivals, to avoid offending local religious sensibilities the empire otherwise found useful to accommodate. The 1968 Givat ha-Mivtar discovery of Yehohanan's ossuary is itself direct physical evidence that at least one crucified man in Roman Judea did receive a proper Jewish burial, a datum Evans and others cite against Crossan's stronger claim, though it does not by itself settle how common burial was for crucifixion victims generally." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
Pilate has Jesus scourged, and the soldiers make a private game of it: a crown twisted from thorns, a purple robe, mock salutes of "Hail, King of the Jews," and blows to the face (19:1-3). Pilate brings Jesus out before the crowd wearing the crown and robe and announces, "Behold the man" — one more attempt, on top of his earlier declaration "I find no guilt in him" (18:38), to satisfy the crowd with a beaten, humiliated prisoner rather than a corpse. It doesn't work: the chief priests and their officers cry out "Crucify him, crucify him," and when Pilate presses them to explain the charge, they answer that "he has made himself the Son of God" (19:4-7). Rattled, Pilate takes Jesus back inside the Praetorium and asks him privately where he is from; Jesus gives no answer, prompting Pilate to invoke his own authority to release or crucify, which Jesus meets with the claim that Pilate would have no power over him at all had it not been given him "from above" (19:8-11). Pilate tries again to release him, but the crowd shifts to a sharper threat: "If you release this man, you are not Caesar's friend" (19:12).

Start with the scourging itself, because it is not incidental stage-setting. Roman flagellation (verberatio) was a recognized, often lethal legal punishment in its own right, and John's placement of it before Pilate's repeated declarations of innocence, rather than immediately before the execution order the way Mark has it, reads as part of a failed strategy: give the crowd a broken man and let that stand in for a death sentence [[NOTE:roman-scourging-flagellation]]. The crown and robe belong to the same failed strategy, but they are also cruelty with a shape: soldiers dressing a condemned man as a mock king, saluting him, and beating him is documented Roman-army sport at a prisoner's expense elsewhere in the ancient world, not a detail invented for this Gospel alone [[NOTE:crown-purple-robe-mock-enthronement]]. And "Behold the man" carries John's fingerprints doubled over each other: on the surface, Pilate is simply presenting a pitiable, harmless-looking prisoner to head off a death sentence; underneath, John's audience is invited to hear a far larger claim about the incarnate Word standing exposed and unrecognized before the very world that made him [[NOTE:ecce-homo-johannine-irony]].

The charge itself — "he has made himself the Son of God" — lands as new information for Pilate but not for John's reader, who has watched this exact accusation building since the early chapters. What's worth flagging is less the charge's theological content than how differently John's Pilate behaves once he hears it: rattled rather than dismissive, he goes back inside to question Jesus privately about his origin, a scene with no equivalent in the Synoptics. Historians working from the independent, non-Christian sources, chiefly Josephus and Philo, generally describe a Pilate willing to use force bluntly against provincial unrest and with little patience for local religious sensitivity; John's Pilate, legally scrupulous and visibly anxious about a metaphysical question of kingship, is a more textured, arguably more theologically shaped portrait than the governor those outside sources depict, though the two are not necessarily incompatible within a single encounter [[NOTE:pilate-historical-portrait]].

Jesus's answer inside the Praetorium, that Pilate's authority over him has been "given from above," reads, in the commentary tradition, less as a statement about Roman due process than as a Johannine claim that even Rome's coercive power operates only inside the larger sovereignty of God's plan; the political drama on the page is subordinated to a theological argument about where authority actually originates [[NOTE:power-from-above-theological-reading]]. And the crowd's final threat, "not Caesar's friend," plays on something concretely dangerous rather than an empty rhetorical jab: "friend of Caesar" (amicus Caesaris) was a real, valuable status for a Roman governor to hold, and a charge of protecting a rival king carried genuine career risk for a prefect who, with his old patron Sejanus fallen from power around 31 CE, no longer had the political cover he once did [[NOTE:friend-of-caesar-political-charge]].
'@

$beat2 = @'
Worn down, Pilate brings Jesus out one final time and sits down on the judgment seat at a place called the Stone Pavement, Gabbatha in Aramaic — John notes it was the day of preparation for the Passover, about the sixth hour — and presents him to the crowd: "Here is your king" (19:13-14). The chief priests answer "Away with him, away with him, crucify him," and when Pilate presses, "Shall I crucify your King?", they answer with a line that closes off any remaining room for negotiation: "We have no king but Caesar" (19:15). Pilate hands Jesus over to be crucified. The soldiers take him away, and, per John, he goes out "bearing his own cross," to the place called the Place of a Skull, Golgotha, where they crucify him between two other men (19:16-18).

Gabbatha is a real place named with real specificity, and scholars still argue over exactly where it stood. Tradition has long located Pilate's Stone Pavement at the Antonia Fortress, the Roman garrison just northwest of the Temple Mount; a number of archaeologists and historians argue instead for Herod the Great's western palace, a more plausible residence for a Roman prefect visiting the city for a volatile festival, and no excavated pavement or inscription has settled which building John means [[NOTE:gabbatha-lithostrotos-location-debate]]. The timing note attached to it, the day of preparation for the Passover, is one half of a genuine, unresolved chronological problem: John consistently places Jesus's death at the same hour the Passover lambs are being slaughtered in the Temple, a full day earlier than the Synoptic Gospels, where the Last Supper is itself the Passover meal and the crucifixion falls on Passover day proper. Commentators broadly read this as reflecting John's deliberate theological interest in aligning Jesus's death with the Passover lamb rather than a detail harmonizable with the other Gospels' calendar [[NOTE:johannine-passover-chronology-crux]]. The clock John attaches to the moment, "about the sixth hour," creates its own separate, narrower problem: Mark states Jesus was already on the cross by the third hour (Mark 15:25), a straightforward numerical conflict between the two Gospels that proposed harmonizations, different hour-reckoning conventions, or a copying error, have not resolved to any real scholarly consensus [[NOTE:sixth-hour-third-hour-discrepancy]].

"Bearing his own cross" is a detail worth checking against what is actually known of Roman practice. Condemned prisoners typically carried only the crossbeam (the patibulum), not the full upright, which was usually already fixed in the ground at the execution site, so John's image is consistent with documented Roman procedure, even though it stands in apparent tension with the Synoptic tradition, where Simon of Cyrene is compelled to carry the cross for Jesus; commentators variously read the two accounts as complementary stages of the same march, Jesus carrying it out of the Praetorium, Simon taking over partway, or as a genuine discrepancy between independent traditions [[NOTE:patibulum-cross-carrying-practice]].

And crucifixion itself, so central to this chapter and to the entire Gospel tradition, has almost no direct physical evidence behind it anywhere in the ancient world, with one exception. In 1968, an ossuary excavated at Givat ha-Mivtar in Jerusalem was found to hold the remains of a man named, per the ossuary's own inscription, Yehohanan; his right heel bone was still pierced through by a bent iron nail, with fragments of olive wood clinging to it. It is the only skeleton of a crucified man recovered to date, and Joseph Zias and Eliezer Sekeles's 1985 reassessment of the find corrected the original 1970 reconstruction, concluding the nail had been driven sideways through the heel bones rather than through both feet stacked together, likely with a small supporting block of wood involved, physical, first-century confirmation of exactly the kind of mechanics the Gospels themselves never pause to describe [[NOTE:givat-hamivtar-yehohanan-discovery]].
'@

$beat3 = @'
Pilate has a placard made and fixed to the cross — "Jesus of Nazareth, the King of the Jews" — written in Hebrew, Latin, and Greek so that the many Passover pilgrims passing by can read it. The chief priests object to the wording, asking Pilate to change it to read that Jesus only claimed to be King of the Jews; Pilate refuses outright: "What I have written I have written" (19:19-22). Meanwhile the soldiers who crucified him divide his clothes into four shares, one per soldier, but stop at his tunic, woven in one piece with no seam, and instead of tearing it they cast lots for it, "that the Scripture might be fulfilled" — a fulfillment John quotes directly from Psalm 22:18 (19:23-24).

The titulus itself is not a uniquely Christian narrative flourish; posting a placard naming the condemned's crime above his head was standard, attested Roman execution procedure, meant to publicize the offense as a deterrent to onlookers rather than to make any particular theological statement [[NOTE:titulus-inscription-practice]]. What is distinctly John's is the small, pointed exchange over its wording, the chief priests' objection and Pilate's flat refusal to budge, a governor reasserting the only authority he has left after being maneuvered into an execution he plainly did not want.

The garment-division scene folds Jesus's death directly into the language of Psalm 22, a lament psalm whose righteous sufferer is surrounded by mockers who "divide my garments among them, and for my clothing they cast lots." This isn't an isolated borrowing: Psalm 22 supplies concrete narrative details across all four Gospels' Passion accounts, the mockery, the wagging heads, the thirst, and here the garment-division, a pattern of scriptural shaping the commentary tradition treats as evidence that the early church read the crucifixion through an inherited scriptural lens as much as through straightforward eyewitness reportage, a pattern shared across the whole Passion tradition rather than a Johannine invention [[NOTE:psalm-22-passion-typology]].
'@

$beat4 = @'
Standing near the cross, John names a small group of women — Jesus's mother, his mother's sister, Mary the wife of Clopas, and Mary Magdalene — along with the disciple John calls "the one whom he loved." Seeing his mother and that disciple standing together, Jesus tells her, "Woman, behold your son," and tells the disciple, "Behold your mother"; from that hour, John reports, the disciple took her into his own home (19:25-27).

The list of women contains a real, unresolved grammatical puzzle hiding in plain sight. The Greek of 19:25 gives no punctuation to clarify whether "his mother's sister" and "Mary the wife of Clopas" name one and the same woman or two separate women, meaning the verse may describe three women at the cross or four, and nothing in the manuscript tradition or any external source settles which. The case for four rests partly on the practical unlikelihood of two sisters sharing an identical name; the case for three notes that John elsewhere leaves figures unnamed in relation to Jesus, exactly what "his mother's sister" would be if she isn't further identified as Mary the wife of Clopas, which would otherwise leave one woman in the scene entirely anonymous [[NOTE:women-at-cross-three-or-four-question]]. It's a small thing to hang so much unresolved scholarship on, but it's a genuine textual fork, not a settled detail smoothed over by tradition.

The handoff of Mary to the Beloved Disciple is the chapter's quietest scene and also one of its most consequential for how the rest of the Gospel reads: whatever the historical kernel behind it, the moment functions narratively as Jesus, dying, still arranging the care of the people closest to him, tying his mother's story to the unnamed disciple's ongoing witness rather than closing it off at the foot of the cross.
'@

$beat5 = @'
Knowing that everything is now finished, Jesus says, "I thirst," fulfilling Scripture; someone soaks a sponge in sour wine, fixes it to a stalk of hyssop, and holds it to his mouth. Jesus takes the wine and says, "It is finished" — tetelestai — bows his head, and dies (19:28-30). Because it is the day of preparation and the bodies must not remain on the crosses through the Sabbath, the Jewish authorities ask Pilate to have the legs of the crucified broken to hasten death, so the bodies can be taken down. The soldiers break the legs of the two men crucified with Jesus, but finding Jesus already dead, they don't break his; instead, one soldier pierces his side with a spear, and blood and water immediately flow out. The Gospel then breaks its own narrative voice to insist directly that the one who saw this has testified, and that his testimony is true, so that the reader might believe — and cites two fulfillments in a row: "Not one of his bones will be broken," and "They will look on him whom they have pierced" (19:31-37).

Take the leg-breaking first, because it is documented, functional cruelty rather than gratuitous stage direction: crurifragium, the deliberate breaking of the lower legs, was an attested Roman method for accelerating death on the cross, removing a crucified man's ability to push upward on his legs to relieve the pressure crushing his chest, and hastening asphyxiation. The Givat ha-Mivtar skeleton itself carries damage some scholars read as consistent with a sharp blow to the lower leg, rare physical corroboration, from an actual first-century body, of exactly the practice John describes being applied to the two men on either side of Jesus [[NOTE:crurifragium-leg-breaking-practice]].

"It is finished" is worth pausing on for its own linguistic reason. Tetelestai is documented in surviving commercial papyri as a technical term written on bills and receipts to mark a debt as fully paid, and some commentators weigh that specific financial resonance into the theological reading of Jesus's last word; others regard the verb's ordinary sense, finished, completed, accomplished, as far too generic across everyday Greek usage to bear that narrower commercial meaning here, leaving the receipt-language reading a genuinely disputed emphasis rather than an agreed point [[NOTE:tetelestai-commercial-term]].

The spear-thrust and its blood and water is the single most interpretively contested physical detail in the whole Passion narrative, and it deserves the full range of reception rather than a single answer. Read sacramentally, a tradition traced back to patristic writers including Augustine sees blood as pointing to the Eucharist and water to baptism, the two central rites of the early church, symbolically issuing from Christ's side at the moment of death [[NOTE:blood-and-water-sacramental-reading]]. Read medically, a widely cited forensic analysis proposes the detail is consistent with straightforward post-mortem physiology, clotted blood separating from watery serum, or pleural and pericardial fluid released by a chest wound in a body that has already died, offered as a plausible naturalistic account rather than proof the detail happened exactly as described [[NOTE:blood-and-water-medical-reading]]. And read source-critically, some scholars regard the detail as a theologically motivated authorial addition, crafted specifically to set up the Zechariah citation that follows it in the very next verse, not a claim that it's fabricated outright, but that its narrative placement serves the citation as much as the reverse. None of the three readings has driven the others from the field; the honest state of the scholarship is genuine, ongoing plurality.

The narrator's aside, insisting, almost defensively, that "he who saw this has borne witness," is itself a compositional signal worth noticing. The interruption of John's normal third-person narrative voice to vouch directly for a source's reliability is read by source critics as marking a seam in the text's history, whether an editorial hand later vouching for an underlying source, or the Gospel's own author making an uncharacteristically direct appeal to eyewitness authority at the single moment in the whole book that carries the most theological weight [[NOTE:eyewitness-aside-source-criticism]]. The two fulfillment citations that follow work the same way the garment-lots did earlier: "not a bone of him shall be broken" draws on the Passover lamb regulations of Exodus 12:46 and Numbers 9:12, explicitly folding Jesus's death into the lamb typology the Gospel has built since John the Baptist's opening words, "Behold, the Lamb of God"; and "they will look on him whom they have pierced" comes from Zechariah 12:10. Both function as retrospective theological interpretation laid over the narrated events, tying together threads the Gospel has been weaving since its first chapter rather than predictions independently verifiable from outside the text [[NOTE:fulfillment-citations-exodus-zechariah]].
'@

$beat6 = @'
Joseph of Arimathea, a secret disciple of Jesus "for fear of the Jews," asks Pilate for the body and, once granted permission, takes it down. Nicodemus — the Pharisee who first came to Jesus by night back in chapter 3 — joins him, bringing a mixture of myrrh and aloes weighing about seventy-five Roman pounds. Together they wrap the body in linen cloths packed with the spices, following Jewish burial custom, and lay it in a new tomb in a nearby garden, a tomb in which no one had yet been buried, choosing it because the Jewish day of preparation was ending and there was no time to prepare anything further (19:38-42).

Joseph himself is a genuinely interesting figure to weigh historically, because all four Gospels report him independently, each with slightly different narrative details, and each remembering him as a member of the very council that had condemned Jesus. Scholars applying the standard criteria of authenticity to the historical Jesus tradition generally read this kind of embarrassing, awkward-for-the-early-church detail, crediting the burial to an insider of the body that killed Jesus, as more plausibly remembered than invented; Nicodemus's added role here, by contrast, is unique to John and doesn't carry that same cross-Gospel attestation [[NOTE:joseph-arimathea-nicodemus-historicity]].

The spice quantity is easy to read past, but seventy-five Roman pounds, roughly a hundred English pounds, of myrrh and aloes is an extravagant amount for a hurried burial, not a modest one. Commentators regularly point to the parallel of 2 Chronicles 16:14, where a comparably enormous mass of spices marks the burial of King Asa, and read the quantity here as a deliberate honor-signal woven into the narrative, a quiet assertion of royal-scale reverence for Jesus's body even while the scene itself describes a rushed, improvised burial against a closing deadline [[NOTE:seventy-five-pounds-royal-spices]].

On the broader mechanics, linen wrapping, packed spices, a rock-cut chamber tomb, archaeology of Second Temple-period Jerusalem tombs confirms this as standard, well-documented Jewish burial practice for the period, a point of fairly general scholarly agreement that the burial account's basic mechanics are historically plausible [[NOTE:jewish-burial-archaeology-second-temple]]. That basic plausibility is a separate question from, and doesn't resolve, whether Roman crucifixion victims typically received any burial at all: one strand of scholarship has argued Rome generally left crucified bodies exposed as an ongoing deterrent, meaning Jesus's body was more likely abandoned than tombed; the counter-argument holds that Roman administrators frequently allowed burial of executed provincials, particularly around sensitive festival periods, to avoid needlessly inflaming local religious feeling the empire otherwise found useful to accommodate. The Givat ha-Mivtar discovery of Yehohanan's own ossuary is itself direct physical evidence that at least one crucified man in Roman Judea did receive a proper Jewish burial, a data point weighed against the stronger denial-of-burial claim, though it doesn't settle how routine burial was for crucifixion victims generally, and none of it bears on the separate, far more contested question of what happened at this tomb three days later [[NOTE:crucifixion-burial-denial-debate]].
'@

$beats = @($beat1, $beat2, $beat3, $beat4, $beat5, $beat6)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'PONTIUS PILATE' = "Roman prefect of Judea (26-36 CE) who presides over Jesus's trial in this chapter, repeatedly declaring ``I find no guilt in him'' (18:38; 19:4, 6) while ultimately handing him over for crucifixion under pressure from the chief priests and the crowd's ``not Caesar's friend'' threat (19:12). Non-Christian sources (Josephus, Philo) attest Pilate as a real historical prefect; John's portrait of him as unusually scrupulous and reluctant is weighed by scholars against a blunter, more forceful Pilate in those independent sources [[NOTE:pilate-historical-portrait]]."
'GABBATHA (THE STONE PAVEMENT)' = "The Aramaic name John gives (19:13) to the raised platform, Greek Lithostrotos, ``Stone Pavement,'' where Pilate takes his judgment seat before handing Jesus over for crucifixion. Its exact location is disputed: tradition has long placed it at the Antonia Fortress north of the Temple Mount, but a number of archaeologists argue Herod's western palace is the more likely site of Pilate's residence during festival visits, and no pavement or inscription yet excavated settles the question [[NOTE:gabbatha-lithostrotos-location-debate]]."
'GOLGOTHA' = "The execution site outside Jerusalem's walls where Jesus is crucified (19:17-18), named by John using its Aramaic form, ``Place of a Skull,'' alongside the Latin-derived English ``Calvary.'' Its precise location is not established by the Gospel text itself, and modern tradition divides between the Church of the Holy Sepulchre site, venerated since at least the fourth century, and the nineteenth-century ``Garden Tomb'' identification promoted by British visitors; both lie outside the traditional line of the first-century city wall, the one archaeological requirement a site of Roman execution needs to satisfy."
'TITULUS (THE CROSS INSCRIPTION)' = "The placard reading ``Jesus of Nazareth, King of the Jews,'' written in Hebrew, Latin, and Greek and fixed above Jesus on the cross (19:19-22), naming the charge for which he was executed. Attaching a titulus naming the condemned's crime was standard, attested Roman execution practice; only John records the chief priests' objection to the wording and Pilate's refusal to change it [[NOTE:titulus-inscription-practice]]."
'SEAMLESS TUNIC AND CASTING LOTS (PSALM 22:18)' = "The soldiers divide Jesus's outer garments among themselves but cast lots for his one-piece, seamless undertunic rather than tear it (19:23-24), an act John reads as a direct fulfillment of Psalm 22:18, ``they divide my garments among them, and for my clothing they cast lots.'' Psalm 22 supplies concrete details across all four Gospels' Passion narratives, a pattern of scriptural shaping shared with the Synoptics rather than unique to John [[NOTE:psalm-22-passion-typology]]."
'MARY MAGDALENE' = "One of the women named standing at the foot of the cross (19:25) and, in the following chapter, the first witness to the empty tomb. Her presence here is attested independently across all four canonical Passion narratives, among the most widely agreed-upon historical details of the crucifixion account."
'MARY, WIFE OF CLOPAS (THE THREE-OR-FOUR-WOMEN QUESTION)' = "Named in John 19:25 in a list, ``his mother, and his mother's sister, Mary the wife of Clopas, and Mary Magdalene,'' whose Greek grammar does not make clear whether ``his mother's sister'' and ``Mary the wife of Clopas'' name one woman or two, leaving genuine, unresolved scholarly disagreement over whether three or four women stood at the cross [[NOTE:women-at-cross-three-or-four-question]]. Clopas himself appears by name only here and, in a debated connection, at Luke 24:18, where a disciple named Cleopas meets the risen Jesus on the Emmaus road."
'TETELESTAI (``IT IS FINISHED'')' = "Jesus's final recorded word from the cross in John (19:30), a single Greek verb, tetelestai, that can carry both a plain sense of completion and a documented commercial sense, attested in papyri, of a debt marked fully paid, a linguistic double meaning some commentators weigh into the line's theological resonance and others regard as reading too much into an otherwise ordinary word [[NOTE:tetelestai-commercial-term]]."
'BLOOD AND WATER (JOHN 19:34)' = "The detail, unique to John, that a soldier's spear thrust into Jesus's side produces an immediate flow of ``blood and water,'' followed by the narrator's own emphatic insistence on having witnessed it (19:34-35). The image has drawn a genuinely wide range of readings: sacramental, blood as Eucharist, water as baptism, a tradition traced to patristic writers including Augustine; medical and forensic, consistent with post-mortem fluid separation or chest-cavity effusion after death; and source-critical, a theologically motivated detail crafted to set up the Zechariah 12:10 citation that follows [[NOTE:blood-and-water-sacramental-reading]] [[NOTE:blood-and-water-medical-reading]]."
'GIVAT HA-MIVTAR AND YEHOHANAN' = "A burial site in northeast Jerusalem where a 1968 excavation recovered an ossuary inscribed with the name Yehohanan, containing the remains of a man crucified in the first century CE, his heel bone still pierced by an iron nail. It remains the only direct skeletal evidence of Roman crucifixion ever recovered, and Joseph Zias and Eliezer Sekeles's 1985 reassessment of the find corrected and refined the original 1970 analysis of the nail's placement and the practice's mechanics [[NOTE:givat-hamivtar-yehohanan-discovery]]."
'JOSEPH OF ARIMATHEA' = "A wealthy member of the Sanhedrin and, per John, a secret disciple of Jesus ``for fear of the Jews,'' who requests Jesus's body from Pilate after the crucifixion and provides the tomb for his burial (19:38). He appears independently in all four Gospels, a pattern of multiple attestation scholars weigh as evidence he is more plausibly a remembered historical figure than an invented one [[NOTE:joseph-arimathea-nicodemus-historicity]]."
'CRUCIFIXION (ROMAN PENAL PRACTICE)' = "The Roman method of execution applied to Jesus and, per John, to two others crucified alongside him (19:18, 32), typically reserved for slaves, provincials, and those convicted of sedition rather than for Roman citizens. Direct archaeological evidence of the practice is exceptionally rare; the 1968 Givat ha-Mivtar find of Yehohanan's pierced heel bone is the only skeletal confirmation yet recovered, and it corroborates several mechanical details, nail placement, a supporting wood block, and deliberate leg-breaking to hasten death, that ancient literary sources describe only in passing [[NOTE:givat-hamivtar-yehohanan-discovery]] [[NOTE:crurifragium-leg-breaking-practice]]."
'MYRRH AND ALOES (BURIAL SPICES)' = "The burial preparation Nicodemus brings, roughly seventy-five Roman pounds, about a hundred English pounds, of myrrh mixed with aloes, used to pack the linen wrappings around Jesus's body per Jewish burial custom (19:39-40). Commentators widely read the sheer quantity, comparable to the spices marking King Asa's royal burial in 2 Chronicles 16:14, as a deliberate signal of honor rather than a routine, realistic burial detail [[NOTE:seventy-five-pounds-royal-spices]]."
'THE GARDEN TOMB (JOHN 19:41-42)' = "The ``new tomb, in which no one had yet been laid,'' located in a garden near the crucifixion site, where Joseph and Nicodemus lay Jesus's body because of the nearness of the Jewish day of preparation (19:41-42). Rock-cut chamber tombs of exactly this kind, along with linen wrapping and spice-packing, are well attested by archaeology of Second Temple-period Jerusalem, a point of general scholarly agreement about the burial account's basic historical plausibility, distinct from the separate and far more contested question of the resurrection appearances that follow [[NOTE:jewish-burial-archaeology-second-temple]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum — $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch19NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
# Entity-catalog cross-check (gspl_entity_catalog.txt) confirmed every named entity this chapter
# touches already exists in the GSPL universe: Jesus, Pontius Pilate, Pilate's wife, Joseph of
# Arimathea, Nicodemus, Mary (mother of Jesus), Mary Magdalene, Mary mother of James and Joseph /
# Mary mother of James and Joses, Clopas, Golgotha, Gabbatha (the Stone Pavement), Garden Tomb,
# Yehohanan, Praetorium (Pilate's headquarters), and The disciple whom Jesus loved. No new
# Seed-Entity calls are required for this chapter.

$conn.Close()
Write-Host "DONE Chapter 19."
