$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"
$Ch14NodeId = [guid]"019FA96C-F81C-74B1-82C9-81F4FB8F94B1"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'farewell-discourse-genre' = @{ title="A dying figure's last instructions: the farewell-discourse form"; body="George R. Beasley-Murray, John, Word Biblical Commentary vol. 36, 2nd ed. (Nashville: Thomas Nelson, 1999), introductory discussion preceding John 13-17. Beasley-Murray situates John 13:31-16:33 within the well-attested ancient literary genre of the farewell discourse or testament, a departing figure's final address to followers, combining predictions of the speaker's departure, moral exhortation, comfort, and promises for the future, and compares it to Jacob's deathbed address to his sons (Genesis 49) and Moses's farewell addresses in Deuteronomy 31-33, alongside extra-biblical Jewish testament literature (such as the Testaments of the Twelve Patriarchs); on this reading the discourse's shape is a recognized compositional form rather than a stenographic transcript of one evening's table talk." }
'raymond-brown-farewell-discourse-structure' = @{ title="Two discourses spliced into one: Brown on the doubling in John 13-17"; body="Raymond E. Brown, The Gospel According to John XIII-XXI, Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), Introduction to the Book of Glory, section on the Last Discourse. Brown argues the material now printed as one continuous farewell discourse (John 13:31-17:26) shows signs of being composed from at least two originally separate discourses on similar themes, joined by a Johannine editor, with John 14 forming a complete, self-contained unit that already covers departure, the Father's house, the Paraclete, and peace before chapters 15-16 largely repeat the same themes in different language." }
'mone-mansions-rooms-translation' = @{ title="Mansions or rooms? A translation history"; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), commentary ad loc. John 14:2. Carson traces the King James Version's rendering many mansions to the Latin Vulgate's mansiones, a term for a traveler's overnight lodging-station along a road, itself a translation of the Greek monai; modern translations (moving to rooms or dwelling places) reflect both a better sense of the Greek term's ordinary domestic meaning and the recognition that mansion in modern English implies a grandeur foreign to the original image of simple lodging within a household." }
'mone-wordplay-14-2-14-23' = @{ title="The same word twice: a wordplay invisible in translation"; body="Raymond E. Brown, The Gospel According to John XIII-XXI, Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 14:2 and 14:23. Brown notes that the noun mone (room, dwelling place) in 14:2 and the verb form of the same root, rendered make our home, in 14:23, where Jesus says that he and the Father will come and make their mone with the one who loves him, share a root that most English translations render with entirely different words in the two verses, obscuring a deliberate verbal echo: the Father's house Jesus is going to prepare turns out, by 14:23, to already be constituted wherever the believer keeps Jesus's word." }
'seven-i-am-sayings-series' = @{ title="The seventh of seven: I am predicate sayings across John"; body="C.K. Barrett, The Gospel According to St John, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 14:6, with cross-reference to the series as a whole (6:35, 8:12, 10:7/10:9, 10:11/10:14, 11:25, 15:1/15:5). Barrett catalogs I am the way, and the truth, and the life as the last of John's seven classic predicated ego eimi sayings, each pairing the divine self-identification formula with a concrete image drawn from ordinary life: bread of life, light of the world, the gate and door of the sheep, the good shepherd, the resurrection and the life, and the vine." }
'paraclete-translation-range' = @{ title="Advocate, Helper, Comforter, Counselor: one Greek word, four English guesses"; body="Raymond E. Brown, The Gospel According to John XIII-XXI, Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), Appendix V, The Paraclete. Brown surveys the range of English renderings attempted for parakletos (Advocate, Helper, Comforter, Counselor, Intercessor) and shows that no single English word captures both halves of the term's semantic range: its ordinary Greek legal and forensic sense, one called alongside to speak in someone's defense as in a courtroom, and its broader sense of a supportive presence summoned to one's aid, a genuine and still-debated ambiguity in the underlying word rather than a translation failure." }
'bultmann-paraclete-background' = @{ title="Bultmann and the search for the Paraclete's background"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971; German original 1941), commentary ad loc. John 14:16-17. Bultmann argued the Paraclete figure draws on a pre-Christian Gnostic redeemer-myth background, a proposed source since widely contested; the ongoing scholarly disagreement over where the concept originates, whether Jewish legal advocate imagery, Hellenistic-Jewish wisdom traditions, or an originally independent Johannine figure later identified with the Spirit, is itself evidence that the term's precise conceptual ancestry remains unsettled rather than resolved." }
'betz-paraclete-legal-background' = @{ title="Betz and the case for a courtroom Paraclete"; body="Otto Betz, Der Paraklet: Fuersprecher im haeretischen Spaetjudentum, im Johannes-Evangelium und in neu gefundenen gnostischen Schriften, Arbeiten zur Geschichte des Spaetjudentums und Urchristentums 2 (Leiden: E.J. Brill, 1963); discussed in survey form in Raymond E. Brown's Appendix V cited above. Betz argued for a specifically Jewish legal-advocate background to the Paraclete concept, rooted in intercessory and forensic-defender imagery from late Second Temple Judaism, standing as one major position in the still-open debate over the term's origin that Brown and Bultmann represent from different angles." }
'paraclete-another-helper-14-16' = @{ title="Another Helper: what another implies"; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), commentary ad loc. John 14:16. Carson notes the Greek allon, another, in the promise that the Father will give the disciples another Helper specifies another of the same kind rather than a different kind, implying Jesus himself has already been functioning as a parakletos for the disciples, and that the Spirit's coming role continues rather than replaces that function." }
'world-cannot-receive-spirit-14-17' = @{ title="Whom the world cannot receive: an epistemic claim, not a numeric one"; body="George R. Beasley-Murray, John, Word Biblical Commentary vol. 36, 2nd ed. (Nashville: Thomas Nelson, 1999), commentary ad loc. John 14:17. Beasley-Murray reads the statement that the world cannot receive the Spirit because it neither sees him nor knows him as a claim about the world's own incapacity to perceive, rather than a claim that the Spirit's presence or activity is spatially restricted to believers alone, consistent with the Johannine pattern, already introduced around John 3 and John 9, of the world functioning as a term for a mode of unbelieving perception rather than a strict headcount of humanity." }
'not-leave-you-orphans-14-18' = @{ title="I will not leave you as orphans: adoption and household language"; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 14:18. Keener notes the Greek orphanous, translated orphans, sometimes desolate or comfortless, draws on household and legal language for children left without a father's protection and provision, framing the promised return of Jesus's presence, through the Spirit and through Jesus's own promised coming, in terms of a family relationship rather than a purely doctrinal abstraction." }
'greater-works-14-12' = @{ title="Greater works than these: scope and referent debated"; body="D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), commentary ad loc. John 14:12. Carson surveys competing readings of the promise that whoever believes will do greater works than these, ranging from a claim about a greater quantity or geographic spread of comparable miracles, to a qualitative claim about the greater works of gospel proclamation and conversion made possible after Pentecost, noting that the Gospel itself does not resolve which sense is intended, and commentators remain divided." }
'peace-not-as-world-gives-14-27' = @{ title="Not as the world gives: a diplomatic idiom repurposed"; body="Craig S. Keener, The Gospel of John: A Commentary, 2 vols. (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 14:27. Keener notes that peace, shalom in Hebrew and eirene in Greek, functioned as a conventional parting greeting in both Jewish and Greco-Roman farewell custom, so Jesus's line contrasts not the word itself but its ordinary, often merely formal use as a departure pleasantry against the substantive, lasting peace he claims to leave, a rhetorical move recognizable to any first-century audience familiar with the standard farewell idiom." }
'judas-not-iscariot-identity' = @{ title="Judas, not Iscariot: a name John alone preserves, and a harmonization that will not close"; body="Raymond E. Brown, The Gospel According to John XIII-XXI, Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 14:22. Brown notes that this speaker, identified only by the negative disambiguation Judas, not Iscariot, appears under this description nowhere else in the New Testament; the two Synoptic apostle lists that include a second Judas figure disagree with each other on the name itself, since Luke 6:16 and Acts 1:13 list Judas son of James, while Mark 3:18 and Matthew 10:3 list Thaddaeus in the parallel list position, and Brown treats the equation of John's Judas with either Synoptic figure as a plausible but strictly unprovable harmonization rather than an established identification." }
'thaddaeus-judas-son-of-james-variant' = @{ title="Thaddaeus or Judas son of James: the apostle-list discrepancy itself"; body="Textual apparatus of the Nestle-Aland Novum Testamentum Graece, ad loc. Mark 3:18 and Luke 6:16, and the parallel synoptic-apostle-list comparison in standard critical commentary. Some manuscripts of Matthew 10:3 read Lebbaeus, or Lebbaeus called Thaddaeus, in place of Thaddaeus alone, compounding rather than resolving the name variation across the four apostle lists in Matthew, Mark, Luke, and Acts; mainstream text-critical scholarship treats the divergence as evidence of independent naming traditions for one of the less-prominent Twelve rather than scribal error alone." }
'johannine-displacement-ch14-cross-reference' = @{ title="Rise, let us go from here: the seam revisited"; body="Raymond E. Brown, The Gospel According to John XIII-XXI, Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), Introduction to the Book of Glory, section on displacement theories; cross-referencing the Johannine displacement discussion first introduced at John 5-6 (this volume's earlier note and glossary entry, The Johannine Displacement Theory, John 5-6). Brown treats John 14:31's closing command, Rise, let us go from here, followed immediately by two further chapters of uninterrupted discourse in chapters 15-16 before anyone actually moves, as the single clearest internal seam in the Gospel, and surveys the standard proposed resolutions: a deliberate authorial pause with no intervening travel, an added supplementary discourse inserted by a later hand or the evangelist himself without smoothing the seam, or an accidental leaf-displacement in an early exemplar; no single solution commands full scholarly consensus, but the seam's existence itself is not disputed." }
'bultmann-displacement-theory-ch14' = @{ title="Bultmann and the case for physical page displacement"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971; German original 1941), commentary ad loc. John 14:31 and discussion of the Last Discourse's compositional history. Bultmann was among the most influential proponents of reading the abrupt closing command as evidence of an actual physical disordering of pages or sheets in an early exemplar of the Gospel, with chapters 15-17 and other passages originally belonging in a different sequence before a copyist reassembled a damaged manuscript in the wrong order; the theory remains a minority position today but continues to be engaged seriously in the commentary tradition as one live explanation among several for the seam." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
"Let not your hearts be troubled," Jesus tells the eleven at table. "Believe in God; believe also in me. In my Father's house are many rooms... I go to prepare a place for you." Thomas objects that they don't even know where he's going, so how can they know the way; Jesus answers, "I am the way, and the truth, and the life. No one comes to the Father except through me." Philip pushes further — "Lord, show us the Father, and it is enough for us" — and Jesus answers that whoever has seen him has seen the Father, since the Father is in him and he in the Father, and promises that whoever believes in him will do the works he has been doing, and "greater works than these," because he is going to the Father (14:1-14).

Before any single line gets picked apart, it is worth naming what kind of speech this is. John 14 opens a long block of farewell material (13:31-16:33) that runs, almost without interruption, until Jesus and the disciples finally leave the room in chapter 18. Mainstream historical-critical scholarship reads this whole block against a well-attested ancient literary form: the farewell discourse, or testament, a dying or departing figure's final address to those left behind, typically combining a prediction of departure, moral exhortation, comfort for those who remain, and promises about the future. Jacob's blessing of his twelve sons before his death (Genesis 49) and Moses's three farewell addresses before Israel enters the land (Deuteronomy 31-33) both follow the same basic shape, as does a body of extra-biblical Jewish testament literature written in the centuries around Jesus's life [[NOTE:farewell-discourse-genre]]. Reading John 14-17 as an instance of this recognized genre does not mean none of it happened; it means the material's shape, its length, its repetitions, its formal structure, is doing literary work of its own, not simply recording one evening's conversation verbatim. Raymond Brown goes further, arguing on internal grounds that John 14 already reads as a complete, self-contained farewell discourse in its own right, departure, the Father's house, the disciples' unbelief and questions, the Paraclete promise, and a parting gift of peace, all present and resolved by its final verse, with chapters 15-16 substantially reworking the same themes in different language, as though two versions of a similar discourse had been preserved and joined [[NOTE:raymond-brown-farewell-discourse-structure]].

"In my Father's house are many mansions," the King James Version has it, and generations of English readers have pictured something like grand estates. The Greek word behind "mansions," mone, is considerably more modest: it names a lodging-place, a room to stay in, the sort of overnight stopping-point a traveler might use along a road. The King James translators followed the Latin Vulgate's mansiones, itself a term for exactly that kind of traveler's way-station rather than anything like the modern English sense of a stately home; most modern translations now render the word as "rooms" or "dwelling places" instead [[NOTE:mone-mansions-rooms-translation]]. The choice matters for more than accuracy, because John reuses the same root later in this very chapter in a way no English translation preserves: when Jesus promises in 14:23 that he and the Father will come and make their mone, their "home," with the one who loves him and keeps his word, it is the identical root word from 14:2, now describing not a future room prepared in heaven but a present indwelling in the believer. Read side by side in Greek, the Father's house Jesus is going to prepare and the "home" he and the Father make in the believer are the same word twice, a wordplay that simply vanishes once "rooms" in one verse and "make our home" in the other are translated as though they were unrelated ideas [[NOTE:mone-wordplay-14-2-14-23]].

Jesus's answer to Thomas, "I am the way, and the truth, and the life," closes out a series that runs through the whole Gospel: bread of life, light of the world, the door of the sheep, the good shepherd, the resurrection and the life, the true vine, and now this. Each of John's seven great "I am" sayings pairs the same solemn self-identification formula with a concrete, everyday image, and this is the last of the seven, following directly on the heels of Lazarus's raising and its own "I am the resurrection and the life" two chapters earlier [[NOTE:seven-i-am-sayings-series]]. Philip's follow-up request, "show us the Father," gets an answer that pushes the identification further still: to have seen Jesus is to have seen the Father. Whatever else it is doing theologically, the exchange with Philip also raises, without answering, the scope of the promise that immediately follows it: "greater works than these will he do." Read as a claim about a greater quantity or wider geographic reach of the same kinds of miracles Jesus performed, or read instead as a qualitative claim about the different, larger-scale works of gospel proclamation and mass conversion that become possible only after Pentecost, commentators remain divided, and the text itself supplies no tiebreaker [[NOTE:greater-works-14-12]].
'@

$beat2 = @'
Jesus promises to ask the Father for "another Helper," who will be with them forever, "the Spirit of truth, whom the world cannot receive, because it neither sees him nor knows him... you know him, for he dwells with you and will be in you." He promises not to leave them "as orphans": "I will come to you." A little while, and the world will see him no more, but the disciples will see him, because he lives and they will live also; on that day they will know that he is in the Father, and they in him, and he in them. Whoever keeps his commandments loves him, and will be loved by the Father, and Jesus will manifest himself to that person (14:15-21).

The word behind "Helper," parakletos, is the whole chapter's hardest technical term, and it is genuinely, not just superficially, ambiguous. English translations reach for at least four different words trying to cover it: Advocate, Helper, Comforter, Counselor, none of which captures the full range on its own. The underlying Greek carries a legal, forensic sense, one who is called alongside a person to speak in their defense, roughly a courtroom advocate, alongside a broader, less technical sense of a supportive presence summoned to stand by someone in need. That double range is a real feature of the Greek word, not a failure of translation to find the one right English equivalent [[NOTE:paraclete-translation-range]]. Where the concept itself comes from is its own live scholarly argument. Rudolf Bultmann traced the Paraclete to a hypothesized pre-Christian Gnostic redeemer-myth, a background hypothesis that has been extensively challenged since [[NOTE:bultmann-paraclete-background]]; Otto Betz argued instead for specifically Jewish legal-advocate and intercessor traditions from late Second Temple literature [[NOTE:betz-paraclete-legal-background]]. Neither position has retired the other, which is itself worth noting: the term's precise conceptual ancestry remains an open question in the field, not a settled footnote.

The word "another" in "another Helper" is doing real work. In Greek, allon specifies another of the same kind, not a different kind entirely, which implies that Jesus himself has already been functioning in a parakletos role for the disciples all along, and that the promised Spirit continues that same function rather than introducing something categorically new [[NOTE:paraclete-another-helper-14-16]]. And the claim that "the world cannot receive" this Spirit "because it neither sees him nor knows him" reads, on the standard commentary reading, as a claim about the world's incapacity to perceive, consistent with the way "the world" functions throughout this Gospel as shorthand for a mode of unbelieving blindness, rather than a claim that the Spirit's activity is somehow confined only to a small circle of believers and absent everywhere else [[NOTE:world-cannot-receive-spirit-14-17]].

"I will not leave you as orphans" reaches for household and legal language: the Greek orphanous names children left without a father's protection and provision, not simply "sad" or "alone" in a generic sense. Framing the promised return of Jesus's presence, through the Spirit, and through his own promised coming, in terms of a family relationship rather than an abstract doctrinal guarantee is itself a meaningful choice of image, one easily flattened if "orphans" is heard only as a stock English idiom rather than the specific ancient-family claim it is making [[NOTE:not-leave-you-orphans-14-18]].
'@

$beat3 = @'
Judas, "not Iscariot," asks why Jesus intends to manifest himself to the disciples and not to the world. Jesus answers by returning to the theme of love and indwelling: whoever loves him will keep his word, and the Father will love that person, and Father and Son will come and make their home with them; whoever does not love him does not keep his words, which are not Jesus's own but the Father's who sent him. He has told them these things while still with them; the Helper, the Holy Spirit whom the Father will send in his name, will teach them all things and remind them of everything Jesus has said. He leaves them peace, his own peace, "not as the world gives," and tells them not to let their hearts be troubled or afraid; if they loved him, they would rejoice that he goes to the Father, who is greater than he. He has told them before it happens, so that when it happens they may believe. He will not speak much more with them, because the ruler of this world is coming, though he has no claim on Jesus; but so that the world may know that Jesus loves the Father and does as the Father has commanded, he says: "Rise, let us go from here" (14:22-31).

This Judas is worth pausing on for exactly the reason the text pauses on him: he needs the negative disambiguation "not Iscariot" because there were, on the traditional lists, two men named Judas among the Twelve, and this exchange is the only place in the entire New Testament where this second Judas gets a speaking part or any individual description at all [[NOTE:judas-not-iscariot-identity]]. The obvious next question, which Judas from the Synoptic apostle lists is this, turns out not to have a clean answer, because the Synoptic lists do not even agree with each other. Luke's Gospel and Acts both name a "Judas son of James" in the twelfth apostle slot (Luke 6:16; Acts 1:13); Mark and Matthew, listing the same slot, give the name "Thaddaeus" instead (Mark 3:18; Matthew 10:3) [[NOTE:judas-not-iscariot-identity]]. Some manuscripts of Matthew complicate the picture further still, reading "Lebbaeus" or "Lebbaeus called Thaddaeus" in that same position, a third name variant layered onto an already-unsettled list [[NOTE:thaddaeus-judas-son-of-james-variant]]. The natural harmonizing move is to assume all these names refer to one man known by several names or nicknames, and that John's "Judas, not Iscariot" is simply that same figure surfacing under his given name in a fourth source. That is a plausible reading. It is not, on the evidence available, a provable one, and the honest position is to hold the identification loosely rather than assert it as settled fact.

The peace Jesus leaves deserves its own beat of context, because "peace" was not, in the first century, an unusual thing to say on parting. Shalom and its Greek equivalent eirene functioned as conventional farewell greetings in both Jewish and Greco-Roman custom, the ancient equivalent of "take care," which sharpens rather than dilutes what Jesus actually says. The contrast he draws is not peace-versus-no-peace; it is substantive, lasting peace against peace as a merely formal parting pleasantry, a distinction any first-century listener would have caught immediately from the ordinary use of the word they said to each other every time they left a room [[NOTE:peace-not-as-world-gives-14-27]].

And then the chapter's last line creates the single clearest structural problem in the whole Farewell Discourse. "Rise, let us go from here" is exactly what a group of people say when they are about to leave a room, and then nobody leaves. Chapters 15 and 16 continue for two more full chapters of uninterrupted discourse, revisiting many of the same themes, the vine and the branches, the Paraclete again, the disciples' sorrow turning to joy, the world's hatred, before Jesus finally prays in chapter 17 and the group actually departs for the garden in chapter 18. This is the same Johannine displacement question already raised around the seam between chapters 5 and 6 earlier in this volume, and 14:31 is widely regarded as the strongest single piece of evidence for it, a seam so visible that its existence is not seriously disputed, even though the explanation for it remains contested [[NOTE:johannine-displacement-ch14-cross-reference]]. Rudolf Bultmann pressed the displacement theory hardest, proposing that an early manuscript's physical pages were disordered and a later copyist reassembled them in the wrong sequence, so that chapters now numbered 15-17 originally stood elsewhere in the text [[NOTE:bultmann-displacement-theory-ch14]]. Others read it more simply as a deliberate authorial pause, a group that decides to leave, keeps talking anyway, and only moves once the following material has run its course, or as a supplementary discourse added later by the evangelist or a later editor without smoothing over the seam it created. No explanation commands full consensus. What is uncontested is the seam itself: read in sequence, John 14 ends like the meal is over, and then the meal, somehow, is not.
'@

$beats = @($beat1, $beat2, $beat3)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'FAREWELL DISCOURSE (TESTAMENT LITERATURE)' = "A recognized ancient literary genre in which a dying or departing figure delivers a final address to followers or family, combining a prediction of departure, moral exhortation, comfort, and promises for the future. John 13:31-16:33 is read by mainstream commentary as an instance of this form, comparable to Jacob's farewell to his sons (Genesis 49), Moses's farewell addresses (Deuteronomy 31-33), and extra-biblical Jewish testament literature such as the Testaments of the Twelve Patriarchs [[NOTE:farewell-discourse-genre]]. Raymond Brown further argues John 14 forms a complete discourse in its own right, with chapters 15-16 substantially reworking the same themes [[NOTE:raymond-brown-farewell-discourse-structure]]."
'MONE (ROOMS/DWELLING PLACES, JOHN 14:2)' = "The Greek noun behind the King James Version's rendering many mansions, in John 14:2, more accurately translated rooms or dwelling places, an ordinary lodging-place, not a grand estate; the KJV's word choice descends from the Latin Vulgate's mansiones, itself a term for a traveler's overnight way-station [[NOTE:mone-mansions-rooms-translation]]. The same root recurs at 14:23, where Jesus promises that he and the Father will make their mone, their home, with the one who loves him, a verbal echo largely invisible once the two verses are translated with unrelated English words [[NOTE:mone-wordplay-14-2-14-23]]."
'EGO EIMI (I AM) SAYINGS, SEVENTH (JOHN 14:6)' = "I am the way, and the truth, and the life (14:6) is catalogued as the last of John's seven classic predicated ego eimi sayings, following bread of life (6:35), light of the world (8:12), the door and gate of the sheep (10:7, 10:9), the good shepherd (10:11, 10:14), the resurrection and the life (11:25), and the true vine (15:1, 15:5); each pairs the divine self-identification formula with a concrete image from ordinary life [[NOTE:seven-i-am-sayings-series]]."
'PARACLETE (HOLY SPIRIT)' = "The term (Greek parakletos) Jesus uses for the Spirit he promises the Father will send (14:16-17, 14:26), rendered variously across English translations as Advocate, Helper, Comforter, or Counselor, no single English word captures both the term's legal and forensic sense, one called alongside to speak in a person's defense, and its broader sense of a supportive presence summoned to aid someone, a genuine ambiguity in the underlying Greek rather than a translation shortfall [[NOTE:paraclete-translation-range]]. The term's precise conceptual background remains debated: Rudolf Bultmann proposed a pre-Christian Gnostic redeemer-myth origin [[NOTE:bultmann-paraclete-background]], while Otto Betz argued for a Jewish legal-advocate and intercessor background [[NOTE:betz-paraclete-legal-background]]; neither position has become consensus. The Greek allon, another, in the phrase another Helper specifies another of the same kind, implying Jesus has already been functioning as a parakletos for the disciples [[NOTE:paraclete-another-helper-14-16]]. This is the Paraclete's first appearance in the Gospel; the term recurs in John 15-16."
'JUDAS (NOT ISCARIOT)' = "A member of the Twelve who asks Jesus, at the Last Supper, why he will manifest himself to the disciples and not to the world (14:22), his only appearance anywhere in the New Testament with a speaking part or individual description, identified solely by the negative disambiguation distinguishing him from Judas Iscariot. Whether he should be equated with the Judas son of James of Luke 6:16/Acts 1:13 or the Thaddaeus of Mark 3:18/Matthew 10:3 is a genuine, unresolved harmonization question, since the Synoptic apostle lists disagree with each other on the name in that list position [[NOTE:judas-not-iscariot-identity]] [[NOTE:thaddaeus-judas-son-of-james-variant]]."
'THE JOHANNINE DISPLACEMENT THEORY, JOHN 14:31 SEAM' = "John 14:31's closing command, Rise, let us go from here, followed immediately by two further chapters of uninterrupted discourse in chapters 15-16 before the group actually departs in chapter 18, is widely regarded as the clearest internal seam in the entire Farewell Discourse, cross-referencing the displacement theory first introduced at the John 5-6 seam (see THE JOHANNINE DISPLACEMENT THEORY (JOHN 5-6)) [[NOTE:johannine-displacement-ch14-cross-reference]]. Rudolf Bultmann proposed the seam reflects an actual physical disordering of pages in an early manuscript [[NOTE:bultmann-displacement-theory-ch14]]; the theory remains a minority position but is seriously engaged in the commentary tradition, alongside readings of the line as a deliberate authorial pause or a later, imperfectly integrated addition."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum — $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch14NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "Judas (not Iscariot)" "judas-not-iscariot" "character" "Member of the Twelve who asks Jesus why he will manifest himself to the disciples and not the world (John 14:22); his only NT appearance with individual description. Possibly identical to Judas son of James (Luke 6:16/Acts 1:13) or Thaddaeus (Mark 3:18/Matthew 10:3), an unresolved harmonization question."
Seed-Entity "Paraclete (Holy Spirit)" "paraclete-holy-spirit" "vocabulary" "The Greek parakletos, first promised in John 14:16-17 as another Helper, rendered Advocate, Helper, Comforter, or Counselor in various translations; a genuinely ambiguous term spanning legal-advocate and supportive-presence senses, background debated among Bultmann, Brown, and Betz."

$conn.Close()
Write-Host "DONE Chapter 14."
