$ErrorActionPreference = 'Stop'   # fail loudly: a SqlException is otherwise non-terminating
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA96D-7D48-75E0-9BD9-2190171276DC"
$GlossaryNodeId = [guid]"019FA96D-8DD0-70E4-8D98-34AC48833B7E"
$Ch13NodeId = [guid]"019FA96C-E75D-71B3-9D66-C851C19E9A7B"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC'")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA96D-8DD0-70E4-8D98-34AC48833B7E'")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA96D-7D48-75E0-9BD9-2190171276DC' AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'foot-washing-ancient-custom' = @{ title="Whose job was it to wash feet?"; body="John Christopher Thomas, Footwashing in John 13 and the Johannine Community, Journal for the Study of the New Testament Supplement Series 61 (Sheffield: Sheffield Academic Press, 1991), chapter 1. Thomas surveys the ancient evidence and finds foot washing was ordinarily a servant's task performed for arriving guests (compare Genesis 18:4; 19:2; 24:32; 43:24), one a host without slaves might instead leave the guest to do alone, or that a wife or child might perform for a husband or father within a household; Abigail's self-description as ready to ``wash the feet of the servants of my lord'' (1 Samuel 25:41) marks it as an act of extreme self-abasement, and its omission is noted as a conspicuous social slight in Luke 7:44. A teacher washing his own disciples' feet inverted every expectation the custom carried." }
'talmud-disciple-exemption' = @{ title="The one task even a disciple was excused from"; body="Babylonian Talmud, Ketubbot 96a (Soncino Talmud translation), discussed in relation to John 13 by, among others, Craig S. Keener, The Gospel of John: A Commentary, vol. 2 (Peabody, MA: Hendrickson Publishers, 2003), commentary ad loc. John 13:1-11. The passage holds that a disciple should perform for his teacher every service a slave performs for a master, with one exception: untying the master's sandal. Keener and other commentators cite this as evidence that foot-related menial service sat at the very bottom of the status ladder, low enough that even the disciple-teacher relationship, itself modeled on slavery, drew the line there; Jesus's act in John 13 does not merely lower him to a servant's task but to one beneath what his own students would have owed him." }
'no-share-with-me-sacramental-reading' = @{ title="A sacramental echo in 'no share with me'?"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971; German original 1941), commentary on John 13:6-11; compare Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. Bultmann reads Jesus's warning that Peter ``has no share with me'' unless washed as carrying baptismal overtones layered onto the hospitality scene, part of his broader source-critical reconstruction of an ecclesiastical redactor's hand in the Fourth Gospel. Brown weighs the same possibility more cautiously, noting the verse also works as a plain statement about communion with Jesus in this specific moment without requiring a later sacramental gloss; the two readings are not mutually exclusive, and mainstream commentary remains divided on how much weight the sacramental reading deserves." }
'except-for-the-feet-textual-variant' = @{ title="A short reading with a long theological reach"; body="Bruce M. Metzger, A Textual Commentary on the Greek New Testament, 2nd ed. (Stuttgart: Deutsche Bibelgesellschaft / United Bible Societies, 1994), commentary on John 13:10. Several early witnesses lack the clause ``except for his feet'' in Jesus's statement that the one who has bathed needs no further washing ``except for his feet, but is completely clean'' (13:10), leaving only a flatter reading in which the bathed person needs no washing at all. The shorter reading, if original, removes any suggestion that foot washing itself carries continuing ritual necessity for someone already clean; the modern critical preference for the longer reading is a committee judgment call rather than manuscript near-unanimity, and the variant is regularly cited in textual-criticism literature as a case where a single clause carries real theological weight." }
'servant-not-greater-floating-saying' = @{ title="A maxim that travels"; body="John P. Meier, A Marginal Jew: Rethinking the Historical Jesus, Volume One: The Roots of the Problem and the Person (New York: Doubleday, 1991), discussion of the criteria of authenticity, especially multiple attestation. Jesus's closing maxim that ``a servant is not greater than his master, nor is a messenger greater than the one who sent him'' (John 13:16) has independent parallels in Matthew 10:24 and Luke 6:40, each embedded in a different literary setting. Meier's standard treatment of multiple attestation treats sayings that surface this way, detached from any single narrative frame, as strong candidates for genuinely early, freely circulating tradition, distinct from material that reads as one evangelist's own composition." }
'beloved-disciple-first-appearance' = @{ title="A figure who appears here for the first time"; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 13:23; R. Alan Culpepper, Anatomy of the Fourth Gospel: A Study in Literary Design (Philadelphia: Fortress Press, 1983), chapter on characterization. John 13:23 introduces, without warning or explanation, ``one of his disciples, whom Jesus loved,'' reclining close enough to lean back against him at table. No figure answering to this exact description appears anywhere in Mark, Matthew, or Luke; the Beloved Disciple is a distinctly Johannine character who will recur at the cross, the empty tomb, and the epilogue, and whose identity the Gospel itself never states outright. Culpepper reads the figure's anonymity as a deliberate narrative strategy, inviting the reader into the position of ideal disciple rather than settling a historical question." }
'beloved-disciple-traditional-zebedee' = @{ title="The traditional answer: John son of Zebedee"; body="Irenaeus of Lyons, Against Heresies, Book 3, chapter 1, section 1 (as preserved in Eusebius, Ecclesiastical History, Book 5, chapter 8); D.A. Carson, The Gospel According to John, Pillar New Testament Commentary (Grand Rapids: Eerdmans, 1991), introduction and commentary ad loc. John 13:23; 21:20-24. Church tradition from at least the late second century identifies the Beloved Disciple with the apostle John son of Zebedee, author of the Fourth Gospel by the same tradition. Carson defends this identification as still the best-fitting reading of the internal evidence, particularly the Beloved Disciple's consistent proximity to Peter across scenes where the Synoptics place John son of Zebedee alongside Peter as well; the identification remains the majority position in more conservative commentary traditions, though it rests on external patristic testimony rather than anything the Fourth Gospel states by name." }
'beloved-disciple-modern-alternatives' = @{ title="Two live alternatives: Lazarus, or an idealized figure"; body="J.N. Sanders, ``Those Whom Jesus Loved (St John xi. 5),'' New Testament Studies 1, no. 1 (1954): 29-41; Floyd V. Filson, ``Who Was the Beloved Disciple?'' Journal of Biblical Literature 68, no. 2 (1949): 83-88; compare Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971), and Raymond E. Brown, The Community of the Beloved Disciple (New York: Paulist Press, 1979). Sanders and Filson both note that Lazarus is the one named individual the Fourth Gospel explicitly says Jesus loved (John 11:3, 11:5), making him a real candidate for the unnamed disciple introduced here. Bultmann, in a different direction, reads the Beloved Disciple as at least partly an idealized, representative figure of faithful discipleship rather than a straightforwardly historical individual; Brown's later, more cautious book treats the figure's precise identity as an open question the Gospel itself may not intend to answer, a shift from the more traditional leanings of his earlier Anchor Bible commentary volumes. No consensus exists among mainstream scholars on any of these three positions." }
'reclining-banquet-custom' = @{ title="How a supper guest ends up leaning on the host"; body="Dennis E. Smith, From Symposium to Eucharist: The Banquet in the Early Christian World (Minneapolis: Fortress Press, 2003), chapters on Greco-Roman and Jewish banquet customs. Diners at a formal first-century meal reclined on their left side on couches or cushions arranged around a low table, propped on the left elbow with feet extended away from the table, which physically allowed the person occupying the position immediately to a host's right to lean back and rest against the host's chest, exactly as the Beloved Disciple does to ask Jesus a question at Peter's signal (John 13:23-25). Smith's study also situates the host's gesture of handing a specially dipped piece of bread to a particular guest, as Jesus does to identify Judas (13:26), as a recognized mark of honor within the same banquet conventions, which sharpens the irony of the same gesture marking out the betrayer." }
'satan-enters-judas-timing-diff' = @{ title="When did Satan enter Judas? Luke and John disagree on timing"; body="C.K. Barrett, The Gospel According to St John, 2nd ed. (Philadelphia: Westminster Press, 1978), commentary ad loc. John 13:27; compare Luke 22:3. Luke places Satan's entry into Judas earlier, before the meal, immediately motivating his approach to the chief priests to arrange the betrayal (Luke 22:3-6). John instead places it during the meal itself, at the precise moment Judas takes the dipped morsel from Jesus's hand (John 13:27). Barrett notes the two Gospels agree on the theological claim that satanic influence, not mere greed or disillusionment, drives Judas's act, but disagree on exactly when in the sequence of events that influence takes hold, a small but genuine divergence between two independent tellings of the same betrayal." }
'it-was-night-symbolic-literal' = @{ title="And it was night — a plain fact and a loaded one"; body="R. Alan Culpepper, Anatomy of the Fourth Gospel: A Study in Literary Design (Philadelphia: Fortress Press, 1983), chapter on the Gospel's use of light and darkness imagery; compare Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), commentary ad loc. John 13:30. The bare statement that closes Judas's exit, ``and it was night,'' works first as ordinary narrative bookkeeping: an evening meal has run late. Culpepper reads it simultaneously as a deliberate return to the Fourth Gospel's recurring light and darkness dualism, in which walking in darkness signals separation from Jesus who is the light of the world (compare John 3:19-21; 9:4-5; 11:9-10); Judas's literal departure into the dark street doubles, in Culpepper's reading, as his narrative departure from the light altogether. The two readings are not competing options requiring a choice between them; John's prose regularly works on both levels at once." }
'new-commandment-in-group-ethic' = @{ title="A new commandment, and a narrower one"; body="Wayne A. Meeks, ``The Man from Heaven in Johannine Sectarianism,'' Journal of Biblical Literature 91, no. 1 (1972): 44-72. Jesus's command to ``love one another as I have loved you'' (John 13:34-35) has no direct Synoptic parallel, and its scope is explicitly directed inward, toward mutual love among Jesus's own disciples, rather than outward toward neighbor or enemy as in the Synoptic love commands drawn from Leviticus 19:18 (compare Mark 12:31; Matthew 5:44; Luke 6:27). Meeks's classic study of Johannine sectarianism reads this in-group focus as characteristic of a community that had experienced real social separation from the wider synagogue and world, for whom mutual love among insiders functioned as both an ethical command and a badge of communal identity." }
'john-no-institution-words' = @{ title="The Last Supper with no this-is-my-body"; body="Raymond E. Brown, The Gospel According to John (XIII-XXI), Anchor Bible vol. 29A (Garden City, NY: Doubleday & Company, 1970), introduction to the Last Supper narrative, chapters 13-17; D. Moody Smith, John, Abingdon New Testament Commentaries (Nashville: Abingdon Press, 1999), introduction to the Farewell Discourse. All three Synoptic Gospels and Paul's independent tradition in 1 Corinthians 11:23-26 record Jesus identifying the bread and cup as his body and blood at the Last Supper; John's account of the same meal, spanning five chapters, contains no such words at all, replacing them with the foot washing and an extended farewell discourse. Brown and Smith both treat this as one of the most discussed compositional puzzles in Johannine scholarship, precisely because the omission is too large and too consistent across the whole scene to be an oversight; it must reflect a deliberate authorial or editorial choice." }
'bread-of-life-explanation-theory' = @{ title="One theory: the reader already has it, from chapter 6"; body="Raymond E. Brown, The Gospel According to John (I-XII), Anchor Bible vol. 29 (Garden City, NY: Doubleday & Company, 1966), commentary on the Bread of Life discourse, John 6:22-59; Urban C. von Wahlde, The Gospel and Letters of John, vol. 2, Eerdmans Critical Commentary (Grand Rapids: Eerdmans, 2010), commentary ad loc. John 6:51-58. One proposed explanation for the missing institution words is that John has already delivered the Eucharistic teaching earlier, in the Bread of Life discourse's language of eating Jesus's flesh and drinking his blood (John 6:51-58), and considered a second, explicit Last Supper version unnecessary for readers who had followed the Gospel that far. Brown and von Wahlde both note this reading fits John's broader habit of scattering material the Synoptics cluster in one scene across the whole Gospel instead." }
'farewell-discourse-genre-theory' = @{ title="Another theory: a Last Supper rebuilt as a farewell testament"; body="Fernando F. Segovia, The Farewell of the Word: The Johannine Call to Abide (Minneapolis: Fortress Press, 1991), introduction and chapters 1-2. A second explanation reads John 13-17 as a deliberate reworking of Last Supper material into the literary genre of the Jewish farewell testament — a dying or departing figure's final instructions to followers, a form also visible in texts like the Testament of the Twelve Patriarchs. Segovia argues that on this reading, the foot washing supplies the concrete acted-out lesson a testament genre calls for, and the discourse chapters that follow supply the verbal instruction, so that John is not omitting the institution tradition so much as substituting a different governing genre for the whole scene." }
'source-critical-tradition-theory' = @{ title="A third theory: a different underlying source"; body="Rudolf Bultmann, The Gospel of John: A Commentary, trans. G.R. Beasley-Murray (Philadelphia: Westminster Press, 1971), introduction on sources; Urban C. von Wahlde, The Gospel and Letters of John, vol. 1, Eerdmans Critical Commentary (Grand Rapids: Eerdmans, 2010), introduction on compositional history. A third proposed explanation is source-critical rather than literary: Bultmann's reconstruction of the Fourth Gospel's sources posits a Passion tradition distinct from and largely independent of the Synoptic passion source, one that may simply never have carried an institution-of-the-Eucharist unit at all. Von Wahlde's multi-edition theory of John's composition similarly allows that the version of the Last Supper preserved in the Fourth Gospel's earliest layer drew on different underlying material than Mark's, rather than the author of John having deliberately deleted a tradition he otherwise knew." }
'peter-denial-prediction-cross-gospel-agreement' = @{ title="A prediction all four Gospels place at the same supper"; body="Raymond E. Brown, The Death of the Messiah: From Gethsemane to the Grave, vol. 1, Anchor Bible Reference Library (New York: Doubleday, 1994), commentary on the denial predictions. Jesus's prediction that Peter will deny him three times before the rooster crows appears in Mark 14:29-31, Matthew 26:33-35, Luke 22:33-34, and John 13:36-38, in each case placed at the Last Supper on the same night as the arrest that follows. Brown's exhaustive Passion-narrative commentary treats the prediction's consistent placement across all four independent tellings as a point of broad agreement in the tradition, unlike many other Johannine details in this chapter that diverge sharply from the Synoptic sequence; the location and substance of this particular prediction is not a distinctly Johannine peculiarity." }
}

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
John places this scene "before the feast of the Passover," with Jesus knowing that his hour has come to depart from this world to the Father, having loved his own who were in the world and loving them "to the end" (13:1). During supper, with the devil already having put it into the heart of Judas Iscariot to betray him, Jesus rises from the table, lays aside his outer garments, ties a towel around his waist, pours water into a basin, and begins washing the disciples' feet, drying them with the towel. When he reaches Simon Peter, Peter refuses outright — "You shall never wash my feet" — and Jesus answers that unless he washes him, Peter has no share with him; Peter reverses instantly, asking for his hands and head as well. Jesus tells him that one who has bathed needs only to wash his feet, being otherwise completely clean — and adds, pointedly, that not all of them are clean. Once he has finished, dressed again and reclined at the table, Jesus asks whether they understand what he has done, tells them that if their Teacher and Lord has washed their feet, they too ought to wash one another's, and closes with the maxim that a servant is not greater than his master, nor a messenger greater than the one who sent him (13:1-20).

The single most important fact about this scene is not what it symbolizes but what it actually was in its own social world: a genuinely low-status household task, not a devotional flourish [[NOTE:foot-washing-ancient-custom]]. Guests' feet were routinely washed on arrival in ancient hospitality scenes, normally by a servant, sometimes left for the guest to do alone, and in some settings performed by a wife for a husband or a child for a parent — but not normally by a host for his guests, and never by a teacher for his own students.

Rabbinic tradition sharpens exactly how far outside the ordinary Jesus's act falls. A widely cited passage in the Babylonian Talmud holds that a disciple owes his teacher every service a slave owes a master, with one single exception: untying the master's sandal [[NOTE:talmud-disciple-exemption]]. If even a disciple's customary obligation to serve stopped at the foot, Jesus performing full foot washing for his own disciples does not simply lower a teacher to a servant's job; it goes lower than the job description his students themselves would have owed him.

Whether Jesus's warning that Peter has "no share with me" (13:8) unless washed carries a deliberate sacramental undertone is a genuinely open question among commentators [[NOTE:no-share-with-me-sacramental-reading]]. Read one way, it is simply a statement about communion with Jesus in this specific foot-washing moment; read another way, held by some source critics, later ecclesiastical language about baptism has been layered onto the scene. Nothing in the verse itself settles which reading is correct.

A small but real textual crux sits inside Jesus's very next line. Several early manuscripts of John 13:10 lack the clause "except for his feet," leaving only a flatter statement that the bathed person needs no further washing at all [[NOTE:except-for-the-feet-textual-variant]]. Modern critical editions print the longer reading, but the shorter one, if original, would remove any suggestion that the foot washing itself carries continuing ritual necessity for someone already clean — a case where a single clause carries real theological weight.

The closing maxim — "a servant is not greater than his master" (13:16) — is not exclusive to John. Independent versions of the same saying appear in Matthew 10:24 and Luke 6:40, each set inside a different literary context [[NOTE:servant-not-greater-floating-saying]]. A saying that circulates freely enough to be reused by different evangelists in different settings is exactly the kind of material historical-critical scholars weigh as likely early and independently transmitted, distinct from language that reads as one evangelist's own composition.
'@

$beat2 = @'
Troubled in spirit, Jesus states plainly that one of those at the table will betray him; the disciples look at one another, uncertain whom he means. Reclining next to him — close enough to lean back against his chest — is "one of his disciples, whom Jesus loved," introduced here for the first time in the Gospel narrative (13:23). Simon Peter signals to this disciple to ask who it is; leaning back against Jesus, he asks, and Jesus answers that it is the one to whom he will give a piece of dipped bread — and hands it to Judas Iscariot, son of Simon. The instant Judas takes it, Satan enters him, and Jesus tells him to do quickly what he intends to do; none of the others at the table understand the exchange, some assuming Judas has been sent to buy something for the feast or to give something to the poor. Judas takes the bread and goes out at once. It is night (13:21-30).

John 13:23 introduces, without warning or explanation, a disciple identified only as the one "whom Jesus loved" [[NOTE:beloved-disciple-first-appearance]]. No figure fitting this exact description appears anywhere in Mark, Matthew, or Luke; the Beloved Disciple is a distinctly Johannine character who will return at the cross, the empty tomb, and the Gospel's epilogue, and whose actual name this Gospel never once supplies.

The traditional identification, attested in Christian sources from at least the late second century, names him as the apostle John son of Zebedee, the Fourth Gospel's traditional author [[NOTE:beloved-disciple-traditional-zebedee]]. That reading remains the majority position in more conservative commentary, resting chiefly on external church testimony rather than anything the text itself states by name.

Modern scholarship has kept the question genuinely open rather than settled. One proposal identifies the Beloved Disciple with Lazarus of Bethany, the one individual this Gospel explicitly says Jesus loved (11:3, 11:5); another reads him, at least partly, as an idealized figure representing faithful discipleship rather than a single historical person [[NOTE:beloved-disciple-modern-alternatives]]. No consensus exists among mainstream scholars for any of the three positions — Zebedee, Lazarus, or literary ideal — and the honest answer to who he was may be that the Gospel itself does not intend to say.

The physical mechanics of the scene are recoverable from wider banquet custom. First-century diners reclined on their left side on couches around a low table, which let the person positioned nearest a host on his right lean back and rest against the host's chest — exactly the posture that lets the Beloved Disciple ask his question at Peter's unspoken prompting. The same banquet conventions frame the handing of a specially dipped morsel to one particular guest as a recognized mark of honor, which sharpens the irony of that same gesture marking out the betrayer [[NOTE:reclining-banquet-custom]].

One more small divergence is worth noting against the wider tradition. Luke has Satan enter Judas earlier, before the meal, directly motivating his approach to the chief priests (Luke 22:3); John instead places the same satanic entry here, at the exact moment Judas takes the bread from Jesus's hand [[NOTE:satan-enters-judas-timing-diff]]. Both Gospels agree that something more than ordinary greed or disappointment drives Judas's act; they simply disagree on when, in the sequence of the evening, that influence takes hold.

The chapter's last four words — "and it was night" — work on two levels at once. As plain narrative bookkeeping, an evening meal has simply run late. But John's Gospel returns to a light-and-darkness contrast throughout its narrative (compare 3:19-21; 9:4-5; 11:9-10), and Judas's literal walk out into the dark street doubles, on that reading, as a departure from the light altogether [[NOTE:it-was-night-symbolic-literal]]. Nothing about the text requires choosing between the plain and the symbolic reading; John's prose regularly carries both at once.
'@

$beat3 = @'
Now that Judas has gone out, Jesus declares that the Son of Man is glorified, and that God is glorified in him, and will glorify him at once. Addressing the remaining disciples as "little children," he tells them he will be with them only a little longer, and that where he is going they cannot yet come. He gives them "a new commandment": that they love one another as he has loved them, and that this love for one another is how everyone will know they are his disciples (13:31-35). Simon Peter asks where he is going; Jesus answers that Peter cannot follow now, though he will follow later. Peter presses that he is ready to lay down his life for him, and Jesus answers with a flat prediction: before the rooster crows, Peter will have denied him three times (13:36-38).

The command to "love one another as I have loved you" has no direct parallel in the Synoptic Gospels, and its scope is pointedly inward: mutual love among Jesus's own followers, rather than the outward-facing love of neighbor and even enemy commanded in the Synoptic tradition (compare Mark 12:31; Matthew 5:44; Luke 6:27) [[NOTE:new-commandment-in-group-ethic]]. Read against a community that had experienced real separation from the wider synagogue, mutual love among insiders functions here as both an ethical command and a badge of belonging.

Stepping back from this single command to the whole scene it closes, John's Last Supper narrative contains a genuinely striking omission. All three Synoptic Gospels, and Paul's own independent tradition in 1 Corinthians 11:23-26, record Jesus identifying the bread and cup as his body and blood; John's version of the same meal, spanning five full chapters, contains no such words anywhere in it [[NOTE:john-no-institution-words]]. The gap is too large and too consistent across the whole scene to be an oversight — it has to reflect a deliberate choice, and mainstream scholarship has proposed several, not mutually exclusive, explanations for what that choice was.

One explanation holds that John has already delivered the equivalent teaching earlier, in the Bread of Life discourse's language of eating Jesus's flesh and drinking his blood (John 6:51-58), and considered a second, explicit version at the Last Supper unnecessary for a reader who had followed the Gospel that far [[NOTE:bread-of-life-explanation-theory]]. A second reads chapters 13 through 17 as a deliberate reworking of the Last Supper into the Jewish literary genre of a farewell testament, a departing figure's final acted-out lesson and spoken instruction to his followers, with the foot washing supplying the acted lesson and the discourse chapters supplying the instruction in place of the institution words [[NOTE:farewell-discourse-genre-theory]]. A third is source-critical rather than literary: John may simply be drawing on an underlying Passion tradition, independent of the Synoptic source, that never carried an institution-of-the-Eucharist unit to begin with [[NOTE:source-critical-tradition-theory]]. The debate remains one of the most discussed compositional puzzles in Johannine scholarship, and none of the three explanations has won out over the others.

Peter's prediction closes the chapter on more solid cross-Gospel ground than almost anything else in it. The same threefold-denial prediction, at the same supper, on the same night before the arrest, appears independently in Mark 14:29-31, Matthew 26:33-35, and Luke 22:33-34 as well as here [[NOTE:peter-denial-prediction-cross-gospel-agreement]]. Unlike the foot washing, the Beloved Disciple, or the missing institution words — all distinctly Johannine features with no exact Synoptic counterpart — the basic shape and placement of this particular prediction is a point of broad agreement across the whole Gospel tradition, not a peculiarity of John's own telling.
'@

$beats = @($beat1, $beat2, $beat3)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'FOOT WASHING (FIRST-CENTURY CUSTOM)' = "A household hospitality task ordinarily performed by the lowest servant present, or in some settings by a wife for a husband or a child for a parent, but never normally by a teacher for his own students. Jesus performs it himself for the Twelve at the meal before Passover (John 13:1-11), reversing the expected direction of service so thoroughly that even a disciple's customary obligations to a teacher, patterned on a slave's obligations to a master, stopped short of this particular task [[NOTE:foot-washing-ancient-custom]] [[NOTE:talmud-disciple-exemption]]."
'RECLINING AT TABLE (BANQUET CUSTOM)' = "The Greco-Roman and Jewish practice of dining while reclined on the left side on a couch or cushions around a low table, feet extended away from it. The custom explains how the disciple whom Jesus loved could physically lean back against Jesus's chest to ask a whispered question at Peter's signal (John 13:23-25), and frames the honor implied by Jesus handing a specially dipped morsel of bread to a particular guest (13:26) [[NOTE:reclining-banquet-custom]]."
'THE BELOVED DISCIPLE (DISCIPLE WHOM JESUS LOVED)' = "An unnamed disciple, introduced for the first time in this chapter as reclining close enough to Jesus to lean back against him (John 13:23), who recurs at the cross, the empty tomb, and the Gospel's epilogue, and whose identity the Fourth Gospel never states outright [[NOTE:beloved-disciple-first-appearance]]. Church tradition from at least the late second century identifies him with the apostle John son of Zebedee [[NOTE:beloved-disciple-traditional-zebedee]], while modern scholarship has also proposed Lazarus of Bethany, the one individual John explicitly says Jesus loved (11:3, 11:5), or an idealized, representative figure of ideal discipleship rather than a single historical individual [[NOTE:beloved-disciple-modern-alternatives]]."
'SATAN (ENTERS JUDAS, JOHN 13:27)' = "The adversarial figure John says enters Judas Iscariot at the moment he takes the dipped morsel from Jesus's hand (John 13:27), prompting Jesus's command that he do quickly what he intends to do. Luke's Gospel places the same satanic entry earlier, before the meal (Luke 22:3), a small but genuine divergence in timing between two independent tellings of the same betrayal [[NOTE:satan-enters-judas-timing-diff]]."
'NEW COMMANDMENT (JOHN 13:34-35)' = "Jesus's instruction, given immediately after Judas's departure, that his disciples love one another as he has loved them, and that this mutual love is how everyone will recognize them as his disciples (John 13:34-35). The command has no direct Synoptic parallel and is explicitly directed inward, toward the community of Jesus's own followers, in contrast to the Synoptic love commands aimed outward toward neighbor and enemy [[NOTE:new-commandment-in-group-ethic]]."
'THREEFOLD DENIAL PREDICTION (JOHN 13:36-38)' = "Jesus's response to Peter's declaration that he is ready to lay down his life for him: a flat prediction that before the rooster crows, Peter will have denied knowing him three times (John 13:38). The same prediction, placed at the Last Supper on the same night, appears independently in all three Synoptic Gospels as well, making its basic placement a point of agreement across the tradition rather than a distinctly Johannine feature [[NOTE:peter-denial-prediction-cross-gospel-agreement]]."
'ABSENCE OF EUCHARISTIC WORDS IN JOHN''S LAST SUPPER' = "The Fourth Gospel's five-chapter account of Jesus's final meal with his disciples (John 13-17) contains no version of the bread-and-cup words found in all three Synoptic Gospels and in Paul's independent tradition in 1 Corinthians 11:23-26 [[NOTE:john-no-institution-words]]. Proposed explanations include that John assumes readers already have the equivalent teaching from the Bread of Life discourse in chapter 6 [[NOTE:bread-of-life-explanation-theory]], that John has deliberately reworked the scene into the literary genre of a farewell testament built around the foot washing and discourse instead [[NOTE:farewell-discourse-genre-theory]], or that John's Passion tradition simply drew on different underlying source material than the Synoptics did [[NOTE:source-critical-tradition-theory]]."
}

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum — $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
$sortKey = 0.0
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $sortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch13NodeId $id $sortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "Foot Washing (First-Century Custom)" "foot-washing-first-century-custom" "vocabulary" "First-century household hospitality task ordinarily performed by a servant, or by a wife/child within a household, never normally by a teacher for his own students; Jesus performs it for the Twelve in John 13:1-11."
Seed-Entity "Banquet Reclining (Triclinium Custom)" "banquet-reclining-triclinium-custom" "vocabulary" "Greco-Roman/Jewish practice of dining reclined on the left side around a low table, explaining how the Beloved Disciple could lean back against Jesus at the Last Supper (John 13:23-25)."

$conn.Close()
Write-Host "DONE Chapter 13."
