$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

Add-Type -AssemblyName System.Data

$connStr = "Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

function Sha256Hex([string]$text) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text.Trim())
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLower()
}

function Exec-NonQuery([string]$sql, [hashtable]$params) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    foreach ($k in $params.Keys) {
        $cmd.Parameters.AddWithValue("@$k", $params[$k]) | Out-Null
    }
    $cmd.ExecuteNonQuery() | Out-Null
}

function Exec-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    return $cmd.ExecuteScalar()
}

function New-BeatRow([string]$text) {
    $script:MaxNumber = $script:MaxNumber + 1
    $id = [guid]::NewGuid()
    $hash = Sha256Hex $text
    $sql = "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())"
    Exec-NonQuery $sql @{ Id = $id; Text = $text; Hash = $hash; Number = $script:MaxNumber }
    return $id
}

function Add-BeatNode([guid]$nodeId, [guid]$beatId, [double]$sortKey) {
    $sql = "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@NodeId, @BeatId, @SortKey, 1)"
    Exec-NonQuery $sql @{ NodeId = $nodeId; BeatId = $beatId; SortKey = $sortKey }
}

function Seed-Entity([string]$name, [string]$slug, [string]$type, [string]$desc) {
    $exists = Exec-Scalar "SELECT COUNT(*) FROM Entities WHERE UniverseId='0197E9C9-0003-7000-8000-000000000003' AND Slug='$slug'"
    if ($exists -gt 0) { Write-Host "  entity exists, skip: $name"; return }
    $id = [guid]::NewGuid()
    $sql = "INSERT INTO Entities (Id, EntityType, Name, Slug, Status, Description, CreatedAt, ModifiedAt, IsActive, UniverseId) VALUES (@Id, @Type, @Name, @Slug, 'canon', @Desc, SYSUTCDATETIME(), SYSUTCDATETIME(), 1, '0197E9C9-0003-7000-8000-000000000003')"
    Exec-NonQuery $sql @{ Id = $id; Type = $type; Name = $name; Slug = $slug; Desc = $desc }
    Write-Host "  seeded entity: $name"
}

# ---- Live state ----
$script:MaxNumber = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats")
$NotesNodeId = [guid]"019FA01D-FA22-76C6-976C-3EA4F4D54A14"
$GlossaryNodeId = [guid]"019FA026-3758-7A57-AF65-EC1DB4303EF3"
$Ch27NodeId = [guid]"019FA076-F16B-74ED-8384-66A7A6DE8052"

$maxNoteSortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA01D-FA22-76C6-976C-3EA4F4D54A14' AND bn.IsEnabled=1")
$maxGlossarySortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA026-3758-7A57-AF65-EC1DB4303EF3' AND bn.IsEnabled=1")
$maxCh27SortKey = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0) FROM BeatNodes bn WHERE bn.NodeId='019FA076-F16B-74ED-8384-66A7A6DE8052' AND bn.IsEnabled=1")
$maxNoteNumber = [int](Exec-Scalar "SELECT ISNULL(MAX(CAST(LEFT(b.Text, CHARINDEX(' ',b.Text)-1) AS INT)),0) FROM BeatNodes bn JOIN Beats b ON bn.BeatId=b.Id WHERE bn.NodeId='019FA01D-FA22-76C6-976C-3EA4F4D54A14' AND bn.IsEnabled=1 AND CHARINDEX(' ', b.Text) > 1 AND LEFT(b.Text, CHARINDEX(' ',b.Text)-1) NOT LIKE '%[^0-9]%'")

Write-Host "Starting: MaxNumber=$script:MaxNumber MaxNoteSortKey=$maxNoteSortKey MaxNoteNumber=$maxNoteNumber MaxGlossarySortKey=$maxGlossarySortKey MaxCh27SortKey=$maxCh27SortKey"

# ---- Notes (slug -> title/body) in order ----
$notes = [ordered]@{
'jeremiah-canonical-order-theory' = @{ title="A fourth explanation: Jeremiah headed the Prophets"; body="W. D. Davies and Dale C. Allison Jr., A Critical and Exegetical Commentary on the Gospel According to Saint Matthew, International Critical Commentary, vol. 3 (Edinburgh: T&T Clark, 1997), commentary ad loc. Matthew 27:9-10, surveying proposed solutions to the Jeremiah attribution problem. One recurring explanation rests on a documented feature of ancient Jewish canonical ordering: a baraita in the Babylonian Talmud, tractate Bava Batra 14b, lists the order of the Latter Prophets as Jeremiah, Ezekiel, Isaiah, and the Twelve — Jeremiah first, not Isaiah as in the order familiar from most modern printed Bibles. On this reading, when a scroll or collection opened with Jeremiah, citing any prophet within that collected unit under Jeremiah's name — the way a modern reader might cite an anthology by its lead-off author — was a live, real convention rather than an invented excuse. The theory does not resolve every open question (it does not, by itself, explain why Matthew draws so heavily on Zechariah's specific wording rather than anything in Jeremiah proper), but it is a genuine, textually grounded convention of the period, not modern special pleading." }
'gundry-jeremiah-typology-dissent' = @{ title="A dissenting reading: not a citation at all, but a reenactment"; body="Robert H. Gundry, Matthew: A Commentary on His Handbook for a Mixed Church under Persecution, 2nd ed. (Grand Rapids, MI: Eerdmans, 1994), commentary ad loc. 27:9-10. Gundry pushes back on the widely held view that Matthew is simply blending a Zechariah quotation with incidental Jeremiah imagery. He argues instead that Matthew treats the potter's-field and purchased-field material in Jeremiah 18-19 and 32 as a pattern the chief priests' own actions reenact — a typological fulfillment rather than a verbal quotation drawn from a specific verse — with Zechariah's wording supplying the actual words attached to that underlying Jeremiah-shaped pattern. However the mechanism is finally judged, Gundry's dissent is a useful reminder that 'fulfilled what was spoken through the prophet Jeremiah' need not commit Matthew to quoting Jeremiah verbatim at all." }
'augustine-jerome-patristic-treatment' = @{ title="The earliest readers already saw the problem"; body="Augustine of Hippo, De Consensu Evangelistarum (The Harmony of the Gospels), Book 3, chapter 7, in Nicene and Post-Nicene Fathers, First Series, vol. 6, ed. Philip Schaff (Buffalo, NY: Christian Literature Publishing Co., 1888); Jerome, Commentary on Matthew, Book 4, on Matthew 27:9-10, trans. Thomas P. Scheck, The Fathers of the Church, vol. 117 (Washington, DC: Catholic University of America Press, 2008). This is not a discrepancy modern criticism discovered. Augustine addressed it directly, noting that some manuscript copies of Matthew known to him lacked the name 'Jeremiah' altogether and read simply 'the prophet' — and judged it more plausible that a copyist had mistakenly supplied the wrong prophet's name to an unmarked citation than that a correct name had later been deliberately removed. Jerome's treatment adds a striking, independently reported detail: he says a member of the Nazarene sect showed him a Hebrew-language writing attributed to Jeremiah that contained wording matching Matthew's quotation almost verbatim, though he does not claim to have verified the document's authenticity or antiquity himself. If accurate, Jerome's report supplies the first concrete evidence for the theory — already floated without a source in this book's own JEREMIAH glossary entry — that Matthew may have had access to a now-lost Jeremiah-attributed text rather than simply erring. No such document survives today for independent checking." }
'papias-judas-death-fragment' = @{ title="A third account: Papias on Judas's body"; body="Papias of Hierapolis, Exposition of the Sayings of the Lord, Book 4 (fragment), preserved in a Matthew catena attributed to Apollinaris of Laodicea, in Bart D. Ehrman, ed. and trans., The Apostolic Fathers, vol. 2, Loeb Classical Library 25 (Cambridge, MA: Harvard University Press, 2003), Papias fragment 3. Writing in the early second century, decades before any Gospel manuscript we can independently check, Papias reports a version of Judas's end that matches neither Matthew's hanging nor Acts's headlong fall in a field: Judas, in this telling, went on living for a time as 'a great example of impiety,' his body swelling to a monstrous size until he could not pass through a space a wagon could pass through, his eyelids swollen shut, his genitals grotesquely enlarged and discharging pus and worms, before he finally died in his own field, which stayed foul-smelling and uninhabited ever after. Scholars dispute exactly where Apollinaris's own paraphrase ends and Papias's original wording resumes, but the fragment's existence is not in dispute: within a century of the events, the church already had a third, independently circulating tradition about how Judas died, layered on top of — not simply choosing between — Matthew's and Luke's." }
'moss-judas-death-harmonization-scholarship' = @{ title="What to do with three accounts, not two"; body="Candida R. Moss, 'A Note on the Death of Judas in Papias,' New Testament Studies 65, no. 3 (2019): 350-361. Moss's close study of the Papias fragment argues that later readers, from Apollinaris onward, have generally used Papias's grotesque swelling to bridge Matthew's hanging and Acts's bursting-open into one continuous sequence — Judas hangs, survives, swells with disease, and finally bursts. She argues this harmonizing use goes beyond what Papias's own words support, and that the fragment may originally have circulated as its own free-standing tradition about Judas's fate, independent of both canonical accounts rather than a bridge between them. Read this way, the honest state of the evidence by the early second century is not two competing accounts of one death but three, and the mainstream critical position — that these represent independent, non-reconcilable traditions about a death none of the New Testament's authors witnessed firsthand — has as much claim on the evidence as any harmonization." }
'bruce-judas-rope-harmonization' = @{ title="The classic harmonization: the rope, not the story, gave way"; body="F. F. Bruce, The Book of the Acts, rev. ed., New International Commentary on the New Testament (Grand Rapids, MI: Eerdmans, 1988), commentary ad loc. Acts 1:18. Bruce lays out the oldest and still most common harmonization attempt directly: Judas hanged himself, exactly as Matthew reports, over a ravine or from a tree on a slope above the field later purchased with his silver; the rope or the branch subsequently gave way, or his body decomposed and fell, striking the ground hard enough to rupture it — producing, without contradiction, the 'falling headlong' and bursting body Acts separately describes. Bruce notes Augustine had already proposed a version of this same reading centuries earlier. The harmonization is coherent and cannot be ruled out, but it is also, on its own terms, an inference built to fit two texts together rather than something either author states; neither Matthew nor Acts describes a rope breaking, and readers who treat the two accounts as simply independent, unreconciled traditions are working from exactly the same evidence Bruce is." }
'deuteronomy-innocent-blood-ritual' = @{ title="The Torah's own hand-washing rite: the unsolved-murder heifer"; body="Jeffrey H. Tigay, Deuteronomy = Devarim: The Traditional Hebrew Text with the New JPS Translation, JPS Torah Commentary (Philadelphia: Jewish Publication Society, 1996), commentary ad loc. Deuteronomy 21:1-9. Deuteronomy 21:6-9 sets out a specific legal ritual for an unsolved murder: when a slain body is found in open country and the killer is unknown, the elders of the nearest town bring a heifer to an unworked valley, break its neck, and wash their hands over the animal while declaring, 'Our hands did not shed this blood, neither did our eyes see it' — a formal, textually commanded act of disclaiming responsibility for bloodshed the community did not commit and could not solve, addressed to God rather than to any human court. Tigay's commentary situates the rite among the Torah's mechanisms for handling bloodguilt that has no identifiable human perpetrator to try. This is not a generic, universal hand-washing gesture available to any culture for any purpose; it is a specific, textually attested Israelite legal-ritual act with a defined occasion (an unsolved killing) and a defined form (elders, a heifer, a declaration of ignorance), on the books centuries before the first century CE." }
'brown-pilate-deuteronomy-link' = @{ title="Borrowing the Torah's gesture, not just any water"; body="Raymond E. Brown, The Death of the Messiah: From Gethsemane to the Grave (New York: Doubleday, 1994), discussion of Matthew 27:24. Brown reads Matthew's staging of Pilate's hand-washing as a deliberate borrowing of this specific Deuteronomic form, not an ad hoc dramatic flourish invented for a Roman governor. The elders of Deuteronomy 21 wash their hands over a heifer to disclaim responsibility for a killing they did not commit and cannot solve; Matthew's Pilate washes his hands before a crowd to disclaim responsibility for a killing he is, in the same scene, actively ordering. Brown treats that inversion as Matthew's own theological point rather than confusion about the custom's meaning: the text borrows Israel's own legal-ritual language of innocence and hands it, pointedly, to the one person in the scene with the actual power to stop the killing and the actual authority that ordered it carried out — precisely the man this book has already established, on independent grounds, as the least plausible person in the empire to have performed a Jewish purity rite (see PONTIUS PILATE)." }
'nostra-aetate-repudiation' = @{ title="Rome's own repudiation of the verse's later use"; body="Pope Paul VI, Nostra Aetate: Declaration on the Relation of the Church to Non-Christian Religions, Second Vatican Council, promulgated October 28, 1965, section 4. The document states plainly: 'What happened in His passion cannot be charged against all the Jews, without distinction, then alive, nor against the Jews of today,' and further states that Jews should not be spoken of 'as rejected or accursed by God.' This is the Catholic Church's own formal, institutional repudiation of the reading of Matthew 27:25 that had, for centuries, been used to justify collective, hereditary blame and violent persecution — issued not by outside critics but by the largest Christian communion on earth, at its highest deliberative level. Other major denominations issued comparable statements in the following decades. The existence of this repudiation does not change what the verse says; it is separate, documented evidence that mainstream Christian institutions, not only historical-critical scholars, now treat the transgenerational-curse reading as a serious historical error with a body count, not a live theological option." }
'brown-matthew-2725-redaction' = @{ title="Whose voice is this crowd's line, really?"; body="Raymond E. Brown, The Death of the Messiah: From Gethsemane to the Grave (New York: Doubleday, 1994), discussion of Matthew 27:25. Brown treats 'his blood be on us and on our children' as unique to Matthew among the four Gospels and reads it as reflecting Matthew's own community's specific, decades-later conflict with a reorganizing Pharisaic Judaism — the same authorship-and-audience situation this book has already established in detail for chapter 23's woes (see notes [318], [319], [320], [321], [322]) — rather than a transcript of an actual crowd's actual words on that actual afternoon. Brown calls it one of the most consequential single verses in the New Testament for its later effects and argues explicitly against reading it as establishing any inherited guilt: in Matthew's own narrative logic, 'children' most plausibly points forward to the generation that would live through Jerusalem's destruction in 70 CE, understood by Matthew as judgment on that generation specifically, not a curse Matthew intends to fall on people not yet born in perpetuity. That reading explains the verse's function inside Matthew's own theology without requiring — or licensing — its later use against Jewish people across the centuries that followed." }
'luz-2725-wirkungsgeschichte' = @{ title="Tracking this verse's reception, the same way as chapter 23's"; body="Ulrich Luz, Matthew 21-28: A Commentary, Hermeneia series, trans. James E. Crouch (Minneapolis: Fortress Press, 2005), commentary ad loc. Matthew 27:25. Luz's history-of-influence (Wirkungsgeschichte) method, already used in this book's treatment of chapter 23's woes, applies with even more force here: he traces this single verse's use across centuries of Christian preaching, art, and eventually state-sponsored violence, as one of the clearest cases in the New Testament of a line's later reception doing damage its own first-century author and audience could not have intended or foreseen. Luz's own conclusion lines up with the mainstream critical position stated plainly elsewhere in this chapter: the verse belongs to Matthew's specific literary and polemical situation, decades after the crucifixion, and its transformation into a doctrine of collective, hereditary Jewish guilt is a later imposition on the text, not a reading the text itself demands." }
'licona-poetic-device-controversy' = @{ title="A modern scholarly controversy over how to read this passage"; body="Michael R. Licona, The Resurrection of Jesus: A New Historiographical Approach (Downers Grove, IL: IVP Academic, 2010), 306-309; Norman L. Geisler, 'An Open Letter to Mike Licona on His View of the Resurrected Saints in Matthew 27:52-53' (2011), published on normangeisler.com. Licona, defending the historicity of Jesus's own resurrection at length in the same book, proposed that Matthew 27:52-53's darkness-earthquake-and-raised-saints passage specifically was more likely a 'poetic device' — apocalyptic imagery signaling the cosmic significance of Jesus's death, in the vein of the special-effects language this book's earlier note on this passage already traces to Ezekiel 37 [20] — rather than a claim of literal historical fact. The proposal produced a sharp, public controversy within conservative evangelical scholarship: Norman Geisler published open letters arguing Licona's reading violated the doctrine of biblical inerrancy, and the dispute contributed to Licona's departure from a teaching position at a Southern Baptist-affiliated institution. The episode is worth citing here not for who was right, but as a striking, close-to-home data point: even scholars strongly committed to defending every other element of the Passion narrative's historicity have found this specific passage, on its own textual and generic merits, to be a live candidate for non-literal reading — from inside the tradition, not only from outside it." }
'setr-licona-roundtable' = @{ title="The scholarly response, weighed in a journal roundtable"; body="'Roundtable Discussion: Michael R. Licona's View of the Matthean Resurrected Saints as Poetic Device,' Southeastern Theological Review 3, no. 1 (Summer 2012). The journal convened multiple evangelical scholars to weigh in directly on the dispute rather than let it play out only in open letters and blog posts; Craig Blomberg's contribution took a notably more moderate position than Geisler's, arguing Licona's proposal was a defensible, if debatable, genre judgment rather than a denial of scriptural authority. The roundtable format itself is evidence the question was treated as a genuine, unsettled interpretive problem inside mainstream evangelical scholarship, not a fringe position needing only to be dismissed." }
}

Write-Host "Prepared $($notes.Count) notes"

# ---- Chapter beats (with [[NOTE:slug]] placeholders) ----
$beat1 = @'
This book's own JEREMIAH glossary entry already lays out the basic shape of the problem at 27:9-10: Matthew names "Jeremiah the prophet" as the source of a prophecy about thirty pieces of silver, a potter, and a field, and those specific words are not in the book of Jeremiah at all — they track Zechariah 11:12-13 closely, with Matthew apparently folding in adjacent potter-and-field imagery from Jeremiah 18-19 and 32 alongside it. That entry surveys the leading modern explanation (a deliberate composite citation, naming only the more prominent prophet) fairly. What is worth adding here, without repeating that ground, is how much further both ancient and modern scholarship has actually gone in trying to explain it.

One recurring modern proposal rests on a real, checkable feature of ancient Jewish canonical ordering rather than guesswork about Matthew's intentions: a baraita preserved in the Babylonian Talmud lists the order of the Latter Prophets as Jeremiah, Ezekiel, Isaiah, and the Twelve — Jeremiah first, not Isaiah as in the sequence familiar from most modern printed Bibles [[NOTE:jeremiah-canonical-order-theory]]. If a scroll or collected unit of prophetic writings opened with Jeremiah, citing anything within that unit "by Jeremiah" would function the way citing an anthology by its lead author still does today. Robert Gundry pushes back on the whole framing, arguing Matthew is not quoting Jeremiah at all but treating the potter-and-field material in Jeremiah 18-19 and 32 as a pattern the chief priests' own actions reenact, with Zechariah supplying the actual wording attached to that pattern [[NOTE:gundry-jeremiah-typology-dissent]] — a genuinely different account of what "fulfilled" is doing in this sentence, not a variation on the composite-citation theory.

None of this is a modern discovery embarrassing an ancient text that never noticed its own problem. Augustine addressed the discrepancy directly, noting that some manuscripts of Matthew known to him omitted "Jeremiah" entirely and read only "the prophet," and judged a copyist's mistaken insertion more likely than a correct name being stripped out later. Jerome adds an independently striking detail: he reports that a member of the Nazarene sect showed him a Hebrew-language writing attributed to Jeremiah containing wording close to Matthew's quotation, though he does not vouch for that document's age or authenticity himself [[NOTE:augustine-jerome-patristic-treatment]]. If accurate, that report is the first concrete evidence — not merely a theoretical possibility — for a genuinely lost, non-canonical "Jeremiah" tradition standing behind Matthew's citation. No such text survives today for anyone to check. The honest state of the evidence, after roughly seventeen centuries of both defenders and critics working on the same nine words, is a real, unresolved textual puzzle with several live, non-equivalent explanations on the table — not a single settled answer and not a simple error either.
'@

$beat2 = @'
Judas's death by hanging (27:3-10), after returning the silver in remorse, is not the New Testament's only account of how he died. Acts 1:18 has him instead falling headlong in a field purchased with that same money, his body bursting open — a scene this book's own JUDAS ISCARIOT glossary entry already states plainly as an unreconciled internal contradiction, the clearest one attached to any member of the Twelve. What that entry does not cover is that the earliest Christian writers were already aware a third account existed, and that the harmonization attempts built to save both canonical texts are themselves worth examining rather than assuming.

Papias of Hierapolis, writing in the early second century — decades closer to the events than any Gospel manuscript that survives for comparison — describes Judas surviving for a time in horrific physical decline: his body swelling grotesquely, his eyelids swollen shut, his genitals enlarged and discharging, before he finally died in his own field, which reportedly stayed foul-smelling and uninhabited long afterward [[NOTE:papias-judas-death-fragment]]. Candida Moss's close modern study of this fragment argues that later readers, from the fourth-century writer who preserved it onward, have generally used Papias's account to stitch Matthew's hanging and Acts's bursting-open into one continuous sequence — but that this harmonizing use may go beyond what Papias's own words actually support, and that his account may originally have circulated as its own independent tradition rather than a bridge between the other two [[NOTE:moss-judas-death-harmonization-scholarship]].

The oldest and still most commonly offered harmonization proposes something simpler: Judas hanged himself exactly as Matthew describes, and the rope or branch later gave way, or the body decomposed and fell, striking the ground hard enough to rupture it — producing, without contradiction, the falling and bursting Acts separately reports. F. F. Bruce lays this reading out directly, noting Augustine had proposed a version of it centuries earlier [[NOTE:bruce-judas-rope-harmonization]]. It is a coherent proposal and cannot be ruled out. It is also, on its own terms, an inference neither Matthew nor Acts states — no rope breaking appears in either text — built to fit two accounts together rather than read from either one directly. Set against Papias's independent third tradition, the honest range of scholarly opinion runs from confident harmonization on one end to treating all three accounts as genuinely separate, non-reconcilable memories of an event none of their authors witnessed on the other, with no way from outside the texts to settle which end is right.
'@

$beat3 = @'
Pilate's hand-washing (27:24) — already flagged elsewhere in this book's Pontius Pilate profile as a Jewish ritual act implausibly placed in a Roman prefect's mouth — has a specific, textually checkable Torah background worth naming rather than treating as a generic universal gesture of innocence. Deuteronomy 21:6-9 sets out a defined legal-ritual procedure for exactly one situation: an unsolved murder, a body found in open country with no known killer. The elders of the nearest town bring a heifer to an unworked valley, break its neck, and wash their hands over the animal while declaring, "Our hands did not shed this blood, neither did our eyes see it" — a formal act of disclaiming responsibility for bloodshed the community did not commit and cannot solve, addressed to God rather than to a human court [[NOTE:deuteronomy-innocent-blood-ritual]].

Matthew's staging borrows that specific form rather than inventing a plausible-sounding Roman custom or reaching for a vague, cross-cultural hand-washing symbol. Raymond Brown reads the borrowing as deliberate and pointed rather than confused: the Deuteronomy ritual exists for elders who genuinely do not know who committed a killing and genuinely cannot stop it; Matthew's Pilate washes his hands before a crowd while actively ordering the very killing he is disclaiming, in the same scene, with the actual Roman authority to prevent it [[NOTE:brown-pilate-deuteronomy-link]]. Whether that inversion reflects Matthew shaping a real detail for maximum theological irony, or inventing the gesture outright to make the same point, isn't something this book's method can settle from the text alone. What is checkable is the background itself: this is not folk custom or vague ritual color, but a specific, dateable piece of Israelite law given a precise new context and audience it was never written for.
'@

$beat4 = @'
"His blood be on us and on our children" (27:25) is unique to Matthew among the four Gospels, and it needs to be handled with the same care, not less, than this book gave chapter 23's sustained polemic against the scribes and Pharisees — the same methodological questions apply, and this book will not re-derive that framework here [[NOTE:brown-matthew-2725-redaction]]. Mainstream historical-critical scholarship reads this line the way it reads that earlier chapter: as Matthew's own community's polemic against a rival, reorganizing Pharisaic Judaism, written decades after the crucifixion into a Gospel whose author and first audience were themselves Jewish, not as a transcript of an actual crowd's actual words on that actual afternoon, and not as a claim about inherited, transgenerational guilt binding people not yet born [[NOTE:luz-2725-wirkungsgeschichte]]. Read inside Matthew's own narrative logic, "our children" most plausibly points forward to the generation that lived through Jerusalem's destruction in 70 CE — judgment on one specific later generation, in Matthew's own theological framework, not a curse aimed at every subsequent generation of Jewish people for all time.

That distinction is not a modern political gloss laid over an old text; it is the same authorship-and-audience question this book has asked, and answered the same way, throughout Matthew. It carries unusual weight here because of what later readers actually did with this verse. For centuries, this line was lifted out of its first-century argument and used to justify collective blame, exclusion, and violence against Jewish communities across the Christian world. The Catholic Church's own formal repudiation of that reading came at the Second Vatican Council: Nostra Aetate states plainly that Christ's passion "cannot be charged against all the Jews, without distinction, then alive, nor against the Jews of today," and that Jews are not to be spoken of as rejected or accursed by God [[NOTE:nostra-aetate-repudiation]]. Other major Christian bodies issued comparable statements in the decades that followed. None of that changes what the Greek text says. It is separate, documented evidence that the near-universal position of both mainstream biblical scholarship and mainstream Christian institutions today is that this verse's historical use as license for collective punishment was a serious, centuries-long error — not a live theological option this book is choosing to avoid, but a reading the evidence and the churches themselves have already rejected.
'@

$beat5 = @'
The earthquake, the splitting rocks, and the tombs opening so that "many bodies of the saints who had fallen asleep were raised" (27:51-53) already received this book's fullest treatment of an unattested miracle claim: no source outside Matthew — not Josephus, not any Roman historian, not the other three Gospels — records any of it, despite a scale that should have been almost impossible to miss in a city the size of first-century Jerusalem [20]. What is worth adding is that this passage has also produced a genuine controversy inside modern scholarship committed to defending the Gospels' historical reliability, not only among historical-critical scholars working from outside that commitment.

In a 2010 book otherwise devoted to a lengthy historical case for Jesus's own resurrection, Michael Licona proposed that this specific passage — the raised saints, distinct from the resurrection he spends the rest of the book defending — most likely functions as a "poetic device," apocalyptic imagery signaling the cosmic weight of Jesus's death rather than a claim of literal historical fact [[NOTE:licona-poetic-device-controversy]]. The proposal set off a sharp public dispute inside conservative evangelical scholarship: Norman Geisler argued in open letters that Licona's reading abandoned biblical inerrancy, and the controversy contributed to Licona's departure from a teaching post at a Southern Baptist-affiliated seminary. A theological journal convened a multi-scholar roundtable to weigh the dispute directly, with contributors like Craig Blomberg taking a considerably more moderate line than Geisler's — treating Licona's proposal as a defensible genre judgment rather than a doctrinal violation [[NOTE:setr-licona-roundtable]]. The episode is worth citing here for what it demonstrates rather than for who was right: even scholars strongly invested in defending the Passion narrative's historicity in every other respect have found this specific passage, on its own textual and generic merits, a live candidate for a non-literal reading — the same conclusion this book's own note on the passage reaches from outside that tradition entirely, arrived at independently from inside it.
'@

$beat6 = @'
One detail in this chapter's opening scenes deserves a pointer rather than a repeated argument. Pilate's offer to release either Jesus or Barabbas under a claimed Passover-pardon custom (27:15-26) rests on an amnesty practice with zero attestation in any surviving Roman or Jewish source outside the Gospels themselves — this book's own Barabbas glossary entry already states that gap plainly, and its fuller discussion, including why the custom's historicity remains a genuinely open and actively debated question among scholars rather than a documented fact, sits in this book's treatment of John's parallel account of the same scene. Nothing in Matthew's version changes that assessment or adds independent evidence either way; it is the same open gap, told a second time.
'@

$beats = @($beat1, $beat2, $beat3, $beat4, $beat5, $beat6)

# ---- Glossary additions (heading -> body) ----
$glossary = [ordered]@{
'THE JEREMIAH ATTRIBUTION: CANONICAL ORDER AND THE CHURCH FATHERS (MATTHEW 27:9-10)' = "Supplementary background to this book's JEREMIAH entry, which already lays out the basic composite-citation problem at 27:9-10. Two further explanations circulate in modern scholarship: that Jeremiah headed a collected unit of the Latter Prophets in some canonical orderings (Babylonian Talmud, Bava Batra 14b), making a citation from within that unit nameable after its lead book [[NOTE:jeremiah-canonical-order-theory]]; and Robert Gundry's dissenting view that Matthew is not quoting Jeremiah at all but presenting the chief priests' actions as a typological reenactment of Jeremiah's potter-and-field narratives, with Zechariah supplying only the wording [[NOTE:gundry-jeremiah-typology-dissent]]. The puzzle is also ancient rather than modern: Augustine and Jerome both addressed it directly in the fourth and fifth centuries, with Jerome reporting — without vouching for it himself — a Hebrew writing attributed to Jeremiah that a Nazarene sect member showed him, containing wording close to Matthew's own [[NOTE:augustine-jerome-patristic-treatment]]."
'PAPIAS ACCOUNT OF JUDAS ISCARIOT DEATH (A THIRD TRADITION)' = "Beyond the contradiction this book's JUDAS ISCARIOT entry already names between Matthew's hanging (27:3-10) and Acts's headlong bursting fall (Acts 1:18), the early-second-century bishop Papias of Hierapolis preserves a third, independently circulating account: Judas surviving for a time in grotesque physical decline before dying, diseased, in his own field [[NOTE:papias-judas-death-fragment]]. Modern scholarship is divided on whether Papias's account was meant to harmonize Matthew and Acts into one sequence or originally stood as its own separate tradition [[NOTE:moss-judas-death-harmonization-scholarship]]; the oldest harmonization proposal on record, a rope or branch giving way after the hanging, is laid out directly by F. F. Bruce, who traces it back to Augustine [[NOTE:bruce-judas-rope-harmonization]]. See PAPIAS OF HIERAPOLIS; JUDAS ISCARIOT."
'INNOCENT-BLOOD HAND-WASHING (DEUTERONOMY 21:6-9)' = "The Torah's own legal-ritual background for Pilate's hand-washing gesture at Matthew 27:24. Deuteronomy 21:6-9 provides a specific procedure for an unsolved murder: the elders of the nearest town break a heifer's neck in an unworked valley and wash their hands over it, declaring their hands did not shed the blood and their eyes did not see it — a formal disclaimer of responsibility for a killing the community cannot solve, addressed to God rather than a court [[NOTE:deuteronomy-innocent-blood-ritual]]. Raymond Brown reads Matthew's Pilate as borrowing this exact form and inverting it: unlike Deuteronomy's elders, Pilate disclaims a killing he is, in the same scene, actively ordering and has the actual power to stop [[NOTE:brown-pilate-deuteronomy-link]]. Distinct from NETILAT YADAYIM (RITUAL HAND-WASHING), which concerns ordinary pre-meal purity practice rather than a legal disclaimer of bloodguilt. See PONTIUS PILATE."
'EARTHQUAKE AND RAISED SAINTS (MATTHEW 27:51-53)' = "The darkness, earthquake, and 'many bodies of the saints' raised at Jesus's death (27:51-53), unique to Matthew among the four Gospels and unattested in any independent contemporary source, already receives this book's fullest historical-critical treatment elsewhere [20]. The passage has also generated a notable controversy inside scholarship committed to defending Gospel historicity: Michael Licona's 2010 proposal that it functions as apocalyptic 'poetic device' rather than literal history drew a sharp public rebuttal from Norman Geisler and cost Licona a teaching post, before a theological journal convened scholars including Craig Blomberg to weigh the dispute directly [[NOTE:licona-poetic-device-controversy]] [[NOTE:setr-licona-roundtable]]."
}

Write-Host "Prepared $($glossary.Count) glossary entries"

# ---- Insert Notes ----
$slugToNumber = @{}
foreach ($slug in $notes.Keys) {
    $n = $notes[$slug]
    $noteNum = $maxNoteNumber + 1
    $maxNoteNumber = $noteNum
    $text = "$noteNum - $($n.title)`n`n$($n.body)"
    $id = New-BeatRow $text
    $maxNoteSortKey += 50
    Add-BeatNode $NotesNodeId $id $maxNoteSortKey
    $slugToNumber[$slug] = $noteNum
}
Write-Host "Inserted $($notes.Count) notes, ending at [$maxNoteNumber]"

# ---- Insert chapter beats with placeholder replacement ----
foreach ($beatText in $beats) {
    $resolved = $beatText
    foreach ($slug in $slugToNumber.Keys) {
        $resolved = $resolved.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $maxCh27SortKey += 100
    $id = New-BeatRow $resolved
    Add-BeatNode $Ch27NodeId $id $maxCh27SortKey
}
Write-Host "Inserted $($beats.Count) chapter beats"

# ---- Insert glossary entries ----
foreach ($heading in $glossary.Keys) {
    $body = $glossary[$heading]
    foreach ($slug in $slugToNumber.Keys) {
        $body = $body.Replace("[[NOTE:$slug]]", "[$($slugToNumber[$slug])]")
    }
    $text = "$heading`n`n$body"
    $id = New-BeatRow $text
    $maxGlossarySortKey += 50
    Add-BeatNode $GlossaryNodeId $id $maxGlossarySortKey
}
Write-Host "Inserted $($glossary.Count) glossary entries"

# ---- Seed new entities ----
Seed-Entity "Eglah Arufah (Innocent-Blood Ritual)" "eglah-arufah-innocent-blood-ritual" "vocabulary" "Deuteronomy 21:6-9's legal-ritual procedure for an unsolved murder: elders break a heifer's neck and wash their hands over it, disclaiming bloodguilt for a killing they cannot solve. Torah background for Pilate's hand-washing at Matthew 27:24."
Seed-Entity "Nostra Aetate" "nostra-aetate" "vocabulary" "Second Vatican Council declaration (1965) explicitly repudiating collective, hereditary Jewish guilt for Christ's death, addressing the historical misuse of Matthew 27:25."

$conn.Close()
Write-Host "DONE Matthew Chapter 27 depth pass."
