$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
Add-Type -AssemblyName System.Data

$conn = New-Object System.Data.SqlClient.SqlConnection("Server=(localdb)\MSSQLLocalDB;Database=StreetSamurai;Trusted_Connection=True;TrustServerCertificate=True;")
$conn.Open()
$em = [char]8212
$dg = [char]176
$GSPL = [guid]"0197E9C9-0003-7000-8000-000000000003"

function Sha256Hex([string]$t) {
    $s = [System.Security.Cryptography.SHA256]::Create()
    return ([System.BitConverter]::ToString($s.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($t.Trim()))) -replace '-','').ToLower()
}
function Exec-NonQuery([string]$sql, [hashtable]$p) {
    $c = $conn.CreateCommand(); $c.CommandText = $sql
    foreach ($k in $p.Keys) { $c.Parameters.AddWithValue("@$k", $p[$k]) | Out-Null }
    $c.ExecuteNonQuery() | Out-Null
}
function Exec-Scalar([string]$sql) { $c = $conn.CreateCommand(); $c.CommandText = $sql; return $c.ExecuteScalar() }
function Next-Note([string]$notes) {
    return [int](Exec-Scalar @"
SELECT ISNULL(MAX(CAST(LEFT(bt.Text, CHARINDEX(' ',bt.Text)-1) AS INT)),0)
FROM BeatNodes bn JOIN Beats bt ON bt.Id=bn.BeatId
WHERE bn.NodeId='$notes' AND bn.IsEnabled=1
  AND CHARINDEX(' ', bt.Text) > 1 AND LEFT(bt.Text, CHARINDEX(' ',bt.Text)-1) NOT LIKE '%[^0-9]%'
"@) + 1
}
function Add-Note([string]$notes, [int]$num, [string]$title, [string]$body) {
    $sk = [double](Exec-Scalar "SELECT ISNULL(MAX(bn.SortKey),0)+50 FROM BeatNodes bn WHERE bn.NodeId='$notes'")
    $bnum = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats") + 1
    $id = [guid]::NewGuid()
    $text = "$num $em $title" + "`n`n" + $body.Trim()
    Exec-NonQuery "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 0, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())" @{ Id = $id; Text = $text; Hash = (Sha256Hex $text); Number = $bnum }
    Exec-NonQuery "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@N, @B, @S, 1)" @{ N = [guid]$notes; B = $id; S = $sk }
}
function Add-GazChapter([string]$bookId, [string]$slugBase, [double]$sortKey, [string]$body) {
    $t = "A Gazetteer of Places"
    $exists = [int](Exec-Scalar "SELECT COUNT(*) FROM Nodes WHERE ParentNodeId='$bookId' AND Title='$t'")
    if ($exists -gt 0) {
        $bid = Exec-Scalar "SELECT TOP 1 bn.BeatId FROM Nodes n JOIN BeatNodes bn ON bn.NodeId=n.Id WHERE n.ParentNodeId='$bookId' AND n.Title='$t' AND bn.IsEnabled=1"
        $tx = [regex]::Replace($body.Trim(), "`n{3,}", ("`n" + "`n")).Trim()
        Exec-NonQuery "UPDATE Beats SET Text=@T, TextHash=@H, UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id" @{ T = $tx; H = (Sha256Hex $tx); Id = [guid]$bid }
        Write-Host "    chapter REWRITTEN ($($tx.Length) chars)"
        return
    }
    $nodeId = [guid]::NewGuid()
    Exec-NonQuery @"
SET QUOTED_IDENTIFIER ON;
INSERT INTO Nodes (Id, Slug, Title, Kind, Status, SortKey, StartedAt, CharsNarrated, CreatedAt, UpdatedAt,
                   NarratedBeatCount, TotalBeatsToNarrate, IsCanon, Version, UniverseId, NodeType, ParentNodeId)
VALUES (@Id, @Slug, @T, 'chapter', 'draft', @SK, SYSUTCDATETIME(), 0, SYSUTCDATETIME(), SYSUTCDATETIME(),
        0, 0, 0, 0, @Uni, 'chapter', @Parent)
"@ @{ Id = $nodeId; Slug = "$slugBase-gazetteer"; T = $t; SK = $sortKey; Uni = $GSPL; Parent = [guid]$bookId }
    $bnum = [int](Exec-Scalar "SELECT MAX(Number) FROM Beats") + 1
    $beatId = [guid]::NewGuid()
    $text = [regex]::Replace($body.Trim(), "`n{3,}", ("`n" + "`n")).Trim()
    Exec-NonQuery "INSERT INTO Beats (Id, Text, TextHash, Act, SceneType, Kind, Number, Stale, WasCorrected, IsChapterStart, Version, EntityStale, CreatedAt, UpdatedAt) VALUES (@Id, @Text, @Hash, 0, 'scene', 'prose', @Number, 0, 0, 1, 0, 0, SYSUTCDATETIME(), SYSUTCDATETIME())" @{ Id = $beatId; Text = $text; Hash = (Sha256Hex $text); Number = $bnum }
    Exec-NonQuery "INSERT INTO BeatNodes (NodeId, BeatId, SortKey, IsEnabled) VALUES (@N, @B, 100.0, 1)" @{ N = $nodeId; B = $beatId }
    Write-Host "    chapter added ($($text.Length) chars)"
}

# ---- the gazetteer entries ----
# k   = match key(s) tested against the book's prose; '|' separates alternatives
# grp = group heading (printed only if at least one entry under it matched)
# h   = entry heading, c = coordinate line, b = body
$Entries = @(
 @{grp='GALILEE AND THE NORTH'}
 @{k='Galilee'; h='GALILEE'; c="a region, not a point $em no single fix"; b="The northern territory, ruled throughout the Gospel period by Herod Antipas as a tetrarchy rather than governed directly from Rome $em a distinction that matters, because it means the trial narratives cross a jurisdictional boundary. Roughly forty miles north to south, densely settled, and agriculturally rich. Josephus counts a frankly unbelievable number of towns in it and is not believed on the figure, but the density behind the exaggeration is real. Individual towns carry their own entries below; the lake has one of its own."}
 @{k='Nazareth'; h='NAZARETH'; c="32.7019$dg N, 35.3033$dg E"; b="Modern Nazareth, Northern District, Israel. The village of the childhood; an unwalled agricultural settlement of modest size in the first century, with rock-cut tombs, cisterns, and agricultural installations excavated within the modern city. Identification secure $em the name has never been lost."}
 @{k='Precipice|Kedumim'; h='MOUNT OF PRECIPICE (MOUNT KEDUMIM)'; c="32.6828$dg N, 35.2986$dg E"; b="A signposted escarpment about a mile and a half south of Nazareth, shown as the cliff of the attempt on Jesus's life in Luke's account of the synagogue sermon. One caution the tradition rarely offers: Luke says the crowd drove him to the brow of the hill on which the town was built, and this is not that hill. The view over the Jezreel Valley is genuine and worth the walk. It is simply not where the text puts the event. Locality-level fix."}
 @{k='Sepphoris'; h='SEPPHORIS (TZIPPORI)'; c="32.7456$dg N, 35.2786$dg E"; b="About an hour's walk north-west of Nazareth. The administrative capital of Galilee, rebuilt on a substantial scale during Jesus's youth. It is never named in any Gospel, which is itself worth noticing: the largest building project within walking distance of Nazareth goes entirely unmentioned. Identification secure."}
 @{k='Capernaum'; h='CAPERNAUM (KFAR NAHUM)'; c="32.8811$dg N, 35.5750$dg E"; b="North shore of the Sea of Galilee. The base of operations; excavated, with a fourth-or-fifth-century white limestone synagogue standing on the black basalt foundations of an earlier one, and an octagonal Byzantine church built over a first-century house complex venerated from early date as Peter's. A customs post fits the political geography, since the town sat near the boundary of Herod Antipas's territory. Identification secure."}
 @{k='Chorazin'; h='CHORAZIN (KORAZIM)'; c="32.9111$dg N, 35.5628$dg E"; b="Two and a half miles north of Capernaum, in the basalt hills. Named only in the woe pronounced on it. Extensively excavated ruins, including a basalt synagogue, are visible today. Identification secure; the town is, in the ordinary sense, gone."}
 @{k='Bethsaida'; h="BETHSAIDA $em two candidates"; c="et-Tell: 32.9103$dg N, 35.6306$dg E | el-Araj: 32.8933$dg N, 35.6191$dg E"; b="Home of Andrew, Peter, and Philip in John's account. The identification is genuinely unsettled: et-Tell, a mound about a mile and a half from the present shoreline, has been excavated since 1987 and is the long-standing candidate; el-Araj, closer to the lake, has produced first-century remains and a Byzantine church and now has substantial support. A caution for anyone checking a map: there is a second, unrelated et-Tell in the West Bank identified with biblical Ai $em not this site."}
 @{k='Magdala'; h='MAGDALA (MIGDAL)'; c="32.8250$dg N, 35.5156$dg E"; b="West shore of the Sea of Galilee. The place-name behind Mary Magdalene's byname. A first-century synagogue was excavated here from 2009, along with the carved Magdala Stone; the town also had a harbour and a fish-processing industry. Identification secure."}
 @{k='Magadan|Dalmanutha'; h="MAGADAN AND DALMANUTHA $em unlocated"; c="no secure fix for either"; b="Matthew names Magadan as the landfall after the feeding of the four thousand. Mark, at the identical point of the identical episode, names Dalmanutha. Neither place is attested anywhere else in ancient literature, the manuscripts vary for both, and no site has been securely identified for either. Two Gospels, one boat trip, two unknown harbours. The honest entry is a blank."}
 @{k='Cana'; h="CANA $em two candidates"; c="Khirbet Qana: 32.8236$dg N, 35.3042$dg E | Kafr Kanna: 32.7500$dg N, 35.3500$dg E"; b="Kafr Kanna has been shown to pilgrims since the Middle Ages and is more accessible; Khirbet Qana is an unoccupied ruin excavated since 1998 which has produced first-century Jewish occupation, a synagogue, ritual baths, Hasmonean coins, and a cave shrine with a shelf built for six stone jars. The traditional site has produced no evidence of Roman-period Jewish settlement. Contested, with the archaeological weight now favouring Khirbet Qana."}
 @{k='Nain'; h='NAIN (NEIN)'; c="32.6306$dg N, 35.3500$dg E"; b="A village on the north slope of the hill of Moreh, south-east of Nazareth, where the widow's son is raised. A small modern village occupies the site. Identification generally accepted."}
 @{k='Gennesaret|Ginosar'; h='GENNESARET (THE PLAIN OF GINOSAR)'; c="32.8475$dg N, 35.5228$dg E (kibbutz Ginosar)"; b="The fertile crescent on the north-west shore, roughly five miles by two, which the Gospels use as a district name rather than a town. Josephus praises its soil at length and at some length again. The boat pulled out of the lakebed here in 1986, when a drought dropped the water level, is a first-century vessel of the size and construction the fishing narratives require $em which settles nothing about any particular voyage and a great deal about the ordinary equipment of the trade."}
 @{k='Sea of Galilee|Kinneret'; h='SEA OF GALILEE'; c="32.833$dg N, 35.583$dg E (lake centre)"; b="Also Lake Tiberias, also Kinneret. Thirteen miles long, eight wide, forty-three metres at its deepest, and about two hundred metres below sea level $em which is the fact that explains the weather. Cold air spilling off Mount Hermon and the Golan onto warm air sitting over a lake in a basin produces exactly the sudden violent squalls the storm narratives describe. Identification, it should hardly need saying, secure."}
 @{k='Tiberias'; h='TIBERIAS'; c="32.7944$dg N, 35.5333$dg E"; b="On the west shore, founded by Herod Antipas within Jesus's lifetime and named for the emperor. Like Sepphoris, it is never entered in any Gospel; John mentions boats coming from it and nothing more. Two substantial cities built within sight of the ministry, and the narrative walks around both. Identification secure."}
 @{k='Gergesa|Kursi'; h='GERGESA (KURSI)'; c="32.8261$dg N, 35.6504$dg E"; b="East shore of the Sea of Galilee, and the leading candidate for the scene of the pig-herd exorcism, chiefly because it is the only spot on that shore with a steep slope running down to the water. Byzantine remains including a large monastery were excavated here. The place-name in the manuscripts varies between Gerasa, Gadara, and Gergesa, and the identification follows the topography rather than the text."}
 @{k='Gadara|Gadarene'; h='GADARA (UMM QAIS)'; c="32.6542$dg N, 35.6875$dg E"; b="A Greco-Roman city in modern Jordan, about six miles south-east of the lake, extensively excavated, and one of the three place-names the manuscripts offer for the pig-herd exorcism. The difficulty is arithmetic. The text has a herd run down a steep bank into the sea, and Gadara's territory reaches the water only at a distance that makes the run hard to picture. Identification of the city secure; its identification as the scene of the episode is not."}
 @{k='Gerasa|Jerash'; h='GERASA (JERASH)'; c="32.2806$dg N, 35.8972$dg E"; b="Also in modern Jordan, and the best-preserved Roman provincial city in the Near East $em colonnaded street, hippodrome, two theatres, an oval forum. It is also some thirty-seven miles from the Sea of Galilee, which makes it the least defensible of the three readings for the exorcism, and it is the reading of the earliest manuscripts of Mark. Identification of the city secure; the geography is a problem the text does not solve."}
 @{k='Decapolis'; h='DECAPOLIS'; c="a region, not a point $em no single fix"; b="A loose grouping of Hellenised cities east and south-east of the lake, of which Gadara, Gerasa, Hippos, Pella, and Damascus appear in the ancient lists. Coordinates for individual members are given in their own entries. Mark has Jesus cross into this territory more than once; the Decapolis is the Gospels' shorthand for the Gentile side of the water."}
 @{k='Mount Tabor'; h='MOUNT TABOR'; c="32.6872$dg N, 35.3903$dg E"; b="A distinctive dome rising from the Jezreel Valley, and the traditional site of the Transfiguration from at least the fourth century. Against it: the summit carried a settlement in the first century, which fits poorly with a mountain apart. Contested; see also Mount Hermon."}
 @{k='Mount Hermon'; h='MOUNT HERMON'; c="33.4161$dg N, 35.8575$dg E"; b="The high massif on the modern Syria-Lebanon border, snow-covered much of the year and by far the highest ground in the region. Favoured by many modern scholars for the Transfiguration on the grounds of proximity to Caesarea Philippi, where the preceding scene is set, and because it is genuinely a high mountain apart. Contested; see also Mount Tabor."}
 @{k='Caesarea Philippi|Banias|Paneas'; h='CAESAREA PHILIPPI (BANIAS / PANEAS)'; c="33.2486$dg N, 35.6944$dg E"; b="At the foot of Mount Hermon, at one of the sources of the Jordan. A Herodian city rebuilt by Philip the tetrarch, long a cult site of the god Pan, whose grotto and rock-cut niches are the visible ruins today. The setting of Peter's confession. Identification secure."}
 @{k='Omrit'; h='OMRIT'; c="33.2183$dg N, 35.6631$dg E"; b="An excavated site two miles from Banias which produced a Roman temple whose architecture resembles the temple shown on Philip's coinage $em making it a candidate for the shrine Herod built to Augustus near Paneas, a building Josephus mentions and declines to locate. Omrit is named in no Gospel. It earns an entry for what it establishes about the setting of Peter's confession: the question of who Jesus is was put in the shadow of a temple to a living emperor."}
 @{k='Nahal Abel'; h='NAHAL ABEL FARMSTEAD'; c="no verified published fix"; b="A Hasmonean-period Galilean farmstead excavated with its loom weights, storage jars, and iron tools effectively in place. It is cited in this book as an archaeological control on ordinary rural life $em what a household actually kept and how much of it $em not as the site of any Gospel event. Published reports place it in the Galilee near Nahal Abel; a site coordinate could not be confirmed, so none is printed."}
 @{k='Jezreel'; h='JEZREEL VALLEY'; c="32.5964$dg N, 35.2419$dg E"; b="The broad plain cutting east to west across northern Israel, the corridor used by every army moving between Egypt and Mesopotamia, and the ground Nazareth looks down on from its ridge. Megiddo, on its southern edge, supplies the name Armageddon. Identification secure; the valley is still farmland."}
 @{k='Via Maris'; h='VIA MARIS'; c="a route, not a point $em no single fix"; b="The trunk road linking Egypt to Damascus: up the coast, inland across the Jezreel Valley, then past the north-west shore of the Sea of Galilee near Capernaum. This is the unromantic reason a customs post and a garrison officer belong in a lakeside fishing village. It was on a highway."}
 @{k='Zebulun|Naphtali'; h='ZEBULUN AND NAPHTALI'; c="tribal territories, not points $em no single fix"; b="Two of the northern tribal allotments, covering roughly the Lower Galilee and the hill country north-west of the lake. Matthew quotes Isaiah on them to locate the start of the ministry, which is a claim about prophecy rather than about administration: the tribal territories had not functioned as units of government for some seven centuries by the time he wrote."}
 @{k='Ituraea|Trachonitis|Golan|Abilene'; h='ITURAEA, TRACHONITIS, ABILENE, AND THE GOLAN'; c="Abila Lysaniou: 33.6267$dg N, 36.1058$dg E; the regions have no single fix"; b="Luke dates the beginning of John's preaching by naming the rulers of several small territories at once, and the list is checkable. Ituraea and Trachonitis lie north and east of the Sea of Galilee $em broadly the modern Golan Heights and the Hauran $em and were held by Philip the tetrarch. Abilene is the territory of Abila Lysaniou on the Barada river north-west of Damascus, and its coordinate is given because the town, unlike the regions, is a point. The ruler Luke names there, Lysanias, has been the subject of a long argument: the Lysanias known to Josephus was killed about 36 BCE, six decades too early, and the defence of Luke rests on an inscription from Abila naming a later tetrarch of the same name, taken by many to be a descendant. Contested, and one of the better test cases for how much weight a single inscription can carry."}
 @{k='Tyre'; h='TYRE'; c="33.2708$dg N, 35.1961$dg E"; b="A Phoenician port on the coast of modern Lebanon, some thirty-five miles from Capernaum, and the setting of the encounter with the Syrophoenician woman. Long history, a famous purple dye industry, and an excavated Roman hippodrome and necropolis. Identification secure."}
 @{k='Sidon'; h='SIDON'; c="33.5599$dg N, 35.3756$dg E"; b="Twenty-five miles further north along the same coast, and named with Tyre both in the woes and in the travel notes. Continuously inhabited since antiquity, which is precisely why less of the ancient city is available to excavation than at Tyre. Locality-level fix."}

 @{grp='THE COAST AND THE PLAIN'}
 @{k='Caesarea Maritima'; h='CAESAREA MARITIMA'; c="32.5000$dg N, 34.8917$dg E"; b="Herod's great artificial harbour on the Mediterranean coast, and the seat of the Roman governor $em meaning Pilate's normal residence was here, not Jerusalem. The inscription naming Pilate as prefect of Judea was found in its theatre in 1961. Identification secure and extensively excavated."}
 @{k='Arimathea'; h='ARIMATHEA (RANTIS)'; c="32.0281$dg N, 35.0194$dg E"; b="A hill village about twenty miles north-west of Jerusalem, generally identified with modern Rantis, and the home town of the councillor who supplied the tomb. The identification rests on the name and is reasonable rather than demonstrated; the village has not been excavated in a way that would settle it."}
 @{k='Ekron|Baal-zebub|Beelzebul'; h='EKRON (TEL MIQNE)'; c="31.7775$dg N, 34.8519$dg E"; b="A Philistine city of the coastal plain, excavated from 1981, which in 1996 produced a royal inscription naming the city outright $em an unusually direct confirmation of an identification. It appears in this book not as a Gospel site but as the home of Baal-zebub, the god consulted in 2 Kings, whose name stands behind Beelzebul in the accusation levelled against Jesus. Identification secure."}
 @{k='Ramah'; h='RAMAH (AL-RAM)'; c="31.8536$dg N, 35.2333$dg E"; b="A town a few miles north of Jerusalem on the road into the hill country. The name means, simply, height, and there are several Ramahs in the Hebrew Bible $em a standing trap for anyone matching quotations to maps. Matthew applies Jeremiah's voice heard in Ramah to the killing of the children at Bethlehem, a town on the far side of Jerusalem. Identification of this Ramah generally accepted."}

 @{grp='SAMARIA'}
 @{k='Samaria|Sebaste'; h='SAMARIA / SEBASTE'; c="32.2764$dg N, 35.1950$dg E"; b="The ancient capital of the northern kingdom, rebuilt by Herod as Sebaste $em the Greek for Augustus $em in the emperor's honour, with a temple, forum, colonnaded street, and theatre still traceable. Note the usage: the Gospels employ Samaria almost always as the name of the district, not the city, and no Gospel scene takes place inside the city itself. Identification secure."}
 @{k='Sychar'; h='SYCHAR (ASKAR)'; c="32.2199$dg N, 35.2974$dg E"; b="A village on the lower slope of Mount Ebal east of Nablus, and the leading candidate for the town near Jacob's Well. The identification rests on the name and the distance rather than on excavation, and a minority reading of the manuscripts points to Shechem itself. Locality-level fix; the area is now built up."}
 @{k="Jacob's Well"; h="JACOB'S WELL"; c="32.2095$dg N, 35.2853$dg E"; b="At the eastern edge of modern Nablus, near ancient Shechem, in the crypt of an Orthodox church. A deep, genuinely ancient well at the traditional site of the conversation with the Samaritan woman. The identification is old and geographically coherent; the well is real and still holds water."}
 @{k='Gerizim'; h='MOUNT GERIZIM'; c="32.2009$dg N, 35.2733$dg E"; b="Above Nablus. The Samaritan holy mountain and the site of their temple, destroyed by the Hasmonean John Hyrcanus in the second century BCE. This is the mountain meant by this mountain in the Samaritan woman's question about where worship properly belongs. Identification secure; the ruins are excavated."}
 @{k='Aenon|Salim'; h='AENON NEAR SALIM'; c="Salim: 32.2094$dg N, 35.3317$dg E; Aenon itself: no secure fix"; b="John's second baptism location, described as near Salim because there was much water there. There is a village of Salim three to four miles east of Nablus, and a nearby place called 'Ainun that preserves the name; a survey in 1962 reported an extensive tell with architectural remains in its vicinity. That is as close as the evidence gets. The coordinate printed is Salim's. None is printed for Aenon, because none can be confirmed."}

 @{grp='THE JORDAN VALLEY AND THE WILDERNESS'}
 @{k='Jordan'; h="THE JORDAN BAPTISM SITE $em two banks, two countries"; c="Qasr el-Yahud (west): 31.8383$dg N, 35.5392$dg E | Al-Maghtas (east): 31.8372$dg N, 35.5503$dg E"; b="The traditional baptism area lies near the river's outflow toward the Dead Sea, and the tradition is split across an international border by the river itself: the western site, Qasr el-Yahud, and the eastern site, Al-Maghtas in Jordan $em which is also the leading candidate for Bethany beyond the Jordan $em sit barely a kilometre apart at almost the same latitude. Both hold Byzantine church remains. The general locality is well attested; a precise spot is not recoverable, not least because the river has moved."}
 @{k='Ephraim'; h='EPHRAIM (TAYBEH)'; c="31.9544$dg N, 35.3003$dg E"; b="A hill village some fifteen kilometres north-east of Jerusalem on the edge of the wilderness, identified with modern Taybeh $em today one of the few remaining majority-Christian villages in the West Bank. John alone names it, as the place Jesus withdrew to after the raising of Lazarus, once the authorities had settled on his death. The identification is long-standing and topographically apt; the ancient name did not survive, the village having been renamed Taybeh centuries later, and the same site has separately been proposed as Ophrah of Benjamin."}
 @{k='Wilderness of Judea|wilderness of Judea'; h='THE WILDERNESS OF JUDEA'; c="a region, not a point $em no single fix"; b="The barren descent east of the Jerusalem watershed toward the Dead Sea, losing something over a thousand metres in fifteen miles. Not empty $em it carried roads, and later monasteries, and the Qumran settlement $em but agriculturally dead, which is what the word means here. Both John's preaching and the temptation narrative are set in it."}
 @{k='Quruntul|Mount of Temptation'; h='JEBEL QURUNTUL (MOUNT OF TEMPTATION)'; c="31.8747$dg N, 35.4306$dg E"; b="The cliff above Jericho, with a Greek Orthodox monastery fixed to its face, shown since the Crusader period as the site of the forty days. No Gospel names a mountain for the temptation at all. The identification is devotional rather than evidential. The climb is real."}
 @{k='Jericho'; h='JERICHO'; c="Tell es-Sultan (ancient): 31.8710$dg N, 35.4443$dg E | modern town: 31.8667$dg N, 35.4500$dg E"; b="On the road up from the Jordan valley to Jerusalem $em the ascent the Good Samaritan's road descends. Worth knowing: there are effectively two Jerichos, the ancient mound and the separate Herodian-era winter-palace town nearby, which is why a Gospel can have Jesus both entering and leaving Jericho in successive verses without contradiction. Identification secure."}
 @{k='Tulul Abu|winter palace|Winter Palace'; h='THE HERODIAN WINTER PALACE AT JERICHO (TULUL ABU EL-ALAYIQ)'; c="31.8537$dg N, 35.4337$dg E"; b="The palace complex on the Wadi Qelt just west of the modern town, built in stages first by the Hasmoneans and then by Herod: swimming pools, bath houses, a colonnaded garden. Josephus places Herod's death here. This is the second Jericho referred to in the entry above, and the reason the Gospels can move in and out of the town without contradicting themselves. Identification secure."}
 @{k='Wadi Qelt|Adummim'; h='WADI QELT / THE ASCENT OF ADUMMIM'; c="31.8443$dg N, 35.4143$dg E"; b="The gorge carrying the ancient road from Jericho up to Jerusalem $em the road of the Good Samaritan, and the direction of travel is part of the parable's accuracy: Jerusalem down to Jericho is a fall of roughly a thousand metres in seventeen miles, exactly as the text says. Steep, narrow, and with cover on both sides, which is a sufficient explanation of why robbers feature. Locality-level fix on the wadi; the road is a line, not a point."}
 @{k='Machaerus'; h='MACHAERUS'; c="31.5672$dg N, 35.6242$dg E"; b="A Herodian fortress on a peak east of the Dead Sea, in modern Jordan, where Josephus places the imprisonment and execution of John the Baptist. Excavated, including the throne room and courtyard of the kind of court a birthday banquet would require. Identification secure; Josephus supplies the location, the Gospels do not."}
 @{k='Moab'; h='MOAB'; c="a region, not a point $em no single fix"; b="The plateau east of the Dead Sea, in modern Jordan. Machaerus stands on its western edge and carries a coordinate of its own. Moab itself is a historical territory rather than a first-century administrative unit: by the Gospel period the area was divided between the Nabataean kingdom and Herodian Perea, and no one living there would have given Moab as their address."}

 @{grp='JERUSALEM AND ITS APPROACHES'}
 @{k='Judea'; h='JUDEA'; c="a region, not a point $em no single fix"; b="The southern territory around Jerusalem, and from 6 CE a Roman province under a prefect $em Pilate's jurisdiction. Its boundaries were redrawn repeatedly across the century, which is why the word does different work in different passages: sometimes the hill district immediately around Jerusalem, sometimes the whole of Jewish Palestine, Galilee included. The wilderness along its eastern edge has an entry of its own."}
 @{k='Jerusalem'; h='JERUSALEM'; c="31.7767$dg N, 35.2342$dg E (the walled Old City)"; b="The coordinate is for the walled Old City, whose present walls are Ottoman and which encloses less than the Herodian city in the south and more in the north. Anyone matching Gospel scenes to a modern map should hold that fact steadily. The line of the first-century wall is the single most consequential uncertainty in the archaeology of this city, because whether Golgotha stood inside it or outside it depends on where that line ran."}
 @{k='Bethlehem'; h='BETHLEHEM'; c="Church of the Nativity: 31.7043$dg N, 35.2076$dg E"; b="Five miles south of Jerusalem. The Church of the Nativity, begun under Constantine in the fourth century, stands over a grotto venerated as the birthplace $em making it one of the oldest continuously used churches on earth. Note what the text does and does not say: no Gospel mentions a stable or a cave, and the word rendered inn (kataluma) means a guest room, not a commercial inn, for which Greek has a different word. A minority scholarly view places the birth at Nazareth instead, and a separate proposal has argued for Bethlehem of Galilee in the north."}
 @{k='Herodium'; h='HERODIUM'; c="31.6658$dg N, 35.2414$dg E"; b="Herod the Great's artificial cone of a fortress-palace south-east of Bethlehem, and $em on the identification published in 2007 $em the site of his own tomb. The king of the nativity narrative has a findable address. Identification of the site secure; the tomb identification is accepted by many and disputed by some."}
 @{k='Bethany'; h='BETHANY (AL-EIZARIYA)'; c="31.7700$dg N, 35.2644$dg E"; b="On the eastern slope of the Mount of Olives, about two miles from Jerusalem, on the Jericho road. The village of Martha, Mary, and Lazarus, and the base for the final week. The modern Arabic name preserves Lazarus $em al-Eizariya, the place of Lazarus $em and a tomb venerated as his is shown there. Identification of the village secure; the tomb is traditional."}
 @{k='Bethphage'; h='BETHPHAGE'; c="31.7773$dg N, 35.2509$dg E (Church of Bethphage)"; b="On the Mount of Olives between Bethany and the summit, and the village where the colt is fetched. The Franciscan church marks the traditional spot and supplies the coordinate. The place is named in all three Synoptics and nowhere else in antiquity in a way that would fix it, so the location is traditional rather than established."}
 @{k='Mount of Olives'; h='MOUNT OF OLIVES'; c="31.7783$dg N, 35.2439$dg E"; b="The ridge east of the Old City, separated from the Temple Mount by the Kidron valley, carrying the road to Bethany and Jericho. The vantage point for the discourse on the Temple's destruction $em from which the building being discussed was in plain view. Identification secure."}
 @{k='Gethsemane'; h='GETHSEMANE'; c="31.7794$dg N, 35.2402$dg E"; b="Across the Kidron valley at the foot of the Mount of Olives, by the Church of All Nations. The name means something like oil press, a workaday agricultural label rather than a mystical one. A first-century ritual bath was identified nearby in 2020, consistent with an agricultural installation on the site. The general locality is secure; the precise enclosure is traditional."}
 @{k='Kidron'; h='KIDRON VALLEY'; c="a valley, not a point $em no single fix"; b="The ravine running north to south between the Old City's eastern wall and the Mount of Olives, then on toward the Dead Sea. It is crossed on the way to Gethsemane, and it carried the Temple's waste water and the drainage from the altar. Findable on any map of the city; not reducible to a coordinate."}
 @{k='Gehenna|Hinnom|Topheth'; h='GEHENNA (THE VALLEY OF HINNOM) AND TOPHETH'; c="a valley, not a point $em no single fix"; b="The ravine on the western and southern sides of the Old City, joining the Kidron near the south-eastern corner. Its Hebrew name, Ge-Hinnom, is the origin of Gehenna, the word the Gospels use for final punishment and which English versions usually render hell. Topheth, within it, is where 2 Kings locates the child sacrifice Josiah destroyed. One correction is owed here, because it is repeated everywhere: the claim that the valley was a perpetually burning municipal rubbish tip in the first century rests on no ancient source at all. Its earliest known statement is a commentary by Rabbi David Kimhi around 1200 CE, and neither literature nor excavation supports it $em what excavation has found in the valley is burials, in quantity. The valley's grim reputation is thoroughly biblical. The garbage fire is a medieval guess with a very good publicist."}
 @{k='Palatial Mansion|Wohl'; h='THE PALATIAL MANSION'; c="31.7753$dg N, 35.2321$dg E (Wohl Archaeological Museum)"; b="An aristocratic Herodian-period house in the Upper City, excavated by Nahman Avigad and now displayed underground: some six hundred square metres, frescoed walls, mosaic floors, and multiple ritual baths. It is not the high priest's house, and this book does not claim that it is. It is the best available evidence for what the house of a priestly family in Jesus's Jerusalem physically was $em which is worth having when a narrative moves a prisoner into one at night."}
 @{k='Praetorium|Gabbatha|Stone Pavement'; h="THE PRAETORIUM AND GABBATHA $em two candidates"; c="Herod's palace / the Citadel: 31.7761$dg N, 35.2278$dg E | Antonia Fortress: no surveyed fix published"; b="Where Pilate heard the case is genuinely open. The traditional route starts at the Antonia Fortress at the platform's north-western corner, whose bedrock lies under the Omariya school; no published surveyed coordinate for it could be confirmed, so none is printed. The paved court long shown beneath the Sisters of Zion convent as Gabbatha has been redated to Hadrian's rebuilding of the city a century after the trial. The alternative, now widely preferred, is Herod's palace on the western wall, in the Citadel area by the Jaffa Gate, on the reasoning that a governor visiting for a festival would occupy the royal palace rather than a barracks. Contested. The route of the Via Dolorosa is devotional, and its stations were fixed centuries later."}
 @{k='Golgotha|Holy Sepulchre|Garden Tomb|the Skull'; h="GOLGOTHA AND THE TOMB $em two candidates"; c="Church of the Holy Sepulchre: 31.7786$dg N, 35.2294$dg E | Garden Tomb: 31.7836$dg N, 35.2247$dg E"; b="The Church of the Holy Sepulchre stands over a disused limestone quarry containing rock-cut tombs of the right period, outside the city wall as it ran at the time, and excavation beneath the church has recovered traces of cultivated ground $em olive and vine $em of roughly the right date. The Garden Tomb, identified in the nineteenth century, is a genuine rock-cut tomb but is generally dated earlier than the first century and has almost no support in scholarship. Contested in popular presentation; not seriously contested in the field."}
 @{k="Giv'at ha-Mivtar|Yehohanan|Givat"; h="GIV'AT HA-MIVTAR"; c="31.8018$dg N, 35.2254$dg E"; b="A neighbourhood in north-eastern Jerusalem, and the reason this book can describe a crucifixion in physical detail. In 1968 a rock-cut tomb here produced the ossuary of a man named Yehohanan with an iron nail still driven through his heel bone $em the only direct skeletal evidence of a Roman crucifixion yet recovered. He was a Jerusalem man of roughly Jesus's generation, and he was given an ordinary family burial, which bears directly on the question of whether a crucified body could be buried at all. Identification of the site secure."}
 @{k='Emmaus'; h="EMMAUS $em unlocated"; c="no secure fix"; b="Manuscripts disagree on the distance from Jerusalem $em sixty stadia in most, one hundred and sixty in Codex Sinaiticus $em and the candidate sites split accordingly: Emmaus Nicopolis has the oldest identification but sits at roughly the longer distance, while Abu Ghosh and el-Qubeibeh match the shorter reading but carry no ancient claim to the name. A real village, genuinely mislaid."}

 @{grp='THE TEMPLE'}
 @{k='Temple'; h='THE TEMPLE MOUNT'; c="31.7781$dg N, 35.2358$dg E"; b="The vast Herodian platform, whose retaining walls are the largest surviving remains of the building. Nothing of the sanctuary itself stands. The courts, porticoes, money-changers' tables, and treasury chests of the Gospel scenes were all on this platform. Identification secure; the platform is the single most certainly located place in the New Testament."}
 @{k='Royal Stoa'; h='THE ROYAL STOA'; c="31.7760$dg N, 35.2362$dg E"; b="The great basilica along the southern edge of the platform $em one hundred and sixty-two columns in four rows, by Josephus's count. This, and not the sanctuary, is the likeliest setting for the money-changers and for the seated teaching in the Temple, because it was the commercial and public end of the complex. Nothing of it stands; the southern retaining wall is its foundation."}
 @{k="Robinson's Arch"; h="ROBINSON'S ARCH"; c="31.7757$dg N, 35.2347$dg E"; b="The springer of a monumental staircase projecting from the western wall near its southern corner, named for the American scholar who identified it in 1838. It carried a stair from the street below up into the Royal Stoa. The supporting pier and the paved street beneath it $em with the collapse debris of 70 CE still lying where it fell $em are excavated and visible. Identification secure."}
 @{k="Solomon's Portico"; h="SOLOMON'S PORTICO"; c="on the platform's eastern side; no separate surveyed fix published"; b="The colonnade where John sets the winter dialogue and where Acts has the early community gather. The name is traditional and the attribution to Solomon is not historical $em the eastern wall's lower courses are pre-Herodian, but nothing like that old. The Temple Mount coordinate above locates the portico to within a few hundred metres, which is as close as the evidence permits and closer than most readers need."}
 @{k='Court of Women'; h='THE COURT OF WOMEN'; c="within the Temple complex; no separate surveyed fix published"; b="The large outer court where the Mishnah places the great lamps of the Sukkot illumination ceremony, and where John situates the declaration about being the light of the world, adding that it happened by the treasury. The two details corroborate each other, because the treasury chests stood in this court. The court went with the rest of the sanctuary. Only the platform survives."}
 @{k='Bethesda'; h='POOL OF BETHESDA'; c="31.7814$dg N, 35.2358$dg E"; b="By the Sheep Gate in the north-east of the Old City, beside the Church of St Anne. Excavation revealed a twin-pool complex whose layout accommodates the five porticoes John describes $em four sides and a dividing colonnade $em after the detail had long been treated as evidence the author did not know Jerusalem. Identification secure."}
 @{k='Siloam'; h='POOL OF SILOAM'; c="31.7690$dg N, 35.2343$dg E"; b="At the southern end of the City of David, fed by the Gihon spring through Hezekiah's tunnel. The Second Temple-period pool, with its stepped stone sides, was uncovered from 2004 during sewer work, some distance from the smaller Byzantine pool previously shown to visitors. Identification secure."}

 @{grp='BEYOND THE LAND'}
 @{k='Egypt'; h='EGYPT'; c="a country, not a point $em no single fix"; b="The destination of the flight after the nativity, and the standard refuge for anyone leaving Judea in a hurry: outside Herod's jurisdiction, reachable in under two weeks, and holding a large established Jewish population, Alexandria's above all. No Gospel names a town. No coordinate is printed, because the text supplies no place to locate."}
 @{k='Idumea'; h='IDUMEA'; c="a region, not a point $em no single fix"; b="The territory south of Judea, ancient Edom, forcibly Judaised by the Hasmoneans in the second century BCE. Its single most useful fact is genealogical: it is where Herod the Great's family came from, which is why the king of the nativity narrative was a Jewish ruler whose Jewishness his subjects could question, and did. Mark notes crowds coming from Idumea."}
 @{k='Syria'; h='SYRIA'; c="a Roman province, not a point $em no single fix"; b="The province north of Judea, governed from Antioch, whose legate outranked the prefect in Jerusalem. That hierarchy is why Luke can date a census by reference to Quirinius as governor of Syria $em and why that dating is among the hardest problems in the Gospels. No coordinate is printed; Antioch lies outside the scope of this list."}
 @{k='Cyrene'; h='CYRENE (SHAHHAT)'; c="32.8250$dg N, 21.8581$dg E"; b="A Greek city in what is now north-eastern Libya, and the stated home of Simon, the man conscripted to carry the cross. It held a substantial Jewish community, which makes the detail unremarkable rather than exotic. Mark alone names Simon's sons, Alexander and Rufus, in the manner of a writer identifying a man his audience might know. Identification secure and extensively excavated."}
 @{k='Nineveh'; h='NINEVEH (KUYUNJIK, MOSUL)'; c="36.3594$dg N, 43.1528$dg E"; b="The Assyrian capital, across the Tigris from modern Mosul, destroyed in 612 BCE. It reaches the Gospels only through the saying about the men of Nineveh repenting at Jonah's preaching $em a reference to a story, not a place anyone in the narrative goes. Identification secure. The site has been repeatedly damaged in recent conflict, including deliberate destruction in 2015 and 2016."}
 @{k='Sodom|Gomorrah'; h="SODOM AND GOMORRAH $em candidates, contested"; c="Bab edh-Dhra: 31.2531$dg N, 35.5375$dg E | Tall el-Hammam: 31.8402$dg N, 35.6737$dg E | Numeira: no confirmed fix"; b="Named in the Gospels only as a comparison in the judgement sayings, but the archaeology is a live argument and worth stating precisely. Bab edh-Dhra, south-east of the Dead Sea, is the long-standing candidate, with nearby Numeira proposed for Gomorrah $em though no coordinate for Numeira could be confirmed, so none is printed. Tall el-Hammam, north-east of the Dead Sea, has been argued more recently, including a 2021 claim of destruction by airburst which drew substantial published criticism. Contested, and it should be said plainly: no site has been shown to be Sodom. What exists is a set of destroyed Bronze Age towns in roughly the right region."}
)

$preamble = @"
Every place named in this book that can be located is listed here with coordinates, so that any of it can be typed into a map and looked at. That is not a gimmick. The argument running through this whole series is that these events are set in a real landscape rather than a symbolic one, and the fastest way to feel the difference is to see the hill, measure the walk, and notice that two villages competing for the same name are eleven miles apart.

Entries are grouped by region and run roughly north to south, then outward from the land.

Four conventions, stated plainly.

Coordinates are decimal degrees on the WGS84 datum, the system a phone or web map uses, so they can be pasted in directly. They locate a site, not a spot: a figure given for a town centre or an archaeological mound is accurate to the settlement, not to a doorway.

Where a coordinate could not be verified, none is given. There are a few of those, and the omission is deliberate $em a plausible-looking figure invented for completeness would be exactly the failure this book exists to avoid.

Where the identification itself is disputed, both or all candidates are listed with their own coordinates, and the state of the argument is summarised rather than resolved. Contested does not mean unknowable; it means the evidence has not settled it yet.

Where a place cannot be located at all, it still gets an entry saying so. Regions, valleys, roads, and provinces are not points, and are marked as such rather than given a spurious centre. An honest blank is information.

One caution before the list. Coordinates carry an air of authority that can outrun what they actually establish. That a tomb sits at a given latitude tells you where a building venerated as a tomb stands today. It does not tell you what happened there. The figures below are a reliable guide to where to stand and a poor guide to what to believe, and this book would rather you had both facts than one.
"@

$books = @(
 @{code='MATTHEW'; id='019FA049-322F-75EF-AAB7-0C0DE8DBDB85'; notes='019FA01D-FA22-76C6-976C-3EA4F4D54A14'; slug='matthew'; sk=2975.0}
 @{code='MARK';    id='019FA966-2F28-7A30-9662-F0F6F33C4D54'; notes='019FA968-1B3B-75DC-84CF-0C7D9C4E783C'; slug='mark';    sk=1675.0}
 @{code='LUKE';    id='019FA969-3232-772B-998A-BB2D5158F96E'; notes='019FA96B-18E2-7BB4-BAEB-11ACA24934F4'; slug='luke';    sk=2475.0}
 @{code='JOHN';    id='019FA96B-CAD8-7769-BF17-363E3641048E'; notes='019FA96D-7D48-75E0-9BD9-2190171276DC'; slug='john';    sk=2175.0}
)

foreach ($b in $books) {
    Write-Host $b.code
    $pc = $conn.CreateCommand()
    $pc.CommandText = "SELECT bt.Text FROM Nodes c JOIN Nodes p ON p.Id=c.ParentNodeId JOIN BeatNodes bn ON bn.NodeId=c.Id JOIN Beats bt ON bt.Id=bn.BeatId WHERE p.NodeCode='" + $b.code + "' AND bn.IsEnabled=1 AND c.Title NOT IN ('Notes','A Gazetteer of Places')"
    $pr = $pc.ExecuteReader(); $psb = New-Object System.Text.StringBuilder
    while ($pr.Read()) { [void]$psb.Append($pr.GetString(0)) }
    $pr.Close()
    $prose = $psb.ToString()
    Write-Host ("    proselen=" + $prose.Length)
    $existingNum = Exec-Scalar "SELECT MIN(CAST(LEFT(bt.Text, CHARINDEX(' ',bt.Text)-1) AS INT)) FROM BeatNodes bn JOIN Beats bt ON bt.Id=bn.BeatId WHERE bn.NodeId='$($b.notes)' AND bn.IsEnabled=1 AND bt.Text LIKE '%How the coordinates in the gazetteer%'"
    if ($existingNum -isnot [DBNull] -and $existingNum) {
        $n = [int]$existingNum
        Write-Host "    reusing existing note $n"
        $skipNote = $true
    } else { $n = Next-Note $b.notes; $skipNote = $false }
    if (-not $skipNote) { Add-Note $b.notes $n "How the coordinates in the gazetteer were obtained" @"
Coordinates are given in decimal degrees on the WGS84 datum, compiled from standard published geographic and archaeological gazetteer references for each site and cross-checked between sources where they differ. They are site-level fixes $em a settlement, a mound, a church $em and are not surveyed points for a specific structure or feature unless the entry says so. Where sources disagreed materially, or where no reliable figure could be confirmed, no coordinate is printed and the entry states the omission. Elevation is not given. Readers should be aware that a coordinate locates a modern place bearing an ancient name, or a modern building venerated as an ancient site, and that this is a separate question from whether the identification is correct $em which each entry addresses on its own.
"@ }
    $body = $preamble.Trim() + " [$n]" + "`n`n"

    # first pass: which entries match this book's prose
    $matched = New-Object System.Collections.ArrayList
    foreach ($ent in $Entries) {
        if ($ent.ContainsKey('grp')) { [void]$matched.Add($ent); continue }
        $hit = $false
        foreach ($key in ($ent.k -split '\|')) {
            if ($prose.IndexOf($key, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) { $hit = $true; break }
        }
        if ($hit) { [void]$matched.Add($ent) }
    }

    # second pass: emit, dropping group headings with no entries under them
    $count = 0
    for ($i = 0; $i -lt $matched.Count; $i++) {
        $ent = $matched[$i]
        if ($ent.ContainsKey('grp')) {
            $hasChild = ($i + 1 -lt $matched.Count) -and (-not $matched[$i + 1].ContainsKey('grp'))
            if ($hasChild) { $body += $ent.grp + "`n`n" }
            continue
        }
        $body += $ent.h + "`n" + $ent.c + "`n" + $ent.b.Trim() + "`n`n"
        $count++
    }
    Write-Host "    entries: $count"
    Add-GazChapter $b.id $b.slug $b.sk $body
}

$conn.Close()
Write-Host "DONE"
