$ErrorActionPreference = 'Stop'
$cs = "Server=(localdb)\MSSQLLocalDB;Database=Prose;Integrated Security=true;TrustServerCertificate=true"

function Query($sql) {
  $cn = New-Object System.Data.SqlClient.SqlConnection $cs
  $cn.Open()
  $cmd = $cn.CreateCommand()
  $cmd.CommandText = $sql
  $cmd.CommandTimeout = 120
  $da = New-Object System.Data.SqlClient.SqlDataAdapter $cmd
  $dt = New-Object System.Data.DataTable
  [void]$da.Fill($dt)
  $cn.Close()
  return ,$dt
}

$cols = Query @"
SELECT c.TABLE_NAME, c.ORDINAL_POSITION, c.COLUMN_NAME, c.DATA_TYPE,
       c.CHARACTER_MAXIMUM_LENGTH, c.NUMERIC_PRECISION, c.NUMERIC_SCALE, c.IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t ON t.TABLE_NAME = c.TABLE_NAME AND t.TABLE_TYPE = 'BASE TABLE'
WHERE c.TABLE_NAME NOT LIKE '%[_]History'
ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION
"@

$pks = Query @"
SELECT tc.TABLE_NAME, ku.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
"@

$fks = Query @"
SELECT cp.TABLE_NAME AS FromTable, kcu.COLUMN_NAME AS FromCol,
       rt.TABLE_NAME AS ToTable, rkcu.COLUMN_NAME AS ToCol
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS cp ON rc.CONSTRAINT_NAME = cp.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu ON kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS rt ON rc.UNIQUE_CONSTRAINT_NAME = rt.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE rkcu ON rkcu.CONSTRAINT_NAME = rt.CONSTRAINT_NAME AND rkcu.ORDINAL_POSITION = kcu.ORDINAL_POSITION
"@

# Temporal (system-versioned) base tables
$temporal = Query @"
SELECT t.name AS TableName
FROM sys.tables t
WHERE t.temporal_type = 2
"@

# Row counts for base tables
$rowcounts = Query @"
SELECT t.name AS TableName, SUM(p.rows) AS Rows
FROM sys.tables t
JOIN sys.partitions p ON p.object_id = t.object_id AND p.index_id IN (0,1)
WHERE t.name NOT LIKE '%[_]History'
GROUP BY t.name
"@

# Build lookups
$pkSet = @{}
foreach ($r in $pks.Rows) { $pkSet["$($r.TABLE_NAME)|$($r.COLUMN_NAME)"] = $true }

$fkMap = @{}
foreach ($r in $fks.Rows) { $fkMap["$($r.FromTable)|$($r.FromCol)"] = "$($r.ToTable).$($r.ToCol)" }

$temporalSet = @{}
foreach ($r in $temporal.Rows) { $temporalSet["$($r.TableName)"] = $true }

$rcMap = @{}
foreach ($r in $rowcounts.Rows) { $rcMap["$($r.TableName)"] = [long]$r.Rows }

# Group columns by table
$tables = $cols.Rows | Group-Object TABLE_NAME | Sort-Object Name

$sb = New-Object System.Text.StringBuilder
function W($s) { [void]$sb.AppendLine($s) }

$today = Get-Date -Format 'yyyy-MM-dd'
$baseCount = $tables.Count
$histCount = (Query "SELECT COUNT(*) AS C FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%[_]History'").Rows[0].C

W "# Prose Database Schema"
W ""
W "> GENERATED by ``tools/gen-schema.ps1`` (or hand-regenerated via the same queries). Do not hand-edit --"
W "> regenerate after migrations. Snapshot date: $today."
W ""
W "This is the **live SQL schema** (canon lives in the DB, not files -- SS-LAW-1). Use it to"
W "understand table shapes and joins when working with Hub-routed CLI/MCP commands."
W ""
W "**HARD, ABSOLUTE (2026-08-22): nothing reaches the database except through Prose.Hub -- reads"
W "AND writes, no exceptions.** No raw ``sqlcmd``, not even a read-only lookup. If a Hub-routed"
W "command doesn't yet expose something you need, that's a gap to raise, not a reason to query"
W "the database directly."
W ""
W "## Conventions"
W ""
W "- **$baseCount base tables** are documented below. **$histCount ``*_History`` tables** are omitted: each is a"
W "  system-versioned temporal mirror of its base table with the same columns plus the period columns"
W "  ``SysStart`` / ``SysEnd``. Tables marked **(temporal)** below have such a history twin; query their"
W "  history with ``FOR SYSTEM_TIME ALL``."
W "- **PK** = primary-key column. **-> Table.Col** = foreign key to that column."
W "- ``Id`` columns are ``uniqueidentifier`` (GUID) unless noted. EF Core owns this schema (code-first migrations)."
W ""
W "## Table index"
W ""

# Index grouped alphabetically with row counts
foreach ($g in $tables) {
  $rc = if ($rcMap.ContainsKey($g.Name)) { $rcMap[$g.Name] } else { 0 }
  $tw = if ($temporalSet.ContainsKey($g.Name)) { ' *(temporal)*' } else { '' }
  W "- [``$($g.Name)``](#$($g.Name.ToLower())) -- $($g.Group.Count) cols, ~$rc rows$tw"
}
W ""
W "---"
W ""

function TypeStr($r) {
  $t = $r.DATA_TYPE
  $len = $r.CHARACTER_MAXIMUM_LENGTH
  if ($len -ne [DBNull]::Value -and $len -ne $null) {
    if ([int]$len -eq -1) { return "$t(max)" }
    return "$t($len)"
  }
  if ($t -in @('decimal','numeric') -and $r.NUMERIC_PRECISION -ne [DBNull]::Value) {
    return "$t($($r.NUMERIC_PRECISION),$($r.NUMERIC_SCALE))"
  }
  return $t
}

foreach ($g in $tables) {
  $name = $g.Name
  $tw = if ($temporalSet.ContainsKey($name)) { ' *(temporal -- has `' + $name + '_History`)*' } else { '' }
  $rc = if ($rcMap.ContainsKey($name)) { $rcMap[$name] } else { 0 }
  W "### $name"
  W ""
  W "~$rc rows.$tw"
  W ""
  W "| # | Column | Type | Null | Key |"
  W "|---|--------|------|------|-----|"
  foreach ($c in $g.Group) {
    $type = TypeStr $c
    $null = if ($c.IS_NULLABLE -eq 'YES') { 'yes' } else { 'no' }
    $key = ''
    if ($pkSet.ContainsKey("$name|$($c.COLUMN_NAME)")) { $key = 'PK' }
    if ($fkMap.ContainsKey("$name|$($c.COLUMN_NAME)")) {
      $fk = '-> ' + $fkMap["$name|$($c.COLUMN_NAME)"]
      $key = if ($key) { "$key, $fk" } else { $fk }
    }
    W "| $($c.ORDINAL_POSITION) | ``$($c.COLUMN_NAME)`` | $type | $null | $key |"
  }
  W ""
}

$out = "D:\Projects\MindAttic\Prose\docs\schema.md"
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "Wrote $out"
Write-Output "Base tables: $baseCount  History: $histCount  FKs: $($fks.Rows.Count)  PKs: $($pks.Rows.Count)"
