namespace StreetSamurai.Core.Data.Entities;

/// <summary>
/// Pre-prose structural commitments for a story node — the anti-tell layer.
///
/// The StoryScope study (UMD/DeepMind, arXiv 2604.03136; 61,608 stories) showed AI
/// fiction is detectable at 93.2% accuracy from narrative-structure decisions alone,
/// and that prose editing does not remove the tells. The detectable decisions:
/// zero subplots, linear chronology, internal-understanding resolutions, moral
/// tidiness, flat event escalation (Claude's #1 fingerprint), event-type monoculture
/// (Claude's #2), reflexive epilogues, intertextual poverty.
///
/// This record commits the structural counters BEFORE any prose is generated.
/// Generated by <see cref="StreetSamurai.Core.Services.StructuralBlueprintService"/>
/// from the node bible + beat spine; verified after writing by StoryScopeAuditService.
/// One row per story node. Sidecar table by design — never columns on the
/// system-versioned Nodes temporal table.
/// </summary>
public class NodeStructuralBlueprint
{
    public Guid Id         { get; set; } = Guid.NewGuid();
    public Guid NodeId     { get; set; }
    public Guid UniverseId { get; set; }

    // ── Subplot plan (humans: 42% thematically-parallel subplots vs AI 21%) ──

    public bool    HasSubplot     { get; set; }

    /// <summary>The B-story in one or two sentences — a runnable thread, not a vibe.</summary>
    public string? SubplotSummary { get; set; }

    /// <summary>How the B-story echoes (not restates) the A-plot's thematic argument.</summary>
    public string? SubplotTheme   { get; set; }

    // ── Temporal scheme (AI defaults to strict chronology; humans cut) ──

    /// <summary>linear | frame | nonlinear</summary>
    public string  TemporalScheme { get; set; } = "linear";

    /// <summary>Where the anachrony lands and what it withholds — e.g. "Beat 3 is a
    /// flashback to the debt; Beat 11 reveals the flashback's true timestamp."</summary>
    public string? AnachronyPlan  { get; set; }

    // ── Resolution (AI: internal understanding 47% vs human 27%) ──

    /// <summary>external | unresolved | mixed. "internal" is not a valid value —
    /// protagonist-achieves-inner-peace is the single most AI-typical exit.</summary>
    public string  ResolutionMode { get; set; } = "external";

    /// <summary>What stays open, or which outside force decides.</summary>
    public string? ResolutionNote { get; set; }

    // ── Moral polarity (humans ambivalent 59% vs AI 38%) ──

    /// <summary>ambivalent | clear. "clear" is allowed but surfaced by the audit as a
    /// logged deviation for human judgment, not silently accepted.</summary>
    public string  MoralPolarity     { get; set; } = "ambivalent";
    public string? MoralPolarityNote { get; set; }

    // ── Escalation curve (Claude fingerprint #1: flat escalation, SHAP 0.402) ──

    /// <summary>JSON int array, one 1-10 intensity target per beat, monotonic
    /// non-decreasing act-over-act to the climax beat. Parallel to spine order.</summary>
    public string EscalationCurveJson { get; set; } = "[]";

    // ── Event-type palette (Claude fingerprint #2: event monoculture) ──

    /// <summary>JSON array of {beatIndex, eventType, revelationMode}. eventType from the
    /// open palette (confrontation, discovery, chase, confession, ceremony, negotiation,
    /// ambush, loss, betrayal, ...) with no back-to-back repeats. revelationMode is
    /// suspense | curiosity | surprise | none (NarraBench Revelation dimension); the
    /// audit flags stories where more than 60% of beats are "none".</summary>
    public string EventTypePaletteJson { get; set; } = "[]";

    // ── Form device (TTCW Originality-in-Form: pros 63.9% vs LLMs 0-8.3%) ──

    /// <summary>Optional formal/structural originality choice decided up front —
    /// document interleave, dual timeline, epistolary fragment, second-person
    /// interlude. Null = conventional form (fine, but chosen, not defaulted).</summary>
    public string? FormDevice { get; set; }

    // ── Ending (Claude fingerprint: epilogues + quiet endings) ──

    /// <summary>avalanche | quiet. "quiet" is a logged deviation, like MoralPolarity=clear.</summary>
    public string  EndingStyle { get; set; } = "avalanche";

    /// <summary>True = the story ends on its last event; no retrospective narration
    /// of what it all meant.</summary>
    public bool    NoEpilogue  { get; set; } = true;
    public string? EndingNote  { get; set; }

    // ── Intertextual anchors (humans: explicit named references 47% vs AI 24%) ──

    /// <summary>JSON array of {entityId, name, entityType, howReferenced} — 3-5 named
    /// in-world works/brands/places from the entity DB that the prose must touch.</summary>
    public string IntertextualAnchorsJson { get; set; } = "[]";

    /// <summary>beat | chapter. Book-scale nodes (more than 60 beats) plan and audit at
    /// chapter granularity: the escalation curve, event palette, and beat tags index
    /// CHAPTER units instead of individual beats (tags attach to each chapter's first
    /// beat). Set at generation time; readers must honor it when interpreting the arrays.</summary>
    public string   Granularity { get; set; } = "beat";

    /// <summary>llm | manual | retrofit</summary>
    public string   GeneratedBy { get; set; } = "llm";
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt   { get; set; } = DateTime.UtcNow;

    // Navigation
    public Node? Node { get; set; }
    public List<NodeStructuralBlueprintBeatTag> BeatTags { get; set; } = new();
}

/// <summary>
/// Per-beat structural assignment under a blueprint — which beat carries the subplot,
/// where the anachrony cut lands, which beat touches an intertextual anchor, which
/// beat is the escalation peak. Mirrors PlantPayoff's beat-FK pattern.
/// </summary>
public class NodeStructuralBlueprintBeatTag
{
    public Guid Id          { get; set; } = Guid.NewGuid();
    public Guid BlueprintId { get; set; }
    public Guid BeatId      { get; set; }

    /// <summary>subplot | anachrony-cut | intertextual-touchpoint | escalation-target</summary>
    public string  TagType { get; set; } = "";

    /// <summary>Human-readable instruction for this beat — e.g. "carries the B-story",
    /// "this is the frame's return-to-present".</summary>
    public string? Note    { get; set; }

    public NodeStructuralBlueprint? Blueprint { get; set; }
    public Beat? Beat { get; set; }
}
